Repository mongodb-js/compass, pull requests merged in 2022-11, with the labels that each got.

#3664 feat(compass-editor): add leafygreen dark theme for the editor COMPASS-6241
  packages/compass-components/src/hooks/use-theme.tsx
  packages/compass-components/src/index.ts
  packages/compass-editor/src/ace/index.ts
  packages/compass-editor/src/ace/theme.ts
  packages/compass-editor/src/base-editor.tsx
Labels: feature flagged, feat

#3681 feat(pipeline-preview): handle output stages COMPASS-6257
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-editor.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-preview.spec.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-preview.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-stages-preview.spec.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-stages-preview.tsx
  packages/compass-aggregations/src/components/stage-preview/stage-preview.jsx
  packages/compass-aggregations/src/modules/is-modified.js
  packages/compass-aggregations/src/modules/pipeline-builder/builder-helpers.ts
  packages/compass-aggregations/src/modules/pipeline-builder/index.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-builder.spec.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-builder.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-preview-manager.spec.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-preview-manager.ts
  packages/compass-aggregations/src/modules/pipeline-builder/text-editor-output-stage.ts
  packages/compass-aggregations/src/modules/pipeline-builder/text-editor-pipeline.spec.ts
  packages/compass-aggregations/src/modules/pipeline-builder/text-editor-pipeline.ts
  packages/compass-aggregations/src/utils/stage.js
Labels: feature flagged, feat

#3651 feat(preview-menu): add pipeline preview options menu COMPASS-6265
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/index.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-preview.spec.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-preview.tsx
  packages/compass-aggregations/src/components/pipeline-output-options-menu.tsx
  packages/compass-aggregations/src/components/pipeline-results-workspace/index.spec.tsx
  packages/compass-aggregations/src/components/pipeline-results-workspace/index.tsx
  packages/compass-aggregations/src/components/pipeline-results-workspace/pipeline-results-header.tsx
  packages/compass-aggregations/src/components/pipeline-results-workspace/pipeline-results-list.spec.tsx
  packages/compass-aggregations/src/components/pipeline-results-workspace/pipeline-results-list.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/index.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/index.tsx
  packages/compass-aggregations/src/components/pipeline/pipeline.jsx
  packages/compass-crud/index.d.ts
  packages/compass-crud/src/components/document-json-view.jsx
  packages/compass-crud/src/components/document-list-view.jsx
  packages/compass-crud/src/components/document.jsx
  packages/compass-crud/src/components/editable-document.jsx
  packages/compass-crud/src/components/json-editor.jsx
  packages/compass-crud/src/components/readonly-document.jsx
Labels: feature flagged, feat

#3687 fix(pipeline-text): remove $s from text
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-preview.tsx
Labels: feature flagged, fix

#3685 chore(dropdown-menu): use dropdown menu component
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-preview.spec.tsx
  packages/compass-aggregations/src/components/pipeline-output-options-menu.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/index.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-menus.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-menus.tsx
  packages/compass-components/src/components/item-action-controls.tsx
  packages/compass-components/src/index.ts
  packages/compass-crud/src/components/add-data-menu.tsx
  packages/compass-crud/src/components/crud-toolbar.spec.tsx
  packages/compass-e2e-tests/helpers/selectors.ts
Labels: no release notes

#3700 fix: improve table view interactions
  packages/compass-crud/src/components/ag-grid-dist.css
  packages/compass-crud/src/components/ag-grid.less
  packages/compass-crud/src/components/document-table-view.jsx
  packages/compass-crud/src/components/table-view-cell.less
Labels: release notes, fix

#3692 feat: replace types dropdown with LG select
  packages/compass-crud/src/components/cell-editor.spec.jsx
  packages/compass-crud/src/components/table-view-cell-editor.less
  packages/compass-crud/src/components/table-view/add-field-button.jsx
  packages/compass-crud/src/components/table-view/cell-editor.jsx
  packages/compass-crud/src/components/table-view/types-dropdown.spec.jsx
  packages/compass-crud/src/components/table-view/types-dropdown.tsx
  packages/compass-crud/src/components/table-view/types.jsx
  packages/compass-crud/src/components/table-view/types.spec.jsx
  packages/compass/src/main/window-manager.ts
Labels: release notes, feat

#3731 fix(pipeline-text): use correct stage operators
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-preview.tsx
Labels: fix, no release notes

#3735 fix(compass-e2e-tests): ensure default settings are set
  packages/compass-e2e-tests/helpers/compass.ts
Labels: fix, no release notes

#3736 fix(compass-connections): do not save auto-connection in recents COMPASS-6290
  packages/compass-connections/src/stores/connections-store.spec.ts
  packages/compass-connections/src/stores/connections-store.ts
  packages/compass-e2e-tests/tests/auto-connect.test.ts
Labels: release notes, fix

#3737 feat(query-history): convert compass query history to new components COMPASS-6221
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-query-history/README.md
  packages/compass-query-history/package.json
  packages/compass-query-history/src/actions/actions.ts
  packages/compass-query-history/src/components/card/card-body.jsx
  packages/compass-query-history/src/components/card/card-body.spec.jsx
  packages/compass-query-history/src/components/card/card-header.jsx
  packages/compass-query-history/src/components/card/card-header.spec.jsx
  packages/compass-query-history/src/components/card/card.jsx
  packages/compass-query-history/src/components/card/card.module.less
  packages/compass-query-history/src/components/card/card.spec.jsx
  packages/compass-query-history/src/components/card/index.js
  packages/compass-query-history/src/components/favorite/favorite-list-item.jsx
  packages/compass-query-history/src/components/favorite/favorite-list-item.module.less
  packages/compass-query-history/src/components/favorite/favorite-list-item.spec.jsx
  packages/compass-query-history/src/components/favorite/favorite-list-item.spec.tsx
  packages/compass-query-history/src/components/favorite/favorite-list-item.tsx
  packages/compass-query-history/src/components/favorite/index.js
  packages/compass-query-history/src/components/list/list.jsx
  packages/compass-query-history/src/components/list/list.module.less
  packages/compass-query-history/src/components/list/list.spec.jsx
  packages/compass-query-history/src/components/query-history/query-history.jsx
  packages/compass-query-history/src/components/query/query.jsx
  packages/compass-query-history/src/components/query/query.spec.jsx
  packages/compass-query-history/src/components/query/query.tsx
  packages/compass-query-history/src/components/recent/index.js
  packages/compass-query-history/src/components/recent/recent-list-item.jsx
  packages/compass-query-history/src/components/recent/recent-list-item.module.less
  packages/compass-query-history/src/components/recent/recent-list-item.spec.jsx
  packages/compass-query-history/src/components/recent/recent-list-item.spec.tsx
  packages/compass-query-history/src/components/recent/recent-list-item.tsx
  packages/compass-query-history/src/components/saving/index.js
  packages/compass-query-history/src/components/saving/saving.jsx
  packages/compass-query-history/src/components/saving/saving.module.less
  packages/compass-query-history/src/components/saving/saving.spec.jsx
  packages/compass-query-history/src/components/toolbar/toolbar.tsx
  packages/compass-query-history/src/components/zero-graphic.tsx
  packages/compass-query-history/src/stores/favorite-list-store.js
  packages/compass-query-history/src/stores/query-history-store.js
  packages/compass-query-history/src/typings.d.ts
  packages/compass-query-history/src/utils/format-query.js
  packages/compass-query-history/src/utils/format-query.ts
Labels: release notes, feat

#3743 feat(query-history): use the same date hook in query history as in saved aggregations COMPASS-6221
  packages/compass-components/src/hooks/use-formatted-date.tsx
  packages/compass-components/src/index.ts
  packages/compass-components/src/utils/format-date.ts
  packages/compass-query-history/src/components/recent/recent-list-item.tsx
  packages/compass-query-history/src/stores/recent-list-store.js
  packages/compass-saved-aggregations-queries/src/components/saved-item-card.tsx
Labels: release notes, feat

#3739 fix(compass-preferences-model): account for changes in preferences while fetching
  packages/compass-preferences-model/src/preferences.spec.ts
  packages/compass-preferences-model/src/preferences.ts
Labels: fix, no release notes

#3741 feat(aggregations): telemetry COMPASS-6177
  packages/compass-aggregations/src/components/saved-pipelines/saved-pipeline-card.spec.jsx
  packages/compass-aggregations/src/components/saved-pipelines/saved-pipeline-card.tsx
  packages/compass-aggregations/src/components/saved-pipelines/saved-pipelines.spec.jsx
  packages/compass-aggregations/src/components/stage-editor-toolbar/delete-stage.spec.jsx
  packages/compass-aggregations/src/modules/aggregation.ts
  packages/compass-aggregations/src/modules/explain.ts
  packages/compass-aggregations/src/modules/pipeline-builder/builder-helpers.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-mode.ts
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
  packages/compass-aggregations/src/modules/saved-pipeline.ts
  packages/compass-aggregations/src/modules/update-view.js
Labels: feat, no release notes

#3761 feat: expose protectConnectionStrings in settings UI COMPASS-6262
  packages/compass-settings/src/components/settings/features.spec.tsx
  packages/compass-settings/src/components/settings/features.tsx
Labels: release notes, feat

#3744 feat(text-aggregation): add resizer on text editor COMPASS-6284
  packages/compass-aggregations/src/components/input-workspace/input-workspace.jsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/index.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-editor.tsx
  packages/compass-aggregations/src/components/resize-handle.tsx
  packages/compass-aggregations/src/components/resize-handle/resize-handle.jsx
  packages/compass-aggregations/src/components/resize-handle/resize-handle.module.less
  packages/compass-aggregations/src/components/stage/stage.jsx
Labels: feature flagged, feat

#3764 feat: Kerberos password field setting COMPASS-5950
  packages/compass-e2e-tests/helpers/commands/get-connect-form-state.ts
  packages/compass-e2e-tests/helpers/commands/set-connect-form-state.ts
  packages/compass-e2e-tests/tests/connection-form.test.ts
  packages/compass-e2e-tests/tests/show-kerberos-password-field.test.ts
  packages/compass-preferences-model/src/preferences.ts
  packages/compass-settings/src/components/settings/features.spec.tsx
  packages/compass-settings/src/components/settings/features.tsx
  packages/compass/src/index.d.ts
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-gssapi.spec.tsx
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-gssapi.tsx
Labels: release notes, feat

#3765 fix(compass-preferences-model): default enableShell to true
  packages/compass-preferences-model/src/preferences.spec.ts
  packages/compass-preferences-model/src/preferences.ts
Labels: fix, no release notes

#3747 fix: only auto-connect in 1st window and not after disconnect COMPASS-6293
  packages/compass-connections/src/components/connections.tsx
  packages/compass-connections/src/stores/connections-store.ts
  packages/compass-e2e-tests/tests/auto-connect.test.ts
  packages/compass-home/src/components/home.tsx
  packages/compass/src/app/auto-connect.spec.ts
  packages/compass/src/app/auto-connect.ts
  packages/compass/src/main/auto-connect.ts
  packages/compass/src/main/window-manager.ts
Labels: fix, no release notes

#3767 feat(compass-settings): add support for numeric inputs
  packages/compass-preferences-model/src/preferences.ts
  packages/compass-settings/src/components/settings/features.spec.tsx
  packages/compass-settings/src/components/settings/features.tsx
  packages/compass-settings/src/components/settings/privacy.spec.tsx
  packages/compass-settings/src/components/settings/privacy.tsx
  packages/compass-settings/src/components/settings/settings-list.tsx
  packages/compass-settings/src/utils/pick.ts
Labels: feat, no release notes

#3762 fix(aggregations): empty stage
  packages/compass-aggregations/src/utils/stage.js
  packages/compass-aggregations/src/utils/stage.spec.js
Labels: release notes, fix

#3775 chore(connect): update Create Free Cluster link COMPASS-6287
  packages/compass-connections/src/components/connections.spec.tsx
  packages/compass-connections/src/components/form-help/form-help.tsx
Labels: no release notes

#3759 fix(hadron-document): check for root level when deciding if `_id` key is editable COMPASS-6160
  packages/compass-crud/src/components/cell-editor.spec.jsx
  packages/hadron-document/src/element.ts
  packages/hadron-document/test/element.test.ts
Labels: release notes, fix

#3769 feat: track application launched telemetry COMPASS-6077
  packages/compass/src/app/index.js
  packages/compass/src/main/application.ts
  packages/compass/src/main/window-manager.ts
Labels: feat, no release notes

#3779 fix(compass-aggregations): stricter validation and better error messages for stages
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-builder.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-parser/stage-parser.spec.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-parser/stage-parser.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-parser/utils.ts
  packages/compass-aggregations/src/modules/pipeline-builder/stage.ts
  packages/compass-aggregations/src/utils/stage.js
Labels: fix, no release notes

#3788 fix(e2e): wait for syntax error and always reset maxTimeMS at the end
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
Labels: fix, no release notes

#3782 fix(compass-settings): keep internal state of settings modal up-to-date COMPASS-6296
  packages/compass-preferences-model/src/index.ts
  packages/compass-preferences-model/src/preferences.spec.ts
  packages/compass-preferences-model/src/preferences.ts
  packages/compass-preferences-model/src/renderer-ipc.ts
  packages/compass-preferences-model/src/setup-preferences.ts
  packages/compass-settings/src/components/modal.spec.tsx
  packages/compass-settings/src/components/modal.tsx
  packages/compass-settings/src/components/settings/features.tsx
  packages/compass-settings/src/components/settings/privacy.tsx
  packages/compass-settings/src/components/settings/theme.tsx
  packages/compass-settings/src/stores/index.ts
  packages/compass-settings/src/stores/settings.spec.ts
  packages/compass-settings/src/stores/settings.ts
  packages/compass-settings/src/stores/updated-fields.ts
Labels: fix, no release notes

#3780 fix(compass-aggregations): check that parsed pipeline is an array
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-builder.spec.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-builder.ts
Labels: fix, no release notes

#3786 feat(compass-explain-plan): update explain plan components COMPASS-6236
  packages/compass-e2e-tests/tests/collection-explain-plan-tab.test.ts
  packages/compass-explain-plan/package.json
  packages/compass-explain-plan/src/components/explain-stage/explain-stage.jsx
  packages/compass-explain-plan/src/components/explain-summary/explain-summary.jsx
  packages/compass-explain-plan/src/components/explain-summary/explain-summary.module.less
  packages/compass-explain-plan/src/components/explain-tree/explain-tree.jsx
  packages/compass-explain-plan/src/components/index-definition-type/index-definition-type.jsx
  packages/compass-explain-plan/src/components/index-definition-type/index-definition-type.module.less
  packages/compass-explain-plan/src/components/index-definition-type/index-definition-type.spec.jsx
  packages/compass-explain-plan/src/components/summary-index-stat/summary-index-stat.jsx
  packages/compass-explain-plan/src/components/summary-index-stat/summary-index-stat.module.less
Labels: release notes, feat

#3796 feat(text-aggregation): show stale results banner COMPASS-6291
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-editor.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-preview.spec.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-preview.tsx
  packages/compass-aggregations/src/modules/pipeline-builder/text-editor-pipeline.spec.ts
  packages/compass-aggregations/src/modules/pipeline-builder/text-editor-pipeline.ts
  packages/compass-aggregations/test/mocks/data-service.ts
Labels: feature flagged, feat

#3802 fix(compass-preferences-model): ignore squirrel options
  packages/compass-preferences-model/src/global-config.spec.ts
  packages/compass-preferences-model/src/global-config.ts
Labels: release notes, fix

#3800 chore(aggregations): add tracking event when stage value changes COMPASS-6310
  packages/compass-aggregations/src/components/stage-editor/stage-editor.jsx
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
Labels: release notes, feat

#3807 chore(compass-components): add xsmall icon size COMPASS-6306
  packages/compass-components/src/components/document-list/element-actions.tsx
  packages/compass-components/src/components/document-list/element-editors.tsx
  packages/compass-components/src/components/document-list/element.tsx
  packages/compass-components/src/components/item-action-controls.tsx
  packages/compass-components/src/components/leafygreen.tsx
  packages/compass-crud/src/components/table-view/add-field-button.jsx
  packages/compass-crud/src/components/table-view/ag-grid.less
  packages/compass-crud/src/components/table-view/breadcrumb.jsx
  packages/compass-crud/src/components/table-view/cell-editor.jsx
  packages/compass-crud/src/components/table-view/cell-renderer.jsx
Labels: no release notes

#3811 fix(aggregations): fix the saved pipelines popover's scrolling COMPASS-6277
  packages/compass-aggregations/src/components/saved-pipelines/saved-pipelines.tsx
Labels: release notes, fix

#3805 feat: remove trackErrors setting COMPASS-5708
  packages/compass-export-to-language/src/modules/transpiler.spec.ts
  packages/compass-preferences-model/src/preferences.spec.ts
  packages/compass-preferences-model/src/preferences.ts
  packages/compass-preferences-model/src/react.spec.tsx
  packages/compass-preferences-model/src/react.ts
  packages/compass-settings/src/components/settings/privacy.spec.tsx
  packages/compass-settings/src/components/settings/privacy.tsx
  packages/index-model/test/fixture-bugsnag.js
  packages/index-model/test/index.test.js
Labels: release notes, feat

#3813 fix(compass-aggregations): ignore disabled stages when validating pipeline for preview COMPASS-6318
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.spec.ts
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
Labels: fix, no release notes

#3818 fix(compass): disable deprecation warnings in production COMPASS-6322
  packages/compass-e2e-tests/tests/global-preferences.test.ts
  packages/compass/src/main/application.ts
  packages/compass/src/main/disable-node-deprecations.ts
Labels: release notes, fix

#3820 fix: apply settings categories dark styles COMPASS-6327
  packages/compass-settings/src/components/modal.tsx
  packages/compass-settings/src/components/sidebar.tsx
Labels: fix, no release notes

#3816 fix(compass-settings): ignore non-digits in number input COMPASS-6326
  packages/compass-settings/src/components/settings/settings-list.tsx
Labels: release notes, fix

#3821 fix(pipeline-preview): do not overflow the preview container COMPASS-6320
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/index.tsx
Labels: feature flagged, fix

#3828 fix(schema): increase compass schema value bubble contrast COMPASS-6230
  packages/compass-schema/src/components/value-bubble/value-bubble.jsx
Labels: release notes, fix

#3822 chore(telemetry): track aggregation changes in text mode COMPASS-6328
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-editor.spec.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-editor.tsx
Labels: feature flagged

#3827 feat(insert): Convert more insert dialog code to compass components & leafygreen COMPASS-6285
  packages/compass-crud/src/components/insert-document-dialog.tsx
  packages/compass-crud/src/components/insert-document-footer.tsx
  packages/compass-crud/src/components/insert-json-document.module.less
  packages/compass-crud/src/components/insert-json-document.tsx
  packages/compass-crud/src/components/table-view/cell-editor.tsx
  packages/compass-e2e-tests/helpers/selectors.ts
Labels: release notes, feat

#3834 feat: add --show-example-config flag COMPASS-6084
  packages/compass-preferences-model/src/global-config.ts
  packages/compass-preferences-model/src/index.ts
  packages/compass-preferences-model/src/preferences.ts
  packages/compass/src/main/index.ts
Labels: release notes, feat

#3819 fix(pipeline-parser): do not duplicate disabled stages COMPASS-6313
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-parser/pipeline-parser.spec.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-parser/pipeline-parser.ts
Labels: feature flagged, fix

#3844 fix(compass): fix macOS protocol handler connection string passing
  packages/compass/src/main/window-manager.ts
Labels: release notes, fix

#3842 fix(compass-indexes): fix typo on Indexes screen
  packages/compass-indexes/src/components/indexes-table/usage-field.spec.tsx
  packages/compass-indexes/src/components/indexes-table/usage-field.tsx
Labels: release notes, fix

#3838 fix(compass-preferences-model): avoid race condition when installing listeners
  packages/compass-preferences-model/src/renderer-ipc.ts
Labels: release notes, fix
