Repository mongodb-js/compass, pull requests merged in 2022-07, with the labels that each got.

#3218 fix: improve `Binary` handling COMPASS-5848
  packages/compass-components/src/components/bson-value.spec.tsx
  packages/compass-components/src/components/bson-value.tsx
  packages/hadron-type-checker/src/type-checker.js
  packages/hadron-type-checker/test/type-checker.test.js
Labels: release notes, fix

#3228 fix: automatically refresh after CSFLE insert COMPASS-5806
  packages/compass-crud/src/stores/crud-store.js
  packages/compass-crud/src/stores/crud-store.spec.js
  packages/compass-e2e-tests/tests/collection-import.test.ts
  packages/compass-e2e-tests/tests/in-use-encryption.test.ts
Labels: release notes, fix

#3243 fix(compass-crud): drop `__safeContent__` when replacing COMPASS-5856
  packages/compass-crud/src/stores/crud-store.js
  packages/compass-e2e-tests/tests/in-use-encryption.test.ts
Labels: release notes, fix

#3239 feat(hadron-document)!: handle nested fields and dots & dollars well COMPASS-5805
  packages/compass-crud/src/stores/crud-store.js
  packages/hadron-document/src/document.ts
  packages/hadron-document/src/element.ts
  packages/hadron-document/src/object-generator.ts
  packages/hadron-document/test/document.test.ts
Labels: release notes, feat

#3240 feat(compass): Update icons and installers to new brand COMPASS-5120
  packages/compass/app-icons/README.md
  packages/compass/app-icons/darwin/background.png
  packages/compass/app-icons/darwin/background@2x.png
  packages/compass/app-icons/darwin/mongodb-compass.icns
  packages/compass/app-icons/linux/mongodb-compass.png
  packages/compass/app-icons/win32/background.jpg
  packages/compass/app-icons/win32/banner.jpg
  packages/compass/app-icons/win32/mongodb-compass-installer-loading.gif
  packages/compass/app-icons/win32/mongodb-compass.ico
Labels: release notes, feat

#3256 feat(compass-aggregations): Add right glyph caret down to buttons with menus in compass-aggregations
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-menus.tsx
Labels: release notes, feat

#3262 fix: allow updating unindexed encrypted fields COMPASS-5809
  packages/compass-crud/src/stores/crud-store.js
  packages/compass-crud/src/stores/crud-store.spec.js
  packages/compass-e2e-tests/tests/in-use-encryption.test.ts
  packages/data-service/src/csfle-collection-tracker.spec.ts
  packages/data-service/src/csfle-collection-tracker.ts
  packages/hadron-document/src/document.ts
  packages/hadron-document/src/object-generator.ts
  packages/hadron-document/test/document.test.ts
Labels: release notes, fix

#3249 feat(compass-schema-validation): update warnings components to leafygreen COMPASS-5747
  packages/compass-schema-validation/src/components/validation-states/validation-states.jsx
  packages/compass-schema-validation/src/components/validation-states/validation-states.module.less
  packages/compass-schema-validation/src/components/validation-states/validation-states.spec.jsx
Labels: release notes, feat

#3286 fix(hadron-document): handle oddball fp numbers well in `.toEJSON()` COMPASS-5974
  packages/hadron-document/src/utils.ts
  packages/hadron-document/test/document.test.ts
Labels: release notes, fix

#3284 feat(connection-form): Add enableUtf8Validation option to advanced url options COMPASS-4944
  packages/connection-form/src/utils/url-options.ts
Labels: release notes, feat

#3292 feat / focus editor when click shell
  packages/compass-shell/src/components/compass-shell/compass-shell.jsx
Labels: release notes

#3246 feat(compass-crud): Update toolbar to leafygreen components COMPASS-5672
  packages/compass-components/src/components/spin-loader.tsx
  packages/compass-crud/package.json
  packages/compass-crud/src/components/add-data-menu.tsx
  packages/compass-crud/src/components/crud-toolbar.spec.tsx
  packages/compass-crud/src/components/crud-toolbar.tsx
  packages/compass-crud/src/components/document-list.jsx
  packages/compass-crud/src/components/legacy-toolbar.jsx
  packages/compass-crud/src/components/toolbar.jsx
  packages/compass-crud/src/stores/crud-store.spec.js
  packages/compass-explain-plan/src/components/explain-toolbar/explain-toolbar.tsx
  packages/compass-query-bar/src/components/query-bar.tsx
Labels: feature flagged, feat
