Repository mongodb-js/compass, pull requests merged in 2022-12, with the labels that each got.

#3856 feat: cancellable aggregate and schema analysis COMPASS-5668
  packages/compass-aggregations/src/modules/aggregation.spec.ts
  packages/compass-aggregations/src/modules/aggregation.ts
  packages/compass-aggregations/src/modules/explain.ts
  packages/compass-aggregations/src/modules/input-documents.js
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
  packages/compass-aggregations/src/modules/pipeline-builder/text-editor-pipeline.ts
  packages/compass-aggregations/src/utils/cancellable-aggregation.ts
  packages/compass-aggregations/test/mocks/data-service.ts
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-crud/src/utils/cancellable-queries.ts
  packages/compass-import-export/src/modules/export.spec.js
  packages/compass-import-export/src/modules/export.ts
  packages/compass-schema-validation/src/modules/sample-documents.js
  packages/compass-schema/src/modules/schema-analysis.js
  packages/compass-schema/src/modules/schema-analysis.spec.js
  packages/compass-schema/src/stores/store.js
  packages/compass-utils/src/cancellable-promise.ts
  packages/data-service/src/data-service.spec.ts
  packages/data-service/src/data-service.ts
Labels: release notes, feat

#3860 feat: cancellable find and explain COMPASS-5668
  packages/compass-crud/package.json
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-crud/src/utils/cancellable-queries.spec.ts
  packages/compass-crud/src/utils/cancellable-queries.ts
  packages/compass-explain-plan/src/modules/explain.js
  packages/compass-explain-plan/src/modules/index.js
  packages/compass-explain-plan/src/modules/is-datalake.js
  packages/compass-explain-plan/src/stores/store.js
  packages/compass-import-export/src/modules/export.ts
  packages/compass-import-export/src/modules/load-fields.spec.js
  packages/compass-import-export/src/modules/load-fields.ts
  packages/compass-import-export/src/utils/collection-stream.ts
  packages/data-service/src/connect.spec.ts
  packages/data-service/src/data-service.spec.ts
  packages/data-service/src/data-service.ts
Labels: release notes, feat

#3864 feat(aggregations): Implement new input docs card design COMPASS-6234
  packages/compass-aggregations/src/components/input-builder-toolbar/index.js
  packages/compass-aggregations/src/components/input-builder-toolbar/input-builder-toolbar.jsx
  packages/compass-aggregations/src/components/input-builder-toolbar/input-builder-toolbar.module.less
  packages/compass-aggregations/src/components/input-builder-toolbar/input-builder-toolbar.spec.jsx
  packages/compass-aggregations/src/components/input-builder/index.js
  packages/compass-aggregations/src/components/input-builder/input-builder.jsx
  packages/compass-aggregations/src/components/input-builder/input-builder.module.less
  packages/compass-aggregations/src/components/input-builder/input-builder.spec.jsx
  packages/compass-aggregations/src/components/input-collapser/index.js
  packages/compass-aggregations/src/components/input-collapser/input-collapser.jsx
  packages/compass-aggregations/src/components/input-collapser/input-collapser.spec.jsx
  packages/compass-aggregations/src/components/input-documents-count/index.js
  packages/compass-aggregations/src/components/input-documents-count/input-documents-count.jsx
  packages/compass-aggregations/src/components/input-documents-count/input-documents-count.module.less
  packages/compass-aggregations/src/components/input-documents-count/input-documents-count.spec.jsx
  packages/compass-aggregations/src/components/input-preview-toolbar/index.js
  packages/compass-aggregations/src/components/input-preview-toolbar/input-preview-toolbar.jsx
  packages/compass-aggregations/src/components/input-preview-toolbar/input-preview-toolbar.module.less
  packages/compass-aggregations/src/components/input-preview-toolbar/input-preview-toolbar.spec.jsx
  packages/compass-aggregations/src/components/input-preview/index.js
  packages/compass-aggregations/src/components/input-preview/input-preview.jsx
  packages/compass-aggregations/src/components/input-preview/input-preview.module.less
  packages/compass-aggregations/src/components/input-preview/input-preview.spec.jsx
  packages/compass-aggregations/src/components/input-refresh/index.js
  packages/compass-aggregations/src/components/input-refresh/input-refresh.jsx
  packages/compass-aggregations/src/components/input-toolbar/index.js
  packages/compass-aggregations/src/components/input-toolbar/input-toolbar.jsx
  packages/compass-aggregations/src/components/input-toolbar/input-toolbar.module.less
  packages/compass-aggregations/src/components/input-toolbar/input-toolbar.spec.jsx
  packages/compass-aggregations/src/components/input-workspace/index.js
  packages/compass-aggregations/src/components/input-workspace/input-workspace.jsx
  packages/compass-aggregations/src/components/input-workspace/input-workspace.module.less
  packages/compass-aggregations/src/components/input-workspace/input-workspace.spec.jsx
  packages/compass-aggregations/src/components/input/index.js
  packages/compass-aggregations/src/components/input/input.jsx
  packages/compass-aggregations/src/components/input/input.module.less
  packages/compass-aggregations/src/components/input/input.spec.jsx
  packages/compass-aggregations/src/components/pipeline-builder-input-documents.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace.jsx
Labels: release notes, feat

#3850 feat: expose feature flags as settings COMPASS-6336
  packages/compass-aggregations/src/components/pipeline-results-workspace/pipeline-results-header.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-menus.tsx
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-mode.ts
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
  packages/compass-preferences-model/src/preferences.ts
  packages/compass-preferences-model/src/renderer-ipc.ts
  packages/compass-settings/src/components/modal.tsx
  packages/compass-settings/src/components/settings/featureflags.tsx
  packages/compass/src/app/theme.ts
  packages/compass/src/index.d.ts
  packages/compass/src/main/index.ts
  packages/connection-form/src/components/advanced-options-tabs/csfle-tab/csfle-tab.tsx
Labels: release notes, feat

#3877 fix(compass-components): bring back ThemeProvider for browser-repl
  packages/compass-components/src/hooks/use-theme.tsx
  packages/compass-components/src/index.ts
Labels: fix, no release notes

#3866 feat(data-service): cancellable counts COMPASS-5668
  packages/compass-aggregations/src/modules/input-documents.js
  packages/compass-import-export/src/modules/export.ts
  packages/compass-schema-validation/src/modules/sample-documents.js
  packages/data-service/src/data-service.spec.ts
  packages/data-service/src/data-service.ts
Labels: release notes, feat

#3874 fix(compass-editors): fix nested field autocomplete COMPASS-6335
  packages/compass-aggregations/README.md
  packages/compass-editor/src/ace/query-autocompleter.test.ts
  packages/compass-editor/src/ace/util.ts
Labels: release notes, fix

#3882 fix(compass-crud): reset contains error check on document json view edit cancel COMPASS-6059
  packages/compass-crud/src/components/json-editor.tsx
Labels: release notes, fix

#3885 fix(aggregations): run preview on pipeline value change COMPASS-6353
  packages/compass-aggregations/src/modules/import-pipeline.js
  packages/compass-aggregations/src/modules/pipeline-builder/text-editor-pipeline.ts
Labels: feature flagged, fix

#3890 fix(schema): pass the preference as a prop when nesting Field COMPASS-6363
  packages/compass-schema/src/components/field/field.jsx
Labels: release notes, fix

#3896 fix(compass-schema): opening nested field schema
  packages/compass-schema/src/components/field/field.jsx
Labels: fix, no release notes

#3900 fix(crud): Fix adding a field in the CRUD table view COMPASS-6359
  packages/compass-crud/src/components/table-view/add-field-button.tsx
Labels: fix, no release notes

#3902 chore(sidebar): indent collections in the sidebar COMPASS-6380
  packages/compass-databases-navigation/src/collection-item.tsx
  packages/compass-databases-navigation/src/placeholder-item.tsx
Labels: release notes

#3886 feat: index tab UI improvements COMPASS-6323, COMPASS-6329
  packages/compass-indexes/src/components/indexes-table/indexes-table.spec.tsx
  packages/compass-indexes/src/components/indexes-table/indexes-table.tsx
  packages/compass-indexes/src/components/indexes-table/key-list.spec.tsx
  packages/compass-indexes/src/components/indexes-table/key-list.tsx
  packages/compass-indexes/src/components/indexes-table/name-field.tsx
  packages/compass-indexes/src/components/indexes-table/property-field.tsx
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
  packages/compass-indexes/src/components/indexes/indexes.spec.tsx
  packages/compass-indexes/src/components/indexes/indexes.tsx
  packages/compass-indexes/src/modules/indexes.spec.ts
  packages/compass-indexes/src/modules/indexes.ts
Labels: release notes, feat

#3907 fix(aggregations): hide add stage in toolbar COMPASS-6373
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-stages.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-stages.tsx
  packages/compass-aggregations/src/modules/pipeline-builder/builder-helpers.spec.ts
  packages/compass-aggregations/src/modules/pipeline-builder/builder-helpers.ts
Labels: release notes, fix

#3912 feat(aggregations): add refresh document count in aggregation results COMPASS-6156
  packages/compass-aggregations/src/components/pipeline-results-workspace/pipeline-pagination-count.spec.tsx
  packages/compass-aggregations/src/components/pipeline-results-workspace/pipeline-pagination-count.tsx
  packages/compass-aggregations/src/components/pipeline-results-workspace/pipeline-pagination.tsx
  packages/compass-aggregations/src/modules/count-documents.ts
  packages/compass-crud/src/components/crud-toolbar.spec.tsx
  packages/compass-crud/src/components/crud-toolbar.tsx
  packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
  packages/compass-e2e-tests/tests/collection-import.test.ts
  packages/compass-e2e-tests/tests/connection.test.ts
Labels: release notes, feat

#3915 feat(aggregations): confirm when deleting pipeline COMPASS-4137
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.tsx
  packages/compass-aggregations/src/components/saved-pipelines/saved-pipeline-card.spec.jsx
  packages/compass-aggregations/src/components/saved-pipelines/saved-pipeline-card.tsx
  packages/compass-aggregations/src/components/saved-pipelines/saved-pipeline-confirmation-modals.tsx
  packages/compass-aggregations/src/components/saved-pipelines/saved-pipelines.spec.jsx
  packages/compass-aggregations/src/components/saved-pipelines/saved-pipelines.spec.tsx
  packages/compass-aggregations/src/components/saved-pipelines/saved-pipelines.tsx
  packages/compass-aggregations/src/modules/saved-pipeline.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
Labels: release notes, feat

#3914 fix: export to Language (Java) has incorrect class name COMPASS-6159
  packages/bson-transpilers/README.md
  packages/bson-transpilers/codegeneration/CodeGenerationVisitor.js
  packages/bson-transpilers/index.js
  packages/bson-transpilers/lib/symbol-table/javascripttogo.js
  packages/bson-transpilers/lib/symbol-table/javascripttojava.js
  packages/bson-transpilers/lib/symbol-table/pythontogo.js
  packages/bson-transpilers/lib/symbol-table/pythontojava.js
  packages/bson-transpilers/lib/symbol-table/shelltogo.js
  packages/bson-transpilers/lib/symbol-table/shelltojava.js
  packages/bson-transpilers/symbols/go/templates.yaml
  packages/bson-transpilers/symbols/java/templates.yaml
  packages/bson-transpilers/test/run-yaml.test.js
  packages/bson-transpilers/test/yaml/bson-methods.yaml
  packages/bson-transpilers/test/yaml/bson.yaml
  packages/bson-transpilers/test/yaml/builders.yaml
  packages/bson-transpilers/test/yaml/driver-syntax.yaml
  packages/bson-transpilers/test/yaml/error-argument.yaml
  packages/bson-transpilers/test/yaml/error-builders.yaml
  packages/bson-transpilers/test/yaml/error-misc.yaml
  packages/bson-transpilers/test/yaml/error-syntax.yaml
  packages/bson-transpilers/test/yaml/error-unimplemented.yaml
  packages/bson-transpilers/test/yaml/imports.yaml
  packages/bson-transpilers/test/yaml/native.yaml
  packages/bson-transpilers/test/yaml/non-idiomatic.yaml
  packages/bson-transpilers/test/yaml/partial.yaml
  packages/bson-transpilers/test/yaml/syntax.yaml
  packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
  packages/compass-export-to-language/src/modules/transpiler.spec.ts
  packages/compass-export-to-language/src/modules/transpiler.ts
Labels: release notes, fix

#3916 fix(crud): enable next page button when count is unknown COMPASS-6340
  packages/compass-crud/src/components/crud-toolbar.spec.tsx
  packages/compass-crud/src/components/crud-toolbar.tsx
Labels: release notes, fix
