Repository mongodb-js/compass, pull requests merged in 2022-06, with the labels that each got.

#3153 fix(document-view): isRoot fix COMPASS-5872
  packages/compass-crud/src/components/document.jsx
Labels: release notes, fix

#3150 fix(saved-pipelines): open pipeline in correct namespace COMPASS-5871
  packages/compass-aggregations/src/components/aggregations/aggregations.jsx
  packages/compass-aggregations/src/components/pipeline/modals/restore-pipeline-modal.jsx
  packages/compass-aggregations/src/components/pipeline/pipeline.jsx
  packages/compass-aggregations/src/modules/index.ts
  packages/compass-aggregations/src/stores/store.js
  packages/compass-saved-aggregations-queries/src/stores/open-item.ts
Labels: release notes, fix

#3145 feat: enable In-Use Encryption COMPASS-5634
  packages/compass-e2e-tests/helpers/commands/add-collection.ts
  packages/compass-e2e-tests/helpers/commands/set-connect-form-state.ts
  packages/compass-e2e-tests/tests/connection.test.ts
  packages/compass-e2e-tests/tests/in-use-encryption.test.ts
  packages/compass/src/index.d.ts
  packages/connection-form/package.json
  packages/connection-form/src/components/advanced-options-tabs/advanced-options-tabs.tsx
  packages/connection-form/src/components/connect-form.tsx
  packages/data-service/src/data-service.spec.ts
  packages/databases-collections/src/components/collection-fields/has-fle2-support.js
  packages/databases-collections/src/components/collection-fields/has-fle2-support.spec.js
Labels: release notes, feat

#3154 feat(explain-aggregation): show index key in explain COMPASS-5857
  packages/compass-aggregations/src/components/pipeline-explain/explain-indexes.tsx
  packages/compass-aggregations/src/components/pipeline-explain/explain-query-performance.tsx
  packages/compass-aggregations/src/components/pipeline-explain/explain-results.tsx
  packages/compass-aggregations/src/components/pipeline-explain/index.spec.tsx
  packages/compass-aggregations/src/modules/explain.ts
  packages/compass-aggregations/src/modules/index.ts
  packages/compass-aggregations/src/modules/indexes.ts
  packages/compass-aggregations/src/stores/index.js
  packages/compass-aggregations/src/stores/store.js
  packages/compass-aggregations/src/stores/store.spec.js
  packages/compass-components/src/components/accordion.tsx
  packages/connection-form/src/components/advanced-options-tabs/csfle-tab/csfle-tab.tsx
Labels: release notes, feat

#3162 chore(aggregations): explain tracking COMPASS-5875
  packages/compass-aggregations/src/modules/aggregation.ts
  packages/compass-aggregations/src/modules/count-documents.ts
  packages/compass-aggregations/src/modules/explain.ts
  packages/compass-aggregations/src/utils/stage.js
Labels: release notes

#3171 fix(queries): Ignore duplicate recent queries COMPASS-2237
  packages/compass-query-history/src/models/favorite-query-collection.spec.js
  packages/compass-query-history/src/models/favorite-query.spec.js
  packages/compass-query-history/src/models/recent-query-collection.spec.js
  packages/compass-query-history/src/models/recent-query.spec.js
  packages/compass-query-history/src/stores/favorite-list-store.js
  packages/compass-query-history/src/stores/favorite-list-store.spec.js
  packages/compass-query-history/src/stores/recent-list-store.js
  packages/compass-query-history/src/stores/recent-list-store.spec.js
  packages/compass-query-history/src/utils/comparable-query.js
  packages/compass-query-history/src/utils/comparable-query.spec.js
  packages/compass-query-history/src/utils/index.js
Labels: fix

#3169 feat(explain-plan-helper): add support for indexes in stages COMPASS-5878
  packages/explain-plan-helper/src/get-execution-stats.ts
  packages/explain-plan-helper/src/index.spec.ts
  packages/explain-plan-helper/src/index.ts
  packages/explain-plan-helper/test/fixtures/aggregate_$lookup_with_indexes.json
  packages/explain-plan-helper/test/fixtures/sharded_aggregate_$lookup_with_indexes.json
Labels: release notes, feat

#3185 fix(documents): fixes to recent queries
  packages/compass-query-history/src/stores/recent-list-store.js
  packages/compass-query-history/src/stores/recent-list-store.spec.js
Labels: release notes, fix

#3163 feat(connect): Save & Connect button COMPASS-5776
  packages/compass-e2e-tests/helpers/commands/set-connect-form-state.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/connection-form.test.ts
  packages/connection-form/src/components/connect-form-actions.spec.tsx
  packages/connection-form/src/components/connect-form-actions.tsx
  packages/connection-form/src/components/connect-form.spec.tsx
  packages/connection-form/src/components/connect-form.tsx
  packages/connection-form/src/components/save-connection-modal.spec.tsx
  packages/connection-form/src/components/save-connection-modal.tsx
Labels: release notes, feat

#3184 fix(import): pre-create an empty object before creating its properties COMPASS-5076
  packages/compass-import-export/src/utils/dotnotation.js
  packages/compass-import-export/src/utils/dotnotation.spec.js
  packages/compass-import-export/src/utils/dotnotation.ts
  packages/compass-import-export/src/utils/import-apply-types-and-projection.js
Labels: release notes, fix

#3192 feat(compass-indexes): update toolbar to leafygreen components COMPASS-5676
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-indexes/package.json
  packages/compass-indexes/src/components/create-index-button/create-index-button.jsx
  packages/compass-indexes/src/components/create-index-button/create-index-button.spec.jsx
  packages/compass-indexes/src/components/create-index-button/index.js
  packages/compass-indexes/src/components/create-index-modal/create-index-modal.spec.jsx
  packages/compass-indexes/src/components/drop-index-modal/drop-index-modal.spec.jsx
  packages/compass-indexes/src/components/indexes-toolbar.spec.tsx
  packages/compass-indexes/src/components/indexes-toolbar.tsx
  packages/compass-indexes/src/components/indexes/indexes.jsx
  packages/compass-indexes/src/components/indexes/indexes.module.less
  packages/compass-indexes/src/components/indexes/indexes.spec.jsx
  packages/compass-indexes/src/index.js
  packages/compass-indexes/src/index.ts
  packages/compass-indexes/src/stores/store.js
Labels: release notes, feat

#3216 feat(compass-components): Enable ACE code formatter COMPASS-5923
  packages/compass-components/src/components/editor.tsx
Labels: release notes, feat

#3217 fix(connection-form): align advanced tab and input field widths
  packages/connection-form/src/components/advanced-options-tabs/advanced-tab/advanced-tab.tsx
  packages/connection-form/src/components/advanced-options-tabs/advanced-tab/url-options.tsx
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-tab.tsx
  packages/connection-form/src/components/advanced-options-tabs/ssh-tunnel-tab/proxy-and-ssh-tunnel-tab.tsx
  packages/connection-form/src/components/advanced-options-tabs/tls-ssl-tab/tls-certificate-authority.tsx
  packages/connection-form/src/components/advanced-options-tabs/tls-ssl-tab/tls-client-certificate.tsx
  packages/connection-form/src/components/form-field-container.tsx
Labels: release notes, fix

#3212 fix: align elements on the create collection modal COMPASS-5921
  packages/compass-components/src/components/accordion.tsx
  packages/databases-collections/src/components/collation-fields/collation-fields.jsx
  packages/databases-collections/src/components/collation-fields/collation-fields.module.less
  packages/databases-collections/src/components/collection-fields/capped-collection-fields.jsx
  packages/databases-collections/src/components/collection-fields/time-series-fields.jsx
  packages/databases-collections/src/components/collection-fields/time-series-fields.module.less
  packages/databases-collections/src/components/field-set/field-set.module.less
Labels: release notes, fix
