Repository mongodb-js/compass, pull requests merged in 2022-08, with the labels that each got.

#3315 feat(compass-query-bar): update export to language button and icon
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/index.tsx
  packages/compass-query-bar/src/components/query-bar.tsx
Labels: release notes

#3310 feat(bson-transpilers): modernize JS exports COMPASS-5870
  packages/bson-transpilers/lib/symbol-table/pythontojavascript.js
  packages/bson-transpilers/lib/symbol-table/shelltojavascript.js
  packages/bson-transpilers/symbols/javascript/templates.yaml
  packages/bson-transpilers/test/yaml/driver-syntax.yaml
  packages/bson-transpilers/test/yaml/imports.yaml
Labels: release notes, feat

#3317 feat: Replace projection inputs with corresponding editor COMPASS-5979
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-indexes-tab.test.ts
  packages/compass-indexes/src/components/create-index-modal/create-index-modal.jsx
  packages/compass-indexes/src/components/create-index-modal/create-index-modal.spec.jsx
  packages/compass-indexes/src/components/type-column/type-column.jsx
  packages/compass-indexes/src/modules/create-index/collation-string.ts
  packages/compass-indexes/src/modules/create-index/columnstore-projection.spec.ts
  packages/compass-indexes/src/modules/create-index/columnstore-projection.ts
  packages/compass-indexes/src/modules/create-index/wildcard-projection.js
  packages/compass-indexes/src/modules/create-index/wildcard-projection.spec.js
  packages/compass-indexes/src/modules/create-index/wildcard-projection.spec.ts
  packages/compass-indexes/src/modules/create-index/wildcard-projection.ts
Labels: release notes, feat

#3322 chore(compass-explain-plan): Hide explain toolbar until explain is run (new feature flagged toolbar)
  packages/compass-explain-plan/src/components/explain-states/explain-states.jsx
  packages/compass-explain-plan/src/components/explain-toolbar/explain-toolbar.spec.tsx
  packages/compass-explain-plan/src/components/explain-toolbar/explain-toolbar.tsx
Labels: feature flagged

#3324 chore(compass-query-bar): Make query input not overflow a few pixels off screen on new toolbar
  packages/compass-components/src/constants/mongodb-ace-theme-query.ts
  packages/compass-query-bar/src/components/option-editor.tsx
Labels: feature flagged

#3325 chore(compass-crud): Make new crud toolbar buttons not wrap at small widths
  packages/compass-crud/src/components/add-data-menu.tsx
  packages/compass-crud/src/components/crud-toolbar.tsx
Labels: feature flagged

#3320 feat(sidebar) New sidebar navtree COMPASS-5960
  packages/compass-components/src/components/placeholder.tsx
  packages/compass-components/src/components/resizeable-sidebar.tsx
  packages/compass-components/src/hooks/use-theme.tsx
  packages/compass-components/src/index.ts
  packages/compass-connections/src/components/connections.tsx
  packages/compass-databases-navigation/src/collection-item.tsx
  packages/compass-databases-navigation/src/constants.tsx
  packages/compass-databases-navigation/src/database-item.tsx
  packages/compass-databases-navigation/src/icon-button.tsx
  packages/compass-databases-navigation/src/placeholder-item.tsx
  packages/compass-databases-navigation/src/tree-item.tsx
  packages/compass-home/src/components/home.tsx
  packages/compass-sidebar/src/components-legacy/sidebar/sidebar.jsx
  packages/compass-sidebar/src/components-legacy/sidebar/sidebar.module.less
  packages/compass-sidebar/src/components/sidebar.tsx
  packages/compass/src/main/menu.ts
Labels: feature flagged, feat

#3336 feat(sidebar): New sidebar title and favorite color area COMPASS-5961
  packages/compass-components/src/components/icon-button.tsx
  packages/compass-components/src/components/item-action-controls.tsx
  packages/compass-components/src/components/resizeable-sidebar.tsx
  packages/compass-components/src/index.ts
  packages/compass-databases-navigation/src/collection-item.tsx
  packages/compass-databases-navigation/src/database-item.tsx
  packages/compass-home/src/components/home.tsx
  packages/compass-sidebar/src/components-legacy/sidebar/sidebar.module.less
  packages/compass-sidebar/src/components/favorite-indicator.tsx
  packages/compass-sidebar/src/components/sidebar-title.tsx
  packages/compass-sidebar/src/components/sidebar.tsx
Labels: feature flagged, feat

#3351 feat(compass-query-bar): disable tab commands in ace editor for query bar for keyboard nav accessibility COMPASS-4900
  packages/compass-query-bar/src/components/option-editor.tsx
  packages/compass-query-bar/src/components/query-bar.spec.tsx
Labels: feature flagged, feat

#3357 fix(css) bring back the scrollbar css
  packages/compass-home/src/index.less
Labels: feature flagged, fix

#3352 feat(compass-aggregations): Update saved aggregations to open as popover COMPASS-5852
  packages/compass-aggregations/src/components/aggregations/aggregations.jsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.tsx
  packages/compass-aggregations/src/components/pipeline/pipeline.jsx
  packages/compass-aggregations/src/components/save-pipeline/index.js
  packages/compass-aggregations/src/components/save-pipeline/save-pipeline-card/save-pipeline-card.module.less
  packages/compass-aggregations/src/components/save-pipeline/save-pipeline.jsx
  packages/compass-aggregations/src/components/save-pipeline/save-pipeline.module.less
  packages/compass-aggregations/src/components/save-pipeline/save-pipeline.spec.jsx
  packages/compass-aggregations/src/components/saved-pipelines/save-pipeline-card/delete-pipeline-button.jsx
  packages/compass-aggregations/src/components/saved-pipelines/save-pipeline-card/delete-pipeline-button.module.less
  packages/compass-aggregations/src/components/saved-pipelines/save-pipeline-card/delete-pipeline-button.spec.jsx
  packages/compass-aggregations/src/components/saved-pipelines/save-pipeline-card/restore-pipeline-button.jsx
  packages/compass-aggregations/src/components/saved-pipelines/save-pipeline-card/restore-pipeline-button.module.less
  packages/compass-aggregations/src/components/saved-pipelines/save-pipeline-card/restore-pipeline-button.spec.jsx
  packages/compass-aggregations/src/components/saved-pipelines/save-pipeline-card/save-pipeline-card.jsx
  packages/compass-aggregations/src/components/saved-pipelines/save-pipeline-card/save-pipeline-card.module.less
  packages/compass-aggregations/src/components/saved-pipelines/save-pipeline-card/save-pipeline-card.spec.jsx
  packages/compass-aggregations/src/components/saved-pipelines/saved-pipelines.spec.jsx
  packages/compass-aggregations/src/components/saved-pipelines/saved-pipelines.tsx
  packages/compass-aggregations/src/modules/pipeline.ts
  packages/compass-aggregations/src/modules/saved-pipeline.js
  packages/compass-aggregations/src/modules/saved-pipeline.spec.ts
  packages/compass-aggregations/src/modules/saved-pipeline.ts
Labels: release notes, feat

#3355 feat(compass-crud): Add error message hint for crud timeout message COMPASS-4638
  packages/compass-crud/src/components/document-list.jsx
  packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
Labels: release notes, feat

#3359 feat(query-history, aggregations): Show namespace on saved queries and pipelines popovers COMPASS-6028
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.tsx
  packages/compass-aggregations/src/components/saved-pipelines/saved-pipelines.spec.jsx
  packages/compass-aggregations/src/components/saved-pipelines/saved-pipelines.tsx
  packages/compass-query-history/src/components/query-history/query-history.jsx
  packages/compass-query-history/src/components/toolbar/toolbar.spec.tsx
  packages/compass-query-history/src/components/toolbar/toolbar.tsx
Labels: release notes, feat

#3362 feat(sidebar): new sidebar db stats COMPASS-5962
  packages/compass-sidebar/src/components/db-stats.tsx
  packages/compass-sidebar/src/components/sidebar.tsx
Labels: feature flagged, feat

#3369 chore(query-bar): styling updates, white background on query bar area, no borders on inputs
  packages/compass-components/src/constants/mongodb-ace-theme-query.ts
  packages/compass-query-bar/src/components/option-editor.tsx
  packages/compass-query-bar/src/components/query-bar.tsx
  packages/compass-query-bar/src/components/query-option.tsx
Labels: feature flagged

#3376 fix(query-history): fix query history actions with feature flag COMPASS-6039
  packages/compass-query-history/src/components/query-history/query-history.module.less
  packages/compass-query-history/src/index.ts
Labels: feature flagged

#3345 fix(compass): include node-forge in unpacked node_modules COMPASS-5802
  packages/compass-e2e-tests/tests/connection.test.ts
  packages/compass/package.json
Labels: release notes, fix

#3374 fix(compass): adjust crypt shared library download script for M1 builds
  packages/compass/scripts/download-csfle.js
Labels: release notes, fix

#3378 fix(compass-home): hide collection submenu on disconnect COMPASS-6047
  packages/compass-home/src/components/home.tsx
Labels: release notes, fix

#3380 fix(indexes): align delete index modal text
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-indexes/src/components/drop-index-modal/drop-index-modal.jsx
  packages/compass-indexes/src/components/drop-index-modal/drop-index-modal.spec.jsx
Labels: release notes, fix

#3382 fix(hadron-build): drop lsb-core-noarch from rpm deps COMPASS-6025
  packages/hadron-build/lib/target.js
Labels: release notes, fix

#3381 fix(data-service): fully remove empty KMS provider options COMPASS-5930
  packages/data-service/src/connection-secrets.spec.ts
  packages/data-service/src/connection-secrets.ts
  packages/data-service/src/connection-storage.spec.ts
Labels: release notes, fix

#3386 fix(index-model): when expireAfterSeconds is 0 COMPASS-3073
  packages/index-model/lib/model.js
  packages/index-model/test/index.test.js
Labels: release notes, fix

#3385 fix(index-model): text index is not compound COMPASS-5386
  packages/index-model/lib/model.js
  packages/index-model/test/index.test.js
Labels: release notes, fix

#3388 fix(hadron-document): fix updating arrays with dots in names COMPASS-6011
  packages/hadron-document/src/object-generator.ts
  packages/hadron-document/test/document.test.ts
Labels: release notes, fix

#3392 feat: replace partial filter expression input with editor COMPASS-6017, COMPASS-6034
  packages/compass-components/src/components/collapsible-field-set.tsx
  packages/compass-indexes/src/components/create-index-actions/create-index-actions.spec.jsx
  packages/compass-indexes/src/components/create-index-actions/create-index-actions.tsx
  packages/compass-indexes/src/components/create-index-actions/index.ts
  packages/compass-indexes/src/components/create-index-fields/create-index-fields.spec.tsx
  packages/compass-indexes/src/components/create-index-form/columnstore-projection.tsx
  packages/compass-indexes/src/components/create-index-form/create-index-form.spec.jsx
  packages/compass-indexes/src/components/create-index-form/create-index-form.tsx
  packages/compass-indexes/src/components/create-index-form/partial-filter-expression.tsx
  packages/compass-indexes/src/components/create-index-form/wildcard-projection.tsx
  packages/compass-indexes/src/components/create-index-modal/create-index-modal.tsx
  packages/compass-indexes/src/modules/create-index/partial-filter-expression.spec.js
Labels: feature flagged, feat

#3391 feat(indexes): add sparse option COMPASS-1963
  packages/compass-indexes/src/components/create-index-form/create-index-form.spec.jsx
  packages/compass-indexes/src/components/create-index-form/create-index-form.tsx
  packages/compass-indexes/src/components/create-index-form/sparse-index.tsx
  packages/compass-indexes/src/components/create-index-modal/create-index-modal.tsx
  packages/compass-indexes/src/modules/create-index/index.spec.js
  packages/compass-indexes/src/modules/create-index/index.ts
  packages/compass-indexes/src/modules/create-index/is-sparse.ts
Labels: release notes, feat

#3394 feat(sidebar) Connection info modal for the new sidebar COMPASS-5966
  packages/compass-sidebar/src/components/connection-info-modal.tsx
  packages/compass-sidebar/src/components/sidebar-title.tsx
  packages/compass-sidebar/src/components/sidebar.tsx
  packages/compass-sidebar/src/stores/store.js
  packages/compass-sidebar/src/stores/store.spec.js
  packages/data-service/src/instance-detail-helper.spec.ts
  packages/data-service/src/instance-detail-helper.ts
  packages/data-service/src/run-command.ts
  packages/instance-model/index.d.ts
  packages/instance-model/lib/model.js
  packages/instance-model/lib/topology-type.js
Labels: feature flagged, feat

#3398 fix(legacy-sidebar): Don't inherit the dark theme from the old sidebar for its modals
  packages/compass-sidebar/src/components-legacy/non-genuine-warning-modal/non-genuine-warning-modal.jsx
  packages/compass-sidebar/src/components-legacy/sidebar-instance/sidebar-instance.jsx
  packages/compass-sidebar/src/components-legacy/sidebar/sidebar.jsx
Labels: bug, feature flagged, fix

#3404 fix(compass-crud): Hide document views when there are no documents
  packages/compass-crud/src/components/document-list.jsx
Labels: release notes, fix

#3401 fix(import-export): fix import deep json overwriting variables COMPASS-5971
  packages/compass-import-export/src/utils/dotnotation.spec.js
  packages/compass-import-export/src/utils/dotnotation.ts
  packages/compass-import-export/src/utils/import-apply-types-and-projection.js
  packages/compass-import-export/src/utils/import-apply-types-and-projection.spec.js
Labels: release notes, fix

#3406 feat(sidebar) copy over csfle/non-genuine markers and modals to the new sidebar
  packages/compass-components/src/components/modal-title.tsx
  packages/compass-sidebar/src/components/csfle-connection-modal.tsx
  packages/compass-sidebar/src/components/csfle-marker.tsx
  packages/compass-sidebar/src/components/non-genuine-marker.tsx
  packages/compass-sidebar/src/components/non-genuine-warning-modal.tsx
  packages/compass-sidebar/src/components/sidebar.tsx
Labels: feature flagged, feat

#3408 feat(sidebar): move db stats to the connection modal COMPASS-6079
  packages/compass-sidebar/src/components/connection-info-modal.tsx
  packages/compass-sidebar/src/components/csfle-marker.tsx
  packages/compass-sidebar/src/components/db-stats.tsx
  packages/compass-sidebar/src/components/non-genuine-marker.tsx
  packages/compass-sidebar/src/components/sidebar.tsx
  packages/compass-sidebar/src/stores/store.js
  packages/database-model/lib/model.js
  packages/instance-model/index.d.ts
Labels: feature flagged, feat

#3409 Fix little things
  packages/compass-sidebar/src/components/db-stats.tsx
  packages/compass-sidebar/src/components/navigation-items.tsx
Labels: feature flagged

#3413 feat(compass-indexes): only show columnstore index option for mongodb server >= 7 COMPASS-5970
  packages/compass-e2e-tests/tests/collection-indexes-tab.test.ts
  packages/compass-indexes/src/components/create-index-fields/create-index-fields.spec.tsx
  packages/compass-indexes/src/components/create-index-form/create-index-form.spec.jsx
  packages/compass-indexes/src/utils/has-columnstore-indexes-support.spec.ts
  packages/compass-indexes/src/utils/has-columnstore-indexes-support.ts
Labels: release notes, feat
