Repository mongodb-js/compass, pull requests merged in 2022-10, with the labels that each got.

#3534 fix(compass): move telemetry setup to main process entirely COMPASS-6113 COMPASS-6092
  packages/compass-e2e-tests/helpers/commands/set-feature.ts
  packages/compass-e2e-tests/tests/import-export-connections.test.ts
  packages/compass-e2e-tests/tests/logging.test.ts
  packages/compass-preferences-model/src/preferences.ts
  packages/compass/src/app/index.js
  packages/compass/src/main/application.ts
  packages/compass/src/main/setup-preferences-and-user-model.ts
  packages/compass/src/main/telemetry.ts
Labels: feature flagged, fix

#3580 fix(query-explain): open info links in browser COMPASS-6193
  packages/compass-explain-plan/src/components/summary-index-stat/summary-index-stat.jsx
  packages/compass-explain-plan/src/components/summary-stat/summary-stat.jsx
Labels: fix

#3577 feat(crud, hadron-react-components): update error styles in crud, remove unused status row component
  packages/compass-crud/src/components/crud-toolbar.spec.tsx
  packages/compass-crud/src/components/crud-toolbar.tsx
  packages/compass-crud/src/components/document-list.jsx
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass/src/app/styles/index.less
  packages/compass/src/app/styles/status-row.less
  packages/hadron-react-components/src/index.js
  packages/hadron-react-components/src/status-row.jsx
  packages/hadron-react-components/test/status-row.test.jsx
Labels: release notes, feat

#3574 fix(crud): menu not fully showing for field actions, remove old backgrounds COMPASS-6186
  packages/compass-components/src/components/document-list/document-edit-actions-footer.tsx
  packages/compass-components/src/components/keyline-card.tsx
  packages/compass-crud/src/components/document-json-view.less
  packages/compass-crud/src/components/document-list.less
  packages/compass-crud/src/components/document.less
  packages/compass-explain-plan/src/components/explain-summary/explain-summary.module.less
  packages/compass-schema/src/components/compass-schema/compass-schema.module.less
Labels: release notes, fix

#3583 feat: use rebranded monospace fonts everywhere and remove Akzidenz COMPASS-6187
  packages/compass/scripts/download-fonts.js
  packages/compass/src/app/styles/deprecated-bootstrap-styles/buttons.less
  packages/compass/src/app/styles/fonts.less
  packages/hadron-build/images/logo.svg
Labels: release notes, feat

#3594 feat(compass-editor): add autocompleter for aggregation, use autocompleter in import pipeline modal COMPASS-6175
  packages/compass-aggregations/src/components/aggregations/aggregations.jsx
  packages/compass-aggregations/src/components/pipeline/modals/import-pipeline.jsx
  packages/compass-aggregations/src/components/pipeline/modals/import-pipeline.spec.jsx
  packages/compass-aggregations/src/components/pipeline/modals/import-pipeline.tsx
  packages/compass-aggregations/src/components/pipeline/pipeline.jsx
  packages/compass-aggregations/src/typings.d.ts
  packages/compass-editor/src/ace/aggregation-autocompleter.test.ts
  packages/compass-editor/src/ace/aggregation-autocompleter.ts
  packages/compass-editor/src/ace/query-autocompleter.test.ts
  packages/compass-editor/src/ace/stage-autocompleter.test.ts
  packages/compass-editor/src/ace/stage-autocompleter.ts
  packages/compass-editor/src/ace/util.ts
  packages/compass-editor/src/ace/validation-autocompleter.test.ts
  packages/compass-editor/src/index.ts
  packages/compass-editor/src/types.ts
  packages/compass-editor/test/completer.ts
  packages/compass-editor/tsconfig.json
  packages/compass-query-bar/src/components/option-editor.tsx
Labels: release notes, feat

#3605 feat(pipeline-builder): pipeline builder toggle COMPASS-6169
  packages/compass-aggregations/src/components/aggregations/aggregations.jsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace.jsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace.module.less
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace.spec.jsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-workspace.spec.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-workspace.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/index.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
  packages/compass-aggregations/src/components/pipeline/pipeline.jsx
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-mode.ts
  packages/compass/src/index.d.ts
Labels: feature flagged, feat

#3624 fix(sidebar): hide create database button on readonly
  packages/compass-sidebar/src/components/navigation-items.spec.tsx
  packages/compass-sidebar/src/components/navigation-items.tsx
  packages/compass-sidebar/src/modules/databases.js
Labels: fix, no release notes

#3636 styles: style with theme in atlas help panel COMPASS-6231
  packages/compass-connections/src/components/form-help/form-help.tsx
  packages/connection-form/src/components/connect-form.tsx
Labels: no release notes

#3641 fix(ace-editor): remove margins from ace brackets
  packages/compass-editor/src/ace/theme.ts
Labels: release notes, fix

#3620 feat(pipeline-builder): pipeline text editor
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/index.spec.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/index.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-editor.spec.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-editor.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-preview.spec.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-preview.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-workspace.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
  packages/compass-aggregations/src/components/settings/settings.jsx
  packages/compass-aggregations/src/modules/import-pipeline.js
  packages/compass-aggregations/src/modules/import-pipeline.spec.js
  packages/compass-aggregations/src/modules/is-modified.js
  packages/compass-aggregations/src/modules/pipeline-builder/builder-helpers.ts
  packages/compass-aggregations/src/modules/pipeline-builder/index.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-builder.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-mode.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-parser/pipeline-parser.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-parser/stage-parser.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-parser/utils.ts
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
  packages/compass-aggregations/src/modules/pipeline-builder/stage.ts
  packages/compass-aggregations/src/modules/pipeline-builder/text-editor.spec.ts
  packages/compass-aggregations/src/modules/pipeline-builder/text-editor.ts
  packages/compass-aggregations/src/modules/saved-pipeline.ts
  packages/compass-editor/src/index.ts
Labels: feature flagged, feat

#3645 fix: close on click info modal close button
  packages/compass-shell/src/components/shell-info-modal/shell-info-modal.jsx
Labels: fix, no release notes

#3649 fix(settings): Make the settings modal a form modal
  packages/compass-components/src/components/modals/modal-header.tsx
  packages/compass-settings/src/components/modal.spec.tsx
  packages/compass-settings/src/components/modal.tsx
  packages/compass-settings/src/components/sidebar.tsx
Labels: fix, no release notes
