Repository mongodb-js/compass, pull requests merged in 2022-09, with the labels that each got.

#3418 feat: remove the COMPASS_CLUSTERED_COLLECTIONS feature flag COMPASS-6093
  packages/compass-e2e-tests/helpers/compass.ts
  packages/compass/src/index.d.ts
  packages/databases-collections/src/components/collection-fields/has-clustered-collection-support.js
  packages/databases-collections/src/components/collection-fields/has-clustered-collection-support.spec.js
Labels: release notes, feat

#3422 feat(connections): New connections sidebar COMPASS-6015
  packages/compass-components/src/components/icons/favorite-icon.tsx
  packages/compass-connections/src/components/connection-list/connection-list.tsx
  packages/compass-connections/src/components/connection-list/connection.tsx
  packages/compass-connections/src/components/connection-list/connections-title.tsx
  packages/compass-connections/src/components/connections.tsx
  packages/compass-sidebar/src/components/sidebar-title.tsx
  packages/compass-sidebar/src/components/sidebar.tsx
Labels: feature flagged, feat

#3430 feat(sidebar): Expand/Collapse the new sidebar COMPASS-5967
  packages/compass-components/src/components/resizeable-sidebar.tsx
  packages/compass-sidebar/src/components/navigation-items.tsx
  packages/compass-sidebar/src/components/sidebar-title.tsx
  packages/compass-sidebar/src/components/sidebar.tsx
  packages/compass-sidebar/src/modules/index.js
  packages/compass-sidebar/src/modules/is-expanded.ts
  packages/compass-sidebar/src/stores/store.js
  packages/compass/src/app/index.js
  packages/compass/src/main/menu.spec.ts
  packages/compass/src/main/menu.ts
Labels: feature flagged, feat

#3441 don't allow the icons to size down when things don't fit
  packages/compass-databases-navigation/src/tree-item.tsx
Labels: feature flagged

#3434 fix(storage-mixin): do not monkey-patch prototypes in SpliceDiskIpcBackend
  packages/storage-mixin/lib/backends/splice-disk-ipc.js
  packages/storage-mixin/lib/backends/splice-disk.js
Labels: release notes, fix

#3445 fix(collection): Make namespace not overflow width, add title to sidebar items COMPASS-6106
  packages/compass-collection/src/components/collection-header-actions/collection-header-actions.tsx
  packages/compass-collection/src/components/collection-header/collection-header.tsx
  packages/compass-databases-navigation/src/collection-item.tsx
  packages/compass-databases-navigation/src/database-item.tsx
Labels: release notes, fix

#3458 revert the bold effect on the old sidebar
  packages/compass-sidebar/src/components-legacy/sidebar/navigation-items.jsx
  packages/compass-sidebar/src/components-legacy/sidebar/sidebar.module.less
Labels: feature flagged

#3455 feat(compass-components): link to Compass FLE docs for encrypted values COMPASS-5633
  packages/compass-components/src/components/bson-value.spec.tsx
  packages/compass-components/src/components/bson-value.tsx
Labels: release notes, feat

#3466 feat(query-bar): update query options to 4 rows, make filter a link COMPASS-6088
  packages/compass-components/src/constants/mongodb-ace-theme-query.ts
  packages/compass-query-bar/src/components/query-bar-row.tsx
  packages/compass-query-bar/src/components/query-bar.spec.tsx
  packages/compass-query-bar/src/components/query-bar.tsx
  packages/compass-query-bar/src/components/query-option.tsx
  packages/compass-query-bar/src/components/query-options-grid.spec.tsx
  packages/compass-query-bar/src/components/query-options-grid.tsx
Labels: feature flagged, feat

#3454 feat(compass): add CLI connection import/export COMPASS-6073 COMPASS-6074
  packages/compass-e2e-tests/helpers/compass.ts
  packages/compass-e2e-tests/tests/import-export-connections.test.ts
  packages/compass/package.json
  packages/compass/src/main/application.ts
  packages/compass/src/main/import-export-connections.ts
  packages/compass/src/main/index.ts
  packages/connection-form/src/components/confirm-edit-connection-string.tsx
  packages/connection-form/src/components/connection-string-input.tsx
  packages/connection-model/lib/connection-collection.js
  packages/connection-model/lib/extended-model.js
  packages/data-service/src/encrypt.spec.ts
  packages/data-service/src/encrypt.ts
  packages/data-service/src/import-export-connection.spec.ts
  packages/data-service/src/import-export-connection.ts
  packages/data-service/src/index.ts
  packages/storage-mixin/lib/backends/splice-disk.js
Labels: release notes, feat

#3467 testing(e2e): port E2E tests to the new sidebar, invert the feature flag check COMPASS-6090
  packages/compass-connections/src/components/connection-list/connection-list.tsx
  packages/compass-connections/src/components/connections.tsx
  packages/compass-databases-navigation/src/database-item.tsx
  packages/compass-databases-navigation/src/placeholder-item.tsx
  packages/compass-e2e-tests/helpers/insert-data.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/in-use-encryption.test.ts
  packages/compass-e2e-tests/tests/instance-sidebar.test.ts
  packages/compass-sidebar/src/components/connection-info-modal.tsx
  packages/compass-sidebar/src/components/database-collection-filter.tsx
  packages/compass-sidebar/src/components/sidebar-title.tsx
  packages/compass-sidebar/src/plugin.jsx
Labels: release notes

#3474 feat(sidebar): New sidebar placeholders COMPASS-6098
  packages/compass-components/src/components/placeholder.tsx
  packages/compass/src/app/index.html
  packages/compass/src/app/styles/index.less
Labels: feature flagged, feat

#3402 feat(compass): flip the new toolbars feature flag, always show new toolbars COMPASS-5679
  packages/compass-collection/src/stores/context.tsx
  packages/compass-components/src/constants/mongodb-ace-theme-query.ts
  packages/compass-crud/src/components/document-json-view.less
  packages/compass-crud/src/components/document-list.jsx
  packages/compass-crud/src/components/document-list.less
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
  packages/compass-e2e-tests/tests/collection-import.test.ts
  packages/compass-e2e-tests/tests/connection.test.ts
  packages/compass-e2e-tests/tests/time-to-first-query.test.ts
  packages/compass-explain-plan/src/components/explain-states/explain-states.jsx
  packages/compass-explain-plan/src/components/explain-states/explain-states.spec.jsx
  packages/compass-explain-plan/src/components/explain-toolbar/explain-toolbar.spec.tsx
  packages/compass-explain-plan/src/components/explain-toolbar/explain-toolbar.tsx
  packages/compass-query-bar/src/components/query-bar.spec.tsx
  packages/compass-query-bar/src/plugin.jsx
  packages/compass-query-bar/src/plugin.spec.jsx
  packages/compass-query-history/src/index.ts
  packages/compass-schema/src/components/compass-schema/compass-schema.jsx
  packages/compass-schema/src/components/schema-toolbar/schema-toolbar.tsx
  packages/compass/src/index.d.ts
Labels: release notes, feat

#3475 feat(sidebar): show icons in the sidebar menus COMPASS-6081
  packages/compass-components/src/components/item-action-controls.tsx
  packages/compass-connections/src/components/connection-list/connection-menu.spec.tsx
  packages/compass-connections/src/components/connection-list/connection-menu.tsx
  packages/compass-crud/src/components/add-data-menu.tsx
  packages/compass-crud/src/components/legacy-toolbar.jsx
  packages/compass-databases-navigation/src/collection-item.tsx
  packages/compass-databases-navigation/src/databases-navigation-tree.spec.tsx
  packages/compass-query-bar/src/components/legacy-query-bar/query-bar.jsx
Labels: release notes, feat

#3479 fix(compass-schema): fix map rendering + add e2e tests COMPASS-6131
  packages/compass-e2e-tests/helpers/insert-data.ts
  packages/compass-e2e-tests/tests/collection-schema-tab.test.ts
  packages/compass-schema/src/components/field/field.jsx
Labels: release notes, fix

#3438 feat(compass-aggregations): update pipeline options to Leafy Green components COMPASS-6048
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-options/index.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-options/pipeline-collation.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-options/pipeline-collation.tsx
  packages/compass-aggregations/src/components/pipeline/collation-toolbar.jsx
  packages/compass-aggregations/src/components/pipeline/collation-toolbar.module.less
  packages/compass-aggregations/src/components/pipeline/collation-toolbar.spec.jsx
  packages/compass-aggregations/src/modules/max-time-ms.js
  packages/compass-aggregations/src/modules/max-time-ms.ts
  packages/compass-aggregations/src/modules/settings.ts
Labels: release notes, feat

#3470 fix(data-service): reconnect csfle client after collMod COMPASS-5989
  packages/data-service/src/connect-mongo-client.ts
  packages/data-service/src/data-service.spec.ts
  packages/data-service/src/data-service.ts
  packages/data-service/test/helpers.ts
Labels: release notes, fix

#3519 fix(crud): improve selection area for insert document editor
  packages/compass-crud/src/components/insert-json-document.jsx
  packages/compass-crud/src/components/insert-json-document.module.less
Labels: release notes, fix
