Repository mongodb-js/compass, pull requests merged in 2023-04, with the labels that each got.

#4215 feat(aggregations): button titles in stage toolbar COMPASS-6686
  packages/compass-aggregations/src/components/stage-toolbar/index.tsx
  packages/compass-aggregations/src/components/stage-toolbar/option-menu.tsx
Labels: release notes, feat

#4221 fix(query-bar): listen to query-history events in query-bar and open saved items COMPASS-6680 COMPASS-6681 COMPASS-6685
  packages/compass-query-bar/src/stores/query-bar-reducer.spec.ts
  packages/compass-query-bar/src/stores/query-bar-reducer.ts
  packages/compass-query-bar/src/stores/query-bar-store.spec.ts
  packages/compass-query-bar/src/stores/query-bar-store.ts
  packages/compass-query-history/src/stores/favorite-list-store.js
  packages/compass-query-history/src/stores/recent-list-store.js
Labels: release notes, fix

#4218 feat(compass-editor): add links to the documentation to the agg and stage autocompleter suggestions COMPASS-6688
  packages/compass-editor/src/codemirror/ace-compat-autocompleter.ts
  packages/compass-editor/src/codemirror/aggregation-autocompleter.ts
  packages/compass-editor/src/codemirror/stage-autocompleter.ts
  packages/compass-editor/src/codemirror/utils.ts
  packages/compass-editor/src/json-editor.tsx
Labels: release notes, feat

#4225 feat(stage-wizard): setup button and panel in aggregations toolbar COMPASS-6653
  packages/compass-aggregations/src/components/aggregation-side-panel/index.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/index.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/index.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-editor.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-workspace.spec.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-workspace.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
  packages/compass-aggregations/src/modules/index.ts
  packages/compass-aggregations/src/modules/side-panel.spec.ts
  packages/compass-aggregations/src/modules/side-panel.ts
  packages/compass-aggregations/src/stores/store.spec.ts
Labels: feature flagged, feat

#4208 fix(config): fix loading configuration file on windows, remove arg check COMPASS-6527
  packages/compass-preferences-model/src/global-config.ts
Labels: release notes, fix

#4228 fix(stage-wizard): show toggle button when feature flag is enabled
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
Labels: feature flagged, fix

#4229 feat(compass-crud): update add data icon to plus with circle from download COMPASS-6494
  packages/compass-crud/src/components/add-data-menu.tsx
Labels: release notes, feat

#4230 feat(stage-wizard): stage wizard card COMPASS-6654
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/index.ts
  packages/compass-aggregations/src/components/stage-wizard/index.spec.tsx
  packages/compass-aggregations/src/components/stage-wizard/index.tsx
Labels: feature flagged, feat

#4237 fix(compass-import-export): remove re-count when not available COMPASS-5179, COMPASS-6649
  packages/compass-import-export/src/modules/cursor-exporter.ts
  packages/compass-import-export/src/modules/export.spec.js
  packages/compass-import-export/src/modules/export.ts
Labels: release notes, fix

#4227 feat(stage-editor): adds support for wizard stages in stage-editor store: COMPASS-6676
  packages/compass-aggregations/src/components/aggregations/aggregations.spec.jsx
  packages/compass-aggregations/src/components/focus-mode/focus-mode-modal-header.spec.tsx
  packages/compass-aggregations/src/components/focus-mode/focus-mode-modal-header.tsx
  packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-editor.tsx
  packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-preview.tsx
  packages/compass-aggregations/src/components/stage-editor/stage-editor.tsx
  packages/compass-aggregations/src/components/stage-preview/index.tsx
  packages/compass-aggregations/src/components/stage-preview/output-stage-preview.tsx
  packages/compass-aggregations/src/components/stage-preview/stage-preview-header.tsx
  packages/compass-aggregations/src/components/stage-toolbar/index.spec.tsx
  packages/compass-aggregations/src/components/stage-toolbar/index.tsx
  packages/compass-aggregations/src/components/stage-toolbar/option-menu.tsx
  packages/compass-aggregations/src/components/stage-toolbar/stage-collapser.tsx
  packages/compass-aggregations/src/components/stage-toolbar/stage-operator-select.tsx
  packages/compass-aggregations/src/components/stage-toolbar/toggle-stage.tsx
  packages/compass-aggregations/src/components/stage.tsx
  packages/compass-aggregations/src/modules/focus-mode.ts
  packages/compass-aggregations/src/modules/pipeline-builder/builder-helpers.ts
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.spec.ts
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
  packages/compass-aggregations/src/modules/pipeline-builder/stage-ids.ts
  packages/compass-aggregations/src/modules/pipeline-builder/stage.ts
  packages/compass-aggregations/src/stores/store.ts
Labels: feature flagged, feat, no release notes

#4239 feat(stage-wizard): add sort form COMPASS-6655
  packages/compass-aggregations/src/components/aggregation-side-panel/feedback-link.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/index.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/index.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/index.ts
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/sort/sort.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/sort/sort.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/use-case-list.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace.spec.jsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace.tsx
  packages/compass-aggregations/src/components/stage-wizard/index.spec.tsx
  packages/compass-aggregations/src/components/stage-wizard/index.tsx
  packages/compass-aggregations/src/modules/pipeline-builder/builder-helpers.spec.ts
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.spec.ts
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
  packages/compass-aggregations/src/modules/side-panel.ts
  packages/compass-aggregations/src/stores/store.spec.ts
  packages/compass-aggregations/src/stores/store.ts
  packages/compass-components/src/components/combobox-with-custom-option.tsx
  packages/compass-components/src/components/combobox-with-custom-options.spec.tsx
  packages/compass-components/src/index.ts
Labels: feature flagged, feat

#4246 feat(import): Import progress COMPASS-6721
  packages/compass-import-export/src/components/import-toast.tsx
  packages/compass-import-export/src/csv/csv-utils.spec.ts
  packages/compass-import-export/src/csv/csv-utils.ts
  packages/compass-import-export/src/modules/import.ts
Labels: release notes, feat

#4244 feat(stage-wizard): telemetry COMPASS-6656
  packages/compass-aggregations/src/components/aggregation-side-panel/index.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
Labels: feature flagged, feat

#4253 feat(export): Map default to our semi-relaxed / compass EJSON style, test with all bson types COMPASS-6708
  packages/compass-import-export/src/export/export-json.spec.ts
  packages/compass-import-export/src/export/export-json.ts
  packages/compass-import-export/test/docs/all-bson-types.exported.canonical.ejson
  packages/compass-import-export/test/docs/all-bson-types.exported.default.ejson
  packages/compass-import-export/test/docs/all-bson-types.exported.relaxed.ejson
  packages/compass-import-export/test/json/complex.exported.ejson
  packages/hadron-document/src/index.ts
Labels: feat, no release notes

#4257 chore(e2e): disable CSFLE tests on latest-alpha
  packages/compass-e2e-tests/tests/in-use-encryption.test.ts
Labels: no release notes

#4247 feat: update new connection text to new window COMPASS-6723
  packages/compass/src/main/menu.spec.ts
  packages/compass/src/main/menu.ts
Labels: release notes, feat

#4248 fix(compass-query-bar): show error border when focused COMPASS-6724
  packages/compass-query-bar/src/components/option-editor.tsx
Labels: release notes, fix

#4243 feat(stage-wizard): sortable wizard card
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/sort/sort.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/index.js
  packages/compass-aggregations/src/components/pipeline-builder-workspace/index.spec.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/index.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace/index.spec.jsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace/index.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace/sortable-list.tsx
  packages/compass-aggregations/src/components/stage-wizard/index.spec.tsx
  packages/compass-aggregations/src/components/stage-wizard/index.tsx
  packages/compass-aggregations/src/components/stage.tsx
Labels: feature flagged, feat

#4262 feat(compass-import-export): add export modal COMPASS-6577
  packages/compass-collection/package.json
  packages/compass-collection/src/stores/index.ts
  packages/compass-crud/src/components/crud-toolbar.tsx
  packages/compass-crud/src/components/insert-document-dialog.tsx
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-import-export/src/components/export-code-view.spec.tsx
  packages/compass-import-export/src/components/export-code-view.tsx
  packages/compass-import-export/src/components/export-field-options.tsx
  packages/compass-import-export/src/components/export-in-progress-modal.tsx
  packages/compass-import-export/src/components/export-modal.tsx
  packages/compass-import-export/src/components/export-select-fields.spec.tsx
  packages/compass-import-export/src/components/export-select-fields.tsx
  packages/compass-import-export/src/components/import-in-progress-modal.tsx
  packages/compass-import-export/src/components/in-progress-modal.tsx
  packages/compass-import-export/src/export-plugin.tsx
  packages/compass-import-export/src/export/gather-fields.spec.ts
  packages/compass-import-export/src/export/gather-fields.ts
  packages/compass-import-export/src/import-plugin.tsx
  packages/compass-import-export/src/index.ts
  packages/compass-import-export/src/modules/export.spec.ts
  packages/compass-import-export/src/modules/export.ts
  packages/compass-import-export/src/stores/export-store.ts
  packages/compass-import-export/src/utils/get-shell-js.spec.js
  packages/compass-import-export/src/utils/get-shell-js.spec.ts
  packages/compass-import-export/src/utils/get-shell-js.ts
  packages/compass-import-export/src/utils/query-has-projection.ts
Labels: feature flagged, feat

#4268 feat(stage-wizard): dynamic stage wizard fields
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/index.ts
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/sort/sort.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/use-case-list.tsx
  packages/compass-aggregations/src/components/stage-wizard/index.spec.tsx
  packages/compass-aggregations/src/components/stage-wizard/index.tsx
  packages/compass-aggregations/src/utils/get-schema.spec.ts
  packages/compass-aggregations/src/utils/get-schema.ts
Labels: feature flagged, feat

#4266 fix: compass readonly allows to drop namespaces from the sidebar COMPASS-6687
  packages/compass-databases-navigation/src/databases-navigation-tree.tsx
  packages/compass-sidebar/src/components/sidebar-databases-navigation.tsx
Labels: release notes, fix

#4270 fix(databases-collections-list): fixes the problem of refresh button on collection tab not refreshing the collection stats - COMPASS-6738
  packages/compass-app-stores/src/stores/instance-store.js
Labels: release notes, fix

#4272 fix(compass-components): fixes custom options combobox not remembering previously selected custom options
  packages/compass-components/src/components/combobox-with-custom-option.tsx
Labels: fix, no release notes

#4274 fix(compass-preferences-model): update windows config file fetching location one folder up COMPASS-6527
  packages/compass-preferences-model/src/global-config.ts
Labels: release notes, fix

#4260 feat(compass-aggregations): adds a project form to support $project use-cases in aggregation wizard - COMPASS-6658
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/index.ts
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/project/project.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/project/project.tsx
  packages/compass-components/src/components/combobox-with-custom-option.tsx
  packages/compass-components/src/components/combobox/Combobox.tsx
Labels: feature flagged, feat, no release notes

#4278 fix(import): If listCSVFields() or analyzeCSVFields() fails it will display the error in the modal COMPASS-6737
  packages/compass-e2e-tests/fixtures/latin1.csv.gz
  packages/compass-e2e-tests/helpers/insert-data.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-import.test.ts
  packages/compass-import-export/src/components/import-modal.tsx
  packages/compass-import-export/src/modules/import.ts
Labels: release notes, fix

#4275 feat(compass-import-export): run export and show progress toasts COMPASS-6580
  packages/compass-collection/src/stores/index.ts
  packages/compass-crud/src/components/crud-toolbar.tsx
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-import-export/src/components/export-modal.tsx
  packages/compass-import-export/src/components/export-toast.tsx
  packages/compass-import-export/src/components/import-toast.tsx
  packages/compass-import-export/src/components/toast-body.tsx
  packages/compass-import-export/src/export-plugin.tsx
  packages/compass-import-export/src/export/export-json.spec.ts
  packages/compass-import-export/src/modules/export.spec.ts
  packages/compass-import-export/src/modules/export.ts
  packages/compass-settings/src/components/settings/featureflags.tsx
Labels: feature flagged, feat

#4273 feat(import): Surface type warnings COMPASS-6543
  packages/compass-import-export/src/components/import-preview.tsx
  packages/compass-import-export/src/csv/csv-types.ts
  packages/compass-import-export/src/csv/csv-utils.spec.ts
  packages/compass-import-export/src/csv/csv-utils.ts
  packages/compass-import-export/src/import/analyze-csv-fields.ts
  packages/compass-import-export/src/import/guess-filetype.ts
  packages/compass-import-export/src/modules/import.ts
  packages/compass-import-export/test/csv/array.analyzed.json
  packages/compass-import-export/test/csv/number-transform.analyzed.json
Labels: release notes, feat

#4289 fix: update duplicated log ids
  packages/compass-import-export/src/modules/export.ts
Labels: fix, no release notes

#4286 feat(stage-wizard): basic group implementation COMPASS-6661
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/basic-group.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/basic-group.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/index.ts
Labels: feature flagged, feat

#4294 fix(export): fix exported CSV field order for large sparse arrays COMPASS-6761
  packages/compass-import-export/src/export/export-utils.spec.ts
  packages/compass-import-export/src/export/export-utils.ts
  packages/compass-import-export/test/csv/complex.exported.csv
  packages/compass-import-export/test/json/complex.exported.csv
Labels: feature flagged, fix

#4288 feat(compass-import-export): show an add more fields button when more fields to show COMPASS-6762
  packages/compass-import-export/src/components/export-select-fields.spec.tsx
  packages/compass-import-export/src/components/export-select-fields.tsx
Labels: feature flagged, feat

#4295 feat(stage-wizard): statistical group use-case COMPASS-6662
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/basic-group.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/basic-group.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/group-with-statistics.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/group-with-statistics.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/index.ts
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/lookup/lookup.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/project/project.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/sort/sort.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/utils.spec.ts
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/utils.ts
  packages/compass-aggregations/test/form-helper.ts
Labels: feature flagged, feat

#4309 feat(import): Combine array fields into one in the import CSV preview COMPASS-6766
  packages/compass-e2e-tests/fixtures/array-documents.csv.gz
  packages/compass-e2e-tests/helpers/insert-data.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-import.test.ts
  packages/compass-import-export/src/components/import-modal.tsx
  packages/compass-import-export/src/components/import-preview.tsx
  packages/compass-import-export/src/csv/csv-utils.spec.ts
  packages/compass-import-export/src/csv/csv-utils.ts
  packages/compass-import-export/src/export/export-utils.spec.ts
  packages/compass-import-export/src/import/analyze-csv-fields.spec.ts
  packages/compass-import-export/src/import/import-csv.spec.ts
  packages/compass-import-export/src/import/list-csv-fields.spec.ts
  packages/compass-import-export/src/modules/import.ts
  packages/compass-import-export/test/csv/array.analyzed.json
  packages/compass-import-export/test/csv/array.preview.json
  packages/compass-import-export/test/csv/complex.analyzed.json
  packages/compass-import-export/test/csv/complex.exported.csv
  packages/compass-import-export/test/csv/complex.preview.json
Labels: release notes, feat

#4310 chore(compass-import-export, compass-e2e-tests): add export e2e tests COMPASS-6731
  packages/compass-crud/src/components/crud-toolbar.tsx
  packages/compass-e2e-tests/helpers/commands/set-export-filename.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-export-legacy.test.ts
  packages/compass-e2e-tests/tests/collection-export.test.ts
  packages/compass-e2e-tests/tests/collection-import.test.ts
  packages/compass-import-export/src/components/export-code-view.spec.tsx
  packages/compass-import-export/src/components/export-code-view.tsx
  packages/compass-import-export/src/components/export-field-options.tsx
  packages/compass-import-export/src/components/export-modal.tsx
  packages/compass-import-export/src/components/export-select-fields.tsx
  packages/compass-import-export/src/components/legacy/export-modal.tsx
  packages/compass-import-export/src/modules/export.ts
  packages/compass/src/index.d.ts
  packages/compass/src/main/index.ts
Labels: feature flagged
