Repository mongodb-js/compass, pull requests merged in 2023-05, with the labels that each got.

#4314 fix(compass-import-export): show cancel button on export aggregation
  packages/compass-import-export/src/components/export-modal.spec.tsx
  packages/compass-import-export/src/components/export-modal.tsx
Labels: feature flagged, fix

#4315 chore(compass-e2e-tests, compass-import-export): add export e2e tests COMPASS-6731
  packages/compass-e2e-tests/helpers/insert-data.ts
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
  packages/compass-e2e-tests/tests/collection-export-legacy.test.ts
  packages/compass-e2e-tests/tests/collection-export.test.ts
  packages/compass-e2e-tests/tests/collection-import.test.ts
  packages/compass-import-export/src/components/export-code-view.spec.tsx
  packages/compass-import-export/src/export/export-csv.ts
  packages/compass-import-export/src/export/export-json.spec.ts
  packages/compass-import-export/src/export/export-json.ts
  packages/compass-import-export/src/import/import-csv.ts
  packages/compass-import-export/src/import/import-json.ts
  packages/compass-import-export/src/modules/export.ts
  packages/compass-import-export/src/utils/get-shell-js.spec.ts
  packages/compass-import-export/src/utils/get-shell-js.ts
  packages/compass-import-export/src/utils/query-has-projection.spec.ts
Labels: feature flagged

#4321 feat(stage-wizard): group with subsets COMPASS-6663
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/basic-group.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/group-with-statistics.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/group-with-statistics.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/group-with-subset.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/group-with-subset.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/index.ts
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/sort/sort.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/utils.spec.ts
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/utils.ts
  packages/compass-aggregations/test/form-helper.ts
Labels: feature flagged, feat

#4347 fix(stage-wizard): lookup changes COMPASS-6770
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/lookup/lookup.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/lookup/lookup.tsx
  packages/compass-aggregations/src/modules/collections-fields.spec.ts
  packages/compass-aggregations/src/modules/collections-fields.ts
Labels: feature flagged, fix

#4358 fix(import): fix guessFileType() when JSON fails and CSV lines are huge
  packages/compass-import-export/src/import/guess-filetype.spec.ts
  packages/compass-import-export/src/import/guess-filetype.ts
  packages/compass-import-export/test/csv/many-columns.analyzed.json
  packages/compass-import-export/test/csv/many-columns.csv
  packages/compass-import-export/test/csv/many-columns.exported.csv
  packages/compass-import-export/test/csv/many-columns.gathered.json
  packages/compass-import-export/test/csv/many-columns.imported.ejson
  packages/compass-import-export/test/csv/many-columns.preview.json
  packages/compass-import-export/test/fixtures.ts
Labels: release notes, fix

#4359 fix(compass-import-export): flush import progress throttle on import error
  packages/compass-import-export/src/modules/import.ts
Labels: release notes, fix

#4360 fix(compass-import-export): fix export gather fields fixture
  packages/compass-import-export/test/csv/many-columns.gathered.json
Labels: fix, no release notes

#4355 feat(compass-aggregations): refactor for get-schema to also add type information - COMPASS-6793
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/index.ts
  packages/compass-aggregations/src/components/stage-wizard/index.tsx
  packages/compass-aggregations/src/modules/collections-fields.ts
  packages/compass-aggregations/src/utils/get-schema.spec.ts
  packages/compass-aggregations/src/utils/get-schema.ts
Labels: feature flagged, feat

#4361 fix: wrap schema analysis telemetry computation in try/catch HELP-45308
  packages/compass-logging/src/logger.ts
  packages/compass-schema/src/stores/store.js
Labels: fix, no release notes

#4364 fix(user-preferences): feature flag default values COMPASS-6525
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
  packages/compass-home/src/components/home.tsx
  packages/compass-preferences-model/src/preferences.ts
  packages/compass-settings/src/components/settings/featureflags.tsx
  packages/compass/src/app/theme.ts
  packages/connection-form/src/components/advanced-options-tabs/csfle-tab/csfle-tab.tsx
Labels: release notes, fix

#4340 fix: allow updates on a sharded collection COMPASS-6058
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
  packages/data-service/src/data-service.ts
Labels: release notes, fix

#4357 chore(stage-wizard): refactor fields combobox COMPASS-6769
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/field-combobox.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/field-combobox.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/basic-group.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/basic-group.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/group-with-statistics.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/group-with-statistics.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/group-with-subset.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/lookup/lookup.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/match/match-condition-form.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/match/match-condition-form.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/match/match-group-form.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/match/match-group-form.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/match/match.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/project/project.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/project/project.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/sort/sort.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/sort/sort.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/utils.ts
  packages/compass-components/src/components/combobox-with-custom-option.tsx
  packages/compass-components/src/components/combobox-with-custom-options.spec.tsx
  packages/compass-components/src/components/combobox/Combobox.tsx
  packages/compass-components/src/components/list-editor.tsx
  packages/compass-e2e-tests/helpers/commands/set-combo-box-value.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
Labels: feature flagged, fix

#4373 refactor: fallback to modifyOneMethod with query COMPASS-6058
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
Labels: no release notes

#4375 fix(import): Detect line breaks, pass it on to papaparse COMPASS-6819
  packages/compass-e2e-tests/tests/collection-import.test.ts
  packages/compass-import-export/scripts/analyze-csv.ts
  packages/compass-import-export/src/components/import-modal.tsx
  packages/compass-import-export/src/components/import-options.tsx
  packages/compass-import-export/src/csv/csv-types.ts
  packages/compass-import-export/src/export/export-csv.spec.ts
  packages/compass-import-export/src/export/gather-fields.spec.ts
  packages/compass-import-export/src/import/analyze-csv-fields.spec.ts
  packages/compass-import-export/src/import/analyze-csv-fields.ts
  packages/compass-import-export/src/import/guess-filetype.spec.ts
  packages/compass-import-export/src/import/guess-filetype.ts
  packages/compass-import-export/src/import/import-csv.spec.ts
  packages/compass-import-export/src/import/import-csv.ts
  packages/compass-import-export/src/import/list-csv-fields.spec.ts
  packages/compass-import-export/src/import/list-csv-fields.ts
  packages/compass-import-export/src/modules/import.ts
  packages/compass-import-export/test/csv/linebreaks.analyzed.json
  packages/compass-import-export/test/csv/linebreaks.csv
  packages/compass-import-export/test/csv/linebreaks.exported.csv
  packages/compass-import-export/test/csv/linebreaks.gathered.json
  packages/compass-import-export/test/csv/linebreaks.imported.ejson
  packages/compass-import-export/test/csv/linebreaks.preview.json
  packages/compass-import-export/test/fixtures.ts
Labels: release notes, fix

#4384 fix(compass-query-bar): update reset on query bar to reset results and emit query-changed COMPASS-6805
  packages/compass-query-bar/src/stores/query-bar-reducer.spec.ts
  packages/compass-query-bar/src/stores/query-bar-reducer.ts
Labels: release notes, fix

#4386 feat(compass-preferences-model, connection-form, compass-settings): toggle state of "Edit connection string" in connection form is now judged also based on the new global preference
  packages/compass-preferences-model/src/preferences.ts
  packages/connection-form/src/components/connect-form.spec.tsx
  packages/connection-form/src/components/connect-form.tsx
  packages/connection-form/src/hooks/use-connect-form.ts
Labels: release notes, feat

#4397 chore(import): work around the flake by throwing on errors and then ignoring the empty output
  packages/compass-import-export/src/import/import-csv.spec.ts
Labels: no release notes

#4374 feat(compass-aggregation): adds drag-n-drop for use-cases available in sidepanel
  packages/compass-aggregations/src/components/add-stage/add-stage.spec.tsx
  packages/compass-aggregations/src/components/add-stage/add-stage.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/use-case-card.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/index.spec.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/index.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/index.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace/dnd-wrapper.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace/index.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace/sortable-list.tsx
  packages/compass-aggregations/src/components/use-case-droppable-area/index.spec.tsx
  packages/compass-aggregations/src/components/use-case-droppable-area/index.tsx
  packages/compass-components/src/components/keyline-card.tsx
Labels: feature flagged, feat

#4412 feat(preferences): enable "Modern Dark Mode" by default
  packages/compass-preferences-model/src/preferences.ts
Labels: release notes, feat

#4346 feat(stage-wizard): guide cues COMPASS-6664
  packages/compass-aggregations/src/components/aggregation-side-panel/index.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/index.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
  packages/compass-aggregations/src/components/stage-toolbar/index.spec.tsx
  packages/compass-aggregations/src/components/stage-toolbar/index.tsx
  packages/compass-aggregations/src/components/stage.tsx
  packages/compass-aggregations/src/components/use-guide-cue.ts
  packages/compass-aggregations/src/utils/local-storage.ts
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
Labels: feature flagged, feat

#4423 chore: Skip connects to kerberosCrossRealm for now
  packages/data-service/src/connect.spec.ts
Labels: no release notes

#4417 feat(compass-import-export): add types docs link to import preview COMPASS-6632
  packages/compass-import-export/src/components/import-preview.tsx
Labels: release notes, feat

#4408 feat(databases-collections): open collection in new tab shortcut
  packages/compass-databases-navigation/src/collection-item.tsx
Labels: release notes, feat

#4418 feat(stage-wizard): scroll to added wizard COMPASS-6740
  configs/mocha-config-compass/register/jsdom-global-register.js
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace/sortable-list.tsx
Labels: feature flagged, feat

#4433 fix(stage-wizard): reduce resizer height to accomodate for padding
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace/index.tsx
Labels: feature flagged, fix

#4422 feat(compass-aggregations): adds support for nested groups in $match stage wizard - COMPASS-6778
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/match/fixtures.ts
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/match/match-condition-form.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/match/match-group-form.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/match/match-group-form.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/match/match.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/match/match.tsx
  packages/compass-aggregations/test/sample-fields.ts
Labels: feature flagged, feat

#4441 fix(compass-aggregations): fixes static light background issue in dark mode for match stage wizard
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/match/match-group-form.tsx
Labels: feature flagged, fix, no release notes

#4440 fix(compass-aggregations): fixes "Incomplete string escaping or encoding" reported in code scanning alerts
  packages/compass-aggregations/src/components/aggregation-side-panel/index.tsx
Labels: fix, no release notes

#4445 fix(webpack-config): externalize built-in node modules with node: schema for web target
  configs/webpack-config-compass/src/index.ts
Labels: fix, no release notes
