Repository mongodb-js/compass, pull requests merged in 2023-12, with the labels that each got.

#5178 feat(crud): telemetry for bulk operations COMPASS-7388
  packages/compass-crud/src/components/bulk-delete-modal.tsx
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-e2e-tests/tests/collection-bulk-delete.test.ts
  packages/compass-e2e-tests/tests/collection-bulk-update.test.ts
  packages/compass-export-to-language/src/components/modal.tsx
  packages/compass-query-bar/src/components/query-history/favorite-list.tsx
  packages/compass-query-bar/src/components/query-history/recent-list.tsx
Labels: feature flagged, feat

#5183 feat(components): add file input backend provider to allow different file backend environments VSCODE-484
  package-lock.json
  packages/compass-components/src/components/file-input.spec.tsx
  packages/compass-components/src/components/file-input.tsx
  packages/compass-components/src/index.ts
  packages/compass-connection-import-export/package.json
  packages/compass-connection-import-export/src/components/file-input.tsx
  packages/compass-home/src/components/home.tsx
  packages/compass-import-export/src/components/export-modal.tsx
  packages/compass-import-export/src/components/import-file-input.tsx
  packages/compass-indexes/src/components/search-indexes-modals/create-search-index-modal.spec.tsx
  packages/connection-form/src/components/advanced-options-tabs/ssh-tunnel-tab/ssh-tunnel-identity.tsx
  packages/connection-form/src/components/advanced-options-tabs/tls-ssl-tab/tls-certificate-authority.tsx
  packages/connection-form/src/components/advanced-options-tabs/tls-ssl-tab/tls-client-certificate.tsx
Labels: feat, no release notes

#5174 feat(atlas-service): migrate from keytar COMPASS-7491
  package-lock.json
  packages/atlas-service/package.json
  packages/atlas-service/src/main.ts
  packages/atlas-service/src/oidc-plugin-logger.ts
  packages/atlas-service/src/renderer.ts
  packages/atlas-service/src/secret-store.ts
  packages/atlas-service/src/store/atlas-signin-reducer.ts
  packages/atlas-service/src/user-config-store.spec.ts
  packages/atlas-service/src/user-config-store.ts
  packages/atlas-service/src/util.ts
Labels: release notes, feat

#5195 fix(connection-form): use ejson shell parser with strict mode on csfle COMPASS-7496
  package-lock.json
  packages/connection-form/package.json
  packages/connection-form/src/utils/csfle-handler.ts
Labels: fix, no release notes

#5194 fix(compass-shell): properly render syntax errors in embedded shell COMPASS-7497
  package-lock.json
  packages/compass-shell/package.json
  packages/compass/package.json
Labels: release notes, fix

#5207 chore: allow type only imports for 'mongodb' package in connection-form
  packages/connection-form/.eslintrc.js
Labels: no release notes

#5217 fix(connection-form): include OIDC in `$external` auth mechanism list COMPASS-7512
  packages/compass-e2e-tests/tests/connection-form.test.ts
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.spec.tsx
  packages/connection-form/src/utils/authentication-handler.spec.ts
  packages/connection-form/src/utils/authentication-handler.ts
Labels: release notes, fix

#5209 feat: add ChangeView component to bulk update preview
  .gitattributes
  package-lock.json
  packages/compass-crud/package.json
  packages/compass-crud/src/components/bulk-update-dialog.tsx
  packages/compass-crud/src/components/change-view/bson-utils.ts
  packages/compass-crud/src/components/change-view/change-view.spec.tsx
  packages/compass-crud/src/components/change-view/change-view.tsx
  packages/compass-crud/src/components/change-view/index.ts
  packages/compass-crud/src/components/change-view/shape-utils.ts
  packages/compass-crud/src/components/change-view/unified-document.spec.ts
  packages/compass-crud/src/components/change-view/unified-document.ts
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-crud/test/before-after-fixtures.ts
  packages/compass-crud/test/fixture-results/all_types_all_types_add.json
  packages/compass-crud/test/fixture-results/all_types_all_types_changed.json
  packages/compass-crud/test/fixture-results/all_types_all_types_identical.json
  packages/compass-crud/test/fixture-results/all_types_all_types_remove.json
  packages/compass-crud/test/fixture-results/all_types_small_change.json
  packages/compass-crud/test/fixture-results/array_changes_add_array_to_array.json
  packages/compass-crud/test/fixture-results/array_changes_add_object_to_array.json
  packages/compass-crud/test/fixture-results/array_changes_add_simple_value_to_array.json
  packages/compass-crud/test/fixture-results/array_changes_remove_array_from_array.json
  packages/compass-crud/test/fixture-results/array_changes_remove_object_from_array.json
  packages/compass-crud/test/fixture-results/array_changes_remove_simple_value_from_array.json
  packages/compass-crud/test/fixture-results/array_changes_simple_array.json
  packages/compass-crud/test/fixture-results/bson_type_change.json
  packages/compass-crud/test/fixture-results/nested_object_changes_nested_object_array_array_simple.json
  packages/compass-crud/test/fixture-results/nested_object_changes_nested_object_array_simple.json
  packages/compass-crud/test/fixture-results/nested_object_changes_nested_object_simple.json
  packages/compass-crud/test/fixture-results/objects_in_arrays_add_number_next_to_object_in_array.json
  packages/compass-crud/test/fixture-results/objects_in_arrays_object_inside_array_changed.json
  packages/compass-crud/test/fixture-results/objects_in_arrays_object_value_nested_in_an_array.json
  packages/compass-crud/test/fixture-results/objects_in_arrays_remove_number_next_to_object_in_array.json
  packages/compass-crud/test/fixture-results/shape_changes_array_to_object.json
  packages/compass-crud/test/fixture-results/shape_changes_array_to_simple.json
  packages/compass-crud/test/fixture-results/shape_changes_object_to_array.json
  packages/compass-crud/test/fixture-results/shape_changes_object_to_simple.json
  packages/compass-crud/test/fixture-results/shape_changes_simple_to_array.json
  packages/compass-crud/test/fixture-results/shape_changes_simple_to_object.json
  packages/compass-crud/test/fixture-results/simple_add_field.json
  packages/compass-crud/test/fixture-results/simple_different_simple_types.json
  packages/compass-crud/test/fixture-results/simple_remove_field.json
  packages/compass-crud/test/fixture-results/simple_same_simple_type.json
  packages/compass-crud/test/fixture-results/simple_simple_add.json
  packages/compass-crud/test/fixture-results/simple_simple_remove.json
  packages/compass-crud/test/fixture-results/stress_tests_airbnb.json
  packages/compass-e2e-tests/tests/collection-bulk-update.test.ts
  packages/data-service/src/data-service.spec.ts
  packages/data-service/src/data-service.ts
Labels: feature flagged, feat

#5219 feat: close toast when the refresh button is clicked COMPASS-7514
  packages/compass-crud/src/components/bulk-actions-toasts.spec.tsx
  packages/compass-crud/src/components/bulk-actions-toasts.tsx
Labels: feature flagged, feat, no release notes

#5231 fix(crud): clear the bulk update syntax error when update preview is not supported and parsing succeeds COMPASS-7522
  package-lock.json
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
Labels: feature flagged, fix

#5232 fix(crud): clone the bulk delete preview docs from the ones in the list COMPASS-7521
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
Labels: feature flagged, fix

#5235 feat(sidebar): disable clicking on the performance tab when unsupported in Atlas
  package-lock.json
  packages/compass-home/src/index.spec.tsx
  packages/compass-sidebar/package.json
  packages/compass-sidebar/src/components/navigation-items.spec.tsx
  packages/compass-sidebar/src/components/navigation-items.tsx
  packages/compass-sidebar/src/index.ts
  packages/compass-sidebar/src/modules/index.ts
  packages/compass-sidebar/src/modules/is-performance-tab-supported.ts
  packages/compass-sidebar/src/stores/store.spec.ts
  packages/compass-sidebar/src/stores/store.ts
Labels: release notes, feat

#5241 fix(aggregations): pass object to the get schema; make sure get schema handles recursive deps
  packages/compass-aggregations/src/components/stage-wizard/index.tsx
  packages/compass-aggregations/src/utils/get-schema.spec.ts
  packages/compass-aggregations/src/utils/get-schema.ts
Labels: fix, no release notes

#5246 feat(crud): release support for bulk update and bulk delete operations COMPASS-7329 COMPASS-7330
  packages/compass-preferences-model/src/feature-flags.ts
Labels: release notes, feat

#5252 feat(crud): disable the save button if the update query is invalid
  packages/compass-crud/src/components/bulk-update-modal.tsx
Labels: feat, no release notes

#5251 fix(bulk-update): remove timeout on error toast
  packages/compass-crud/src/components/bulk-actions-toasts.tsx
Labels: fix, no release notes

#5254 fix(instance): fix namespace stats refresh after document update
  packages/compass-app-stores/src/stores/instance-store.ts
  packages/compass-e2e-tests/tests/collection-import.test.ts
Labels: release notes, fix

#5258 fix(crud): scroll the bulk update preview without its heading
  packages/compass-crud/src/components/bulk-update-modal.tsx
Labels: fix, no release notes

#5253 fix(crud): clear bulk update/write states and abort in flight bulk update previews when changing the collection
  packages/compass-crud/src/stores/crud-store.ts
Labels: release notes, fix

#5249 feat(compass-web): create browser-compatible compass package COMPASS-7413
  configs/webpack-config-compass/polyfills/@emotion/server/create-instance/index.js
  configs/webpack-config-compass/src/index.ts
  package-lock.json
  package.json
  packages/compass-components/src/components/compass-components-provider.tsx
  packages/compass-components/src/components/resize-handle.tsx
  packages/compass-home/src/components/home.tsx
  packages/compass-home/src/components/workspace.tsx
  packages/compass-sidebar/src/components/connection-info-modal.tsx
  packages/compass-sidebar/src/components/csfle-marker.tsx
  packages/compass-sidebar/src/components/favorite-indicator.tsx
  packages/compass-sidebar/src/components/navigation-items.spec.tsx
  packages/compass-sidebar/src/components/navigation-items.tsx
  packages/compass-sidebar/src/components/non-genuine-marker.tsx
  packages/compass-sidebar/src/components/sidebar-title.tsx
  packages/compass-sidebar/src/components/sidebar.tsx
  packages/compass-sidebar/src/plugin.tsx
  packages/compass-web/.depcheckrc
  packages/compass-web/.eslintignore
  packages/compass-web/.eslintrc.js
  packages/compass-web/.mocharc.js
  packages/compass-web/.prettierignore
  packages/compass-web/.prettierrc.json
  packages/compass-web/package.json
  packages/compass-web/polyfills/@mongodb-js/oidc-plugin/index.ts
  packages/compass-web/polyfills/crypto/index.ts
  packages/compass-web/polyfills/dns/index.ts
  packages/compass-web/polyfills/fs/index.ts
  packages/compass-web/polyfills/http/index.ts
  packages/compass-web/polyfills/os-dns-native/index.ts
  packages/compass-web/polyfills/os/index.ts
  packages/compass-web/sandbox/index.html
  packages/compass-web/sandbox/index.tsx
  packages/compass-web/src/index.spec.tsx
  packages/compass-web/src/index.tsx
  packages/compass-web/tsconfig-lint.json
  packages/compass-web/tsconfig.json
  packages/compass-web/webpack.config.js
  packages/compass-workspaces/src/components/index.tsx
  packages/compass-workspaces/src/components/workspaces-provider.tsx
  packages/compass-workspaces/src/components/workspaces.tsx
  packages/compass-workspaces/src/index.ts
  packages/compass-workspaces/src/provider.tsx
  packages/compass-workspaces/src/stores/workspaces.ts
Labels: feat, no release notes

#5273 chore: add streams operation methods to DataService COMPASS-7553
  packages/data-service/src/data-service.spec.ts
  packages/data-service/src/data-service.ts
  packages/data-service/src/run-command.ts
  packages/data-service/test/helpers.ts
Labels: ready for review, enhancement

#5280 fix(indexes): fix table card autosizing COMPASS-7548
  packages/compass-indexes/src/components/indexes-table/indexes-table.tsx
  packages/compass-indexes/src/components/regular-indexes-table/regular-indexes-table.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.tsx
Labels: release notes, fix

#5282 fix(workspaces): open workspace in the same tab when tab type is the same COMPASS-7556
  packages/compass-workspaces/src/stores/workspaces.spec.ts
  packages/compass-workspaces/src/stores/workspaces.ts
Labels: release notes, fix
