Repository mongodb-js/compass, pull requests merged in 2023-09, with the labels that each got.

#4777 chore: zod to validate data in storage
  package-lock.json
  packages/compass-preferences-model/src/preferences.spec.ts
  packages/compass-preferences-model/src/preferences.ts
  packages/compass-preferences-model/src/storage.spec.ts
  packages/compass-preferences-model/src/storage.ts
  packages/compass-preferences-model/src/utils.ts
  packages/compass-preferences-model/test/fixtures/index.ts
  packages/compass-preferences-model/test/fixtures/user_1.27.0.json
  packages/compass-preferences-model/test/fixtures/user_1.31.0.json
  packages/compass-preferences-model/test/fixtures/user_1.38.0.json
  packages/compass-query-bar/package.json
  packages/compass-query-bar/src/components/query-history/index.spec.tsx
  packages/compass-query-bar/src/utils/query-storage.spec.ts
  packages/compass-query-bar/src/utils/query-storage.ts
  packages/compass-query-bar/test/fixtures/favorite_query_1.27.0.json
  packages/compass-query-bar/test/fixtures/favorite_query_1.31.0.json
  packages/compass-query-bar/test/fixtures/favorite_query_1.38.0.json
  packages/compass-query-bar/test/fixtures/index.ts
  packages/compass-query-bar/test/fixtures/recent_query_1.27.0.json
  packages/compass-query-bar/test/fixtures/recent_query_1.31.0.json
  packages/compass-query-bar/test/fixtures/recent_query_1.38.0.json
  packages/compass-shell/package.json
  packages/compass-shell/src/modules/history-storage.js
  packages/compass-user-data/package.json
  packages/compass-user-data/src/user-data.spec.ts
  packages/compass-user-data/src/user-data.ts
  packages/compass-utils/package.json
  packages/compass/src/app/index.jsx
  packages/compass/src/main/telemetry.ts
  packages/connection-storage/package.json
  packages/connection-storage/src/connection-secrets.spec.ts
  packages/connection-storage/src/connection-storage.spec.ts
  packages/connection-storage/src/connection-storage.ts
  packages/connection-storage/test/fixtures/favorite_connection_1.27.0.json
  packages/connection-storage/test/fixtures/favorite_connection_1.31.0.json
  packages/connection-storage/test/fixtures/favorite_connection_1.38.0.json
Labels: no release notes

#4780 fix(import): don't treat non-numbers in CSV headers as array indexes COMPASS-7157
  packages/compass-import-export/src/csv/csv-utils.spec.ts
  packages/compass-import-export/src/csv/csv-utils.ts
  packages/compass-import-export/src/import/import-csv.spec.ts
  packages/compass-import-export/src/import/import-csv.ts
Labels: release notes, fix

#4792 fix(query-bar): limit when custom paste handling is applied; use clipboard data when fixing input COMPASS-7149
  packages/compass-editor/src/index.ts
  packages/compass-editor/src/json-editor.tsx
  packages/compass-query-bar/src/components/option-editor.spec.tsx
  packages/compass-query-bar/src/components/option-editor.tsx
  packages/compass-query-bar/src/components/query-bar.spec.tsx
  packages/compass-query-bar/src/query/leniently-fix-query.ts
Labels: release notes, fix

#4793 feat(feature-flag): Add feature flag for atlas search index management COMPASS-7161
  packages/compass-preferences-model/src/feature-flags.ts
Labels: feat, no release notes

#4799 feat(search-indexes): add a split button so both MongoDB and Search indexes can be created COMPASS-7164
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.spec.tsx
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
  packages/compass-indexes/src/components/indexes/indexes.tsx
Labels: feature flagged, feat, no release notes

#4808 fix(query-bar): account for changed key order in query COMPASS-7194
  packages/compass-query-bar/src/stores/query-bar-reducer.ts
  packages/compass-query-bar/src/types.d.ts
  packages/compass-query-bar/src/utils/index.spec.ts
  packages/compass-query-bar/src/utils/index.ts
Labels: release notes, fix

#4802 feat: search index data-service methods COMPASS-7185
  package-lock.json
  packages/data-service/package.json
  packages/data-service/src/data-service.spec.ts
  packages/data-service/src/data-service.ts
  packages/data-service/src/index.ts
  packages/data-service/src/search-index-detail-helper.ts
  packages/data-service/test/helpers.ts
Labels: feat, no release notes

#4816 chore(search-indexes): add segmented control for search indexes COMPASS-7162
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.spec.tsx
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
  packages/compass-indexes/src/components/indexes/indexes.tsx
Labels: feature flagged, feat, no release notes

#4819 feat: handle 406 error message COMPASS-7189
  packages/atlas-service/src/main.spec.ts
  packages/atlas-service/src/main.ts
  packages/atlas-service/src/renderer.ts
  packages/atlas-service/src/util.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-ai.ts
  packages/compass-query-bar/src/stores/ai-query-reducer.ts
Labels: feat, no release notes

#4811 feat: bump mongosh to 2.0.0, driver to 6.0.0 COMPASS-7057
  .evergreen/functions.yml
  .github/workflows/authors-and-third-party-notices.yaml
  .github/workflows/bump-packages.yaml
  .github/workflows/publish-compass.yaml
  .github/workflows/publish-packages.yaml
  .github/workflows/update-electron.yaml
  package-lock.json
  packages/atlas-service/package.json
  packages/compass-aggregations/package.json
  packages/compass-collection/package.json
  packages/compass-components/package.json
  packages/compass-components/src/components/bson-value.spec.tsx
  packages/compass-components/src/components/bson-value.tsx
  packages/compass-connections/package.json
  packages/compass-crud/package.json
  packages/compass-e2e-tests/package.json
  packages/compass-e2e-tests/tests/logging.test.ts
  packages/compass-explain-plan/package.json
  packages/compass-import-export/package.json
  packages/compass-import-export/src/csv/csv-utils.spec.ts
  packages/compass-import-export/src/import/import-csv.spec.ts
  packages/compass-import-export/src/import/import-json.spec.ts
  packages/compass-import-export/src/utils/collection-stream.spec.ts
  packages/compass-import-export/src/utils/collection-stream.ts
  packages/compass-import-export/test/docs/all-bson-types.js
  packages/compass-indexes/package.json
  packages/compass-preferences-model/package.json
  packages/compass-query-bar/package.json
  packages/compass-query-bar/src/utils/format-query.spec.js
  packages/compass-saved-aggregations-queries/package.json
  packages/compass-schema-validation/package.json
  packages/compass-schema/package.json
  packages/compass-schema/src/modules/schema-analysis.spec.ts
  packages/compass-shell/package.json
  packages/compass-shell/src/components/shell-info-modal/shell-info-modal.spec.jsx
  packages/compass/package.json
  packages/connection-form/package.json
  packages/connection-form/src/components/advanced-options-tabs/csfle-tab/kms-tls-options.tsx
  packages/connection-form/src/utils/csfle-handler.ts
  packages/connection-form/src/utils/validation.spec.ts
  packages/connection-form/src/utils/validation.ts
  packages/connection-storage/package.json
  packages/data-service/package.json
  packages/data-service/src/connect.spec.ts
  packages/data-service/src/csfle-collection-tracker.ts
  packages/data-service/src/data-service.ts
  packages/data-service/src/run-command.ts
  packages/data-service/src/types.ts
  packages/databases-collections/package.json
  packages/hadron-document/package.json
  packages/hadron-document/test/element.test.ts
  packages/hadron-document/test/object-generator.test.ts
  packages/hadron-type-checker/package.json
  packages/hadron-type-checker/test/type-checker.test.js
  packages/mongodb-query-util/package.json
  packages/ssh-tunnel/package.json
Labels: release notes, feat

#4830 fix(aggregations, explain-plan): remove out stages before running explain plan COMPASS-7012
  packages/compass-aggregations/src/modules/insights.spec.ts
  packages/compass-aggregations/src/modules/insights.ts
  packages/compass-aggregations/src/utils/stage.js
  packages/compass-explain-plan/src/stores/explain-plan-modal-store.spec.ts
  packages/compass-explain-plan/src/stores/explain-plan-modal-store.ts
Labels: release notes, fix

#4838 feat(search-indexes): ability to create search indexes
  package-lock.json
  packages/compass-indexes/package.json
  packages/compass-indexes/src/components/create-search-index-modal/index.spec.tsx
  packages/compass-indexes/src/components/create-search-index-modal/index.tsx
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.spec.tsx
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
  packages/compass-indexes/src/components/indexes/indexes.spec.tsx
  packages/compass-indexes/src/components/indexes/indexes.tsx
  packages/compass-indexes/src/modules/search-indexes.spec.ts
  packages/compass-indexes/src/modules/search-indexes.ts
  packages/compass-indexes/test/setup-store.ts
Labels: feat, no release notes

#4836 fix(connection-storage): fix package.json
  packages/connection-storage/package.json
  packages/connection-storage/src/main.ts
Labels: fix, no release notes

#4840 feat(atlas-service): ping if ai feature enabled COMPASS-7193
  packages/atlas-service/src/main.spec.ts
  packages/atlas-service/src/main.ts
  packages/atlas-service/src/util.ts
  packages/compass-aggregations/src/components/pipeline-toolbar/index.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-stages.tsx
  packages/compass-e2e-tests/helpers/atlas-service.ts
  packages/compass-e2e-tests/tests/collection-ai-query.test.ts
  packages/compass-preferences-model/src/feature-flags.ts
  packages/compass-preferences-model/src/index.ts
  packages/compass-preferences-model/src/preferences.ts
  packages/compass-preferences-model/src/react.ts
  packages/compass-preferences-model/src/utils.ts
  packages/compass-query-bar/src/components/query-bar.spec.tsx
  packages/compass-query-bar/src/components/query-bar.tsx
  packages/compass-settings/src/components/settings/atlas-login.tsx
  packages/compass-settings/src/components/settings/feature-preview.tsx
Labels: feature flagged, feat

#4843 fix(atlas-service): deduplicate log id
  packages/atlas-service/src/main.ts
Labels: fix, no release notes

#4842 feat: add empty state for search indexes COMPASS-7204
  packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.spec.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.tsx
  packages/compass-indexes/src/components/search-indexes-table/zero-graphic.tsx
Labels: feat, no release notes

#4847 feat: show search index status badge COMPASS-7205
  package-lock.json
  packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.spec.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.tsx
  packages/data-service/src/index.ts
  packages/data-service/src/search-index-detail-helper.ts
Labels: feat, no release notes

#4848 feat(compass): bump to electron 26
  configs/webpack-config-compass/package.json
  package-lock.json
  packages/atlas-service/package.json
  packages/compass-crud/package.json
  packages/compass-e2e-tests/package.json
  packages/compass-explain-plan/package.json
  packages/compass-find-in-page/package.json
  packages/compass-import-export/package.json
  packages/compass-indexes/package.json
  packages/compass-preferences-model/src/setup-preferences.ts
  packages/compass-query-bar/package.json
  packages/compass-schema-validation/package.json
  packages/compass-shell/package.json
  packages/compass-utils/package.json
  packages/compass/package.json
  packages/compass/src/main/application.ts
  packages/compass/src/main/menu.ts
  packages/connection-storage/package.json
  packages/hadron-build/package.json
  packages/hadron-ipc/package.json
  scripts/package.json
Labels: release notes, feat

#4850 feat: add search indexes details badges COMPASS-7206
  packages/compass-indexes/src/components/regular-indexes-table/regular-indexes-table.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.spec.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.tsx
Labels: feat, no release notes

#4845 feat(compass-preferences-model): add preference for enabling ai features COMPASS-7147
  packages/atlas-service/src/main.ts
  packages/compass-preferences-model/src/preferences.spec.ts
  packages/compass-preferences-model/src/preferences.ts
  packages/compass-preferences-model/src/utils.ts
  packages/compass-query-bar/src/components/query-bar.spec.tsx
  packages/compass-settings/src/components/settings/privacy.spec.tsx
  packages/compass-settings/src/components/settings/privacy.tsx
Labels: feature flagged, feat

#4865 feat(data-service): setup local atlas detection COMPASS-7213
  package-lock.json
  packages/compass-connections/package.json
  packages/connection-form/package.json
  packages/data-service/package.json
  packages/data-service/src/instance-detail-helper.spec.ts
  packages/data-service/src/instance-detail-helper.ts
  packages/data-service/test/helpers.ts
  packages/instance-model/index.d.ts
  packages/instance-model/lib/model.js
Labels: release notes, feat

#4870 feat(preferences-model): update ai query and aggregations feature flag to released COMPASS-6866
  packages/compass-preferences-model/src/feature-flags.ts
Labels: release notes, feat

#4854 feat(search-indexes): new modal to update search indexes COMPASS-7166
  packages/compass-e2e-tests/helpers/commands/create-search-index.ts
  packages/compass-e2e-tests/helpers/commands/drop-search-index.ts
  packages/compass-e2e-tests/helpers/commands/index.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/search-indexes.test.ts
  packages/compass-indexes/src/components/indexes/indexes.spec.tsx
  packages/compass-indexes/src/components/indexes/indexes.tsx
  packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.spec.tsx
  packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.tsx
  packages/compass-indexes/src/components/search-indexes-modals/create-search-index-modal.spec.tsx
  packages/compass-indexes/src/components/search-indexes-modals/create-search-index-modal.tsx
  packages/compass-indexes/src/components/search-indexes-modals/index.ts
  packages/compass-indexes/src/components/search-indexes-modals/update-search-index-modal.spec.tsx
  packages/compass-indexes/src/components/search-indexes-modals/update-search-index-modal.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-index-actions.spec.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-index-actions.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.spec.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.tsx
  packages/compass-indexes/src/modules/search-indexes.spec.ts
  packages/compass-indexes/src/modules/search-indexes.ts
  packages/compass-indexes/test/fixtures/search-indexes.ts
Labels: feat, no release notes

#4868 fix: more auto-update logging, disable if not supported COMPASS-7220
  packages/compass/src/main/auto-update-manager.ts
  packages/compass/src/main/auto-updater.ts
Labels: release notes, fix

#4875 feat: display local Atlas dev environments as such COMPASS-7156
  packages/compass-collection/src/stores/index.ts
  packages/compass-connections/src/modules/telemetry.spec.ts
  packages/compass-connections/src/modules/telemetry.ts
  packages/compass-sidebar/src/components/connection-info-modal.tsx
  packages/compass-sidebar/src/constants/server-version.js
  packages/compass-sidebar/src/stores/store.js
  packages/compass-sidebar/src/stores/store.spec.js
Labels: release notes, feat

#4883 feat(search-indexes): polling COMPASS-7237
  packages/compass-e2e-tests/tests/search-indexes.test.ts
  packages/compass-indexes/src/components/indexes/indexes.tsx
  packages/compass-indexes/src/components/search-indexes-modals/create-search-index-modal.spec.tsx
  packages/compass-indexes/src/components/search-indexes-modals/update-search-index-modal.spec.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.spec.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.tsx
  packages/compass-indexes/src/modules/search-indexes.spec.ts
  packages/compass-indexes/src/modules/search-indexes.ts
  packages/compass-indexes/src/stores/store.ts
Labels: feat, no release notes

#4877 feat: improve handling of AI errors COMPASS-7210
  packages/atlas-service/src/main.spec.ts
  packages/atlas-service/src/main.ts
  packages/atlas-service/src/renderer.ts
  packages/atlas-service/src/util.ts
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-ai.tsx
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-ai.spec.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-ai.ts
  packages/compass-aggregations/src/stores/store.spec.ts
  packages/compass-components/src/components/generative-ai/generative-ai-input.spec.tsx
  packages/compass-components/src/components/generative-ai/generative-ai-input.tsx
  packages/compass-e2e-tests/tests/collection-ai-query.test.ts
  packages/compass-query-bar/src/components/query-ai.tsx
  packages/compass-query-bar/src/stores/ai-query-reducer.spec.ts
  packages/compass-query-bar/src/stores/ai-query-reducer.ts
  packages/compass-utils/src/ipc.ts
Labels: feature flagged, feat

#4849 feat: introduce $vectorSearch aggregation stage to 7.1 and 7.0.x COMPASS-7064
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
  packages/compass-editor/package.json
  packages/compass-query-bar/package.json
Labels: release notes, feat

#4886 fix: don't automatically select regex when detecting regex COMPASS-7144
  packages/compass-import-export/src/csv/csv-utils.ts
  packages/compass-import-export/src/import/analyze-csv-fields.spec.ts
  packages/compass-import-export/src/import/analyze-csv-fields.ts
  packages/compass-import-export/src/import/import-csv.spec.ts
Labels: release notes, fix

#4887 fix(search-indexes): clean up the modal state and do not update on no change
  packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.tsx
  packages/compass-indexes/src/components/search-indexes-modals/update-search-index-modal.spec.tsx
  packages/compass-indexes/src/modules/search-indexes.spec.ts
  packages/compass-indexes/src/modules/search-indexes.ts
Labels: fix, no release notes

#4897 fix(search-indexes): fix delete subtitle and reset state
  packages/compass-indexes/src/modules/search-indexes.ts
Labels: fix, no release notes

#4884 feat(search-indexes): enable feature COMPASS-7238
  packages/compass-preferences-model/src/feature-flags.ts
Labels: release notes, feat

#4894 feat(compass-aggregations): update mongodb-constants to show $vectorSearch operator for mongodb 6.0.10
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/group-with-statistics.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/group-with-subset.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/group-with-subset.tsx
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-preview-manager.ts
  packages/compass-aggregations/src/utils/stage.js
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
  packages/compass-editor/package.json
  packages/compass-editor/src/autocompleter.test.ts
  packages/compass-query-bar/package.json
Labels: release notes, feat

#4893 feat(search-indexes): run an aggregation COMPASS-7168
  packages/compass-app-stores/src/stores/instance-store.js
  packages/compass-collection/src/modules/collection-tab.ts
  packages/compass-collection/src/stores/collection-tab.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/search-indexes.test.ts
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.spec.tsx
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
  packages/compass-indexes/src/components/indexes/indexes.tsx
  packages/compass-indexes/src/components/regular-indexes-table/index-actions.tsx
  packages/compass-indexes/src/components/regular-indexes-table/regular-indexes-table.spec.tsx
  packages/compass-indexes/src/components/regular-indexes-table/regular-indexes-table.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-index-actions.spec.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-index-actions.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.spec.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.tsx
  packages/compass-indexes/src/modules/index.ts
  packages/compass-indexes/src/modules/regular-indexes.ts
  packages/compass-indexes/src/modules/search-indexes.spec.ts
  packages/compass-indexes/src/modules/search-indexes.ts
  packages/compass-indexes/src/stores/store.spec.js
  packages/compass-indexes/src/stores/store.ts
Labels: release notes, feat

#4892 feat(search-indexes): add a drop down to choose a search index template COMPASS-7173
  package-lock.json
  package.json
  packages/compass-aggregations/package.json
  packages/compass-e2e-tests/package.json
  packages/compass-editor/package.json
  packages/compass-indexes/package.json
  packages/compass-indexes/src/components/search-index-template-dropdown/index.spec.tsx
  packages/compass-indexes/src/components/search-index-template-dropdown/index.tsx
  packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.spec.tsx
  packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.tsx
  packages/compass-query-bar/package.json
  packages/compass/package.json
Labels: release notes, feat

#4912 fix(preferences, settings, atlas-service): ensure Atlas Login doesn't show in settings if user didn't get the Gen AI feature rollout
  packages/atlas-service/src/main.ts
  packages/compass-e2e-tests/tests/collection-ai-query.test.ts
  packages/compass-preferences-model/src/feature-flags.ts
  packages/compass-preferences-model/src/index.ts
  packages/compass-preferences-model/src/preferences.spec.ts
  packages/compass-preferences-model/src/preferences.ts
  packages/compass-preferences-model/src/utils.ts
  packages/compass-query-bar/src/components/query-bar.spec.tsx
  packages/compass-settings/src/components/modal.tsx
  packages/compass-settings/src/components/settings/feature-preview.tsx
  packages/compass-settings/src/components/settings/privacy.spec.tsx
  packages/compass-settings/src/components/settings/privacy.tsx
Labels: release notes, fix

#4916 fix(ci): update docker-envs to latest with pinned sharded cluster version
  .evergreen/start-docker-envs.sh
  package-lock.json
  packages/data-service/package.json
  scripts/package.json
Labels: fix, no release notes

#4920 fix: atomic writes to preferences COMPASS-7270 COMPASS-7269
  package-lock.json
  packages/compass-preferences-model/src/storage.spec.ts
  packages/compass-preferences-model/src/storage.ts
  packages/compass-user-data/package.json
  packages/compass-user-data/src/user-data.ts
  packages/compass/src/main/index.ts
Labels: release notes, fix

#4915 feat: open search indexes table when a search index is created COMPASS-7247
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.spec.tsx
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
  packages/compass-indexes/src/components/indexes/indexes.spec.tsx
  packages/compass-indexes/src/components/indexes/indexes.tsx
  packages/compass-indexes/src/modules/index-view.spec.ts
  packages/compass-indexes/src/modules/index-view.ts
  packages/compass-indexes/src/modules/index.ts
  packages/compass-indexes/src/modules/search-indexes.spec.ts
  packages/compass-indexes/src/modules/search-indexes.ts
  packages/compass-indexes/src/stores/store.ts
Labels: release notes, feat

#4928 fix: update .rpm and .deb deps and requirements COMPASS-7203
  package-lock.json
  packages/hadron-build/lib/target.js
  packages/hadron-build/package.json
Labels: release notes, fix
