Repository mongodb-js/compass, pull requests merged in 2023-01, with the labels that each got.

#3924 fix(crud): fix json editor hanging out over the rounded corners
  packages/compass-crud/src/components/document-json-view.tsx
Labels: fix, no release notes

#3926 feat(focus-mode): setup focus mode COMPASS-6386
  packages/compass-aggregations/src/components/focus-mode/focus-mode.spec.tsx
  packages/compass-aggregations/src/components/focus-mode/focus-mode.tsx
  packages/compass-aggregations/src/components/pipeline/pipeline.jsx
  packages/compass-aggregations/src/components/stage-preview-toolbar/stage-preview-toolbar.tsx
  packages/compass-aggregations/src/modules/focus-mode.ts
  packages/compass-aggregations/src/modules/index.ts
  packages/compass-aggregations/src/stores/store.spec.js
  packages/compass-preferences-model/src/preferences.ts
  packages/compass-settings/src/components/settings/featureflags.tsx
Labels: feature flagged, feat

#3944 fix(aggregations): output stage destination name COMPASS-6407
  packages/compass-aggregations/src/utils/stage.js
  packages/compass-aggregations/src/utils/stage.spec.js
Labels: release notes, fix

#3945 fix(compass-shell): set width of compass shell to avoid overflow COMPASS-6411
  packages/compass-shell/src/components/compass-shell/compass-shell.jsx
Labels: release notes, fix

#3946 fix(settings): tweak settings modal text alignment COMPASS-6413
  packages/compass-settings/src/components/settings/theme.tsx
  packages/compass-settings/src/components/sidebar.tsx
Labels: fix, no release notes

#3935 feat(aggregations): add stage button between stages COMPASS-6382
  packages/compass-aggregations/src/components/add-stage/add-stage.jsx
  packages/compass-aggregations/src/components/add-stage/add-stage.spec.jsx
  packages/compass-aggregations/src/components/add-stage/add-stage.spec.tsx
  packages/compass-aggregations/src/components/add-stage/add-stage.tsx
  packages/compass-aggregations/src/components/pipeline-builder-input-documents.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace.jsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace.spec.jsx
  packages/compass-aggregations/src/components/stage-editor-toolbar/add-after-stage.spec.jsx
  packages/compass-aggregations/src/components/stage-editor-toolbar/add-after-stage.tsx
  packages/compass-aggregations/src/components/stage-editor-toolbar/stage-editor-toolbar.tsx
  packages/compass-aggregations/src/components/stage.tsx
Labels: release notes, feat

#3956 fix(compass-e2e-tests): make auto-connect test less flaky on Windows
  packages/compass-e2e-tests/tests/auto-connect.test.ts
Labels: fix, no release notes

#3964 fix(crud): If a date is in the safe range, go with relaxed EJSON rather than canonical COMPASS-5744
  packages/hadron-document/src/utils.ts
  packages/hadron-document/test/document.test.ts
Labels: release notes, fix

#3965 feat(compass-crud): use type from last array element when inserting new element to array COMPASS-6432
  packages/compass-crud/src/components/table-view/cell-editor.tsx
  packages/hadron-document/src/element.ts
  packages/hadron-document/src/index.ts
  packages/hadron-document/src/utils.ts
  packages/hadron-document/test/element.test.ts
Labels: release notes, feat

#3971 feat(collections): redirect to the new collection after creating it COMPASS-6019
  packages/compass-app-stores/src/stores/instance-store.js
  packages/compass-e2e-tests/tests/database-collections-tab.test.ts
  packages/compass-e2e-tests/tests/in-use-encryption.test.ts
  packages/compass-e2e-tests/tests/instance-databases-tab.test.ts
  packages/compass-e2e-tests/tests/instance-sidebar.test.ts
Labels: release notes, feat

#3970 refactor: remove unsafe method in document table COMPASS-6137
  packages/compass-crud/src/components/table-view/document-table-view.tsx
Labels: no release notes

#3977 refactor: remove UNSAFE_ method in cell-editor COMPASS-6138
  .github/PULL_REQUEST_TEMPLATE.md
  packages/compass-crud/src/components/table-view/cell-editor.tsx
Labels: no release notes

#3957 feat(focus-mode): add stage input, editor and output COMPASS-6388
  packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-editor.spec.tsx
  packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-editor.tsx
  packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-preview.spec.tsx
  packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-preview.tsx
  packages/compass-aggregations/src/components/focus-mode/focus-mode.spec.tsx
  packages/compass-aggregations/src/components/focus-mode/focus-mode.tsx
  packages/compass-aggregations/src/components/pipeline-output-options-menu.tsx
  packages/compass-aggregations/src/modules/input-documents.js
  packages/compass-aggregations/src/modules/input-documents.spec.ts
  packages/compass-aggregations/src/modules/input-documents.ts
  packages/compass-aggregations/src/utils/stage.js
Labels: feature flagged, feat

#3980 refactor: remove UNSAFE_ method in insert-document-dialog COMPASS-6139
  packages/compass-crud/src/components/insert-document-dialog.tsx
Labels: no release notes

#3981 chore(import/export): Add and restructure import/export test fixtures COMPASS-6420
  packages/compass-import-export/src/utils/detect-import-file.spec.js
  packages/compass-import-export/src/utils/formatters.spec.js
  packages/compass-import-export/src/utils/import-parser.spec.js
  packages/compass-import-export/src/utils/import-preview.spec.js
  packages/compass-import-export/test/csv/bad.csv
  packages/compass-import-export/test/csv/good-commas.csv
  packages/compass-import-export/test/csv/good-tabs.csv
  packages/compass-import-export/test/csv/number-transform.csv
  packages/compass-import-export/test/csv/sparse.csv
  packages/compass-import-export/test/csv/types/array.csv
  packages/compass-import-export/test/csv/types/binData.csv
  packages/compass-import-export/test/csv/types/boolean.csv
  packages/compass-import-export/test/csv/types/date.csv
  packages/compass-import-export/test/csv/types/decimal.csv
  packages/compass-import-export/test/csv/types/double.csv
  packages/compass-import-export/test/csv/types/int.csv
  packages/compass-import-export/test/csv/types/javascript.csv
  packages/compass-import-export/test/csv/types/javascriptWithScope.csv
  packages/compass-import-export/test/csv/types/long.csv
  packages/compass-import-export/test/csv/types/maxKey.csv
  packages/compass-import-export/test/csv/types/minKey.csv
  packages/compass-import-export/test/csv/types/mixed.csv
  packages/compass-import-export/test/csv/types/null.csv
  packages/compass-import-export/test/csv/types/number.csv
  packages/compass-import-export/test/csv/types/object.csv
  packages/compass-import-export/test/csv/types/objectId.csv
  packages/compass-import-export/test/csv/types/regex.csv
  packages/compass-import-export/test/csv/types/string.csv
  packages/compass-import-export/test/csv/types/symbol.csv
  packages/compass-import-export/test/csv/types/timestamp.csv
  packages/compass-import-export/test/docs/all-bson-types.js
  packages/compass-import-export/test/docs/inconsistent.js
  packages/compass-import-export/test/fixtures.js
  packages/compass-import-export/test/json/complex.json
  packages/compass-import-export/test/json/good.json
  packages/compass-import-export/test/json/json-with-csv-fileext.csv
  packages/compass-import-export/test/json/single-doc.json
  packages/compass-import-export/test/jsonl/extra-line.jsonl
  packages/compass-import-export/test/jsonl/good.jsonl
  packages/compass-import-export/test/other/javascript
Labels: no release notes

#3990 Feat(import): Function to list the fields contained in a CSV file's header row COMPASS-6422
  packages/compass-import-export/src/import/guess-filetype.spec.ts
  packages/compass-import-export/src/import/guess-filetype.ts
  packages/compass-import-export/src/import/list-csv-fields.spec.ts
  packages/compass-import-export/src/import/list-csv-fields.ts
  packages/compass-import-export/src/utils/constants.ts
  packages/compass-import-export/test/csv/array.csv
  packages/compass-import-export/test/csv/complex.csv
  packages/compass-import-export/test/csv/object.csv
  packages/compass-import-export/test/csv/objectarray.csv
  packages/compass-import-export/test/fixtures.js
Labels: feat, no release notes

#4002 fix(aggregations): redesign of add stage button COMPASS-6449
  packages/compass-aggregations/src/components/add-stage/add-stage.tsx
  packages/compass-aggregations/src/components/pipeline-builder-input-documents.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace.tsx
  packages/compass-aggregations/src/components/stage.tsx
Labels: release notes, fix

#4001 feat(import): Function to analyze a CSV file and autodetect the columns' types COMPASS-6423
  packages/compass-import-export/src/import/analyze-csv-fields.spec.ts
  packages/compass-import-export/src/import/analyze-csv-fields.ts
  packages/compass-import-export/src/import/list-csv-fields.spec.ts
  packages/compass-import-export/src/import/list-csv-fields.ts
  packages/compass-import-export/src/utils/csv-header.ts
  packages/compass-import-export/test/csv/array.analyzed.json
  packages/compass-import-export/test/csv/array.csv
  packages/compass-import-export/test/csv/bad.analyzed.json
  packages/compass-import-export/test/csv/complex.analyzed.json
  packages/compass-import-export/test/csv/good-commas.analyzed.json
  packages/compass-import-export/test/csv/good-tabs.analyzed.json
  packages/compass-import-export/test/csv/number-transform.analyzed.json
  packages/compass-import-export/test/csv/object.analyzed.json
  packages/compass-import-export/test/csv/objectarray.analyzed.json
  packages/compass-import-export/test/csv/semicolons.analyzed.json
  packages/compass-import-export/test/csv/spaces.analyzed.json
  packages/compass-import-export/test/csv/sparse.analyzed.json
  packages/compass-import-export/test/csv/types/double.csv
  packages/compass-import-export/test/fixtures.ts
Labels: feat, no release notes

#4004 feat(aggregations): stage toolbar COMPASS-6381
  packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-editor.tsx
  packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-preview.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-preview.tsx
  packages/compass-aggregations/src/components/stage-editor-toolbar/delete-stage.jsx
  packages/compass-aggregations/src/components/stage-editor-toolbar/delete-stage.spec.jsx
  packages/compass-aggregations/src/components/stage-editor-toolbar/index.js
  packages/compass-aggregations/src/components/stage-editor-toolbar/stage-collapser.jsx
  packages/compass-aggregations/src/components/stage-editor-toolbar/stage-collapser.spec.jsx
  packages/compass-aggregations/src/components/stage-editor-toolbar/stage-operator-select.spec.jsx
  packages/compass-aggregations/src/components/stage-editor-toolbar/toggle-stage.jsx
  packages/compass-aggregations/src/components/stage-editor-toolbar/toggle-stage.module.less
  packages/compass-aggregations/src/components/stage-preview-toolbar/index.js
  packages/compass-aggregations/src/components/stage-preview-toolbar/stage-preview-toolbar.spec.jsx
  packages/compass-aggregations/src/components/stage-preview-toolbar/stage-preview-toolbar.tsx
  packages/compass-aggregations/src/components/stage-preview/atlas-stage-preview.tsx
  packages/compass-aggregations/src/components/stage-preview/index.spec.tsx
  packages/compass-aggregations/src/components/stage-preview/index.tsx
  packages/compass-aggregations/src/components/stage-preview/output-stage-preview.spec.tsx
  packages/compass-aggregations/src/components/stage-preview/output-stage-preview.tsx
  packages/compass-aggregations/src/components/stage-preview/stage-preview-header.tsx
  packages/compass-aggregations/src/components/stage-toolbar/index.spec.tsx
  packages/compass-aggregations/src/components/stage-toolbar/index.tsx
  packages/compass-aggregations/src/components/stage-toolbar/option-menu.spec.tsx
  packages/compass-aggregations/src/components/stage-toolbar/option-menu.tsx
  packages/compass-aggregations/src/components/stage-toolbar/stage-collapser.tsx
  packages/compass-aggregations/src/components/stage-toolbar/stage-operator-select.tsx
  packages/compass-aggregations/src/components/stage-toolbar/toggle-stage.tsx
  packages/compass-aggregations/src/components/stage.tsx
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
Labels: release notes, feat

#4012 fix(compass-aggregations): fix atlas only server error detection
  packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-editor.tsx
  packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-preview.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-preview.tsx
  packages/compass-aggregations/src/components/stage-editor/stage-editor.jsx
  packages/compass-aggregations/src/components/stage-preview/index.tsx
  packages/compass-aggregations/src/components/stage-toolbar/option-menu.tsx
  packages/compass-aggregations/src/components/stage.tsx
  packages/compass-aggregations/src/utils/stage.js
Labels: fix, no release notes
