Repository mongodb-js/compass, pull requests merged in 2023-07, with the labels that each got.

#4602 fix(compass-components): case sensitive index key badges COMPASS-6510
  packages/compass-components/src/components/index-keys-badge.tsx
Labels: release notes, fix

#4610 chore(compass-query-bar): update ai button styles, cancel on unmount, fix thunk typing
  packages/compass-query-bar/src/components/generative-ai/ai-text-input.tsx
  packages/compass-query-bar/src/components/query-bar.tsx
  packages/compass-query-bar/src/stores/ai-query-reducer.ts
  packages/compass-query-bar/src/stores/query-bar-reducer.ts
  packages/compass-query-bar/src/utils/index.ts
Labels: feature flagged

#4614 feat(compass-crud): re-introduce "bloated documents" insight COMPASS-6837
  package-lock.json
  packages/compass-components/src/components/document-list/document-actions-group.tsx
  packages/compass-components/src/components/signal-popover.tsx
  packages/compass-crud/package.json
  packages/compass-crud/src/components/editable-document.tsx
  packages/compass-crud/src/components/readonly-document.tsx
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-field-store/src/stores/store.js
  packages/compass-field-store/src/stores/store.spec.js
  packages/hadron-document/src/document.ts
Labels: feature flagged, feat

#4615 fix(compass-query-bar): map project to projection before emitting open-explain-plan event COMPASS-6995
  packages/compass-explain-plan/src/stores/explain-plan-modal-store.ts
  packages/compass-query-bar/src/stores/query-bar-reducer.spec.ts
  packages/compass-query-bar/src/stores/query-bar-reducer.ts
Labels: release notes, fix

#4609 fix(compass-components): use mod for hotkey so windows uses ctrl instead of windows key COMPASS-6777
  packages/compass-aggregations/src/components/focus-mode/focus-mode-modal-header.tsx
  packages/compass-collection/src/components/workspace/workspace.tsx
  packages/compass-components/src/hooks/use-hotkeys.spec.tsx
  packages/compass-components/src/hooks/use-hotkeys.tsx
  packages/compass-shell/src/components/shell-info-modal/keyboard-shortcuts-table.jsx
Labels: release notes, fix

#4618 feat(collection, aggregations): show insight when $lookup stage is used COMPASS-6970
  packages/compass-aggregations/src/utils/insights.ts
  packages/compass-collection/src/components/collection-header/collection-header.spec.tsx
  packages/compass-collection/src/components/collection-header/collection-header.tsx
Labels: feature flagged, feat

#4619 feat(compass-query-bar): pass schema and sample docs to ai, basic auth COMPASS-6979
  package-lock.json
  packages/compass-field-store/package.json
  packages/compass-import-export/package.json
  packages/compass-query-bar/package.json
  packages/compass-query-bar/src/components/query-history/index.spec.tsx
  packages/compass-query-bar/src/modules/ai-query-request.spec.ts
  packages/compass-query-bar/src/modules/ai-query-request.ts
  packages/compass-query-bar/src/stores/ai-query-reducer.spec.ts
  packages/compass-query-bar/src/stores/ai-query-reducer.ts
  packages/compass-query-bar/src/stores/query-bar-store.ts
  packages/compass-query-bar/test/create-mock-ai-endpoint.ts
  packages/compass-schema/package.json
Labels: feature flagged, feat

#4624 fix(explain-compat): handle missing execution stats in raw explain
  packages/mongodb-explain-compat/lib/index.js
  packages/mongodb-explain-compat/package.json
  packages/mongodb-explain-compat/test/fixtures/query-planner-only.json
  packages/mongodb-explain-compat/test/index.js
Labels: release notes, fix

#4622 feat(insights): enable insights by default COMPASS-7000
  packages/compass-components/src/components/signal-popover.tsx
  packages/compass-components/src/hooks/use-focus-hover.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
  packages/compass-preferences-model/src/feature-flags.ts
  packages/compass-query-bar/src/components/option-editor.tsx
Labels: release notes, feat

#4626 chore(query-bar): open query options when applied from ai, better error reporting
  packages/compass-query-bar/src/modules/ai-query-request.spec.ts
  packages/compass-query-bar/src/modules/ai-query-request.ts
  packages/compass-query-bar/src/stores/ai-query-reducer.spec.ts
  packages/compass-query-bar/src/stores/ai-query-reducer.ts
  packages/compass-query-bar/src/stores/query-bar-reducer.ts
  packages/compass-query-bar/src/utils/query.spec.ts
  packages/compass-query-bar/src/utils/query.ts
  packages/compass-query-bar/test/create-mock-ai-endpoint.ts
Labels: feature flagged

#4575 feat(compass-indexes): adds a signal for notifying when there are too many indexes
  package-lock.json
  packages/compass-indexes/package.json
  packages/compass-indexes/src/components/indexes-table/indexes-table.spec.tsx
  packages/compass-indexes/src/components/indexes-table/indexes-table.tsx
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.spec.tsx
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
  packages/compass-indexes/src/components/indexes/indexes.tsx
Labels: feature flagged, feat

#4634 chore: locks semver 5.7.x to 5.7.2, 6.3.x to 6.3.1 and 7.5.x to 7.5.4 - COMPASS-6966, COMPASS-6967, COMPASS-6969
  .snyk
  package-lock.json
  packages/app-migrations/package.json
  packages/compass-crud/package.json
  packages/compass-editor/package.json
  packages/compass/package.json
  scripts/package.json
Labels: no release notes

#4606 fix(schema): error while modifying a filter in the schema tab COMPASS-6944
  .depalignrc.json
  package-lock.json
  packages/compass-query-bar/package.json
  packages/compass-query-bar/src/types.d.ts
  packages/compass-schema/package.json
  packages/compass-schema/src/typings.d.ts
  packages/mongodb-query-util/.depcheckrc
  packages/mongodb-query-util/.eslintignore
  packages/mongodb-query-util/.eslintrc.js
  packages/mongodb-query-util/.mocharc.js
  packages/mongodb-query-util/.prettierignore
  packages/mongodb-query-util/.prettierrc.json
  packages/mongodb-query-util/package.json
  packages/mongodb-query-util/src/bson-equal.spec.ts
  packages/mongodb-query-util/src/bson-equal.ts
  packages/mongodb-query-util/src/get-distinct-values.spec.ts
  packages/mongodb-query-util/src/get-distinct-values.ts
  packages/mongodb-query-util/src/has-distinct-value.spec.ts
  packages/mongodb-query-util/src/has-distinct-value.ts
  packages/mongodb-query-util/src/in-value-range.spec.ts
  packages/mongodb-query-util/src/in-value-range.ts
  packages/mongodb-query-util/src/index.ts
  packages/mongodb-query-util/tsconfig-lint.json
  packages/mongodb-query-util/tsconfig.json
Labels: release notes, fix

#4649 fix: use correct tab name for indexes & validation COMPASS-7022
  packages/compass-collection/src/modules/tabs.ts
  packages/compass-e2e-tests/helpers/commands/navigate-to-collection-tab.ts
  packages/compass-e2e-tests/helpers/selectors.ts
Labels: release notes, fix

#4651 chore: bump @aws-sdk/credential-providers to take in fast-xml-parser@4.2.5 COMPASS-7028
  package-lock.json
  packages/compass/package.json
Labels: no release notes

#4654 fix: strip unknown preferences when loading COMPASS-7026
  packages/compass-preferences-model/src/storage.spec.ts
  packages/compass-preferences-model/src/storage.ts
Labels: release notes, fix

#4670 test(preferences): add storage tests COMPASS-7037
  packages/compass-preferences-model/src/storage.spec.ts
Labels: no release notes

#4661 feat(query-bar): add sign in modal with sign in flow to query bar ai input
  packages/atlas-service/src/main.spec.ts
  packages/atlas-service/src/main.ts
  packages/atlas-service/src/renderer.ts
  packages/atlas-service/src/util.ts
  packages/compass-collection/src/components/collection/collection.tsx
  packages/compass-components/src/components/tab-nav-bar.spec.tsx
  packages/compass-components/src/components/tab-nav-bar.tsx
  packages/compass-components/src/hooks/use-toast.tsx
  packages/compass-query-bar/src/components/generative-ai/ai-sign-in-banner-image.tsx
  packages/compass-query-bar/src/components/generative-ai/ai-sign-in-modal.tsx
  packages/compass-query-bar/src/components/query-bar.tsx
  packages/compass-query-bar/src/stores/ai-query-reducer.spec.ts
  packages/compass-query-bar/src/stores/ai-query-reducer.ts
  packages/compass-query-bar/src/stores/atlas-signin-reducer.spec.ts
  packages/compass-query-bar/src/stores/atlas-signin-reducer.ts
  packages/compass-query-bar/src/stores/query-bar-store.ts
Labels: feature flagged, feat

#4683 fix(atlas-service): listen to state-updated before attempting token refresh
  packages/atlas-service/src/main.spec.ts
  packages/atlas-service/src/main.ts
Labels: feature flagged, fix
