Repository mongodb-js/compass, pull requests merged in 2023-08, with the labels that each got.

#4688 feat(crud, schema, import-export): show insight for unbound array COMPASS-6836
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.tsx
  packages/compass-aggregations/src/utils/insights.ts
  packages/compass-collection/src/components/collection-header/collection-header.tsx
  packages/compass-components/src/components/document-list/document-actions-group.tsx
  packages/compass-components/src/components/signals.tsx
  packages/compass-components/src/index.ts
  packages/compass-crud/src/components/crud-toolbar.tsx
  packages/compass-crud/src/components/editable-document.tsx
  packages/compass-crud/src/components/readonly-document.tsx
  packages/compass-crud/src/utils/index.spec.ts
  packages/compass-crud/src/utils/index.ts
  packages/compass-explain-plan/src/components/explain-plan-side-summary.tsx
  packages/compass-import-export/src/components/import-toast.tsx
  packages/compass-import-export/src/import/import-csv.spec.ts
  packages/compass-import-export/src/import/import-csv.ts
  packages/compass-import-export/src/import/import-json.spec.ts
  packages/compass-import-export/src/import/import-json.ts
  packages/compass-import-export/src/import/import-types.ts
  packages/compass-import-export/src/import/import-utils.spec.ts
  packages/compass-import-export/src/import/import-utils.ts
  packages/compass-import-export/src/modules/import.ts
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
  packages/compass-schema/src/components/field.tsx
  packages/compass-sidebar/src/components/navigation-items.tsx
  packages/databases-collections-list/src/databases.tsx
Labels: release notes, feat

#4695 feat(connections): use modal to highlight legacy connections COMPASS-7072
  package-lock.json
  packages/compass-connections/src/components/connections.spec.tsx
  packages/compass-connections/src/components/connections.tsx
  packages/compass-connections/src/components/legacy-connections-modal.tsx
  packages/compass/package.json
  packages/compass/src/main/application.ts
  packages/connection-storage/src/connection-storage.spec.ts
  packages/connection-storage/src/connection-storage.ts
Labels: release notes, feat

#4696 fix(query-bar): reset ai input state on unauthorized errors
  package-lock.json
  packages/atlas-service/package.json
  packages/atlas-service/src/main.spec.ts
  packages/atlas-service/src/main.ts
  packages/atlas-service/src/renderer.ts
  packages/atlas-service/src/store/atlas-signin-reducer.ts
  packages/atlas-service/src/util.ts
  packages/compass-query-bar/src/stores/ai-query-reducer.spec.ts
  packages/compass-query-bar/src/stores/ai-query-reducer.ts
Labels: feature flagged, fix

#4704 chore(connection-storage): split connection storage between processes COMPASS-7078
  package-lock.json
  packages/atlas-service/package.json
  packages/atlas-service/src/main.ts
  packages/atlas-service/src/renderer.ts
  packages/atlas-service/src/util.ts
  packages/compass-connection-import-export/src/components/export-modal.tsx
  packages/compass-connection-import-export/src/components/import-modal.tsx
  packages/compass-connection-import-export/src/hooks/common.spec.ts
  packages/compass-connection-import-export/src/hooks/common.ts
  packages/compass-connection-import-export/src/hooks/use-export.spec.ts
  packages/compass-connection-import-export/src/hooks/use-export.ts
  packages/compass-connection-import-export/src/hooks/use-import.spec.ts
  packages/compass-connection-import-export/src/hooks/use-import.ts
  packages/compass-connections/src/components/connection-list/connection-list.spec.tsx
  packages/compass-connections/src/components/connection-list/connection-list.tsx
  packages/compass-connections/src/components/connection-list/connection.tsx
  packages/compass-connections/src/components/connections.spec.tsx
  packages/compass-connections/src/components/connections.tsx
  packages/compass-connections/src/components/legacy-connections-modal.tsx
  packages/compass-connections/src/modules/telemetry.spec.ts
  packages/compass-connections/src/modules/telemetry.ts
  packages/compass-connections/src/stores/connections-store.spec.ts
  packages/compass-connections/src/stores/connections-store.ts
  packages/compass-home/src/components/home.tsx
  packages/compass-sidebar/package.json
  packages/compass-sidebar/src/components/favorite-indicator.tsx
  packages/compass-sidebar/src/components/sidebar.tsx
  packages/compass-sidebar/src/modules/connection-info.js
  packages/compass-utils/package.json
  packages/compass-utils/src/cancellable-promise.ts
  packages/compass-utils/src/index.ts
  packages/compass-utils/src/ipc.spec.ts
  packages/compass-utils/src/ipc.ts
  packages/compass/package.json
  packages/compass/src/app/auto-connect.spec.ts
  packages/compass/src/app/auto-connect.ts
  packages/compass/src/main/application.ts
  packages/compass/src/main/import-export-connections.ts
  packages/connection-form/src/components/connection-form.spec.tsx
  packages/connection-form/src/components/connection-form.tsx
  packages/connection-form/src/components/save-connection-modal.tsx
  packages/connection-form/src/hooks/use-connect-form.ts
  packages/connection-form/src/utils/validation.spec.ts
  packages/connection-storage/main.d.ts
  packages/connection-storage/main.js
  packages/connection-storage/package.json
  packages/connection-storage/renderer.d.ts
  packages/connection-storage/renderer.js
  packages/connection-storage/src/connection-storage.spec.ts
  packages/connection-storage/src/connection-storage.ts
  packages/connection-storage/src/import-export-connection.spec.ts
  packages/connection-storage/src/import-export-connection.ts
  packages/connection-storage/src/main.ts
  packages/connection-storage/src/renderer.ts
  packages/connection-storage/src/utils.ts
  scripts/import-test-connections.js
Labels: release notes, fix

#4707 feat(query-editor): Automatically add {} to Find queries COMPASS-6530
  packages/compass-editor/src/index.ts
  packages/compass-editor/src/json-editor.tsx
  packages/compass-query-bar/src/components/option-editor.tsx
  packages/compass-query-bar/src/components/query-bar.spec.tsx
  packages/compass-query-bar/src/components/query-option.tsx
  packages/compass-query-bar/src/query/leniently-fix-query.spec.ts
  packages/compass-query-bar/src/query/leniently-fix-query.ts
Labels: release notes, feat

#4663 fix(drop-ui): clear drop collections input state if drop collections success COMPASS-7035
  packages/databases-collections/src/components/drop-collection-modal.tsx
Labels: release notes, fix

#4714 feat(connections): show list of legacy connections COMPASS-7081
  packages/compass-connections/src/components/connections.spec.tsx
  packages/compass-connections/src/components/legacy-connections-modal.tsx
  packages/compass/src/main/application.ts
  packages/connection-storage/src/connection-storage.spec.ts
  packages/connection-storage/src/connection-storage.ts
  packages/connection-storage/src/renderer.ts
Labels: release notes, feat

#4718 feat(atlas-service): securely persist and restore atlas login state through keychain
  package-lock.json
  packages/atlas-service/package.json
  packages/atlas-service/src/main.spec.ts
  packages/atlas-service/src/main.ts
  packages/compass/src/main/application.ts
Labels: feature flagged, feat

#4725 fix(preferences): allow empty optional string flags COMPASS-7101
  packages/compass-preferences-model/src/global-config.spec.ts
  packages/compass-preferences-model/src/preferences.ts
Labels: release notes, fix

#4738 fix(atlas-service): seaprate token refresh and token restore flows; fix events that token refresh is listening to
  packages/atlas-service/src/main.spec.ts
  packages/atlas-service/src/main.ts
Labels: feature flagged, fix

#4739 feat: track AI related events COMPASS-7109, COMPASS-7110
  packages/compass-query-bar/src/components/option-editor.tsx
  packages/compass-query-bar/src/components/query-ai.spec.tsx
  packages/compass-query-bar/src/components/query-ai.tsx
  packages/compass-query-bar/src/components/query-option.tsx
  packages/compass-query-bar/src/modules/change-filter.spec.ts
  packages/compass-query-bar/src/stores/ai-query-reducer.ts
Labels: feat, no release notes

#4742 feat(compass-settings): add atlas login section to compass settings feature preview tab COMPASS-7098
  configs/mocha-config-compass/compass-plugin.js
  configs/mocha-config-compass/register/compass-preferences-register.js
  package-lock.json
  packages/atlas-service/.mocharc.js
  packages/atlas-service/package.json
  packages/atlas-service/src/components/ai-signin-modal.tsx
  packages/atlas-service/src/main.spec.ts
  packages/atlas-service/src/main.ts
  packages/atlas-service/src/renderer.ts
  packages/atlas-service/src/store/atlas-signin-reducer.spec.ts
  packages/atlas-service/src/store/atlas-signin-reducer.ts
  packages/compass-components/src/components/error-boundary.spec.tsx
  packages/compass-preferences-model/src/preferences.ts
  packages/compass-preferences-model/src/setup-preferences.ts
  packages/compass-settings/package.json
  packages/compass-settings/src/components/modal.tsx
  packages/compass-settings/src/components/settings/atlas-login.tsx
  packages/compass-settings/src/components/settings/feature-preview.tsx
  packages/compass-settings/src/stores/atlas-login.ts
  packages/compass-settings/src/stores/index.ts
  packages/compass-settings/src/stores/settings.ts
  packages/compass-settings/src/stores/utils.ts
  packages/compass-shell/src/stores/store.spec.js
  packages/compass/src/app/index.jsx
Labels: feature flagged, feat

#4746 feat(compass-query-bar): add ask ai button to query bar when filter has content COMPASS-7039
  packages/compass-components/src/components/generative-ai/ai-experience-entry.tsx
  packages/compass-query-bar/src/components/query-bar.spec.tsx
  packages/compass-query-bar/src/components/query-bar.tsx
Labels: feature flagged, feat

#4751 fix(compass-aggregations): only show ai button when in edit mode COMPASS-7136
  packages/compass-aggregations/src/components/pipeline-toolbar/index.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-stages.tsx
Labels: feature flagged, fix

#4756 fix(connections): add support for downgrade to a version with storage-mixin COMPASS-7174
  packages/connection-storage/src/connection-storage.spec.ts
  packages/connection-storage/src/connection-storage.ts
Labels: release notes, fix

#4762 feat(atlas-service, settings): ask users for explicit confirmation of terms and conditions before using ai feature
  package-lock.json
  packages/atlas-service/package.json
  packages/atlas-service/src/components/ai-opt-in-confirmation.tsx
  packages/atlas-service/src/components/atlas-signin.spec.tsx
  packages/atlas-service/src/components/atlas-signin.tsx
  packages/atlas-service/src/main.spec.ts
  packages/atlas-service/src/main.ts
  packages/atlas-service/src/oidc-plugin-logger.ts
  packages/atlas-service/src/renderer.ts
  packages/atlas-service/src/secret-store.ts
  packages/atlas-service/src/store/atlas-signin-reducer.spec.ts
  packages/atlas-service/src/store/atlas-signin-reducer.ts
  packages/atlas-service/src/store/atlas-signin-store.ts
  packages/atlas-service/src/user-config-store.spec.ts
  packages/atlas-service/src/user-config-store.ts
  packages/atlas-service/src/util.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-ai.spec.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-ai.ts
  packages/compass-aggregations/src/stores/store.ts
  packages/compass-home/src/components/home.tsx
  packages/compass-query-bar/src/stores/ai-query-reducer.spec.ts
  packages/compass-query-bar/src/stores/ai-query-reducer.ts
  packages/compass-query-bar/src/stores/query-bar-store.ts
  packages/compass-settings/src/components/index.tsx
  packages/compass-settings/src/components/settings/atlas-login.spec.tsx
  packages/compass-settings/src/components/settings/atlas-login.tsx
  packages/compass-settings/src/stores/atlas-login.ts
  packages/compass-settings/src/stores/index.ts
Labels: feature flagged, feat

#4759 feat: navigate aggregations generated from the query bar ai COMPASS-7106
  packages/compass-aggregations/src/components/pipeline-toolbar/index.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-ai.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-ai.tsx
  packages/compass-aggregations/src/modules/comments.js
  packages/compass-aggregations/src/modules/id.js
  packages/compass-aggregations/src/modules/insights.ts
  packages/compass-aggregations/src/modules/name.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-ai.spec.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-ai.ts
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-mode.ts
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
  packages/compass-aggregations/src/modules/pipeline-builder/text-editor-output-stage.ts
  packages/compass-aggregations/src/modules/pipeline-builder/text-editor-pipeline.ts
  packages/compass-aggregations/src/stores/store.spec.ts
  packages/compass-aggregations/src/stores/store.ts
  packages/compass-collection/src/components/collection/collection.tsx
  packages/compass-components/src/components/generative-ai/ai-feedback.tsx
  packages/compass-components/src/components/generative-ai/ai-guide-cue.tsx
  packages/compass-components/src/components/generative-ai/generative-ai-input.spec.tsx
  packages/compass-components/src/components/generative-ai/generative-ai-input.tsx
  packages/compass-query-bar/src/stores/ai-query-reducer.ts
Labels: feature flagged, feat
