Repository mongodb-js/compass, pull requests merged in 2023-11, with the labels that each got.

#4980 feat: use dark colors for background on initial app loading with dark theme
  packages/compass/src/app/styles/index.less
Labels: release notes, feat

#5047 feat: reset the bulk update modal when re-opened COMPASS-7325
  packages/compass-components/src/components/leafygreen.tsx
  packages/compass-crud/src/components/bulk-update-dialog.spec.tsx
  packages/compass-crud/src/components/bulk-update-dialog.tsx
  packages/compass-crud/src/stores/crud-store.ts
Labels: feature flagged, feat

#5048 chore: factor out the readonly input used in Bulk Update and Bulk Delete modals COMPASS-7387
  package-lock.json
  packages/compass-crud/src/components/bulk-delete-modal.tsx
  packages/compass-crud/src/components/bulk-update-dialog.spec.tsx
  packages/compass-crud/src/components/bulk-update-dialog.tsx
  packages/compass-crud/src/components/readonly-filter.tsx
Labels: feature flagged

#5062 feat: add feedback toasts for bulk updates COMPASS-7327
  packages/compass-crud/src/stores/crud-store.ts
Labels: feature flagged, feat

#5066 fix(compass-home): add z-index to shell container so it overlays sidebar content COMPASS-7395
  packages/compass-home/src/components/workspace.tsx
Labels: release notes, fix

#5067 feat: automatically retry the update preview on transient transaction errors COMPASS-7369
  packages/compass-crud/src/stores/crud-store.ts
  packages/data-service/src/data-service.ts
Labels: feature flagged, feat

#5068 feat(crud): abort in progress update previews COMPASS-7368
  packages/compass-crud/src/stores/crud-store.ts
Labels: feature flagged, feat

#5032 feat: add export to language button in delete modal COMPASS-7335
  package-lock.json
  packages/bson-transpilers/index.js
  packages/bson-transpilers/lib/symbol-table/javascripttogo.js
  packages/bson-transpilers/lib/symbol-table/javascripttojava.js
  packages/bson-transpilers/lib/symbol-table/javascripttophp.js
  packages/bson-transpilers/lib/symbol-table/javascripttopython.js
  packages/bson-transpilers/lib/symbol-table/javascripttoruby.js
  packages/bson-transpilers/lib/symbol-table/javascripttorust.js
  packages/bson-transpilers/lib/symbol-table/javascripttoshell.js
  packages/bson-transpilers/lib/symbol-table/pythontogo.js
  packages/bson-transpilers/lib/symbol-table/pythontojava.js
  packages/bson-transpilers/lib/symbol-table/pythontojavascript.js
  packages/bson-transpilers/lib/symbol-table/pythontophp.js
  packages/bson-transpilers/lib/symbol-table/pythontoruby.js
  packages/bson-transpilers/lib/symbol-table/pythontorust.js
  packages/bson-transpilers/lib/symbol-table/pythontoshell.js
  packages/bson-transpilers/lib/symbol-table/shelltogo.js
  packages/bson-transpilers/lib/symbol-table/shelltojava.js
  packages/bson-transpilers/lib/symbol-table/shelltojavascript.js
  packages/bson-transpilers/lib/symbol-table/shelltophp.js
  packages/bson-transpilers/lib/symbol-table/shelltopython.js
  packages/bson-transpilers/lib/symbol-table/shelltoruby.js
  packages/bson-transpilers/lib/symbol-table/shelltorust.js
  packages/bson-transpilers/symbols/go/templates.yaml
  packages/bson-transpilers/symbols/java/templates.yaml
  packages/bson-transpilers/symbols/javascript/templates.yaml
  packages/bson-transpilers/symbols/php/templates.yaml
  packages/bson-transpilers/symbols/python/templates.yaml
  packages/bson-transpilers/symbols/ruby/templates.yaml
  packages/bson-transpilers/symbols/rust/templates.yaml
  packages/bson-transpilers/symbols/shell/templates.yaml
  packages/bson-transpilers/test/index.test.js
  packages/bson-transpilers/test/yaml/driver-syntax.yaml
  packages/bson-transpilers/test/yaml/imports.yaml
  packages/compass-aggregations/src/modules/export-to-language.js
  packages/compass-crud/src/components/bulk-delete-modal.spec.tsx
  packages/compass-crud/src/components/bulk-delete-modal.tsx
  packages/compass-crud/src/components/delete-data-menu.tsx
  packages/compass-crud/src/components/document-list.tsx
  packages/compass-crud/src/components/readonly-filter.tsx
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-export-to-language/src/components/modal.tsx
  packages/compass-export-to-language/src/modules/transpiler.spec.ts
  packages/compass-export-to-language/src/modules/transpiler.ts
  packages/compass-export-to-language/src/stores/store.js
  packages/compass-export-to-language/src/stores/store.spec.js
  packages/compass-query-bar/src/stores/query-bar-reducer.ts
  packages/compass-schema/src/stores/store.js
  packages/compass-schema/src/stores/store.spec.js
Labels: feature flagged, feat, no release notes

#5078 fix(compass-aggregations): fix preferences check for Atlas-only out stages preview
  packages/compass-aggregations/src/components/stage-preview/output-stage-preview.spec.tsx
  packages/compass-aggregations/src/components/stage-preview/output-stage-preview.tsx
Labels: fix, no release notes

#5090 fix: pass relaxed: false to EJSON.deserialize() so values won't be promoted COMPASS-7431
  packages/compass-import-export/src/export/export-json.spec.ts
  packages/compass-import-export/src/import/import-json.spec.ts
  packages/compass-import-export/src/import/import-json.ts
  packages/compass-import-export/test/fixtures.ts
  packages/compass-import-export/test/json/good.imported.ejson
  packages/compass-import-export/test/json/promotable.exported.csv
  packages/compass-import-export/test/json/promotable.exported.ejson
  packages/compass-import-export/test/json/promotable.gathered.json
  packages/compass-import-export/test/json/promotable.imported.ejson
  packages/compass-import-export/test/json/promotable.json
Labels: release notes, fix

#5072 feat: remove outdated guide cues COMPASS-7396
  packages/compass-aggregations/src/components/aggregation-side-panel/index.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
  packages/compass-crud/src/components/view-switcher.tsx
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-query-bar/src/components/query-bar.tsx
  packages/compass-shell/src/components/shell-header/shell-header.spec.tsx
  packages/compass-shell/src/components/shell-header/shell-header.tsx
  packages/compass-sidebar/src/components/navigation-items.spec.tsx
  packages/compass-sidebar/src/components/navigation-items.tsx
Labels: release notes, feat

#5097 fix(stage-wizard): remove field selector from $count
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/group-with-statistics.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/group/group-with-statistics.tsx
Labels: release notes, fix

#5108 fix: remove the update editor colour overrides COMPASS-7446
  packages/compass-crud/src/components/bulk-update-dialog.tsx
Labels: feature flagged, fix

#5095 fix: use consistent monospace fonts HELP-52113
  packages/compass-crud/src/components/table-view/document-table-view.less
  packages/compass-serverstats/src/components/rtss-lists.less
Labels: release notes, fix

#5111 fix(compass-components): do not keep fallback content when not needed COMPASS-7417
  packages/compass-components/src/components/content-with-fallback.tsx
Labels: release notes, fix

#5112 fix(stage-wizard): indent generated stages
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
Labels: release notes, fix

#5117 fix(connection-storage): remove oidc serialized state from connection COMPASS-7453
  packages/connection-storage/src/connection-secrets.spec.ts
  packages/connection-storage/src/connection-secrets.ts
Labels: bug, release notes, fix

#5105 chore: add a button to save an update query from the Bulk Update modal COMPASS-7331
  packages/compass-components/src/components/interactive-popover.spec.tsx
  packages/compass-components/src/components/interactive-popover.tsx
  packages/compass-components/src/hooks/use-toast.tsx
  packages/compass-crud/package.json
  packages/compass-crud/src/components/bulk-update-dialog.spec.tsx
  packages/compass-crud/src/components/bulk-update-dialog.tsx
  packages/compass-crud/src/components/document-list.tsx
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-query-bar/src/components/query-history-button-popover.tsx
  packages/compass-query-bar/src/components/query-history/favorite-list.tsx
  packages/compass-query-bar/src/components/query-history/index.spec.tsx
  packages/compass-query-bar/src/components/query-history/index.tsx
  packages/compass-query-bar/src/components/query-history/query-item/query-item-action-buttons.tsx
  packages/compass-query-bar/src/components/query-option.tsx
  packages/compass-query-bar/src/constants/query-option-definition.ts
  packages/compass-query-bar/src/stores/query-bar-reducer.ts
  packages/compass-query-bar/src/utils/get-query-attributes.spec.ts
  packages/compass-query-bar/src/utils/get-query-attributes.ts
  packages/compass-saved-aggregations-queries/src/components/saved-item-card.test.tsx
  packages/compass-saved-aggregations-queries/src/components/saved-item-card.tsx
  packages/compass-saved-aggregations-queries/src/hooks/use-grid-filters.tsx
  packages/compass-saved-aggregations-queries/src/stores/aggregations-queries-items.ts
  packages/my-queries-storage/src/query-storage.spec.ts
  packages/my-queries-storage/src/query-storage.ts
Labels: release notes, feature flagged, feat

#5134 feat(stage-wizard): wizard panel hidden by default
  packages/compass-aggregations/src/modules/side-panel.spec.ts
  packages/compass-aggregations/src/stores/store.ts
Labels: feat, no release notes

#5135 feat(query-bar): autoinsert empty document for all fields in the query bar
  packages/compass-editor/src/codemirror/document-autocompleter.ts
  packages/compass-editor/src/codemirror/utils.test.ts
  packages/compass-editor/src/editor.tsx
  packages/compass-editor/src/index.ts
  packages/compass-editor/test/completer.ts
  packages/compass-query-bar/src/components/option-editor.spec.tsx
  packages/compass-query-bar/src/components/option-editor.tsx
  packages/compass-query-bar/src/components/query-option.tsx
Labels: release notes, feat

#5131 feat: saved update queries do not open the modal in readonly mode COMPASS-7460
  packages/compass-query-bar/src/components/query-history/favorite-list.spec.tsx
  packages/compass-query-bar/src/components/query-history/favorite-list.tsx
  packages/compass-query-bar/src/components/query-history/query-item/query-item-card.tsx
  packages/compass-query-bar/src/plugin.spec.tsx
  packages/compass-query-bar/src/stores/query-bar-reducer.spec.ts
  packages/compass-query-bar/src/stores/query-bar-reducer.ts
  packages/compass-query-bar/src/stores/query-bar-store.ts
Labels: feature flagged, feat

#5144 fix(crud): don't show the number of documents if it is null/undefined COMPASS-7454
  packages/compass-crud/src/components/bulk-delete-modal.spec.tsx
  packages/compass-crud/src/components/bulk-delete-modal.tsx
  packages/compass-crud/src/components/bulk-update-dialog.spec.tsx
  packages/compass-crud/src/components/bulk-update-dialog.tsx
  packages/compass-crud/src/components/document-list.tsx
  packages/compass-crud/src/stores/crud-store.ts
Labels: feature flagged, fix

#5147 Fix dnd conflict with container layout
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-toolbar-container.tsx
  packages/compass-components/src/components/workspace-container.tsx
  packages/compass-generative-ai/src/components/ai-experience-entry.tsx
Labels: no release notes

#5156 chore: filter out update queries from My Queries
  packages/compass-saved-aggregations-queries/src/components/aggregations-queries-list.test.tsx
  packages/compass-saved-aggregations-queries/src/components/aggregations-queries-list.tsx
  packages/compass-saved-aggregations-queries/src/stores/index.ts
Labels: feature flagged, feat

#5137 fix(compass-crud): expanded docs retains state after switching tabs COMPASS-7318
  package-lock.json
  packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-preview.spec.tsx
  packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-preview.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-preview.spec.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-as-text-workspace/pipeline-preview.tsx
  packages/compass-aggregations/src/components/pipeline-output-options-menu.tsx
  packages/compass-aggregations/src/components/pipeline-results-workspace/index.spec.tsx
  packages/compass-aggregations/src/components/pipeline-results-workspace/index.tsx
  packages/compass-aggregations/src/components/pipeline-results-workspace/pipeline-results-header.tsx
  packages/compass-aggregations/src/components/pipeline-results-workspace/pipeline-results-list.spec.tsx
  packages/compass-aggregations/src/components/pipeline-results-workspace/pipeline-results-list.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/index.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/index.tsx
  packages/compass-aggregations/src/components/pipeline/pipeline.jsx
  packages/compass-aggregations/src/components/stage-toolbar/option-menu.spec.tsx
  packages/compass-aggregations/src/components/stage-toolbar/option-menu.tsx
  packages/compass-aggregations/src/modules/aggregation.spec.ts
  packages/compass-aggregations/src/modules/aggregation.ts
  packages/compass-aggregations/src/modules/input-documents.ts
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
  packages/compass-aggregations/src/modules/pipeline-builder/text-editor-pipeline.ts
  packages/compass-components/src/components/document-list/document-edit-actions-footer.tsx
  packages/compass-components/src/components/document-list/document.spec.tsx
  packages/compass-components/src/components/document-list/document.tsx
  packages/compass-components/src/components/document-list/element.tsx
  packages/compass-crud/src/components/bulk-delete-modal.tsx
  packages/compass-crud/src/components/document-list-view.spec.tsx
  packages/compass-crud/src/components/document-list-view.tsx
  packages/compass-crud/src/components/document.tsx
  packages/compass-crud/src/components/editable-document.tsx
  packages/compass-crud/src/components/readonly-document.tsx
  packages/compass-e2e-tests/helpers/commands/index.ts
  packages/compass-e2e-tests/helpers/commands/navigate-within-current-collection-tabs.ts
  packages/compass-e2e-tests/helpers/commands/select-focus-mode-stage-output-option.ts
  packages/compass-e2e-tests/helpers/commands/select-pipeline-results-output-option.ts
  packages/compass-e2e-tests/helpers/commands/select-stage-menu-option.ts
  packages/compass-e2e-tests/helpers/commands/select-text-pipeline-output-option.ts
  packages/compass-e2e-tests/helpers/insert-data.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
  packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
  packages/hadron-document/package.json
  packages/hadron-document/src/document.ts
  packages/hadron-document/src/element-events.ts
  packages/hadron-document/src/element.ts
  packages/hadron-document/test/document.test.ts
  packages/hadron-document/test/element.test.ts
Labels: release notes, fix

#5140 feat(bulk-update): render document count and restyle query preview
  packages/compass-crud/src/components/bulk-delete-modal.spec.tsx
  packages/compass-crud/src/components/bulk-delete-modal.tsx
  packages/compass-crud/src/components/bulk-update-dialog.spec.tsx
  packages/compass-crud/src/components/bulk-update-dialog.tsx
  packages/compass-crud/src/components/readonly-filter.tsx
Labels: feature flagged, feat

#5158 feat(search-indexes): clarify search index management support
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
Labels: release notes, feat

#5152 feat: disable the update preview when transactions are not supported COMPASS-7449
  packages/compass-crud/src/components/bulk-update-dialog.spec.tsx
  packages/compass-crud/src/components/bulk-update-dialog.tsx
  packages/compass-crud/src/components/document-list.tsx
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
Labels: feature flagged, feat

#5159 feat: extract toasts and add a CTA for refresh COMPASS-7457
  packages/compass-components/src/components/toast-body.tsx
  packages/compass-components/src/index.ts
  packages/compass-crud/src/components/bulk-actions-toasts.spec.tsx
  packages/compass-crud/src/components/bulk-actions-toasts.tsx
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-bulk-delete.test.ts
  packages/compass-e2e-tests/tests/collection-bulk-update.test.ts
  packages/compass-import-export/src/components/export-toast.tsx
  packages/compass-import-export/src/components/import-toast.tsx
  packages/compass-import-export/src/components/toast-body.tsx
Labels: feature flagged, feat

#5093 feat(connections): add filter to saved connections when there are more than 10 saved COMPASS-7439
  package-lock.json
  packages/compass-connections/package.json
  packages/compass-connections/src/components/connection-list/connection-list.spec.tsx
  packages/compass-connections/src/components/connection-list/connection-list.tsx
Labels: release notes, feat

#5115 feat(connection-storage): migrate from keytar COMPASS-6854
  package-lock.json
  packages/compass/src/main/application.ts
  packages/connection-storage/package.json
  packages/connection-storage/src/connection-storage.spec.ts
  packages/connection-storage/src/connection-storage.ts
Labels: release notes, feat

#5125 test(connection-storage): exported connections tests COMPASS-7464 COMPASS-7392
  packages/connection-storage/src/connection-storage.spec.ts
  packages/connection-storage/test/fixtures/compass-connections.ts
Labels: no release notes

#5173 fix(compass-editor): fix code mirror autocomplete positioning COMPASS-7477
  packages/compass-editor/src/editor.tsx
Labels: fix, no release notes

#5063 feat(databases-collections, compass-sidebar): add rename collection flow COMPASS-5704
  package-lock.json
  packages/compass-app-stores/src/stores/instance-store.ts
  packages/compass-collection/src/modules/tabs.ts
  packages/compass-collection/src/stores/tabs.spec.ts
  packages/compass-collection/src/stores/tabs.ts
  packages/compass-components/src/hooks/use-toast.tsx
  packages/compass-databases-navigation/package.json
  packages/compass-databases-navigation/src/collection-item.tsx
  packages/compass-databases-navigation/src/constants.tsx
  packages/compass-databases-navigation/src/databases-navigation-tree.spec.tsx
  packages/compass-e2e-tests/helpers/commands/save-aggregation-pipeline.ts
  packages/compass-e2e-tests/helpers/insert-data.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
  packages/compass-e2e-tests/tests/collection-rename.test.ts
  packages/compass-home/src/components/home.tsx
  packages/compass-preferences-model/src/feature-flags.ts
  packages/compass-sidebar/src/components/sidebar-databases-navigation.tsx
  packages/data-service/src/data-service.spec.ts
  packages/data-service/src/data-service.ts
  packages/databases-collections/src/components/rename-collection-modal/rename-collection-modal.spec.tsx
  packages/databases-collections/src/components/rename-collection-modal/rename-collection-modal.tsx
  packages/databases-collections/src/index.ts
  packages/databases-collections/src/modules/rename-collection/rename-collection.spec.ts
  packages/databases-collections/src/modules/rename-collection/rename-collection.ts
  packages/databases-collections/src/stores/rename-collection.spec.tsx
  packages/databases-collections/src/stores/rename-collection.ts
  packages/my-queries-storage/src/pipeline-storage.ts
Labels: release notes, feat

#5170 feat(crud): Bulk update empty state COMPASS-7473
  packages/compass-crud/src/components/bulk-update-dialog.spec.tsx
  packages/compass-crud/src/components/bulk-update-dialog.tsx
Labels: feature flagged, feat
