Repository mongodb-js/compass, pull requests merged in 2023-02, with the labels that each got.

#4016 chore(aggregations): use same component for output stage preview COMPASS-6451
  packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-preview.spec.tsx
  packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-preview.tsx
  packages/compass-aggregations/src/components/stage-preview/index.spec.tsx
  packages/compass-aggregations/src/components/stage-preview/index.tsx
  packages/compass-aggregations/src/components/stage-preview/output-stage-preview.spec.tsx
  packages/compass-aggregations/src/components/stage-preview/output-stage-preview.tsx
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
Labels: feature flagged, feat, no release notes

#4017 feat(focus-mode): hide input preview for output and atlas operators COMPASS-6452
  packages/compass-aggregations/src/components/focus-mode/focus-mode-modal-header.tsx
  packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-editor.spec.tsx
  packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-preview.tsx
  packages/compass-aggregations/src/utils/stage.js
Labels: feature flagged, feat

#3994 fix(compass-schema-validation): optimises the opening of tab
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-validation-tab.test.ts
  packages/compass-schema-validation/src/components/compass-schema-validation/compass-schema-validation.jsx
  packages/compass-schema-validation/src/components/document-preview/document-preview.jsx
  packages/compass-schema-validation/src/components/document-preview/document-preview.spec.jsx
  packages/compass-schema-validation/src/components/document-preview/index.js
  packages/compass-schema-validation/src/components/loading-overlay.tsx
  packages/compass-schema-validation/src/components/sample-documents/sample-documents.jsx
  packages/compass-schema-validation/src/components/sample-documents/sample-documents.spec.jsx
  packages/compass-schema-validation/src/components/validation-editor/validation-editor.jsx
  packages/compass-schema-validation/src/components/validation-editor/validation-editor.spec.jsx
  packages/compass-schema-validation/src/components/validation-states/validation-states.jsx
  packages/compass-schema-validation/src/components/validation-states/validation-states.spec.jsx
  packages/compass-schema-validation/src/modules/sample-documents.js
  packages/compass-schema-validation/src/modules/sample-documents.spec.js
  packages/compass-schema-validation/src/modules/validation.js
  packages/compass-schema-validation/src/stores/store.spec.js
Labels: release notes, fix

#4010 feat(focus-mode): resizable editor in focus mode COMPASS-6446
  packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-editor.tsx
  packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-preview.tsx
  packages/compass-aggregations/src/components/focus-mode/focus-mode.tsx
  packages/compass-aggregations/src/components/stage-toolbar/index.tsx
  packages/compass-aggregations/src/components/stage-toolbar/stage-operator-select.tsx
Labels: release notes, feature flagged, feat

#4023 fix(aggregations): stage editor value on index change COMPASS-6447
  packages/compass-aggregations/src/components/stage-editor/stage-editor.jsx
  packages/compass-aggregations/src/components/stage-editor/stage-editor.tsx
  packages/compass-aggregations/src/components/stage-preview/index.tsx
  packages/compass-aggregations/src/components/stage.tsx
Labels: feature flagged, fix, no release notes

#4031 feat(aggregations): add keyboard shortcuts COMPASS-6391
  packages/compass-aggregations/src/components/focus-mode/focus-mode-modal-header.tsx
Labels: release notes, feature flagged, feat

#3961 fix(compass-crud): don't show negative count on delete when no document count COMPASS-5996
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
Labels: release notes, fix

#4039 feat(focus-mode): dark mode COMPASS-6472
  packages/compass-aggregations/src/components/focus-mode/focus-mode.tsx
Labels: feature flagged, feat

#4038 test(focus-mode): add e2e tests COMPASS-6473
  packages/compass-aggregations/src/components/focus-mode/focus-mode-modal-header.tsx
  packages/compass-aggregations/src/components/stage-toolbar/index.tsx
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
Labels: feature flagged, feat

#3995 feat(compass-explain-plan): adds a cancellable loader to explain
  packages/compass-e2e-tests/helpers/commands/run-find-operation.ts
  packages/compass-e2e-tests/helpers/insert-data.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-explain-plan-tab.test.ts
  packages/compass-explain-plan/src/components/explain-plan/explain-plan.jsx
  packages/compass-explain-plan/src/components/explain-states/explain-states.jsx
  packages/compass-explain-plan/src/components/explain-states/explain-states.spec.jsx
  packages/compass-explain-plan/src/constants/explain-states.ts
  packages/compass-explain-plan/src/modules/explain.js
  packages/compass-explain-plan/src/modules/explain.spec.js
  packages/compass-explain-plan/src/stores/store.spec.js
Labels: release notes, feat

#4050 feat(databases-collections): flexi bucket opts for Timeseries
  packages/compass-e2e-tests/helpers/commands/add-collection.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/database-collections-tab.test.ts
  packages/databases-collections/src/components/collection-fields/collection-fields.jsx
  packages/databases-collections/src/components/collection-fields/has-flexible-bucket-config-support.spec.ts
  packages/databases-collections/src/components/collection-fields/has-flexible-bucket-config-support.ts
  packages/databases-collections/src/components/collection-fields/time-series-fields.jsx
  packages/databases-collections/src/components/collection-fields/time-series-fields.spec.jsx
Labels: release notes, feat

#4003 feat(import): Include preview rows in the listCSVFields() result COMPASS-6422
  packages/compass-components/src/components/combobox/Chip.tsx
  packages/compass-components/src/components/combobox/Combobox.styles.ts
  packages/compass-components/src/components/combobox/Combobox.tsx
  packages/compass-components/src/components/combobox/Combobox.types.ts
  packages/compass-components/src/components/combobox/ComboboxMenu/ComboboxMenu.tsx
  packages/compass-components/src/components/combobox/ComboboxOption.tsx
  packages/compass-components/src/components/combobox/README.md
  packages/compass-components/src/components/combobox/utils/OptionObjectUtils.ts
  packages/compass-components/src/components/combobox/utils/flattenChildren.tsx
  packages/compass-components/src/components/combobox/utils/wrapJSX.tsx
  packages/compass-import-export/src/import/list-csv-fields.spec.ts
  packages/compass-import-export/src/import/list-csv-fields.ts
  packages/compass-import-export/test/csv/array.preview.json
  packages/compass-import-export/test/csv/bad.preview.json
  packages/compass-import-export/test/csv/complex.preview.json
  packages/compass-import-export/test/csv/good-commas.preview.json
  packages/compass-import-export/test/csv/good-tabs.preview.json
  packages/compass-import-export/test/csv/number-transform.preview.json
  packages/compass-import-export/test/csv/object.preview.json
  packages/compass-import-export/test/csv/semicolons.preview.json
  packages/compass-import-export/test/csv/spaces.preview.json
  packages/compass-import-export/test/csv/sparse.preview.json
Labels: release notes, feat

#4061 fix(focus-mode): plain object for redux connect
  packages/compass-aggregations/src/components/focus-mode/focus-mode-stage-preview.tsx
Labels: fix, no release notes

#4064 fix(import): Stop on errors when stopOnErrors is true COMPASS-6518
  packages/compass-import-export/src/utils/collection-stream.spec.js
  packages/compass-import-export/src/utils/collection-stream.spec.ts
  packages/compass-import-export/src/utils/collection-stream.ts
Labels: release notes, fix

#4067 fix(focus-mode): feature flagged guide cue COMPASS-6524
  packages/compass-aggregations/src/components/stage.tsx
Labels: fix, no release notes

#3972 feat(collections): when dropping a collection or database, redirect to either the database or databases view COMPASS-6018, COMPASS-6434
  packages/compass-app-stores/src/stores/instance-store.js
  packages/compass-collection/src/stores/index.ts
  packages/compass-e2e-tests/helpers/commands/drop-collection-from-sidebar.ts
  packages/compass-e2e-tests/helpers/commands/drop-database-from-sidebar.ts
  packages/compass-e2e-tests/helpers/commands/index.ts
  packages/compass-e2e-tests/helpers/insert-data.ts
  packages/compass-e2e-tests/tests/database-collections-tab.test.ts
  packages/compass-e2e-tests/tests/instance-databases-tab.test.ts
  packages/compass-e2e-tests/tests/instance-sidebar.test.ts
  packages/compass-e2e-tests/tests/redirect.test.ts
  packages/databases-collections/src/stores/collections-store.js
Labels: release notes, feat

#4070 feat(import): importJSON() COMPASS-6424
  packages/compass-import-export/src/import/import-csv.spec.ts
  packages/compass-import-export/src/import/import-csv.ts
  packages/compass-import-export/src/import/import-json.spec.ts
  packages/compass-import-export/src/import/import-json.ts
  packages/compass-import-export/src/utils/csv.ts
  packages/compass-import-export/src/utils/import.ts
  packages/compass-import-export/test/json/complex.imported.ejson
  packages/compass-import-export/test/json/complex.json
  packages/compass-import-export/test/json/good.imported.ejson
  packages/compass-import-export/test/jsonl/extra-line.imported.ejson
  packages/compass-import-export/test/jsonl/good.imported.ejson
  packages/compass-import-export/test/jsonl/jsonl-with-csv-fileext.imported.ejson
  packages/compass-import-export/test/jsonl/single-doc.imported.ejson
Labels: feat, no release notes

#4060 fix(hardon-document): cancel edit on non-existent field COMPASS-6505
  packages/hadron-document/src/element.ts
  packages/hadron-document/test/element.test.ts
Labels: release notes, fix

#4076 fix(pre-commit): ignore prettier when no files are changed
  scripts/precommit.js
Labels: fix, no release notes

#4074 fix(mongodb-compass): halt autoupdater on application exit to prevent logger crashing COMPASS-6051
  packages/compass-e2e-tests/helpers/compass.ts
  packages/compass/src/main/auto-update-manager.spec.ts
  packages/compass/src/main/auto-update-manager.ts
Labels: release notes, fix

#4075 test(import): import tests for windows line endings, non-utf8 encodings, BOM chars COMPASS-6529
  packages/compass-import-export/src/import/analyze-csv-fields.spec.ts
  packages/compass-import-export/src/import/analyze-csv-fields.ts
  packages/compass-import-export/src/import/guess-filetype.spec.ts
  packages/compass-import-export/src/import/guess-filetype.ts
  packages/compass-import-export/src/import/import-csv.spec.ts
  packages/compass-import-export/src/import/import-csv.ts
  packages/compass-import-export/src/import/import-json.spec.ts
  packages/compass-import-export/src/import/import-json.ts
  packages/compass-import-export/src/utils/collection-stream.ts
  packages/compass-import-export/src/utils/utf8-validator.ts
Labels: no release notes

#4080 feat(import): progressCallback(numDocs, numBytes) COMPASS-6528
  packages/compass-import-export/src/import/analyze-csv-fields.spec.ts
  packages/compass-import-export/src/import/analyze-csv-fields.ts
  packages/compass-import-export/src/import/import-csv.spec.ts
  packages/compass-import-export/src/import/import-csv.ts
  packages/compass-import-export/src/import/import-json.spec.ts
  packages/compass-import-export/src/import/import-json.ts
  packages/compass-import-export/src/utils/byte-counter.ts
  packages/compass-import-export/src/utils/utf8-validator.ts
Labels: feat, no release notes

#4087 chore(import): make the output param (log file) for importCSV and importJSON optional COMPASS-6519 COMPASS-6520
  packages/compass-import-export/src/import/import-csv.ts
  packages/compass-import-export/src/import/import-json.ts
  packages/compass-import-export/src/utils/import.ts
Labels: no release notes

#4084 fix(compass-import-export): also reject truncated UTF-8
  packages/compass-import-export/src/import/import-csv.spec.ts
  packages/compass-import-export/src/utils/utf8-validator.ts
Labels: fix, no release notes

#4094 feat(settings): dark theme improvements in the settings modal COMPASS-6552
  packages/compass-settings/src/components/settings/theme.tsx
  packages/compass-settings/src/components/sidebar.tsx
Labels: release notes, feat

#4086 feat(compass-schema): Support LeafyGreen darkmode COMPASS-6533
  packages/compass-components/src/components/empty-content.tsx
  packages/compass-components/src/index.ts
  packages/compass-schema/src/components/compass-schema.tsx
  packages/compass-schema/src/components/compass-schema/compass-schema.jsx
  packages/compass-schema/src/components/compass-schema/compass-schema.module.less
  packages/compass-schema/src/components/compass-schema/index.js
  packages/compass-schema/src/components/coordinates-minichart/constants.js
  packages/compass-schema/src/components/coordinates-minichart/coordinates-minichart.jsx
  packages/compass-schema/src/components/field.tsx
  packages/compass-schema/src/modules/create-d3-tip.js
  packages/compass-schema/src/modules/date.js
  packages/compass-schema/src/modules/few.js
  packages/compass-schema/src/modules/many.js
Labels: feature flagged, feat

#4079 feat(aggregations): conditional confirmation modal COMPASS-6355
  configs/mocha-config-compass/register/jsdom-global-register.js
  packages/compass-aggregations/src/components/pipeline-confirm-modal/pipeline-confirm-modal.spec.tsx
  packages/compass-aggregations/src/components/pipeline-confirm-modal/pipeline-confirm-modal.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/index.tsx
  packages/compass-aggregations/src/components/pipeline/pipeline.jsx
  packages/compass-aggregations/src/components/saved-pipelines/saved-pipeline-confirmation-modals.tsx
  packages/compass-aggregations/src/components/saved-pipelines/saved-pipelines.spec.tsx
  packages/compass-aggregations/src/components/saved-pipelines/saved-pipelines.tsx
  packages/compass-aggregations/src/modules/index.ts
  packages/compass-aggregations/src/modules/is-new-pipeline-confirm.spec.js
  packages/compass-aggregations/src/modules/is-new-pipeline-confirm.ts
  packages/compass-aggregations/src/modules/saved-pipeline.ts
  packages/compass-aggregations/src/stores/store.spec.js
  packages/compass-components/src/hooks/use-confirmation.spec.tsx
  packages/compass-components/src/hooks/use-confirmation.tsx
  packages/compass-components/src/index.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
  packages/compass-e2e-tests/tests/connection-form.test.ts
  packages/compass-e2e-tests/tests/import-export-connections.test.ts
  packages/compass-e2e-tests/tests/instance-my-queries-tab.test.ts
  packages/compass-e2e-tests/tests/protect-connection-strings.test.ts
  packages/compass-home/src/components/home.tsx
  packages/compass-saved-aggregations-queries/src/components/aggregations-queries-list.tsx
  packages/compass-saved-aggregations-queries/src/components/delete-item-modal.tsx
  packages/compass-saved-aggregations-queries/src/components/index.test.tsx
  packages/compass-saved-aggregations-queries/src/components/saved-item-card.test.tsx
  packages/compass-saved-aggregations-queries/src/stores/delete-item.ts
  packages/compass-saved-aggregations-queries/src/stores/index.ts
  packages/connection-form/src/components/confirm-edit-connection-string.spec.tsx
  packages/connection-form/src/components/confirm-edit-connection-string.tsx
  packages/connection-form/src/components/connect-form.tsx
  packages/connection-form/src/components/connection-string-input.spec.tsx
  packages/connection-form/src/components/connection-string-input.tsx
Labels: release notes, feat

#4105 fix(aggregations): wrap aggregations plugin in confirmation modal
  packages/compass-aggregations/src/plugin.jsx
Labels: fix, no release notes
