Repository mongodb-js/compass, pull requests merged in 2023-06, with the labels that each got.

#4450 chore(e2e): wait for animations on the option before clicking to select it
  packages/compass-e2e-tests/helpers/commands/set-connect-form-state.ts
Labels: no release notes

#4452 fix(compass-import-export): add file type filters when exporting COMPASS-6890
  packages/compass-import-export/src/components/export-modal.tsx
Labels: release notes, fix

#4457 chore(connection-form): add warning to oidc preview authentication method
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.spec.tsx
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.tsx
Labels: feature flagged

#4449 fix: rename "Less Options" to "Fewer Options" COMPASS-6774
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.spec.tsx
  packages/compass-components/src/components/more-options-toggle.spec.tsx
  packages/compass-components/src/components/more-options-toggle.tsx
Labels: release notes, fix

#4453 feat(explain-plan, compass-aggregations): add visual tree and update summary for the aggregation explain plan COMPASS-6821 COMPASS-6888
  packages/compass-aggregations/src/components/focus-mode/focus-mode.tsx
  packages/compass-components/src/components/index-icon.tsx
  packages/compass-components/src/components/index-keys-badge.tsx
  packages/compass-components/src/components/inline-definition.tsx
  packages/compass-components/src/components/modals/modal-header.tsx
  packages/compass-components/src/components/modals/modal.tsx
  packages/compass-components/src/index.ts
  packages/compass-editor/src/json-editor.tsx
  packages/compass-explain-plan/src/components/explain-body/explain-body.module.less
  packages/compass-explain-plan/src/components/explain-cannot-visualize-banner/explain-cannot-visualize-banner.jsx
  packages/compass-explain-plan/src/components/explain-cannot-visualize-banner/explain-cannot-visualize-banner.module.less
  packages/compass-explain-plan/src/components/explain-plan-modal.tsx
  packages/compass-explain-plan/src/components/explain-plan-side-summary.tsx
  packages/compass-explain-plan/src/components/explain-plan-view.tsx
  packages/compass-explain-plan/src/components/explain-tree/explain-tree.tsx
  packages/compass-explain-plan/src/components/explain-tree/tree-layout.tsx
  packages/compass-explain-plan/src/stores/explain-plan-modal-store.ts
Labels: release notes, feat

#4458 fix(import): imported, not exported
  packages/compass-import-export/src/components/import-toast.tsx
Labels: fix, no release notes

#4464 feat(compass-settings): add OIDC settings, add enable device auth setting COMPASS-6849
  packages/compass-preferences-model/src/preferences.ts
  packages/compass-settings/src/components/modal.tsx
  packages/compass-settings/src/components/settings/oidc-settings.spec.tsx
  packages/compass-settings/src/components/settings/oidc-settings.tsx
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.spec.tsx
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.tsx
Labels: feature flagged, feat

#4462 fix: support Dark Mode on TypeEditor dropdown - COMPASS-6893
  packages/compass-components/src/components/document-list/element-editors.tsx
Labels: release notes, fix

#4475 fix(stage-wizard): correct label COMPASS-6895
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
Labels: feature flagged, fix

#4474 feat(stage-wizard): enable feature COMPASS-6814
  packages/compass-preferences-model/src/feature-flags.ts
Labels: release notes, feat

#4489 feat(explain-plan): add zoom control to the modal tree view COMPASS-6843
  packages/compass-explain-plan/src/components/explain-plan-view.tsx
  packages/compass-explain-plan/src/components/explain-tree/explain-tree.tsx
  packages/compass-explain-plan/src/components/explain-tree/tree-layout.tsx
  packages/compass-explain-plan/src/components/zoom-control.tsx
Labels: release notes, feat

#4490 fix(compass-shell): let enableShell setting control runtime start/stop
  packages/compass-shell/src/modules/runtime.js
  packages/compass-shell/src/stores/store.js
  packages/compass-shell/src/stores/store.spec.js
Labels: release notes, fix

#4496 fix(telemetry): track `has_sort`
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
Labels: release notes, fix

#4497 feat(compass-connections): add connecting message when connecting with OIDC COMPASS-6875
  packages/compass-connections/src/components/connecting/connecting.tsx
  packages/compass-connections/src/stores/connections-store.ts
Labels: feature flagged, feat

#4507 fix(compass-crud): show 1 as the page number even if in a collection, no entries are present
  packages/compass-crud/src/stores/crud-store.ts
Labels: release notes, fix

#4484 feat: optionally store OIDC tokens as secrets COMPASS-6801
  package-lock.json
  packages/compass-connections/package.json
  packages/compass-connections/src/stores/connections-store.spec.ts
  packages/compass-connections/src/stores/connections-store.ts
  packages/compass-e2e-tests/helpers/commands/index.ts
  packages/compass-e2e-tests/helpers/commands/save-connection-string-as-favorite.ts
  packages/compass-e2e-tests/tests/oidc.test.ts
  packages/compass-preferences-model/src/preferences.ts
  packages/compass-settings/src/components/settings/oidc-settings.tsx
  packages/data-service/package.json
  packages/data-service/src/connection-secrets.ts
  packages/data-service/src/data-service.ts
Labels: feature flagged, feat

#4479 fix: select combobox option onBlur COMPASS-6511
  package-lock.json
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/field-combobox.tsx
  packages/compass-components/src/components/combobox-with-custom-option.tsx
  packages/compass-components/src/components/combobox/Combobox.tsx
  packages/compass-indexes/package.json
  packages/compass-indexes/src/components/create-index-fields.spec.tsx
  packages/compass-indexes/src/components/create-index-fields.tsx
  packages/compass-indexes/src/components/create-index-form/create-index-form.tsx
  packages/compass-indexes/src/components/create-index-modal/create-index-modal.tsx
  packages/compass-indexes/src/modules/create-index/fields.spec.js
  packages/compass-indexes/src/modules/create-index/fields.ts
  packages/compass-indexes/src/modules/create-index/index.ts
  packages/compass-indexes/src/modules/create-index/new-index-field.spec.ts
  packages/compass-indexes/src/modules/create-index/new-index-field.ts
Labels: release notes, fix

#4508 fix(compass-connections): use mongodb-cloud-info v2 for ipv6 support in cloud metrics COMPASS-6795
  package-lock.json
  packages/compass-connections/package.json
Labels: release notes, fix

#4513 feat(connection-form): set enable OIDC auth mechanism feature flag to released COMPASS-6803
  packages/compass-e2e-tests/tests/connection-form.test.ts
  packages/compass-e2e-tests/tests/oidc.test.ts
  packages/compass-preferences-model/src/feature-flags.ts
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-tab.spec.tsx
Labels: release notes, feat

#4509 chore: Electron 23 COMPASS-6897
  configs/mocha-config-compass/index.js
  configs/mocha-config-compass/register/dns-config-register.js
  configs/webpack-config-compass/package.json
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-crud/package.json
  packages/compass-e2e-tests/package.json
  packages/compass-e2e-tests/tests/connection.test.ts
  packages/compass-explain-plan/package.json
  packages/compass-find-in-page/package.json
  packages/compass-import-export/package.json
  packages/compass-indexes/package.json
  packages/compass-query-bar/package.json
  packages/compass-query-history/package.json
  packages/compass-schema-validation/package.json
  packages/compass-shell/package.json
  packages/compass/package.json
  packages/compass/src/app/index.jsx
  packages/hadron-build/package.json
  packages/hadron-ipc/package.json
  packages/storage-mixin/package.json
  scripts/package.json
Labels: release notes

#4519 fix(compass-editors): editor darkmode background selection color COMPASS-6910
  packages/compass-editor/src/json-editor.tsx
Labels: release notes, fix

#4523 fix(data-service): update how we set ALLOWED_HOSTS when enableUntrustedEndpoints is true COMPASS-6916
  packages/data-service/src/connect-mongo-client.spec.ts
  packages/data-service/src/connect-mongo-client.ts
  packages/data-service/src/connection-options.ts
Labels: feature flagged, fix

#4527 feat: add Atlas error message when connection fails due to IP access issue COMPASS-6842
  package-lock.json
  packages/data-service/package.json
Labels: release notes, feat

#4535 fix: disable the autoupdater for MSI installs (windows without squirrel) COMPASS-6857
  packages/compass/src/main/auto-updater.ts
Labels: release notes, fix

#4528 fix(stage-wizard): button label
  packages/compass-aggregations/src/components/aggregation-side-panel/index.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/index.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace/dnd-wrapper.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
  packages/compass-aggregations/src/modules/side-panel.spec.ts
  packages/compass-aggregations/src/modules/side-panel.ts
Labels: fix, no release notes

#4540 feat(compass-crud): show insight when query is unindexed COMPASS-6832
  package-lock.json
  packages/compass-collection/src/components/collection/collection.tsx
  packages/compass-components/src/components/signal-popover.tsx
  packages/compass-components/src/index.ts
  packages/compass-crud/package.json
  packages/compass-crud/src/components/crud-toolbar.tsx
  packages/compass-crud/src/components/document-list.tsx
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-crud/src/utils/cancellable-queries.spec.ts
  packages/compass-crud/src/utils/cancellable-queries.ts
  packages/compass-crud/src/utils/index.ts
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.spec.tsx
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
  packages/compass-indexes/src/modules/create-index/index.ts
  packages/compass-indexes/src/stores/create-index.js
  packages/compass-query-bar/src/components/option-editor.tsx
  packages/compass-query-bar/src/components/query-bar.tsx
  packages/compass-query-bar/src/components/query-option.tsx
  packages/explain-plan-helper/src/get-planner-info.ts
  packages/explain-plan-helper/src/index.ts
Labels: release notes, feat

#4534 feat(compass-sidebar, databases-list): show insight when number of collections is too high COMPASS-6835
  packages/compass-components/src/components/interactive-popover.tsx
  packages/compass-components/src/components/signal-popover.tsx
  packages/compass-sidebar/src/components/navigation-items.tsx
  packages/databases-collections-list/src/databases.tsx
  packages/databases-collections-list/src/namespace-card.tsx
  packages/databases-collections-list/src/namespace-param.tsx
Labels: release notes, feat

#4545 fix(import): use bulkWrite correctly COMPASS-6928
  packages/compass-import-export/src/utils/collection-stream.ts
Labels: bug, release notes, fix

#4547 chore: regression test for documents containing the field document
  packages/compass-import-export/src/import/import-json.spec.ts
Labels: no release notes

#4553 skip oidc e2e tests unless it is 7.0+ and enterprise
  packages/compass-e2e-tests/tests/oidc.test.ts
Labels: no release notes

#4551 feat(compass-aggregations): add unindexed aggregation insight COMPASS-6833
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.tsx
  packages/compass-aggregations/src/components/saved-pipelines/saved-pipeline-card.tsx
  packages/compass-aggregations/src/components/saved-pipelines/saved-pipelines.spec.tsx
  packages/compass-aggregations/src/components/saved-pipelines/saved-pipelines.tsx
  packages/compass-aggregations/src/modules/aggregation.ts
  packages/compass-aggregations/src/modules/index.ts
  packages/compass-aggregations/src/modules/insights.spec.ts
  packages/compass-aggregations/src/modules/insights.ts
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
  packages/compass-aggregations/src/modules/pipeline-builder/text-editor-pipeline.ts
  packages/compass-aggregations/src/modules/saved-pipeline.spec.ts
  packages/compass-aggregations/src/modules/saved-pipeline.ts
  packages/compass-aggregations/src/stores/store.spec.ts
  packages/compass-aggregations/src/stores/store.ts
  packages/compass-components/src/components/signal-popover.tsx
  packages/compass-crud/src/components/crud-toolbar.tsx
  packages/compass-query-bar/src/components/option-editor.tsx
  packages/compass-sidebar/src/components/navigation-items.tsx
  packages/databases-collections-list/src/databases.tsx
Labels: release notes, feat

#4524 feat(guide-cue): component implementation COMPASS-6334
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-aggregations/src/components/aggregation-side-panel/index.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/index.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
  packages/compass-aggregations/src/components/use-guide-cue.ts
  packages/compass-aggregations/src/utils/local-storage.ts
  packages/compass-components/src/components/guide-cue/guide-cue-exceptions.ts
  packages/compass-components/src/components/guide-cue/guide-cue-groups.ts
  packages/compass-components/src/components/guide-cue/guide-cue-service.spec.ts
  packages/compass-components/src/components/guide-cue/guide-cue-service.ts
  packages/compass-components/src/components/guide-cue/guide-cue-storage.ts
  packages/compass-components/src/components/guide-cue/guide-cue.spec.tsx
  packages/compass-components/src/components/guide-cue/guide-cue.tsx
  packages/compass-components/src/index.ts
  packages/compass-query-bar/package.json
  packages/compass-query-bar/src/components/query-bar.tsx
Labels: release notes, feat

#4557 feat(compass-crud): auto expand object and array field types on field add COMPASS-6939
  package-lock.json
  packages/compass-components/src/components/document-list/element.tsx
Labels: release notes, feat

#4552 feat(compass-components): guide cue for signal popover
  packages/compass-components/src/components/signal-popover.tsx
Labels: feature flagged, feat

#4566 feat(compass-crud): add bloated docs insight to the document list COMPASS-6837
  package-lock.json
  packages/compass-components/src/components/document-list/document-actions-group.tsx
  packages/compass-components/src/components/signal-popover.tsx
  packages/compass-crud/package.json
  packages/compass-crud/src/components/editable-document.tsx
  packages/compass-crud/src/components/readonly-document.tsx
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-field-store/src/stores/store.js
  packages/compass-field-store/src/stores/store.spec.js
  packages/hadron-document/src/document.ts
Labels: feature flagged, feat

#4559 feat(explain-plan): show unindexed query insight in explain plan modal COMPASS-6933
  packages/compass-components/src/components/signal-popover.tsx
  packages/compass-explain-plan/src/components/explain-plan-modal.spec.tsx
  packages/compass-explain-plan/src/components/explain-plan-side-summary.tsx
  packages/compass-explain-plan/src/components/explain-plan-view.spec.tsx
  packages/compass-explain-plan/src/components/explain-plan-view.tsx
  packages/compass-explain-plan/src/stores/explain-plan-modal-store.ts
Labels: release notes, feat

#4569 feat(guide-cue): disable in tests
  packages/compass-components/src/components/guide-cue/guide-cue-service.spec.ts
  packages/compass-components/src/components/guide-cue/guide-cue-service.ts
  packages/compass-e2e-tests/helpers/compass.ts
Labels: feat, no release notes

#4556 feat(compass-crud): show array length on array fields on documents COMPASS-6938
  packages/compass-components/src/components/bson-value.spec.tsx
  packages/compass-components/src/components/bson-value.tsx
  packages/compass-components/src/components/document-list/element.tsx
  packages/compass-e2e-tests/tests/collection-import.test.ts
Labels: release notes, feat

#4558 feat(compass-collection): add ctrl + tab and ctrl + shift + tab hotkeys for switching tabs
  packages/compass-collection/src/components/workspace/workspace.tsx
Labels: release notes, feat

#4560 feat(explain-plan): enable new explain plan by default
  packages/compass-e2e-tests/helpers/commands/navigate-to-collection-tab.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/README.md
  packages/compass-e2e-tests/tests/collection-heading.test.ts
  packages/compass-e2e-tests/tests/database-collections-tab.test.ts
  packages/compass-preferences-model/src/feature-flags.ts
Labels: release notes, feat

#4564 feat(compass-aggregations, compass-collection): adds insights for usage of $text and $regex in aggregation builder and collection header - COMPASS-6834
  packages/compass-aggregations/src/components/focus-mode/focus-mode-modal-header.tsx
  packages/compass-aggregations/src/components/stage-toolbar/index.tsx
  packages/compass-aggregations/src/components/stage-toolbar/toggle-stage.tsx
  packages/compass-aggregations/src/utils/insights.ts
  packages/compass-collection/src/components/collection-header/clustered-badge.tsx
  packages/compass-collection/src/components/collection-header/collection-header.spec.tsx
  packages/compass-collection/src/components/collection-header/collection-header.tsx
  packages/compass-collection/src/components/collection-header/fle-badge.tsx
  packages/compass-collection/src/components/collection-header/read-only-badge.tsx
  packages/compass-collection/src/components/collection-header/time-series-badge.tsx
  packages/compass-collection/src/components/collection-header/view-badge.tsx
  packages/compass-collection/src/components/collection/collection.spec.tsx
  packages/compass-collection/src/components/collection/collection.tsx
  packages/compass-collection/src/components/workspace/workspace.tsx
  packages/compass-collection/src/modules/is-atlas.ts
  packages/compass-collection/src/stores/index.spec.ts
  packages/compass-collection/src/stores/index.ts
  packages/compass-components/src/components/signal-popover.tsx
Labels: release notes, feat

#4577 fix: remove trackingId from modals and track them
  packages/compass-aggregations/src/components/create-view-modal/create-view-modal.jsx
  packages/compass-aggregations/src/components/duplicate-view-modal/duplicate-view-modal.jsx
  packages/compass-aggregations/src/components/saving-pipeline-modal/saving-pipeline-modal.jsx
  packages/compass-shell/src/components/shell-info-modal/shell-info-modal.jsx
  packages/databases-collections/src/components/create-collection-modal/create-collection-modal.jsx
  packages/databases-collections/src/components/create-database-modal/create-database-modal.jsx
Labels: fix, no release notes

#4568 feat(guide-cue): add cues COMPASS-6614
  package-lock.json
  packages/compass-components/src/components/guide-cue/guide-cue-service.ts
  packages/compass-components/src/components/guide-cue/guide-cue.tsx
  packages/compass-components/src/components/item-action-controls.tsx
  packages/compass-components/src/index.ts
  packages/compass-crud/src/components/crud-toolbar.tsx
  packages/compass-crud/src/components/document-list.tsx
  packages/compass-crud/src/components/view-switcher.tsx
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-home/package.json
  packages/compass-home/src/components/home.tsx
  packages/compass-home/src/contexts/app-registry-context.ts
  packages/compass-shell/src/components/compass-shell/compass-shell.spec.jsx
  packages/compass-shell/src/components/shell-header/shell-header.jsx
  packages/compass-shell/src/components/shell-header/shell-header.spec.jsx
  packages/compass-sidebar/src/components/navigation-items.spec.tsx
  packages/compass-sidebar/src/components/navigation-items.tsx
Labels: release notes, feat

#4582 feat(compass-import-export): signal for bloated documents during import
  packages/compass-app-stores/src/stores/instance-store.js
  packages/compass-import-export/src/components/import-toast.tsx
  packages/compass-import-export/src/import/import-csv.spec.ts
  packages/compass-import-export/src/import/import-csv.ts
  packages/compass-import-export/src/import/import-json.spec.ts
  packages/compass-import-export/src/import/import-json.ts
  packages/compass-import-export/src/import/import-types.ts
  packages/compass-import-export/src/import/import-utils.spec.ts
  packages/compass-import-export/src/import/import-utils.ts
  packages/compass-import-export/src/modules/import.ts
Labels: release notes, feat

#4587 feat(compass-query-bar): add query ai entry and text input COMPASS-6956
  package-lock.json
  packages/compass-editor/src/json-editor.tsx
  packages/compass-query-bar/package.json
  packages/compass-query-bar/src/components/generative-ai/ai-experience-entry.ts
  packages/compass-query-bar/src/components/generative-ai/ai-text-input.tsx
  packages/compass-query-bar/src/components/generative-ai/robot-svg.tsx
  packages/compass-query-bar/src/components/option-editor.tsx
  packages/compass-query-bar/src/components/query-bar.tsx
  packages/compass-query-bar/src/components/query-history-button-popover.tsx
  packages/compass-query-bar/src/components/query-history/favorite-list.tsx
  packages/compass-query-bar/src/components/query-history/index.spec.tsx
  packages/compass-query-bar/src/components/query-history/index.tsx
  packages/compass-query-bar/src/components/query-history/recent-list.tsx
  packages/compass-query-bar/src/components/query-option.tsx
  packages/compass-query-bar/src/modules/ai-query-request.spec.ts
  packages/compass-query-bar/src/modules/ai-query-request.ts
  packages/compass-query-bar/src/stores/ai-query-reducer.spec.ts
  packages/compass-query-bar/src/stores/ai-query-reducer.ts
  packages/compass-query-bar/src/stores/query-bar-reducer.spec.ts
  packages/compass-query-bar/src/stores/query-bar-reducer.ts
  packages/compass-query-bar/src/stores/query-bar-store.ts
  packages/compass-query-bar/test/create-mock-ai-endpoint.ts
  packages/compass-schema/src/components/field.spec.tsx
  packages/compass-schema/src/components/minichart/minichart.jsx
Labels: feature flagged, feat

#4596 fix: use value from the evt.target to fix index creation COMPASS-6981
  packages/compass-components/src/components/combobox-with-custom-option.tsx
Labels: release notes, fix

#4588 fix(compass): cap number of log files to 100 MONGOSH-1449
  package-lock.json
  packages/compass-e2e-tests/package.json
  packages/compass-logging/package.json
  packages/compass/package.json
  packages/compass/src/main/logging.ts
Labels: release notes, fix
