Repository mongodb-js/compass, pull requests merged in 2023-03, with the labels that each got.

#4106 feat(compass-schema,compass-schema-validation): more darkmode and maps fixes COMPASS-5686, COMPASS-6553, COMPASS-6569
  packages/compass-components/src/components/document-list/element.tsx
  packages/compass-schema-validation/src/components/sample-documents/sample-documents.jsx
  packages/compass-schema/src/components/compass-schema.tsx
  packages/compass-schema/src/components/coordinates-minichart/coordinates-minichart.jsx
  packages/compass-schema/src/components/coordinates-minichart/marker-popup.module.less
  packages/compass-schema/src/components/coordinates-minichart/utils.js
  packages/compass-schema/src/components/field.tsx
  packages/compass-schema/src/components/minichart/minichart.jsx
  packages/compass/src/main/window-manager.ts
Labels: feat, no release notes

#4110 feat(compass-sidebar): adds the refresh CTA to sidebar
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/in-use-encryption.test.ts
  packages/compass-e2e-tests/tests/instance-my-queries-tab.test.ts
  packages/compass-e2e-tests/tests/instance-sidebar.test.ts
  packages/compass-sidebar/src/components/navigation-items.spec.tsx
  packages/compass-sidebar/src/components/navigation-items.tsx
  packages/compass-sidebar/src/components/sidebar-title.tsx
Labels: release notes, feat

#4115 chore(import): import fixes
  packages/compass-import-export/src/components/import-modal.tsx
  packages/compass-import-export/src/import/analyze-csv-fields.spec.ts
  packages/compass-import-export/src/import/analyze-csv-fields.ts
  packages/compass-import-export/src/import/import-csv.ts
  packages/compass-import-export/src/import/import-json.ts
  packages/compass-import-export/src/utils/csv.spec.ts
  packages/compass-import-export/src/utils/csv.ts
  packages/compass-import-export/src/utils/import-preview.js
  packages/compass-import-export/test/csv/types/date.csv
Labels: no release notes

#4119 feat: enable LG darkmode as public preview COMPASS-6515, COMPASS-6556
  packages/compass-explain-plan/src/components/explain-summary/explain-summary.tsx
  packages/compass-preferences-model/src/preferences.ts
  packages/compass-settings/src/components/settings/featureflags.tsx
Labels: release notes, feat

#4126 fix(compass-aggregations): do not reset stage value if it was already changed COMPASS-6584
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.spec.ts
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
Labels: release notes, fix

#4127 feat: place settings under the most idiomatic menu for the platform COMPASS-6430
  packages/compass/src/main/menu.spec.ts
  packages/compass/src/main/menu.ts
Labels: release notes, feat

#4131 chore(import): remove the (manual) file type selector from import (part of COMPASS-6545)
  packages/compass-e2e-tests/fixtures/broken-json.json.gz
  packages/compass-e2e-tests/tests/collection-import.test.ts
  packages/compass-import-export/src/components/import-modal.tsx
  packages/compass-import-export/src/components/import-options.tsx
  packages/compass-import-export/src/import/import-csv.spec.ts
  packages/compass-import-export/src/import/import-json.spec.ts
  packages/compass-import-export/src/modules/import.spec.ts
  packages/compass-import-export/src/modules/import.ts
Labels: no release notes

#4140 fix(data-service): apply readPref to initial `ping` command COMPASS-6595
  packages/data-service/src/connect-mongo-client.spec.ts
  packages/data-service/src/connect-mongo-client.ts
  packages/data-service/src/data-service.ts
  packages/data-service/src/run-command.ts
Labels: release notes, fix

#4152 feat(compass-aggregations): remove focus mode feature flag, always show COMPASS-6474
  packages/compass-aggregations/src/components/stage-toolbar/index.tsx
  packages/compass-aggregations/src/components/stage.tsx
  packages/compass-preferences-model/src/preferences.ts
Labels: release notes, feat

#4157 chore(compass-editor): validation autocompleter with json COMPASS-6572
  packages/compass-editor/src/codemirror/ace-compat-autocompleter.ts
  packages/compass-editor/src/codemirror/document-autocompleter.ts
  packages/compass-editor/src/codemirror/query-autocompleter.ts
  packages/compass-editor/src/codemirror/stage-autocompleter.ts
  packages/compass-editor/src/codemirror/utils.test.ts
  packages/compass-editor/src/codemirror/utils.ts
  packages/compass-editor/src/codemirror/validation-autocompleter.test.ts
  packages/compass-editor/src/codemirror/validation-autocompleter.ts
  packages/compass-editor/src/index.ts
Labels: feat, no release notes

#4172 fix(import): Fix guessFileType() for large JSON docs COMPASS-6629
  packages/compass-import-export/src/import/guess-filetype.spec.ts
  packages/compass-import-export/src/import/guess-filetype.ts
  packages/compass-import-export/src/modules/import.ts
Labels: release notes, fix

#4174 chore(import): Only use a large modal for CSV imports
  packages/compass-import-export/src/components/import-modal.tsx
Labels: no release notes

#4179 fix(compass-connections): background color on selected connection
  packages/compass-connections/src/components/connection-list/connection.tsx
Labels: fix, no release notes

#4178 fix(import): Fix memory leak in listCSVFields() COMPASS-6630
  packages/compass-import-export/src/import/list-csv-fields.ts
Labels: bug, release notes, fix

#4120 feat: add GitHub source code link to help menu and window menu COMPASS-6585
  packages/compass/src/main/menu.spec.ts
  packages/compass/src/main/menu.ts
Labels: release notes, feat

#4186 fix(import): add dark mode colours for the mixed warning
  packages/compass-import-export/src/components/import-preview.tsx
Labels: release notes, fix

#4185 fix(import): abort analyzeCSVFields() when closing the import modal COMPASS-6633
  packages/compass-import-export/src/import/analyze-csv-fields.ts
  packages/compass-import-export/src/modules/import.ts
Labels: release notes, fix

#4182 fix(import): Optimise CSV field type detection
  packages/compass-import-export/scripts/analyze-csv.ts
  packages/compass-import-export/src/import/analyze-csv-fields.spec.ts
  packages/compass-import-export/src/import/analyze-csv-fields.ts
Labels: release notes, fix

#4210 chore(stage-wizard): setup feature flag COMPASS-6652
  packages/compass-preferences-model/src/preferences.ts
  packages/compass-settings/src/components/settings/featureflags.tsx
Labels: no release notes

#4213 fix(compass-components): display width on default file input variant
  packages/compass-components/src/components/file-input.spec.tsx
  packages/compass-components/src/components/file-input.tsx
  packages/compass-connection-import-export/src/components/file-input.tsx
  packages/compass-import-export/src/components/export-select-output/export-select-output.tsx
  packages/compass-import-export/src/components/import-file-input.tsx
Labels: fix, no release notes
