Repository mongodb-js/compass, pull requests merged in 2023-10, with the labels that each got.

#4906 fix(aggregations): disregard env in snippets COMPASS-6976
  packages/compass-aggregations/src/modules/env.js
  packages/compass-aggregations/src/modules/env.ts
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
Labels: release notes, fix

#4927 feat(search-indexes): fields autocomplete COMPASS-7174
  packages/compass-components/src/components/modals/modal.tsx
  packages/compass-editor/src/codemirror/search-index-autocompleter.test.ts
  packages/compass-editor/src/codemirror/search-index-autocompleter.ts
  packages/compass-editor/src/index.ts
  packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.spec.tsx
  packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.tsx
  packages/compass-indexes/src/components/search-indexes-modals/create-search-index-modal.tsx
  packages/compass-indexes/src/components/search-indexes-modals/update-search-index-modal.tsx
  packages/compass-indexes/src/modules/fields.ts
  packages/compass-indexes/src/modules/index.ts
  packages/compass-indexes/src/stores/store.ts
Labels: release notes, feat

#4921 feat(search-indexes): add annotations in the editor when there are syntax errors in the search index definition COMPASS-7246
  packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.tsx
Labels: release notes, feat

#4934 fix(search-indexes): avoid flicker when modal closes COMPASS-7248
  packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.tsx
  packages/compass-indexes/src/modules/search-indexes.ts
Labels: release notes, fix

#4918 feat: improve AI feedback experience COMPASS-7211, COMPASS-7251
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-ai.tsx
  packages/compass-components/src/components/feedback-popover.spec.tsx
  packages/compass-components/src/components/feedback-popover.tsx
  packages/compass-query-bar/src/components/query-ai.tsx
Labels: release notes, feat

#4837 feat: remove useNewUrlParser and useUnifiedTopology from export to language COMPASS-4897
  packages/bson-transpilers/lib/symbol-table/pythontojavascript.js
  packages/bson-transpilers/lib/symbol-table/shelltojavascript.js
  packages/bson-transpilers/symbols/javascript/templates.yaml
  packages/bson-transpilers/test/yaml/driver-syntax.yaml
  packages/compass-export-to-language/src/modules/transpiler.spec.ts
Labels: release notes, feat

#4948 fix(build): bump devtools-github-repo to fix error logs
  package-lock.json
  packages/hadron-build/package.json
Labels: fix, no release notes

#4950 chore: Use knnVector instead of vectorEmbedding in index template definition COMPASS-7288
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-editor/package.json
  packages/compass-indexes/package.json
  packages/compass-query-bar/package.json
Labels: release notes, feat

#4951 fix(electron): downgrade to 25.8.4 COMPASS-7291
  configs/webpack-config-compass/package.json
  package-lock.json
  packages/atlas-service/package.json
  packages/compass-crud/package.json
  packages/compass-e2e-tests/package.json
  packages/compass-explain-plan/package.json
  packages/compass-find-in-page/package.json
  packages/compass-import-export/package.json
  packages/compass-indexes/package.json
  packages/compass-query-bar/package.json
  packages/compass-schema-validation/package.json
  packages/compass-shell/package.json
  packages/compass-utils/package.json
  packages/compass/package.json
  packages/connection-storage/package.json
  packages/hadron-build/package.json
  packages/hadron-ipc/package.json
  scripts/package.json
Labels: release notes, fix

#4962 fix: use the electron version, not the app's version COMPASS-7305
  packages/hadron-build/commands/release.js
  packages/hadron-build/lib/target.js
Labels: release notes, fix

#4963 fix(data-service): ignore errors when fetching collStats in adf; always fetch collInfo COMPASS-7307
  packages/collection-model/lib/model.js
  packages/data-service/src/data-service.ts
  packages/database-model/lib/model.js
  packages/instance-model/lib/model.js
Labels: release notes, fix

#4969 fix(insert-document): handle invalid bson COMPASS-7316
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
Labels: release notes, fix

#4972 feat(search-indexes): add search index signals COMPASS-7176
  packages/compass-aggregations/src/components/focus-mode/focus-mode-modal-header.spec.tsx
  packages/compass-aggregations/src/components/focus-mode/focus-mode-modal-header.tsx
  packages/compass-aggregations/src/components/focus-mode/focus-mode.spec.tsx
  packages/compass-aggregations/src/components/stage-toolbar/index.spec.tsx
  packages/compass-aggregations/src/components/stage-toolbar/index.tsx
  packages/compass-aggregations/src/modules/index.ts
  packages/compass-aggregations/src/modules/search-indexes.ts
  packages/compass-aggregations/src/stores/store.spec.ts
  packages/compass-aggregations/src/stores/store.ts
  packages/compass-aggregations/src/utils/insights.ts
  packages/compass-collection/src/stores/collection-tab.ts
  packages/compass-components/src/components/signals.tsx
  packages/compass-crud/src/components/crud-toolbar.tsx
  packages/compass-crud/src/components/document-list.tsx
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-crud/src/utils/toolbar-signal.ts
  packages/compass-indexes/src/stores/store.ts
Labels: release notes, feat

#4981 fix(data-service): relax getSearchIndexes error message test
  packages/data-service/src/data-service.spec.ts
Labels: fix, no release notes

#4982 fix(search-indexes): ui fixes COMPASS-7304
  package-lock.json
  packages/compass-components/package.json
  packages/compass-components/src/components/leafygreen.tsx
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
  packages/compass-indexes/src/components/search-index-template-dropdown/index.tsx
  packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.tsx
  packages/compass-indexes/src/modules/search-indexes.ts
Labels: release notes, fix

#4989 fix(search-indexes): smaller column widths COMPASS-7341
  package-lock.json
  packages/compass-indexes/src/components/indexes-table/indexes-table.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.tsx
Labels: release notes, fix

#4994 fix: snyk-js-babeltraverse-5962462 COMPASS-7345
  package-lock.json
  packages/compass-shell/package.json
  packages/compass/package.json
Labels: release notes, fix

#4993 feat(bulk-update): add data-service method to retrieve before/after documents for update preview
  packages/data-service/src/data-service.spec.ts
  packages/data-service/src/data-service.ts
Labels: feat, no release notes

#4998 chore: add feature flags for bulk operations COMPASS-7324
  packages/compass-preferences-model/src/feature-flags.ts
Labels: feat, no release notes

#4999 fix(data-service): address review comments for previewUpdate
  packages/data-service/src/data-service.ts
Labels: fix, no release notes

#5003 feat: add delete button next to querybar COMPASS-7324
  packages/compass-components/src/components/guide-cue/guide-cue-service.ts
  packages/compass-crud/src/components/crud-toolbar.spec.tsx
  packages/compass-crud/src/components/crud-toolbar.tsx
  packages/compass-crud/src/components/delete-data-menu.tsx
  packages/compass-crud/src/components/document-list.tsx
Labels: feat, no release notes

#5001 feat(stage-wizard): implement text search wizard
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/index.ts
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/search/text-search.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/search/text-search.tsx
  packages/compass-aggregations/src/components/stage-wizard/index.tsx
  packages/compass-aggregations/src/modules/search-indexes.spec.ts
  packages/compass-aggregations/src/modules/search-indexes.ts
  packages/compass-aggregations/src/stores/store.ts
Labels: release notes, feat

#5005 feat: delete bulk operation modal COMPASS-7326
  package-lock.json
  packages/compass-crud/package.json
  packages/compass-crud/src/components/bulk-delete-modal.spec.tsx
  packages/compass-crud/src/components/bulk-delete-modal.tsx
  packages/compass-crud/src/components/document-list.tsx
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
Labels: feature flagged, feat, no release notes

#5011 feat: add feedback toasts for delete bulk ops COMPASS-7328
  packages/compass-crud/src/stores/crud-store.ts
Labels: feature flagged, feat, no release notes

#5009 fix(generative-ai): add type button html attribute so ai entry buttons don't get html form submit events COMPASS-7356
  packages/compass-generative-ai/src/components/ai-experience-entry.tsx
Labels: release notes, fix

#4977 feat: remove NONE and authMechanism=DEFAULT COMPASS-7308
  packages/compass-e2e-tests/helpers/connect-form-state.ts
  packages/compass-e2e-tests/tests/connection-form.test.ts
  packages/compass-e2e-tests/tests/protect-connection-strings.test.ts
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-default.tsx
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-tab.spec.tsx
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-tab.tsx
Labels: release notes, feat

#5002 feat: Improve stage wizard discoverability and interaction COMPASS-7350
  package-lock.json
  packages/compass-aggregations/src/components/aggregation-side-panel/index.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/index.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/index.ts
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/use-case-card.tsx
  packages/compass-aggregations/src/components/pipeline-builder-workspace/pipeline-builder-ui-workspace/dnd-wrapper.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/index.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/index.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-settings/pipeline-extra-settings.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-toolbar-container.tsx
  packages/compass-aggregations/src/components/stage-wizard/index.tsx
  packages/compass-aggregations/src/modules/side-panel.spec.ts
  packages/compass-aggregations/src/modules/side-panel.ts
  packages/compass-aggregations/src/stores/store.spec.ts
  packages/compass-components/.depcheckrc
  packages/compass-components/package.json
  packages/compass-components/src/components/keyline-card.tsx
  packages/compass-components/src/components/workspace-container.tsx
Labels: release notes, feat

#5037 fix(stage-wizard): ux fixes for $search wizard
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/search/text-search.spec.tsx
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/search/text-search.tsx
  packages/compass-aggregations/src/components/stage-wizard/index.tsx
  packages/compass-aggregations/test/form-helper.ts
Labels: release notes, fix
