Repository mongodb-js/compass, pull requests merged in 2024-08, with the labels that each got.

#6080 feat(query-bar): release query history autocompletion COMPASS-8096
  packages/compass-preferences-model/src/feature-flags.ts
  packages/compass-query-bar/src/components/option-editor.spec.tsx
Labels: release notes, feat

#6063 fix(e2e) Port OIDC tests to multiple connections COMPASS-8105
  package-lock.json
  packages/compass-connections/src/components/connection-status-toasts.tsx
  packages/compass-e2e-tests/helpers/commands/hide-index.ts
  packages/compass-e2e-tests/helpers/commands/save-connection-string-as-favorite.ts
  packages/compass-e2e-tests/helpers/commands/unhide-index.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/package.json
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
  packages/compass-e2e-tests/tests/collection-bulk-delete.test.ts
  packages/compass-e2e-tests/tests/collection-indexes-tab.test.ts
  packages/compass-e2e-tests/tests/connection-form.test.ts
  packages/compass-e2e-tests/tests/import-export-connections.test.ts
  packages/compass-e2e-tests/tests/my-queries-tab.test.ts
  packages/compass-e2e-tests/tests/oidc.test.ts
  packages/compass-e2e-tests/tests/protect-connection-strings.test.ts
  packages/compass-e2e-tests/tests/search-indexes.test.ts
Labels: feature flagged, fix, no release notes

#6082 fix(sidebar): tweak some sidebar sizes after design review COMPASS-8111
  packages/compass-components/src/components/resizeable-sidebar.tsx
  packages/compass-connections-navigation/src/base-navigation-item.tsx
  packages/compass-connections-navigation/src/tree-item.tsx
Labels: fix, no release notes

#6086 feat(connections): show device auth code in the confirmation modal for multiple connectinos connect flow COMPASS-8140
  package-lock.json
  packages/compass-components/package.json
  packages/compass-components/src/hooks/use-confirmation.tsx
  packages/compass-connections/src/components/connection-status-notifications.tsx
  packages/compass-connections/src/components/legacy-connections.tsx
  packages/compass-connections/src/stores/connections-store.spec.tsx
  packages/compass-connections/src/stores/connections-store.tsx
  packages/compass-e2e-tests/helpers/selectors.ts
Labels: feature flagged, feat

#6083 fix(sidebar): Make the hover/active background effect take up the full element. ie. flush with the sides
  packages/compass-connections-navigation/src/base-navigation-item.tsx
  packages/compass-connections-navigation/src/utils.ts
Labels: fix, no release notes

#6069 feat(compass-crud): adds ability to load more documents per page in Documents view COMPASS-6903
  package-lock.json
  packages/compass-components/package.json
  packages/compass-components/src/components/virtual-list.spec.tsx
  packages/compass-components/src/components/virtual-list.tsx
  packages/compass-components/src/hooks/use-virtual-list-item-observer.ts
  packages/compass-components/src/index.ts
  packages/compass-connections-navigation/src/connections-navigation-tree.tsx
  packages/compass-crud/package.json
  packages/compass-crud/src/actions/index.ts
  packages/compass-crud/src/components/crud-toolbar.spec.tsx
  packages/compass-crud/src/components/crud-toolbar.tsx
  packages/compass-crud/src/components/document-json-view.tsx
  packages/compass-crud/src/components/document-list.tsx
  packages/compass-crud/src/components/editable-document.tsx
  packages/compass-crud/src/components/json-editor.tsx
  packages/compass-crud/src/components/virtualized-document-json-view.spec.tsx
  packages/compass-crud/src/components/virtualized-document-json-view.tsx
  packages/compass-crud/src/components/virtualized-document-list-view.spec.tsx
  packages/compass-crud/src/components/virtualized-document-list-view.tsx
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
  packages/compass-e2e-tests/tests/collection-import.test.ts
  packages/hadron-document/src/document.ts
Labels: release notes, feat

#6094 fix: do not replace tabs of different connections COMPASS-8113
  packages/compass-workspaces/src/stores/workspaces.spec.ts
  packages/compass-workspaces/src/stores/workspaces.ts
Labels: feature flagged, fix

#6101 fix(telemetry): better hostname parsing for telemetry COMPASS-8148
  packages/compass/src/app/utils/telemetry.spec.ts
  packages/compass/src/app/utils/telemetry.ts
Labels: fix, no release notes

#6085 fix: new tab design COMPASS-8122
  package-lock.json
  packages/compass-components/package.json
  packages/compass-components/src/components/icons/logo-icon.tsx
  packages/compass-components/src/components/icons/server-icon.tsx
  packages/compass-components/src/components/workspace-tabs/tab.spec.tsx
  packages/compass-components/src/components/workspace-tabs/tab.tsx
  packages/compass-components/src/components/workspace-tabs/workspace-tabs.spec.tsx
  packages/compass-components/src/components/workspace-tabs/workspace-tabs.tsx
  packages/compass-connections/src/hooks/use-tab-connection-theme.spec.ts
  packages/compass-connections/src/hooks/use-tab-connection-theme.ts
  packages/compass-e2e-tests/helpers/commands/collection-workspaces.ts
  packages/compass-e2e-tests/helpers/commands/connection-workspaces.ts
  packages/compass-e2e-tests/helpers/commands/database-workspaces.ts
  packages/compass-e2e-tests/helpers/commands/wait-for-connection-result.ts
  packages/compass-e2e-tests/helpers/commands/workspace-tabs.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/tabs.test.ts
  packages/compass-workspaces/package.json
  packages/compass-workspaces/src/components/workspaces.tsx
  packages/compass-workspaces/src/index.spec.tsx
Labels: release notes, fix

#6106 fix: add shell open events with entrypoints COMPASS-8136
  packages/compass-collection/src/components/collection-header-actions/collection-header-actions.tsx
  packages/compass-sidebar/src/components/multiple-connections/connections-navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
  packages/databases-collections-list/src/items-grid.tsx
Labels: fix, no release notes

#6108 fix(build): throw error when build fails
  packages/hadron-build/lib/run.js
Labels: fix, no release notes

#6110 fix(connect-form): rotate the colour wheel so that red lines up with red COMPASS-8146
  packages/compass-connections/src/hooks/use-tab-connection-theme.spec.ts
  packages/compass-e2e-tests/helpers/commands/connect-form.ts
  packages/compass-e2e-tests/helpers/commands/save-connection-string-as-favorite.ts
  packages/compass-e2e-tests/tests/connection-form.test.ts
  packages/connection-form/src/hooks/use-connection-color.ts
Labels: fix, no release notes

#6099 feat(preferences): add app settings for new proxy options COMPASS-8141
  configs/mocha-config-compass/main-process.js
  package-lock.json
  packages/compass-e2e-tests/helpers/compass.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/atlas-login.test.ts
  packages/compass-e2e-tests/tests/auto-connect.test.ts
  packages/compass-e2e-tests/tests/global-preferences.test.ts
  packages/compass-preferences-model/package.json
  packages/compass-preferences-model/src/compass-utils.ts
  packages/compass-preferences-model/src/feature-flags.ts
  packages/compass-preferences-model/src/index.ts
  packages/compass-preferences-model/src/preferences-persistent-storage.spec.ts
  packages/compass-preferences-model/src/preferences-persistent-storage.ts
  packages/compass-preferences-model/src/preferences-schema.ts
  packages/compass-preferences-model/src/preferences.ts
  packages/compass-preferences-model/src/provider.ts
  packages/compass-preferences-model/src/react.ts
  packages/compass-preferences-model/src/setup-preferences.ts
  packages/compass-preferences-model/src/utils.ts
  packages/compass-preferences-model/tsconfig.json
  packages/compass-settings/src/components/modal.spec.tsx
  packages/compass-settings/src/components/modal.tsx
  packages/compass-settings/src/components/settings/proxy-settings-custom.spec.tsx
  packages/compass-settings/src/components/settings/proxy-settings-custom.tsx
  packages/compass-settings/src/components/settings/proxy-settings.spec.tsx
  packages/compass-settings/src/components/settings/proxy-settings.tsx
  packages/compass-settings/src/components/sidebar.spec.tsx
  packages/compass-settings/src/components/sidebar.tsx
  packages/compass-settings/src/index.ts
  packages/compass-settings/src/stores/index.ts
  packages/compass-settings/src/stores/settings.ts
  packages/compass/src/app/components/home.tsx
  packages/compass/src/app/index.tsx
  packages/compass/src/main/application.ts
  packages/mongodb-explain-compat/package.json
Labels: feature flagged, feat

#6116 fix: rename Connect app menu item COMPASS-8161
  packages/compass/src/main/menu.spec.ts
  packages/compass/src/main/menu.ts
Labels: fix, no release notes

#6120 feat(compass): apply proxy settings to electron app and session COMPASS-8143
  package-lock.json
  packages/compass-e2e-tests/tests/proxy.test.ts
  packages/compass-preferences-model/package.json
  packages/compass/package.json
  packages/compass/src/app/utils/csp.ts
  packages/compass/src/main/application.ts
  packages/compass/src/main/window-manager.ts
Labels: feature flagged, feat

#6127 fix(compass): account for server RHEL distro rename
  packages/compass/scripts/download-csfle.js
Labels: fix, no release notes

#6128 fix(compass-connections): text-overflow: ellipsis on very long connection names in connection errors COMPASS-8112
  packages/compass-connections/src/components/connection-status-notifications.tsx
Labels: fix, no release notes

#6090 feat: remove useSystemCA by making it default COMPASS-8077
  package-lock.json
  package.json
  packages/atlas-service/package.json
  packages/compass-e2e-tests/helpers/commands/connect-form.ts
  packages/compass-e2e-tests/helpers/connect-form-state.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/connection-form.test.ts
  packages/compass-e2e-tests/tests/connection.test.ts
  packages/compass-shell/package.json
  packages/compass-web/polyfills/@mongodb-js/devtools-connect/index.ts
  packages/compass/package.json
  packages/connection-form/src/components/advanced-options-tabs/csfle-tab/kms-tls-options.tsx
  packages/connection-form/src/components/advanced-options-tabs/tls-ssl-tab/tls-certificate-authority.tsx
  packages/connection-form/src/components/advanced-options-tabs/tls-ssl-tab/tls-ssl-tab.spec.tsx
  packages/connection-form/src/components/advanced-options-tabs/tls-ssl-tab/tls-ssl-tab.tsx
  packages/connection-form/src/utils/oidc-handler.spec.ts
  packages/connection-form/src/utils/tls-handler.spec.ts
  packages/connection-form/src/utils/tls-handler.ts
  packages/connection-storage/src/compass-main-connection-storage.ts
  packages/data-service/package.json
  packages/data-service/src/connect-mongo-client.spec.ts
  packages/data-service/src/connect-mongo-client.ts
  packages/data-service/src/connection-options.ts
Labels: release notes, feat

#6124 fix(compass,atlas-service): apply proxy to main thread HTTP calls COMPASS-8165
  package-lock.json
  packages/atlas-service/package.json
  packages/atlas-service/src/main.spec.ts
  packages/atlas-service/src/main.ts
  packages/compass-utils/src/cancellable-promise.ts
  packages/compass/package.json
  packages/compass/src/main/application.ts
  packages/compass/src/main/auto-update-manager.ts
Labels: feature flagged, fix

#6131 fix(compass-components): keep the colour tabs' background COMPASS-8168
  packages/compass-components/src/components/workspace-tabs/tab.tsx
  packages/compass-connections/src/hooks/use-tab-connection-theme.spec.ts
  packages/compass-connections/src/hooks/use-tab-connection-theme.ts
Labels: fix, no release notes

#6129 feat(connection-form): add option to prefer ID token over access token COMPASS-8107
  package-lock.json
  packages/atlas-service/package.json
  packages/atlas-service/src/main.spec.ts
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.spec.tsx
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.tsx
  packages/data-service/package.json
Labels: release notes, feat

#6142 chore: upgrade electron to 30.4.0
  configs/webpack-config-compass/package.json
  package-lock.json
  packages/atlas-service/package.json
  packages/compass-crud/package.json
  packages/compass-e2e-tests/package.json
  packages/compass-explain-plan/package.json
  packages/compass-find-in-page/package.json
  packages/compass-import-export/package.json
  packages/compass-indexes/package.json
  packages/compass-query-bar/package.json
  packages/compass-schema-validation/package.json
  packages/compass-shell/package.json
  packages/compass-utils/package.json
  packages/compass-web/package.json
  packages/compass/package.json
  packages/connection-storage/package.json
  packages/hadron-build/package.json
  packages/hadron-ipc/package.json
  scripts/package.json
Labels: release notes

#6138 feat: release multiple connections COMPASS-7905
  .evergreen/buildvariants-and-tasks.in.yml
  .evergreen/buildvariants-and-tasks.yml
  .evergreen/functions.yml
  packages/compass-connections-navigation/src/sc-connections-navigation-tree.spec.tsx
  packages/compass-connections/src/components/legacy-connections.spec.tsx
  packages/compass-e2e-tests/helpers/compass.ts
  packages/compass-e2e-tests/index.ts
  packages/compass-preferences-model/src/feature-flags.ts
  packages/compass-preferences-model/src/preferences-schema.ts
  packages/compass-shell/src/plugin.spec.tsx
  packages/compass-sidebar/src/components/legacy/navigation-items.spec.tsx
  packages/compass/src/main/menu.spec.ts
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.spec.tsx
  packages/connection-form/src/components/advanced-options-tabs/csfle-tab/csfle-tab.spec.tsx
  packages/connection-form/src/components/connection-form.spec.tsx
  packages/connection-form/src/hooks/use-connection-color.spec.tsx
Labels: release notes, feat

#6152 fix(e2e): three lines for three errors, not four
  packages/compass-e2e-tests/tests/collection-import.test.ts
Labels: fix, no release notes

#6153 fix(e2e): deal with the fact that the modal might already be closed
  packages/compass-e2e-tests/helpers/commands/disconnect.ts
  packages/compass-e2e-tests/helpers/commands/hide-visible-modal.ts
  packages/compass-e2e-tests/helpers/commands/index.ts
  packages/compass-e2e-tests/helpers/commands/remove-connections.ts
Labels: fix, no release notes

#6156 fix(e2e-tests): re-enable OIDC tests on 8.0.x COMPASS-7966
  packages/compass-e2e-tests/tests/oidc.test.ts
Labels: fix, no release notes

#6133 feat: add per-connection proxy settings COMPASS-8142
  README.md
  configs/webpack-config-compass/src/index.ts
  package-lock.json
  packages/atlas-service/package.json
  packages/compass-connections/src/components/legacy-connections.tsx
  packages/compass-connections/src/hooks/use-connection-form-preferences.tsx
  packages/compass-e2e-tests/.depcheckrc
  packages/compass-e2e-tests/helpers/commands/connect-form.ts
  packages/compass-e2e-tests/helpers/connect-form-state.ts
  packages/compass-e2e-tests/helpers/proxy.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/oidc.test.ts
  packages/compass-e2e-tests/tests/proxy.test.ts
  packages/compass-preferences-model/package.json
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
  packages/compass-web/.depcheckrc
  packages/compass-web/polyfills/@mongodb-js/devtools-proxy-support/index.ts
  packages/compass-web/webpack.config.js
  packages/compass/licenses.json
  packages/compass/package.json
  packages/compass/src/main/application.ts
  packages/connection-form/src/components/advanced-connection-options.tsx
  packages/connection-form/src/components/advanced-options-tabs/advanced-options-tabs.tsx
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.tsx
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-tab.tsx
  packages/connection-form/src/components/advanced-options-tabs/ssh-tunnel-tab/app-proxy.tsx
  packages/connection-form/src/components/advanced-options-tabs/ssh-tunnel-tab/proxy-and-ssh-tunnel-tab.spec.tsx
  packages/connection-form/src/components/advanced-options-tabs/ssh-tunnel-tab/proxy-and-ssh-tunnel-tab.tsx
  packages/connection-form/src/components/connection-form.tsx
  packages/connection-form/src/hooks/use-connect-form-preferences.tsx
  packages/connection-form/src/hooks/use-connect-form.ts
  packages/connection-form/src/utils/connection-ssh-handler.ts
  packages/data-service/package.json
  packages/data-service/src/connect-mongo-client.spec.ts
  packages/data-service/src/connect-mongo-client.ts
  packages/data-service/src/connection-options.ts
  packages/data-service/src/data-service.ts
  packages/data-service/src/redact.spec.ts
  packages/data-service/src/redact.ts
  packages/data-service/src/ssh-tunnel-helpers.ts
  packages/data-service/src/ssh-tunnel.ts
  packages/ssh-tunnel/.depcheckrc
  packages/ssh-tunnel/.eslintignore
  packages/ssh-tunnel/.eslintrc.js
  packages/ssh-tunnel/.mocharc.js
  packages/ssh-tunnel/.prettierignore
  packages/ssh-tunnel/.prettierrc.json
  packages/ssh-tunnel/package.json
  packages/ssh-tunnel/src/index.spec.ts
  packages/ssh-tunnel/src/index.ts
  packages/ssh-tunnel/src/socksv5.d.ts
  packages/ssh-tunnel/test/fixtures/rsa
  packages/ssh-tunnel/test/fixtures/rsa.pub
  packages/ssh-tunnel/tsconfig-lint.json
  packages/ssh-tunnel/tsconfig.json
Labels: release notes, feat

#6158 fix(connection-storage): store `useApplicationLevelProxy` flag to disk COMPASS-8219
  packages/connection-storage/src/compass-main-connection-storage.spec.ts
  packages/connection-storage/src/compass-main-connection-storage.ts
Labels: feature flagged, fix

#6160 fix(compass-e2e-tests): skip failing search index test COMPASS-8220
  packages/compass-e2e-tests/tests/search-indexes.test.ts
Labels: fix, no release notes

#6157 feat: release feature flag for proxy support COMPASS-8167
  packages/compass-connections/src/hooks/use-connection-form-preferences.tsx
  packages/compass-e2e-tests/tests/oidc.test.ts
  packages/compass-e2e-tests/tests/proxy.test.ts
  packages/compass-preferences-model/src/feature-flags.ts
  packages/compass-settings/src/components/modal.tsx
Labels: release notes, feat

#6161 fix(compass-crud): in the bulk update preview, convert array indexes from strings to numbers COMPASS-8218
  packages/compass-crud/src/components/change-view/unified-document.ts
  packages/compass-crud/test/before-after-fixtures.ts
  packages/compass-crud/test/fixture-results/all_types_all_types_changed.json
  packages/compass-crud/test/fixture-results/array_changes_add_array_to_array.json
  packages/compass-crud/test/fixture-results/array_changes_add_object_to_array.json
  packages/compass-crud/test/fixture-results/array_changes_add_simple_value_to_array.json
  packages/compass-crud/test/fixture-results/array_changes_remove_simple_value_from_array.json
  packages/compass-crud/test/fixture-results/array_changes_simple_array.json
  packages/compass-crud/test/fixture-results/nested_object_changes_nested_object_array_array_simple.json
  packages/compass-crud/test/fixture-results/nested_object_changes_nested_object_array_simple.json
  packages/compass-crud/test/fixture-results/objects_in_arrays_add_number_next_to_object_in_array.json
  packages/compass-crud/test/fixture-results/objects_in_arrays_many_items.json
  packages/compass-crud/test/fixture-results/objects_in_arrays_object_inside_array_changed.json
  packages/compass-crud/test/fixture-results/objects_in_arrays_object_value_nested_in_an_array.json
  packages/compass-crud/test/fixture-results/objects_in_arrays_remove_number_next_to_object_in_array.json
Labels: release notes, fix

#6169 fix(deps): bump shell-bson-parser to 1.1.2 MONGOSH-1859
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-crud/package.json
  packages/compass-editor/package.json
  packages/compass-export-to-language/package.json
  packages/compass-import-export/package.json
  packages/compass-indexes/package.json
  packages/compass-query-bar/package.json
  packages/compass-schema-validation/package.json
  packages/connection-form/package.json
  packages/databases-collections/package.json
  packages/explain-plan-helper/package.json
Labels: release notes, fix
