Repository mongodb-js/compass, pull requests merged in 2024-02, with the labels that each got.

#5414 feat(compass-indexes): add vector search index creation to create search indexes modal COMPASS-7302
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-editor/package.json
  packages/compass-indexes/package.json
  packages/compass-indexes/src/components/search-index-template-dropdown/index.spec.tsx
  packages/compass-indexes/src/components/search-index-template-dropdown/index.tsx
  packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.spec.tsx
  packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.tsx
  packages/compass-indexes/src/components/search-indexes-modals/create-search-index-modal.tsx
  packages/compass-indexes/src/components/search-indexes-modals/update-search-index-modal.tsx
  packages/compass-indexes/src/modules/search-indexes.spec.ts
  packages/compass-indexes/src/modules/search-indexes.ts
  packages/compass-indexes/src/utils/vector-search-indexes.spec.ts
  packages/compass-indexes/src/utils/vector-search-indexes.ts
  packages/compass-indexes/test/setup-store.ts
  packages/compass-query-bar/package.json
  packages/data-service/src/data-service.spec.ts
  packages/data-service/src/data-service.ts
  packages/data-service/src/search-index-detail-helper.ts
Labels: release notes, feat

#5413 feat(compass-indexes): display vector search type in search indexes table COMPASS-7509
  packages/compass-indexes/src/components/indexes-table/badge-with-icon-link.spec.tsx
  packages/compass-indexes/src/components/indexes-table/badge-with-icon-link.tsx
  packages/compass-indexes/src/components/regular-indexes-table/property-field.tsx
  packages/compass-indexes/src/components/regular-indexes-table/type-field.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.spec.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.tsx
  packages/compass-indexes/src/modules/search-indexes.spec.ts
  packages/compass-indexes/src/modules/search-indexes.ts
  packages/compass-indexes/test/fixtures/search-indexes.ts
Labels: release notes, feat

#5363 fix(compass): improve validation of command line arguments COMPASS-7260
  .evergreen/functions.yml
  package-lock.json
  packages/compass-e2e-tests/helpers/compass.ts
  packages/compass-preferences-model/src/preferences-schema.ts
  packages/compass/package.json
  packages/compass/src/app/auto-connect.ts
  packages/compass/src/main/application.ts
  packages/compass/src/main/auto-connect.spec.ts
  packages/compass/src/main/auto-connect.ts
  packages/compass/src/main/validate-connection-string.ts
Labels: release notes, fix

#5403 fix(crud): hide update/delete labels on narrow windows
  packages/compass-crud/src/components/delete-data-menu.tsx
  packages/compass-crud/src/components/update-data-menu.tsx
Labels: release notes, fix

#5429 fix(compass-web): do not bundle react with the package; make sure webpack doesn't namespace the library output
  packages/compass-web/webpack.config.js
Labels: fix, no release notes

#5431 fix(ci): setup ssh key safely COMPASS-7621
  .evergreen/functions.yml
  .evergreen/setup-ssh-key.sh
Labels: fix, no release notes

#5430 fix(compass): remove userId from telemetry calls MONGOSH-7609
  packages/compass/src/main/telemetry.ts
Labels: fix, no release notes

#5409 fix(databases-collections): address design feedback on the rename collection flow COMPASS-7504
  packages/compass-e2e-tests/tests/collection-rename.test.ts
  packages/databases-collections/src/components/rename-collection-modal/rename-collection-modal.spec.tsx
  packages/databases-collections/src/components/rename-collection-modal/rename-collection-modal.tsx
  packages/databases-collections/src/index.ts
  packages/databases-collections/src/modules/rename-collection/rename-collection.spec.ts
  packages/databases-collections/src/modules/rename-collection/rename-collection.ts
  packages/databases-collections/src/stores/rename-collection.spec.tsx
  packages/databases-collections/src/stores/rename-collection.ts
Labels: feature flagged, fix

#5466 chore(connection-storage): kick this can down the road
  packages/connection-storage/src/connection-storage.spec.ts
Labels: no release notes

#5446 chore: extract an interface named ConnectionProvider and adapt the current connection loader to use it.
  package-lock.json
  packages/compass-connections/src/components/connection-list/connection-list.spec.tsx
  packages/compass-connections/src/components/connection-list/connection.tsx
  packages/compass-connections/src/components/connections.spec.tsx
  packages/compass-connections/src/components/connections.tsx
  packages/compass-connections/src/stores/connections-store.spec.ts
  packages/compass-connections/src/stores/connections-store.ts
  packages/compass-e2e-tests/tests/connection-form.test.ts
  packages/compass-home/package.json
  packages/compass-home/src/components/home.tsx
  packages/compass/src/app/auto-connect.spec.ts
  packages/connection-form/src/components/connection-form.tsx
  packages/connection-form/src/hooks/use-connect-form.ts
  packages/connection-info/src/connection-info.ts
  packages/connection-info/src/index.ts
  packages/connection-storage/package.json
  packages/connection-storage/provider.d.ts
  packages/connection-storage/provider.js
  packages/connection-storage/renderer.d.ts
  packages/connection-storage/src/connection-repository.spec.ts
  packages/connection-storage/src/connection-repository.ts
  packages/connection-storage/src/connection-storage.spec.ts
  packages/connection-storage/src/connection-storage.ts
  packages/connection-storage/src/main.ts
  packages/connection-storage/src/provider.ts
Labels: feature flagged, no release notes

#5471 fix(query-bar, schema): double space not applied from schema or query history COMPASS-6980
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/match/match.spec.tsx
  packages/compass-crud/package.json
  packages/compass-crud/src/components/bulk-delete-modal.spec.tsx
  packages/compass-crud/src/components/bulk-update-modal.spec.tsx
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
  packages/compass-import-export/package.json
  packages/compass-indexes/package.json
  packages/compass-query-bar/package.json
  packages/compass-query-bar/src/stores/query-bar-reducer.spec.ts
  packages/compass-query-bar/src/utils/format-query.spec.js
  packages/compass-query-bar/src/utils/query.ts
  packages/compass-schema-validation/package.json
  packages/compass-schema/src/components/value-bubble.tsx
  packages/connection-form/package.json
  packages/databases-collections/package.json
Labels: release notes, fix

#5441 fix: send atlas uid as userId to compass telemetry COMPASS-7610
  packages/atlas-service/src/main.spec.ts
  packages/atlas-service/src/main.ts
  packages/atlas-service/src/util.spec.ts
  packages/atlas-service/src/util.ts
  packages/compass-e2e-tests/tests/atlas-login.test.ts
  packages/compass-e2e-tests/tests/logging.test.ts
  packages/compass-preferences-model/src/preferences-schema.ts
  packages/compass/src/main/telemetry.ts
Labels: fix, no release notes

#5489 fix(compass-indexes): reset atlas search index on reopen and type change
  packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.spec.tsx
  packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.tsx
Labels: release notes, fix

#5455 feat(autoupdates): install updates without confirmation in the background by default COMPASS-7616
  package-lock.json
  packages/compass-components/src/hooks/use-toast.tsx
  packages/compass-home/src/components/home.tsx
  packages/compass-preferences-model/src/preferences-schema.ts
  packages/compass/package.json
  packages/compass/src/app/index.tsx
  packages/compass/src/main/auto-update-manager.spec.ts
  packages/compass/src/main/auto-update-manager.ts
Labels: release notes, feat

#5497 fix: don't include the version number in process.title because it shows in the menubar in macOS Sonoma COMPASS-7513
  packages/compass/src/main/index.ts
Labels: release notes, fix

#5458 chore(databases-collections): add UI for new rename collection warning COMPASS-7664
  package-lock.json
  packages/compass-e2e-tests/tests/collection-rename.test.ts
  packages/databases-collections/package.json
  packages/databases-collections/src/components/rename-collection-modal/rename-collection-modal.spec.tsx
  packages/databases-collections/src/components/rename-collection-modal/rename-collection-modal.tsx
  packages/databases-collections/src/index.ts
  packages/databases-collections/src/modules/rename-collection/rename-collection.spec.ts
  packages/databases-collections/src/modules/rename-collection/rename-collection.ts
  packages/databases-collections/src/stores/rename-collection.spec.tsx
  packages/databases-collections/src/stores/rename-collection.ts
Labels: feature flagged

#5500 fix(export): show the folder via the main process COMPASS-7671
  packages/compass-import-export/package.json
  packages/compass-import-export/src/utils/reveal-file.ts
  packages/compass/src/main/window-manager.ts
Labels: release notes, fix

#5462 feat(compass-saved-aggregations-queries): update namespace for saved aggregations/queries (COMPASS-7665)
  packages/compass-e2e-tests/tests/instance-my-queries-tab.test.ts
  packages/compass-saved-aggregations-queries/src/components/open-item-modal.tsx
  packages/compass-saved-aggregations-queries/src/stores/open-item.ts
Labels: release notes, feat

#5503 chore: add feature flag for multiple connections
  packages/compass-preferences-model/src/feature-flags.ts
Labels: feature flagged, feat, no release notes
