Repository mongodb-js/compass, pull requests merged in 2024-01, with the labels that each got.

#5287 fix(compass-crud): persist and restore documents list scroll top position COMPASS-7370
  configs/mocha-config-compass/index.js
  configs/mocha-config-compass/react.js
  configs/mocha-config-compass/register/node-env-register.js
  package-lock.json
  packages/compass-components/src/components/workspace-container.tsx
  packages/compass-crud/package.json
  packages/compass-crud/src/components/bulk-delete-modal.tsx
  packages/compass-crud/src/components/document-list.tsx
  packages/compass-crud/src/components/insert-document-dialog.tsx
  packages/compass-workspaces/package.json
  packages/compass-workspaces/src/components/workspace-tab-state-provider.spec.tsx
  packages/compass-workspaces/src/components/workspace-tab-state-provider.tsx
  packages/compass-workspaces/src/components/workspaces-provider.tsx
  packages/compass-workspaces/src/components/workspaces.tsx
  packages/compass-workspaces/src/provider.tsx
  packages/compass-workspaces/src/stores/workspaces.ts
Labels: release notes, fix

#5309 fix(export,query-bar): bump mongodb-query-parser COMPASS-7515
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-crud/package.json
  packages/compass-import-export/package.json
  packages/compass-indexes/package.json
  packages/compass-query-bar/package.json
  packages/compass-schema-validation/package.json
  packages/connection-form/package.json
  packages/databases-collections/package.json
Labels: release notes, fix

#5326 feat(connection-form): add show favorite actions preference, make save prop required VSCODE-406
  packages/connection-form/src/components/connection-form-actions.spec.tsx
  packages/connection-form/src/components/connection-form-actions.tsx
  packages/connection-form/src/components/connection-form.spec.tsx
  packages/connection-form/src/components/connection-form.tsx
  packages/connection-form/src/hooks/use-connect-form-preferences.tsx
Labels: feat, no release notes

#5344 fix(compass-components): prevent document keys from getting ellipsized on safari COMPASS-7377
  packages/compass-components/src/components/document-list/element-editors.tsx
Labels: fix, no release notes

#5334 chore(garasign): sign linux artifacts
  .evergreen/functions.yml
  package-lock.json
  packages/hadron-build/lib/target.js
  packages/hadron-build/package.json
Labels: release notes

#5351 fix(crud): make sure that the initial state of the store is set right away instead of through setState calls
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-crud/src/stores/index.ts
Labels: release notes, fix

#5356 fix(compass-preference-model): account for all the preferences for the implementation of ReadOnlyPreferenceService
  packages/compass-preferences-model/src/index.ts
  packages/compass-preferences-model/src/preferences-schema.ts
  packages/compass-preferences-model/src/preferences.spec.ts
  packages/compass-preferences-model/src/preferences.ts
  packages/compass-preferences-model/src/provider.ts
  packages/compass-preferences-model/src/setup-preferences.ts
  packages/compass-preferences-model/src/storage.spec.ts
  packages/compass-preferences-model/src/storage.ts
  packages/compass-sidebar/src/modules/databases.spec.ts
  packages/compass-web/src/index.tsx
Labels: fix, no release notes
