Repository mongodb-js/compass, pull requests merged in 2024-09, with the labels that each got.

#6178 feat: add connectionInfo.atlasMetadata.instanceSize COMPASS-8236
  packages/compass-web/src/connection-storage.spec.ts
  packages/compass-web/src/connection-storage.tsx
  packages/connection-info/src/connection-info.ts
Labels: feat, no release notes

#6184 fix: update webpack SNYK-JS-WEBPACK-7840298 (COMPASS-8238)
  configs/webpack-config-compass/package.json
  configs/webpack-config-compass/src/webpack-plugin-start-electron.ts
  package-lock.json
Labels: release notes, fix

#6185 feat(compass-connections): useConnectionSupports(connectionId, connectionFeature) hook COMPASS-8213
  packages/compass-connections/src/hooks/use-connection-supports.spec.ts
  packages/compass-connections/src/hooks/use-connection-supports.ts
  packages/compass-connections/src/stores/store-context.tsx
Labels: feat, no release notes

#6180 chore(deps): bump mongodb-client-encryption and crypt_shared COMPASS-7066
  .evergreen/buildvariants-and-tasks.in.yml
  .evergreen/buildvariants-and-tasks.yml
  .evergreen/functions.yml
  package-lock.json
  package.json
  packages/atlas-service/package.json
  packages/compass-e2e-tests/tests/in-use-encryption.test.ts
  packages/compass/package.json
  packages/compass/scripts/download-csfle.js
  packages/data-service/package.json
  packages/hadron-build/commands/release.js
Labels: release notes

#6193 fix(query-bar, editor): update query history autocompletion to be more selective COMPASS-8241
  packages/compass-editor/src/codemirror/query-autocompleter-with-history.test.ts
  packages/compass-editor/src/codemirror/query-autocompleter-with-history.ts
  packages/compass-editor/src/codemirror/query-history-autocompleter.test.ts
  packages/compass-editor/src/codemirror/query-history-autocompleter.ts
  packages/compass-query-bar/src/components/option-editor.tsx
  packages/compass-query-bar/src/components/query-history/index.spec.tsx
Labels: release notes, fix

#6197 fix(compass-crud): fix nextPage availability logic COMPASS-8239
  packages/compass-crud/src/components/crud-toolbar.spec.tsx
  packages/compass-crud/src/components/crud-toolbar.tsx
Labels: release notes, fix

#6199 feat(editor, query-bar): on query history autocomplete move cursor to end of content, small ux updates
  packages/compass-editor/src/codemirror/query-history-autocompleter.ts
  packages/compass-editor/src/editor.tsx
  packages/compass-query-bar/src/components/option-editor.tsx
Labels: release notes, feat

#6196 fix(indexes): check for vector search support when showing edit templates COMPASS-8235
  packages/compass-indexes/src/components/search-index-template-dropdown/index.spec.tsx
  packages/compass-indexes/src/components/search-index-template-dropdown/index.tsx
  packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.tsx
  packages/compass-indexes/src/components/search-indexes-modals/update-search-index-modal.spec.tsx
  packages/compass-indexes/src/components/search-indexes-modals/update-search-index-modal.tsx
Labels: release notes, fix

#6204 fix: remove outdated shortcut COMPASS-8259
  packages/compass-shell/src/components/shell-info-modal/keyboard-shortcuts-table.tsx
Labels: release notes, fix

#6209 fix(explain-plan): use executionStats verbosity COMPASS-8263
  packages/compass-explain-plan/src/stores/explain-plan-modal-store.ts
  packages/data-service/src/data-service.ts
Labels: release notes, fix

#6166 feat(connection-form): support for multiple kms options from same provider COMPASS-8082
  packages/compass-connections/src/stores/connections-store-redux.ts
  packages/compass-e2e-tests/helpers/commands/connect-form.ts
  packages/compass-e2e-tests/helpers/connect-form-state.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/connection.test.ts
  packages/compass-e2e-tests/tests/in-use-encryption.test.ts
  packages/connection-form/src/components/advanced-options-tabs/csfle-tab/csfle-tab.spec.tsx
  packages/connection-form/src/components/advanced-options-tabs/csfle-tab/csfle-tab.tsx
  packages/connection-form/src/components/advanced-options-tabs/csfle-tab/kms-local-key-generator.tsx
  packages/connection-form/src/components/advanced-options-tabs/csfle-tab/kms-provider-card.tsx
  packages/connection-form/src/components/advanced-options-tabs/csfle-tab/kms-provider-content.tsx
  packages/connection-form/src/components/advanced-options-tabs/csfle-tab/kms-provider-fields.tsx
  packages/connection-form/src/components/advanced-options-tabs/csfle-tab/kms-provider-status-indicator.tsx
  packages/connection-form/src/components/advanced-options-tabs/csfle-tab/kms-tls-options.tsx
  packages/connection-form/src/components/connection-form.spec.tsx
  packages/connection-form/src/hooks/use-connect-form.ts
  packages/connection-form/src/utils/csfle-handler.spec.ts
  packages/connection-form/src/utils/csfle-handler.ts
  packages/connection-form/src/utils/csfle-kms-fields.ts
  packages/connection-form/src/utils/validation.ts
  packages/connection-info/src/connection-secrets.spec.ts
  packages/connection-info/src/connection-secrets.ts
  packages/connection-storage/src/compass-main-connection-storage.spec.ts
  packages/databases-collections/src/components/collection-fields/fle2-fields.jsx
  packages/databases-collections/src/modules/create-namespace.ts
Labels: release notes, feat

#6222 fix(deps): update dset to latest
  package-lock.json
Labels: fix, no release notes

#6226 fix(deps): override body-parser and bump express COMPASS-8288)
  package-lock.json
  packages/compass-web/package.json
Labels: fix, no release notes

#6205 fix: trimming whitespaces when creating/editing a namespace COMPASS-8123
  packages/databases-collections/src/components/create-namespace-modal.spec.tsx
  packages/databases-collections/src/components/rename-collection-modal/rename-collection-modal.spec.tsx
  packages/databases-collections/src/components/rename-collection-modal/rename-collection-modal.tsx
  packages/databases-collections/src/modules/create-namespace.ts
  packages/databases-collections/src/modules/rename-collection/rename-collection.ts
Labels: release notes, fix

#6240 fix(connections): ensure that connectionInfoAccess hook value is stable
  packages/compass-connections/src/connection-info-provider.tsx
Labels: fix, no release notes

#6235 fix(telemetry): add support for multiple kms providers
  packages/compass-e2e-tests/tests/logging.test.ts
  packages/compass-telemetry/src/telemetry-events.ts
  packages/compass/src/app/utils/telemetry.spec.ts
  packages/compass/src/app/utils/telemetry.ts
Labels: fix, no release notes

#6267 chore(compass-collection): move tab names to plugins COMPASS-8320
  package-lock.json
  packages/collection-model/index.d.ts
  packages/compass-aggregations/src/index.ts
  packages/compass-aggregations/src/plugin-title.tsx
  packages/compass-aggregations/test/configure-store.ts
  packages/compass-collection/package.json
  packages/compass-collection/src/components/collection-header/collection-header.tsx
  packages/compass-collection/src/components/collection-header/index.ts
  packages/compass-collection/src/components/collection-tab-provider.tsx
  packages/compass-collection/src/components/collection-tab.tsx
  packages/compass-collection/src/modules/collection-tab.ts
  packages/compass-collection/src/stores/collection-tab.ts
  packages/compass-components/src/components/tab-nav-bar.spec.tsx
  packages/compass-components/src/components/tab-nav-bar.tsx
  packages/compass-crud/package.json
  packages/compass-crud/src/index.ts
  packages/compass-crud/src/plugin-title.tsx
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-crud/src/utils/data-service.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-indexes/package.json
  packages/compass-indexes/src/index.ts
  packages/compass-indexes/src/modules/collection-stats.ts
  packages/compass-indexes/src/modules/index.ts
  packages/compass-indexes/src/plugin-title.tsx
  packages/compass-indexes/src/stores/store.spec.ts
  packages/compass-indexes/src/stores/store.ts
  packages/compass-indexes/test/setup-store.ts
  packages/compass-schema-validation/src/components/validation-states/validation-states.spec.tsx
  packages/compass-schema-validation/src/index.ts
  packages/compass-schema-validation/src/plugin-title.tsx
  packages/compass-schema/src/index.ts
  packages/compass-schema/src/plugin-title.tsx
Labels: no release notes

#6273 feat(global-writes): setup global-writes plugin COMPASS-8275
  package-lock.json
  packages/compass-collection/src/components/collection-tab.tsx
  packages/compass-connections/src/provider.ts
  packages/compass-global-writes/.depcheckrc
  packages/compass-global-writes/.eslintignore
  packages/compass-global-writes/.eslintrc.js
  packages/compass-global-writes/.mocharc.js
  packages/compass-global-writes/.prettierignore
  packages/compass-global-writes/.prettierrc.json
  packages/compass-global-writes/package.json
  packages/compass-global-writes/src/components/index.spec.tsx
  packages/compass-global-writes/src/components/index.tsx
  packages/compass-global-writes/src/index.ts
  packages/compass-global-writes/src/plugin-title.tsx
  packages/compass-global-writes/src/services/atlas-global-writes-service.ts
  packages/compass-global-writes/src/store/index.ts
  packages/compass-global-writes/src/store/reducer.ts
  packages/compass-global-writes/tsconfig-lint.json
  packages/compass-global-writes/tsconfig.json
  packages/compass-telemetry/src/telemetry-events.ts
  packages/compass-web/package.json
  packages/compass-web/src/entrypoint.tsx
  packages/compass-workspaces/src/types.ts
  packages/compass/package.json
  packages/compass/src/app/components/workspace.tsx
Labels: feat, no release notes

#6287 fix(atlas-service): use metricsId for clusterId when doing automation agent requests
  packages/atlas-service/src/atlas-service.ts
  packages/compass-web/scripts/start-electron-proxy.js
  packages/compass-web/src/connection-storage.tsx
  packages/compass-web/webpack.config.js
Labels: fix, no release notes

#6225 fix(connection-form): vscode support & cleanup COMPASS-8098
  packages/compass-connections/src/components/legacy-connections.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
  packages/compass/src/app/components/home.spec.tsx
  packages/connection-form/src/components/advanced-options-tabs/advanced-options-tabs.spec.tsx
  packages/connection-form/src/components/advanced-options-tabs/advanced-options-tabs.tsx
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-gssapi.spec.tsx
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-gssapi.tsx
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.spec.tsx
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.tsx
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-tab.spec.tsx
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-tab.tsx
  packages/connection-form/src/components/advanced-options-tabs/csfle-tab/csfle-tab.tsx
  packages/connection-form/src/components/advanced-options-tabs/ssh-tunnel-tab/proxy-and-ssh-tunnel-tab.tsx
  packages/connection-form/src/components/connection-form-actions.spec.tsx
  packages/connection-form/src/components/connection-form-actions.tsx
  packages/connection-form/src/components/connection-form.spec.tsx
  packages/connection-form/src/components/connection-form.tsx
  packages/connection-form/src/hooks/use-connect-form-settings.tsx
  packages/connection-form/src/hooks/use-connect-form.ts
Labels: fix, no release notes

#6289 feat(global-writes): add unsharded state COMPASS-8276
  package-lock.json
  packages/compass-global-writes/package.json
  packages/compass-global-writes/src/components/index.spec.tsx
  packages/compass-global-writes/src/components/index.tsx
  packages/compass-global-writes/src/components/states/sharding.spec.tsx
  packages/compass-global-writes/src/components/states/sharding.tsx
  packages/compass-global-writes/src/components/states/unsharded.tsx
  packages/compass-global-writes/src/components/states/usharded.spec.tsx
  packages/compass-global-writes/src/index.ts
  packages/compass-global-writes/src/plugin-title.tsx
  packages/compass-global-writes/src/services/atlas-global-writes-service.ts
  packages/compass-global-writes/src/store/index.spec.ts
  packages/compass-global-writes/src/store/index.ts
  packages/compass-global-writes/src/store/reducer.ts
  packages/compass-global-writes/tests/cluster-api-response.json
  packages/compass-global-writes/tests/create-store.tsx
Labels: feat, no release notes

#6294 fix: remove compass-preferences from connection-form completely COMPASS-8098
  package-lock.json
  packages/compass-sidebar/src/components/legacy/favorite-indicator.tsx
  packages/compass-sidebar/src/components/legacy/navigation-items.spec.tsx
  packages/compass-sidebar/src/components/legacy/navigation-items.tsx
  packages/compass-sidebar/src/components/legacy/sidebar-databases-navigation.tsx
  packages/compass-sidebar/src/components/legacy/sidebar-title.tsx
  packages/compass-sidebar/src/components/legacy/sidebar.tsx
  packages/compass-sidebar/src/plugin.tsx
  packages/connection-form/package.json
  packages/connection-form/src/components/connection-form.spec.tsx
  packages/connection-form/src/components/favorite-color-picker.tsx
  packages/connection-form/src/components/save-connection-modal.spec.tsx
  packages/connection-form/src/components/save-connection-modal.tsx
  packages/connection-form/src/hooks/use-connection-color.spec.tsx
  packages/connection-form/src/hooks/use-connection-color.ts
  packages/connection-form/src/index.ts
Labels: fix, no release notes
