Repository mongodb-js/compass, pull requests merged in 2024-07, with the labels that each got.

#5980 fix(schema): prevent application from hanging when selecting ranges too fast on the "Schema" tab COMPASS-8048
  packages/compass-query-bar/src/index.tsx
  packages/compass-schema/src/components/coordinates-minichart/coordinates-minichart.jsx
  packages/compass-schema/src/components/field.tsx
  packages/compass-schema/src/components/minichart/minichart.jsx
  packages/compass-schema/src/components/unique-minichart/unique-minichart.jsx
  packages/compass-schema/src/components/value-bubble.tsx
  packages/compass-schema/src/stores/store.ts
Labels: release notes, fix

#5917 feat(databases-collections, collection): add "Visualize Your Data" button to workspace headers CLOUDP-247464
  package-lock.json
  packages/compass-collection/src/components/collection-header-actions/collection-header-actions.tsx
  packages/compass-components/src/components/workspace-container.tsx
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/databases-collections-list/package.json
  packages/databases-collections-list/src/collections.tsx
  packages/databases-collections-list/src/index.spec.tsx
  packages/databases-collections-list/src/items-grid.tsx
  packages/databases-collections-list/src/namespace-card.tsx
  packages/databases-collections-list/src/use-create.tsx
  packages/databases-collections-list/src/use-refresh.tsx
  packages/databases-collections/package.json
  packages/databases-collections/src/components/collections.tsx
Labels: feat, no release notes

#5965 feat(databases): show "Add Data" CTA when there are no user databases in the cluster COMPASS-7908
  packages/compass-components/src/components/empty-content.tsx
  packages/databases-collections-list/src/databases.tsx
  packages/databases-collections-list/src/items-grid.tsx
  packages/databases-collections/src/components/databases.tsx
  packages/databases-collections/src/components/load-sample-data.tsx
  packages/databases-collections/src/components/zero-graphic.tsx
Labels: feat, no release notes

#5988 fix(serverstats): use telemetry hook in component COMPASS-8056
  packages/compass-serverstats/src/components/detailview-component.jsx
  packages/compass-serverstats/src/components/detailview-component.tsx
  packages/compass-serverstats/src/components/server-stats-lists-component.jsx
Labels: release notes, fix

#5997 fix: expanding an inactive connection triggers connect COMPASS-8060
  packages/compass-connections-navigation/src/base-navigation-item.tsx
  packages/compass-connections-navigation/src/navigation-item.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
Labels: feature flagged, fix

#6008 fix: new duplicate connection behaviour for MC (COMPASS-8069)
  packages/compass-connections/src/components/connections.tsx
  packages/compass-connections/src/stores/connections-store.spec.tsx
  packages/compass-connections/src/stores/connections-store.tsx
  packages/compass-e2e-tests/tests/connection-form.test.ts
  packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
Labels: feature flagged, fix

#5995 feat(compass-editor, compass-query-bar): show query history in autocomplete COMPASS-8017
  package-lock.json
  packages/compass-components/src/index.ts
  packages/compass-editor/package.json
  packages/compass-editor/src/codemirror/query-autocompleter-with-history.test.ts
  packages/compass-editor/src/codemirror/query-autocompleter-with-history.ts
  packages/compass-editor/src/codemirror/query-history-autocompleter.ts
  packages/compass-editor/src/editor.tsx
  packages/compass-editor/src/index.ts
  packages/compass-query-bar/src/components/option-editor.spec.tsx
  packages/compass-query-bar/src/components/option-editor.tsx
  packages/compass-query-bar/src/components/query-history-button-popover.tsx
  packages/compass-query-bar/src/stores/query-bar-reducer.ts
  packages/compass-query-bar/src/stores/query-bar-store.spec.ts
  packages/compass-query-bar/src/stores/query-bar-store.ts
Labels: release notes, feat

#6011 fix(ci): temporarily use override to bump mongodb-redact package
  package-lock.json
  package.json
Labels: fix, no release notes

#5996 fix(shell): persist shell input; prevent tab from blinking; fix telemetry
  package-lock.json
  packages/compass-shell/package.json
  packages/compass-shell/src/components/compass-shell/compass-shell.spec.tsx
  packages/compass-shell/src/components/compass-shell/compass-shell.tsx
  packages/compass-shell/src/components/compass-shell/tab-compass-shell.tsx
  packages/compass-shell/src/components/shell-header/shell-header.tsx
  packages/compass-shell/src/components/shell-info-modal/shell-info-modal.tsx
  packages/compass-shell/src/index.ts
  packages/compass-shell/src/modules/index.ts
  packages/compass-shell/src/modules/runtime.ts
  packages/compass-shell/src/modules/worker-runtime.ts
  packages/compass-shell/src/plugin.spec.tsx
  packages/compass-shell/src/plugin.tsx
  packages/compass-shell/src/stores/index.ts
  packages/compass-shell/src/stores/store.spec.ts
  packages/compass-shell/src/stores/store.ts
Labels: feature flagged, fix

#5999 feat(workspaces, databases, collections, collection): allow to open shell with initial state; add shell entrypoints to tab headers
  package-lock.json
  packages/compass-collection/package.json
  packages/compass-collection/src/components/collection-header-actions/collection-header-actions.tsx
  packages/compass-preferences-model/src/react.ts
  packages/compass-shell/src/components/compass-shell/tab-compass-shell.tsx
  packages/compass-shell/src/plugin.tsx
  packages/compass-workspaces/src/components/workspaces.tsx
  packages/compass-workspaces/src/provider.tsx
  packages/compass-workspaces/src/stores/workspaces.ts
  packages/compass-workspaces/src/types.ts
  packages/databases-collections-list/src/items-grid.tsx
Labels: feature flagged, feat

#6019 fix(compass-app-stores): fixes stale listeners getting triggered on globalAppRegistry events
  packages/compass-aggregations/src/modules/aggregation.ts
  packages/compass-aggregations/src/modules/index.ts
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.ts
  packages/compass-aggregations/src/modules/pipeline-builder/text-editor-output-stage.ts
  packages/compass-aggregations/src/modules/update-view.spec.ts
  packages/compass-aggregations/src/modules/update-view.ts
  packages/compass-app-stores/src/stores/instance-store.spec.ts
  packages/compass-app-stores/src/stores/instance-store.ts
  packages/compass-sidebar/src/components/legacy/sidebar-databases-navigation.tsx
  packages/compass-sidebar/src/modules/databases.ts
Labels: fix, no release notes

#6027 fix(compass-sidebar): do not filter out low level items when a top level item matches the filter COMPASS-8026
  packages/compass-sidebar/src/components/legacy/sidebar-databases-navigation.tsx
  packages/compass-sidebar/src/components/use-filtered-connections.spec.ts
  packages/compass-sidebar/src/components/use-filtered-connections.ts
Labels: release notes, fix

#6013 fix(hadron-document): allow expanding an element that has its type changed to array or object COMPASS-7929
  packages/hadron-document/src/element.ts
  packages/hadron-document/test/element.test.ts
Labels: release notes, fix

#6034 refactor(compass-connections): remove extra save on connect
  packages/compass-connections/src/components/legacy-connections.spec.tsx
  packages/compass-connections/src/components/legacy-connections.tsx
  packages/compass-connections/src/index.ts
  packages/compass-connections/src/stores/connections-store.spec.tsx
  packages/compass-connections/src/stores/connections-store.tsx
Labels: feature flagged

#6037 fix: save&connect COMPASS-8068
  packages/compass-connections/src/components/legacy-connections.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
  packages/compass/src/app/utils/telemetry.spec.ts
  packages/compass/src/app/utils/telemetry.ts
  packages/connection-form/src/components/connection-form-actions.spec.tsx
  packages/connection-form/src/components/connection-form-actions.tsx
  packages/connection-form/src/components/connection-form.spec.tsx
  packages/connection-form/src/components/connection-form.tsx
Labels: feature flagged, fix

#6044 refactor(hadron-build): remove usage of "async" package and its tasks COMPASS-5051
  package-lock.json
  packages/hadron-build/commands/release.js
  packages/hadron-build/lib/zip.js
  packages/hadron-build/package.json
Labels: no release notes

#6051 fix(query-bar): save hint in queries
  packages/compass-query-bar/src/utils/get-query-attributes.spec.ts
  packages/compass-query-bar/src/utils/get-query-attributes.ts
  packages/my-queries-storage/src/query-storage-schema.ts
Labels: release notes, fix

#6052 fix(import-export): promoteValues: false for export json COMPASS-8099
  packages/compass-import-export/src/export/export-csv.ts
  packages/compass-import-export/src/export/export-cursor.ts
  packages/compass-import-export/src/export/export-json.ts
  packages/compass-import-export/test/docs/all-bson-types.exported.canonical.ejson
  packages/compass-import-export/test/docs/all-bson-types.exported.csv
  packages/compass-import-export/test/docs/all-bson-types.exported.default.ejson
  packages/compass-import-export/test/docs/all-bson-types.exported.relaxed.ejson
  packages/compass-import-export/test/docs/all-bson-types.gathered.json
  packages/compass-import-export/test/docs/all-bson-types.js
Labels: release notes, fix

#6040 feat(compass-editor, compass-query-bar): provide auto completed query history matching user input COMPASS-8018
  package-lock.json
  packages/compass-editor/package.json
  packages/compass-editor/src/codemirror/aggregation-autocompleter.test.ts
  packages/compass-editor/src/codemirror/query-autocompleter-with-history.test.ts
  packages/compass-editor/src/codemirror/query-autocompleter-with-history.ts
  packages/compass-editor/src/codemirror/query-autocompleter.test.ts
  packages/compass-editor/src/codemirror/query-history-autocompleter.test.ts
  packages/compass-editor/src/codemirror/query-history-autocompleter.ts
  packages/compass-editor/src/codemirror/search-index-autocompleter.test.ts
  packages/compass-editor/src/codemirror/stage-autocompleter.test.ts
  packages/compass-editor/src/codemirror/validation-autocompleter.test.ts
  packages/compass-editor/test/completer.ts
  packages/compass-query-bar/src/components/option-editor.tsx
  packages/compass-query-bar/src/stores/query-bar-reducer.spec.ts
  packages/compass-query-bar/src/stores/query-bar-reducer.ts
Labels: feature flagged, feat

#6009 feat(compass-crud): allows nested elements to also expand in steps
  packages/compass-components/src/components/document-list/document-fields-toggle-group.tsx
  packages/compass-components/src/components/document-list/document.spec.tsx
  packages/compass-components/src/components/document-list/document.tsx
  packages/compass-components/src/components/document-list/element.tsx
  packages/compass-components/src/components/document-list/index.ts
  packages/compass-components/src/components/document-list/visible-field-toggle.tsx
  packages/compass-components/src/components/document-list/visible-fields-toggle.spec.tsx
  packages/hadron-document/src/document.ts
  packages/hadron-document/src/element-events.ts
  packages/hadron-document/src/element.ts
  packages/hadron-document/src/index.ts
  packages/hadron-document/test/document.test.ts
  packages/hadron-document/test/element.test.ts
Labels: release notes, feat

#6057 feat(sidebar): Add the shell icon on hover to the connections in the sidebar COMPASS-8050 COMPASS-8071
  packages/compass-connections-navigation/src/connections-navigation-tree.spec.tsx
  packages/compass-connections-navigation/src/connections-navigation-tree.tsx
  packages/compass-connections-navigation/src/item-actions.ts
  packages/compass-connections-navigation/src/navigation-item.tsx
  packages/compass-connections-navigation/src/tree-data.ts
  packages/compass-connections-navigation/src/virtual-list/virtual-list.tsx
  packages/compass-e2e-tests/helpers/commands/open-shell.ts
  packages/compass-e2e-tests/helpers/commands/sidebar-connection.ts
  packages/compass-e2e-tests/tests/connection.test.ts
  packages/compass-e2e-tests/tests/instance-sidebar.test.ts
  packages/compass-e2e-tests/tests/read-only.test.ts
  packages/compass-e2e-tests/tests/shell.test.ts
  packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
Labels: feature flagged, feat

#6060 feat(compass-editor, compass-query-bar): query history autocomplete formatting COMPASS-8063
  package-lock.json
  packages/compass-editor/package.json
  packages/compass-editor/src/codemirror/query-autocompleter-with-history.test.ts
  packages/compass-editor/src/codemirror/query-autocompleter-with-history.ts
  packages/compass-editor/src/codemirror/query-history-autocompleter.ts
  packages/compass-editor/src/editor.tsx
  packages/compass-query-bar/src/components/option-editor.spec.tsx
  packages/compass-query-bar/src/components/option-editor.tsx
Labels: dependencies, feature flagged, feat

#6056 feat(compass): display warning message to user when Compass cannot access cred…
  packages/compass/src/app/index.tsx
  packages/compass/src/main/application.ts
Labels: release notes, feat

#6059 fix(compass-connections, sidebar): move all connection related logic and state to compass-connections COMPASS-8067
  package-lock.json
  packages/compass-connections/package.json
  packages/compass-connections/src/components/connection-status-toasts.tsx
  packages/compass-connections/src/components/legacy-connections.spec.tsx
  packages/compass-connections/src/components/legacy-connections.tsx
  packages/compass-connections/src/components/non-genuine-connection-modal.tsx
  packages/compass-connections/src/connections-manager.ts
  packages/compass-connections/src/hooks/use-connection-form-preferences.tsx
  packages/compass-connections/src/hooks/use-connection-repository.ts
  packages/compass-connections/src/hooks/use-connections-with-status.ts
  packages/compass-connections/src/index.ts
  packages/compass-connections/src/stores/connections-store.spec.tsx
  packages/compass-connections/src/stores/connections-store.tsx
  packages/compass-sidebar/package.json
  packages/compass-sidebar/src/components/legacy/sidebar.tsx
  packages/compass-sidebar/src/components/multiple-connections/connections-navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
  packages/compass-sidebar/src/components/non-genuine-warning-modal.tsx
  packages/compass-sidebar/src/modules/index.ts
  packages/compass-sidebar/src/modules/instance.spec.ts
  packages/compass-sidebar/src/modules/instance.ts
  packages/compass-sidebar/src/modules/is-genuine-mongodb-visible.spec.ts
  packages/compass-sidebar/src/modules/is-genuine-mongodb-visible.ts
  packages/compass-sidebar/src/stores/store.spec.ts
  packages/compass-utils/src/cancellable-promise.ts
  packages/compass-welcome/package.json
  packages/compass-welcome/src/components/welcome-tab.tsx
  packages/compass/src/app/components/entrypoint.tsx
  packages/compass/src/app/components/home.spec.tsx
  packages/compass/src/app/components/home.tsx
  packages/connection-form/src/components/connection-form-modal.tsx
Labels: feature flagged, fix

#6070 fix(build): use an older ffmpeg version when packaging
  packages/hadron-build/lib/target.js
Labels: fix, no release notes

#6067 feat(compass): report hostname for atlas COMPASS-8094
  packages/compass/src/app/utils/telemetry.spec.ts
  packages/compass/src/app/utils/telemetry.ts
Labels: feat, no release notes

#6064 feat(compass-editor, compass-query-bar): autocomplete icon COMPASS-8031
  packages/compass-editor/src/codemirror/ace-compat-autocompleter.ts
  packages/compass-editor/src/codemirror/query-autocompleter-with-history.ts
  packages/compass-editor/src/codemirror/query-history-autocompleter.ts
  packages/compass-editor/src/editor.tsx
Labels: feature flagged, feat

#6073 fix(hadron-build): move app to temp directory for building on windows COMPASS-8051
  packages/compass-e2e-tests/tests/logging.test.ts
  packages/compass/.depcheckrc
  packages/compass/src/main/logging.ts
  packages/compass/src/main/optional-deps.ts
  packages/hadron-build/commands/release.js
Labels: release notes, fix

#6018 feat: new telemetry events for connections
  packages/compass-connection-import-export/src/components/export-modal.tsx
  packages/compass-connection-import-export/src/components/import-modal.tsx
  packages/compass-connection-import-export/src/hooks/use-export-connections.spec.ts
  packages/compass-connection-import-export/src/hooks/use-export-connections.ts
  packages/compass-connection-import-export/src/hooks/use-import-connections.spec.ts
  packages/compass-connection-import-export/src/hooks/use-import-connections.ts
  packages/compass-connections/src/hooks/use-connection-repository.ts
  packages/compass-connections/src/stores/connections-store.spec.tsx
  packages/compass-connections/src/stores/connections-store.tsx
  packages/compass-connections/src/utils/telemetry.spec.tsx
  packages/compass-connections/src/utils/telemetry.tsx
  packages/compass/src/app/utils/telemetry.spec.ts
Labels: feat, no release notes

#6074 chore(deps): bump shell and driver
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-e2e-tests/package.json
  packages/compass-explain-plan/package.json
  packages/compass-generative-ai/package.json
  packages/compass-import-export/package.json
  packages/compass-indexes/package.json
  packages/compass-query-bar/package.json
  packages/compass-schema/package.json
  packages/compass-shell/package.json
  packages/compass-sidebar/package.json
  packages/compass-web/package.json
  packages/compass/package.json
  packages/connection-form/package.json
  packages/connection-form/src/utils/csfle-handler.ts
  packages/connection-form/src/utils/csfle-kms-fields.ts
  packages/connection-info/package.json
  packages/data-service/package.json
Labels: dependencies

#6071 chore(explain-plan-helper): add support for express plan COMPASS-7794
  package-lock.json
  packages/compass-explain-plan/src/components/explain-plan-side-summary.tsx
  packages/compass-explain-plan/src/components/explain-tree/explain-tree-data.ts
  packages/compass-explain-plan/src/components/explain-tree/explain-tree-stage.tsx
  packages/explain-plan-helper/package.json
  packages/explain-plan-helper/src/index.spec.ts
  packages/explain-plan-helper/src/index.ts
  packages/explain-plan-helper/src/utils.spec.ts
  packages/explain-plan-helper/src/utils.ts
  packages/explain-plan-helper/test/fixtures/clustered_scan.json
  packages/explain-plan-helper/test/fixtures/count_scan.json
  packages/explain-plan-helper/test/fixtures/express_clustered_scan.json
  packages/explain-plan-helper/test/fixtures/express_index_scan.json
Labels: release notes

#6076 fix(compass-connections): recognize empty name during duplication
  packages/compass-connections/src/stores/connections-store.spec.tsx
  packages/compass-connections/src/stores/connections-store.tsx
Labels: fix, no release notes

#6075 feat(compass-editor, compass-query-bar): added star icon to autocomplete favorite queries
  packages/compass-editor/src/codemirror/query-autocompleter-with-history.test.ts
  packages/compass-editor/src/codemirror/query-history-autocompleter.ts
  packages/compass-editor/src/editor.tsx
  packages/compass-editor/src/index.ts
  packages/compass-query-bar/src/components/option-editor.spec.tsx
  packages/compass-query-bar/src/components/option-editor.tsx
Labels: feature flagged, feat

#6079 feat(compass-query-bar): selectively autocomplete query history in additional options COMPASS-8118
  packages/compass-query-bar/src/components/option-editor.spec.tsx
  packages/compass-query-bar/src/components/option-editor.tsx
  packages/compass-query-bar/src/components/query-option.tsx
Labels: feature flagged, feat
