Repository mongodb-js/compass, pull requests merged in 2024-10, with the labels that each got.

#6315 fix(hadron-build): use `ditto` instead of zip to package on MacOS COMPASS-7737
  packages/hadron-build/lib/zip.js
Labels: release notes, fix

#6316 chore(ci): use "archive.targz_pack" command to archive e2e logs
  .evergreen/functions.yml
Labels: no release notes

#6318 feat(compass-indexes): Poll rolling indexes where available, add status column COMPASS-8217 COMPASS-8329
  packages/compass-indexes/src/components/indexes/indexes.spec.tsx
  packages/compass-indexes/src/components/regular-indexes-table/property-field.tsx
  packages/compass-indexes/src/components/regular-indexes-table/regular-indexes-table.spec.tsx
  packages/compass-indexes/src/components/regular-indexes-table/regular-indexes-table.tsx
  packages/compass-indexes/src/components/regular-indexes-table/status-field.tsx
  packages/compass-indexes/src/modules/regular-indexes.spec.ts
  packages/compass-indexes/src/modules/regular-indexes.ts
  packages/compass-indexes/src/modules/rolling-indexes-service.ts
Labels: feat, no release notes

#6317 chore(ci): log electron app messages
  packages/compass-e2e-tests/helpers/compass.ts
Labels: no release notes

#6232 chore(ci): build and test packaged app on the newer macos version (2nd attempt) COMPASS-8090
  .evergreen/buildvariants-and-tasks.in.yml
  .evergreen/buildvariants-and-tasks.yml
Labels: no release notes

#6309 feat(indexes): add an option to create indexes through rolling build COMPASS-8216
  packages/atlas-service/src/atlas-service.ts
  packages/atlas-service/src/util.ts
  packages/compass-indexes/src/components/create-index-form/checkbox-input.tsx
  packages/compass-indexes/src/components/create-index-form/create-index-form.tsx
  packages/compass-indexes/src/modules/create-index.tsx
  packages/compass-indexes/src/modules/regular-indexes.ts
  packages/compass-indexes/src/modules/rolling-indexes-service.spec.ts
  packages/compass-indexes/src/modules/rolling-indexes-service.ts
Labels: feat, no release notes

#6321 fix(proxy): show friendly error when proxy config is not supported COMPASS-8345
  packages/compass/src/main/application.ts
Labels: release notes, fix

#6304 feat: add sharded state COMPASS-8279
  package-lock.json
  packages/compass-global-writes/package.json
  packages/compass-global-writes/src/components/index.spec.tsx
  packages/compass-global-writes/src/components/index.tsx
  packages/compass-global-writes/src/components/shard-zones-table.spec.tsx
  packages/compass-global-writes/src/components/shard-zones-table.tsx
  packages/compass-global-writes/src/components/states/shard-key-correct.spec.tsx
  packages/compass-global-writes/src/components/states/shard-key-correct.tsx
  packages/compass-global-writes/src/components/states/sharding.spec.tsx
  packages/compass-global-writes/src/components/states/usharded.spec.tsx
  packages/compass-global-writes/src/plugin-title.tsx
  packages/compass-global-writes/src/services/atlas-global-writes-service.ts
  packages/compass-global-writes/src/store/index.spec.ts
  packages/compass-global-writes/src/store/index.ts
  packages/compass-global-writes/src/store/reducer.ts
  packages/compass-global-writes/tests/create-store.tsx
Labels: feat, no release notes

#6336 feat(connection-form): allow editing connected connections, but only the name, colour and favorite checkbox COMPASS-8160
  packages/compass-connections-navigation/src/item-actions.ts
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
  packages/connection-form/src/components/advanced-options-tabs/csfle-tab/csfle-tab.spec.tsx
  packages/connection-form/src/components/connection-form-actions.spec.tsx
  packages/connection-form/src/components/connection-form-actions.tsx
  packages/connection-form/src/components/connection-form.spec.tsx
  packages/connection-form/src/components/connection-form.tsx
  packages/connection-form/src/components/connection-string-input.spec.tsx
  packages/connection-form/src/components/connection-string-input.tsx
  packages/connection-form/src/components/form-help/form-help.tsx
Labels: feature flagged, feat

#6333 fix(deps): bump mongosh, driver, bson
  package-lock.json
  packages/atlas-service/package.json
  packages/compass-aggregations/package.json
  packages/compass-components/package.json
  packages/compass-connections/package.json
  packages/compass-crud/package.json
  packages/compass-e2e-tests/package.json
  packages/compass-explain-plan/package.json
  packages/compass-generative-ai/package.json
  packages/compass-import-export/package.json
  packages/compass-indexes/package.json
  packages/compass-preferences-model/package.json
  packages/compass-query-bar/package.json
  packages/compass-saved-aggregations-queries/package.json
  packages/compass-schema-validation/package.json
  packages/compass-schema/package.json
  packages/compass-shell/package.json
  packages/compass-sidebar/package.json
  packages/compass-web/package.json
  packages/compass-workspaces/package.json
  packages/compass/package.json
  packages/compass/src/app/utils/telemetry.spec.ts
  packages/compass/src/main/validate-connection-string.ts
  packages/connection-form/package.json
  packages/connection-form/src/utils/csfle-handler.spec.ts
  packages/connection-form/src/utils/csfle-handler.ts
  packages/connection-info/package.json
  packages/connection-info/src/connection-secrets.spec.ts
  packages/connection-info/src/connection-secrets.ts
  packages/connection-storage/package.json
  packages/data-service/package.json
  packages/databases-collections/package.json
  packages/hadron-document/package.json
  packages/hadron-type-checker/package.json
  packages/mongodb-query-util/package.json
  packages/my-queries-storage/package.json
Labels: release notes, fix

#6344 feat(connection-form): show a banner on the connection form explaining why you can't edit the connection COMPASS-8264
  packages/connection-form/src/components/connection-form.spec.tsx
  packages/connection-form/src/components/connection-form.tsx
Labels: release notes, feat

#6341 feat(connection-form): up to three buttons: save, connect, save & connect COMPASS-8360
  packages/compass-connections/src/components/legacy-connections.spec.tsx
  packages/compass-connections/src/stores/connections-store-redux.ts
  packages/compass-connections/src/stores/connections-store.spec.tsx
  packages/compass-connections/src/stores/connections-store.tsx
  packages/compass-connections/src/stores/store-context.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
  packages/compass-web/src/entrypoint.spec.tsx
  packages/connection-form/src/components/connection-form-modal-actions.spec.tsx
  packages/connection-form/src/components/connection-form-modal-actions.tsx
  packages/connection-form/src/components/connection-form.spec.tsx
  packages/connection-form/src/components/connection-form.tsx
  packages/connection-form/src/hooks/use-connect-form-settings.tsx
Labels: release notes, feat

#6360 chore(telemetry): add "Index Create Failed" to mirror Index Created COMPASS-8100
  packages/compass-indexes/src/modules/regular-indexes.ts
  packages/compass-indexes/src/modules/search-indexes.ts
  packages/compass-telemetry/src/telemetry-events.ts
Labels: no release notes

#6347 feat(compass-global-writes): sharding in progress state COMPASS-8277
  packages/compass-global-writes/src/components/index.tsx
  packages/compass-global-writes/src/components/states/sharding.spec.tsx
  packages/compass-global-writes/src/components/states/sharding.tsx
  packages/compass-global-writes/src/plugin-title.spec.tsx
  packages/compass-global-writes/src/plugin-title.tsx
  packages/compass-global-writes/src/services/atlas-global-writes-service.ts
  packages/compass-global-writes/src/store/index.spec.ts
  packages/compass-global-writes/src/store/reducer.ts
Labels: feat, no release notes

#6370 fix(compass-generative-ai): Increase the character size restriction for query and aggregation genai COMPASS-8369
  packages/compass-generative-ai/src/atlas-ai-service.spec.ts
  packages/compass-generative-ai/src/atlas-ai-service.ts
  packages/compass-generative-ai/src/components/generative-ai-input.spec.tsx
  packages/compass-generative-ai/src/components/generative-ai-input.tsx
Labels: release notes, fix

#6371 feat(compass-global-writes): invalid and mismatching shard key state COMPASS-8278
  packages/compass-global-writes/src/components/index.tsx
  packages/compass-global-writes/src/components/shard-key-markup.tsx
  packages/compass-global-writes/src/components/states/shard-key-correct.spec.tsx
  packages/compass-global-writes/src/components/states/shard-key-correct.tsx
  packages/compass-global-writes/src/components/states/shard-key-invalid.spec.tsx
  packages/compass-global-writes/src/components/states/shard-key-invalid.tsx
  packages/compass-global-writes/src/components/states/shard-key-mismatch.spec.tsx
  packages/compass-global-writes/src/components/states/shard-key-mismatch.tsx
  packages/compass-global-writes/src/services/atlas-global-writes-service.ts
  packages/compass-global-writes/src/store/index.spec.ts
  packages/compass-global-writes/src/store/reducer.ts
Labels: feat, no release notes

#6385 fix(proxy): do not lock users out of Compass when using authenticated proxies COMPASS-8382
  packages/compass-settings/src/components/settings/proxy-settings-custom.tsx
  packages/compass/src/main/application.ts
Labels: release notes, fix

#6356 feat(compass-global-writes): zone table - add search and collapse/expand COMPASS-8336
  package-lock.json
  packages/compass-components/package.json
  packages/compass-components/src/components/leafygreen.tsx
  packages/compass-global-writes/src/components/shard-zones-table.spec.tsx
  packages/compass-global-writes/src/components/shard-zones-table.tsx
  packages/compass-global-writes/src/components/states/shard-key-correct.tsx
  packages/compass-web/src/url-builder.ts
Labels: feat, no release notes

#6400 chore(ci): Add a workflow to validate PR titles
  .github/workflows/check-pr-title.yml
Labels: no-title-validation

#6387 fix(deps): bump electron to 32.2.1 COMPASS-8399
  .evergreen/buildvariants-and-tasks.in.yml
  .evergreen/buildvariants-and-tasks.yml
  .evergreen/print-compass-env.js
  configs/webpack-config-compass/package.json
  package-lock.json
  packages/atlas-service/package.json
  packages/compass-components/src/components/file-input.spec.tsx
  packages/compass-components/src/components/file-input.tsx
  packages/compass-components/src/index.ts
  packages/compass-crud/package.json
  packages/compass-e2e-tests/package.json
  packages/compass-editor/src/editor.tsx
  packages/compass-explain-plan/package.json
  packages/compass-find-in-page/package.json
  packages/compass-import-export/package.json
  packages/compass-import-export/src/components/export-modal.tsx
  packages/compass-indexes/package.json
  packages/compass-query-bar/package.json
  packages/compass-schema-validation/package.json
  packages/compass-shell/package.json
  packages/compass-utils/package.json
  packages/compass-web/package.json
  packages/compass-workspaces/src/stores/workspaces.spec.ts
  packages/compass/package.json
  packages/compass/src/app/index.tsx
  packages/connection-form/src/components/advanced-options-tabs/csfle-tab/csfle-tab.spec.tsx
  packages/connection-form/src/components/advanced-options-tabs/ssh-tunnel-tab/ssh-tunnel-identity.spec.tsx
  packages/connection-form/src/components/advanced-options-tabs/tls-ssl-tab/tls-ssl-tab.spec.tsx
  packages/connection-storage/package.json
  packages/hadron-build/lib/target.js
  packages/hadron-build/package.json
  packages/hadron-ipc/package.json
  scripts/package.json
Labels: release notes, fix

#6404 fix(compass-crud): persist modified document value COMPASS-8373
  packages/compass-crud/src/components/json-editor.tsx
  packages/compass-crud/src/components/virtualized-document-json-view.spec.tsx
  packages/hadron-document/src/document.ts
Labels: release notes, fix

#6405 feat(global-writes): open global writes tab when creating a collection COMPASS-8280
  packages/compass-workspaces/src/provider.tsx
  packages/compass-workspaces/src/stores/workspaces.ts
  packages/databases-collections/src/modules/create-namespace.ts
Labels: feat, no release notes

#6414 chore(scripts): include electron-to-chromium to the list of packages to be updated with electron
  scripts/update-electron.js
Labels: no-title-validation

#6418 chore(ci): add no-title-validation label to autogenerated PRs
  .github/workflows/bump-packages.yaml
  .github/workflows/update-electron.yaml
Labels: no-title-validation

#6374 feat(compass-global-writes): sharding error state COMPASS-8349
  packages/compass-global-writes/src/components/common-styles.ts
  packages/compass-global-writes/src/components/create-shard-key-form.spec.tsx
  packages/compass-global-writes/src/components/create-shard-key-form.tsx
  packages/compass-global-writes/src/components/index.tsx
  packages/compass-global-writes/src/components/shard-zones-table.tsx
  packages/compass-global-writes/src/components/states/shard-key-correct.tsx
  packages/compass-global-writes/src/components/states/shard-key-invalid.tsx
  packages/compass-global-writes/src/components/states/shard-key-mismatch.tsx
  packages/compass-global-writes/src/components/states/sharding-error.spec.tsx
  packages/compass-global-writes/src/components/states/sharding-error.tsx
  packages/compass-global-writes/src/components/states/sharding.tsx
  packages/compass-global-writes/src/components/states/unsharded.tsx
  packages/compass-global-writes/src/components/states/usharded.spec.tsx
  packages/compass-global-writes/src/services/atlas-global-writes-service.ts
  packages/compass-global-writes/src/store/index.spec.ts
  packages/compass-global-writes/src/store/reducer.ts
Labels: feat, no release notes

#6425 chore(e2e): adjust the scripts to make it easier to run atlas cloud e2e tests locally
  .evergreen/functions.yml
  .evergreen/start-atlas-cloud-cluster.sh
  packages/compass-e2e-tests/helpers/test-runner-context.ts
Labels: no-title-validation
