Repository mongodb-js/compass, pull requests merged in 2024-11, with the labels that each got.

#6429 fix(e2e): account for a recurring MFA reminder when singing in to cloud ui
  packages/compass-e2e-tests/helpers/compass-web-sandbox.ts
Labels: fix, no release notes, no-title-validation

#6432 chore(e2e): automatically create db user and add ip address to the access list before running tests
  .evergreen/functions.yml
  .evergreen/start-atlas-cloud-cluster.sh
Labels: no-title-validation

#6436 chore(e2e): screenshot if failed in rolling-indexes test
  packages/compass-e2e-tests/tests/atlas-cloud/rolling-indexes.test.ts
Labels: no-title-validation

#6427 fix(user-data): use semaphore to limit reads COMPASS-7256
  packages/compass-user-data/src/semaphore.spec.ts
  packages/compass-user-data/src/semaphore.ts
  packages/compass-user-data/src/user-data.ts
Labels: release notes, fix

#6441 chore(compass-editor): refactor JSON editor actions container into its own component
  packages/compass-editor/src/action-button.tsx
  packages/compass-editor/src/actions-container.tsx
  packages/compass-editor/src/editor.tsx
  packages/compass-editor/src/index.ts
  packages/compass-editor/src/types.ts
Labels: no-title-validation

#6439 chore(compass-components): less document whitespace
  packages/compass-components/src/components/document-list/document-actions-group.tsx
  packages/compass-components/src/components/document-list/element.tsx
Labels: no-title-validation

#6446 feat(editor): expandable json editor
  packages/compass-crud/src/components/json-editor.tsx
  packages/compass-editor/src/action-button.tsx
  packages/compass-editor/src/actions-container.tsx
  packages/compass-editor/src/editor.tsx
Labels: release notes, feat, no-title-validation

#6453 chore(ci): allow for more numbers in tickets
  .github/workflows/check-pr-title.yml
Labels: no-title-validation

#6445 chore: fix typo in AggregationCopiedEvent description
  packages/compass-telemetry/src/telemetry-events.ts
Labels: no-title-validation

#6459 chore(global-writes): fix subtab container styles
  packages/compass-global-writes/src/components/index.tsx
Labels: no-title-validation

#6408 fix(compass-global-writes): try/catch and show error when global-writes fetch fails COMPASS-8333
  packages/compass-global-writes/src/store/index.spec.ts
  packages/compass-global-writes/src/store/reducer.ts
Labels: fix, no release notes

#6434 feat: Add gen ai org and project settings to Compass for CompassWeb usage COMPASS-8377
  packages/compass-preferences-model/src/compass-web-preferences-access.ts
  packages/compass-preferences-model/src/preferences-schema.ts
  packages/compass-preferences-model/src/preferences.spec.ts
  packages/compass-preferences-model/src/provider.ts
  packages/compass-web/src/entrypoint.tsx
Labels: feat, no release notes

#6465 fix(atlas-service): pass csrf tokens with the requests COMPASS-8490
  packages/atlas-service/src/atlas-service.spec.ts
  packages/atlas-service/src/atlas-service.ts
  packages/compass-web/sandbox/index.tsx
  packages/compass-web/sandbox/sandbox-atlas-sign-in.tsx
  packages/compass-web/scripts/electron-proxy.js
Labels: fix, no release notes

#6447 fix(crud): expandable readonly document COMPASS-4635
  packages/compass-components/src/components/document-list/document.tsx
  packages/compass-components/src/components/document-list/element.tsx
  packages/compass-crud/src/components/readonly-document.tsx
Labels: release notes, fix

#6451 fix(compass-global-writes): handle loading error COMPASS-8446
  packages/compass-global-writes/src/components/index.tsx
  packages/compass-global-writes/src/components/states/loading-error.spec.tsx
  packages/compass-global-writes/src/components/states/loading-error.tsx
  packages/compass-global-writes/src/store/index.spec.ts
  packages/compass-global-writes/src/store/reducer.ts
Labels: fix, no release notes

#6474 chore(deps): bump cross-spawn
  package-lock.json
  packages/compass-e2e-tests/package.json
  packages/compass/package.json
Labels: no-title-validation

#6464 chore(connections): send active and inactive connections with "New Connection" telemetry event COMPASS-8476
  docs/tracking-plan.md
  packages/compass-connections/src/stores/connections-store-redux.ts
  packages/compass-telemetry/src/telemetry-events.ts
Labels: no release notes

#6449 chore(connections-navigation): add connect button to connections in sidebar COMPASS-8381
  packages/compass-components/src/components/item-action-controls.tsx
  packages/compass-connections-navigation/src/base-navigation-item.tsx
  packages/compass-connections-navigation/src/connections-navigation-tree.tsx
  packages/compass-connections-navigation/src/item-actions.ts
  packages/compass-connections-navigation/src/navigation-item.tsx
  packages/compass-e2e-tests/helpers/commands/connect.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
Labels: feat

#6458 feat(sidebar): active connections toggle COMPASS-8114
  packages/compass-components/src/components/icons/connected-plugs.tsx
  packages/compass-components/src/components/icons/disconnected-plug.tsx
  packages/compass-components/src/index.ts
  packages/compass-sidebar/src/components/multiple-connections/connections-navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
  packages/compass-sidebar/src/components/navigation-items-filter.tsx
  packages/compass-sidebar/src/components/use-filtered-connections.spec.ts
  packages/compass-sidebar/src/components/use-filtered-connections.ts
Labels: release notes, feat

#6479 fix(compass-global-writes): make global writes tab not appear for readonly and config/local/admin collections COMPASS-8447
  packages/compass-collection/src/components/collection-tab.tsx
Labels: fix, no release notes

#6486 feat(sidebar): connections filter popover COMPASS-8503
  packages/compass-components/src/components/icons/connected-plugs.tsx
  packages/compass-components/src/components/icons/disconnected-plug.tsx
  packages/compass-components/src/index.ts
  packages/compass-sidebar/src/components/connections-filter-popover.tsx
  packages/compass-sidebar/src/components/multiple-connections/connections-navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
  packages/compass-sidebar/src/components/navigation-items-filter.tsx
  packages/compass-sidebar/src/components/use-filtered-connections.spec.ts
  packages/compass-sidebar/src/components/use-filtered-connections.ts
Labels: release notes, feat

#6491 fix(components): fix incorrect usage of useid
  packages/compass-components/src/components/interactive-popover.tsx
  packages/compass-components/src/hooks/use-sort.spec.ts
  packages/compass-components/src/hooks/use-sort.tsx
Labels: fix, no release notes, no-title-validation

#6475 refactor(compass-global-writes): remove in-progress states
  packages/compass-global-writes/src/components/create-shard-key-form.tsx
  packages/compass-global-writes/src/components/index.spec.tsx
  packages/compass-global-writes/src/components/index.tsx
  packages/compass-global-writes/src/components/states/incomplete-sharding-setup.tsx
  packages/compass-global-writes/src/components/states/shard-key-correct.tsx
  packages/compass-global-writes/src/components/states/shard-key-mismatch.tsx
  packages/compass-global-writes/src/components/states/sharding-error.tsx
  packages/compass-global-writes/src/components/states/sharding.tsx
  packages/compass-global-writes/src/store/index.spec.ts
  packages/compass-global-writes/src/store/index.ts
  packages/compass-global-writes/src/store/reducer.ts
Labels: no release notes, no-title-validation

#6502 Update comment in connections-filter-popover.tsx
  packages/compass-sidebar/src/components/connections-filter-popover.tsx
Labels: no release notes, no-title-validation

#6485 fix(menu): remove accelerators for linux COMPASS-8494
  packages/compass/src/main/menu.spec.ts
  packages/compass/src/main/menu.ts
Labels: release notes, fix

#6500 fix(web, connections): filter out paused clusters; cleanup connections on plugin deactivate COMPASS-8510 CLOUDP-284226
  packages/compass-connections/src/index.spec.tsx
  packages/compass-connections/src/index.tsx
  packages/compass-connections/src/stores/connections-store-redux.ts
  packages/compass-connections/src/stores/connections-store.spec.tsx
  packages/compass-web/src/connection-storage.tsx
Labels: fix, no release notes, no-title-validation

#6498 chore(evergreen): authenticate with docker so that we don't make unauthenticated pulls
  .evergreen/docker-config/bin/docker-credential-from-env
  .evergreen/docker-config/config.json
  .evergreen/functions.yml
  .evergreen/preinstall.sh
  .evergreen/print-compass-env.js
Labels: no release notes, no-title-validation

#6472 fix(compass-global-writes): show error on all invalid statuses COMPASS-8451
  packages/compass-global-writes/src/components/states/shard-key-correct.tsx
  packages/compass-global-writes/src/plugin-title.spec.tsx
  packages/compass-global-writes/src/plugin-title.tsx
Labels: fix, no release notes

#6508 chore(compass-connections): Move connection modal UI from compass-sidebar to compass-connections COMPASS-8471
  package-lock.json
  packages/compass-connections/src/components/connection-modal.tsx
  packages/compass-connections/src/index.tsx
  packages/compass-connections/src/stores/connections-store-redux.ts
  packages/compass-sidebar/package.json
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
  packages/compass-welcome/src/components/welcome-tab.tsx
  packages/compass/src/app/components/home.spec.tsx
  packages/compass/src/app/components/home.tsx
Labels: no release notes

#6517 chore: remove the code that tries to generate the vulnerability report tickets
  .evergreen/functions.yml
  package.json
Labels: no-title-validation

#6516 chore(e2e): fix for rare e2e test flake
  packages/compass-e2e-tests/helpers/commands/hide-visible-toasts.ts
Labels: no-title-validation

#6518 chore(connections): remove single connection ui and hooks COMPASS-8469
  package-lock.json
  packages/compass-connections-navigation/src/sc-connections-navigation-tree.spec.tsx
  packages/compass-connections/package.json
  packages/compass-connections/src/components/atlas-help/atlas-help.tsx
  packages/compass-connections/src/components/connecting/connecting-animation.spec.tsx
  packages/compass-connections/src/components/connecting/connecting-animation.tsx
  packages/compass-connections/src/components/connecting/connecting-background.tsx
  packages/compass-connections/src/components/connecting/connecting-illustration.tsx
  packages/compass-connections/src/components/connecting/connecting.spec.tsx
  packages/compass-connections/src/components/connecting/connecting.tsx
  packages/compass-connections/src/components/connection-list/connection-icon.tsx
  packages/compass-connections/src/components/connection-list/connection-list.spec.tsx
  packages/compass-connections/src/components/connection-list/connection-list.tsx
  packages/compass-connections/src/components/connection-list/connection.spec.tsx
  packages/compass-connections/src/components/connection-list/connection.tsx
  packages/compass-connections/src/components/connection-list/connections-title.tsx
  packages/compass-connections/src/components/form-help/form-help.tsx
  packages/compass-connections/src/components/legacy-connections.spec.tsx
  packages/compass-connections/src/components/legacy-connections.tsx
  packages/compass-connections/src/index.spec.tsx
  packages/compass-connections/src/index.tsx
  packages/compass-connections/src/provider.ts
  packages/compass-connections/src/stores/connections-store-redux.spec.tsx
  packages/compass-connections/src/stores/connections-store-redux.ts
  packages/compass-connections/src/stores/connections-store.tsx
  packages/compass-connections/src/stores/store-context.tsx
  packages/compass/src/app/components/home.tsx
  packages/compass/src/app/components/workspace.tsx
  packages/compass/src/app/index.tsx
  packages/compass/src/main/auto-connect.spec.ts
  packages/compass/src/main/auto-connect.ts
  packages/compass/src/main/menu.spec.ts
  packages/compass/src/main/menu.ts
  packages/compass/src/main/window-manager.ts
Labels: no release notes

#6534 chore(ci): use github app for tokens
  .github/workflows/authors-and-third-party-notices.yaml
  .github/workflows/bump-packages.yaml
  .github/workflows/merge-bump-packages-pr.yaml
  .github/workflows/update-electron.yaml
  CONTRIBUTING.md
Labels: no-title-validation

#6535 fix: avoid global writes for self managed sharding COMPASS-8579
  packages/compass-connections/src/utils/connection-supports.spec.ts
  packages/compass-connections/src/utils/connection-supports.ts
  packages/compass-web/src/connection-storage.spec.ts
  packages/compass-web/src/connection-storage.tsx
  packages/connection-info/src/connection-info.ts
Labels: fix, no release notes

#6536 chore(ci): use the devtools bot user token for PRs
  .github/workflows/bump-packages.yaml
  .github/workflows/update-electron.yaml
Labels: no release notes, no-title-validation

#6539 fix: global writes feature flag COMPAS-8524
  packages/compass-collection/src/components/collection-tab.tsx
  packages/compass-preferences-model/src/feature-flags.ts
  packages/compass-preferences-model/src/preferences-schema.ts
Labels: fix, no release notes
