Repository mongodb-js/compass, pull requests merged in 2024-03, with the labels that each got.

#5509 fix(compass-components): calculate the maximum line length in a more stack efficient way COMPASS-7647
  packages/compass-components/src/components/document-list/document.spec.tsx
  packages/compass-components/src/components/document-list/element-editors.tsx
Labels: release notes, fix

#5511 fix(crud): don't render the Save button if there is no favourite query storage COMPASS-7679
  packages/compass-crud/src/components/bulk-update-modal.spec.tsx
  packages/compass-crud/src/components/bulk-update-modal.tsx
Labels: fix, no release notes

#5491 feat(autoupdates): sync auto updater and menu state COMPASS-7673
  packages/compass/src/main/application.ts
  packages/compass/src/main/auto-update-manager.ts
  packages/compass/src/main/menu.spec.ts
  packages/compass/src/main/menu.ts
Labels: feat, no release notes

#5501 feat(compass-workspace): breadcrumbs COMPASS-7593
  package-lock.json
  packages/compass-collection/src/components/collection-header/collection-header.spec.tsx
  packages/compass-collection/src/components/collection-header/collection-header.tsx
  packages/compass-collection/src/components/collection-stats-item/collection-stats-item.spec.tsx
  packages/compass-collection/src/components/collection-stats-item/collection-stats-item.tsx
  packages/compass-collection/src/components/collection-stats-item/index.ts
  packages/compass-collection/src/components/collection-stats/collection-stats.spec.tsx
  packages/compass-collection/src/components/collection-stats/collection-stats.tsx
  packages/compass-collection/src/components/collection-stats/index.ts
  packages/compass-collection/src/components/collection-tab-stats.tsx
  packages/compass-collection/src/components/collection-tab.tsx
  packages/compass-components/package.json
  packages/compass-components/src/components/breadcrumb.spec.tsx
  packages/compass-components/src/components/breadcrumb.tsx
  packages/compass-components/src/components/tab-nav-bar.spec.tsx
  packages/compass-components/src/components/tab-nav-bar.tsx
  packages/compass-components/src/index.ts
  packages/compass-e2e-tests/helpers/commands/get-active-tab-namespace.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-heading.test.ts
  packages/compass-e2e-tests/tests/collection-import.test.ts
  packages/compass-e2e-tests/tests/collection-rename.test.ts
  packages/compass-e2e-tests/tests/instance-sidebar.test.ts
Labels: release notes, feat

#5530 fix: bump devtools-docker-test-envs
  .evergreen/start-docker-envs.sh
  package-lock.json
  packages/data-service/package.json
Labels: fix, no release notes

#5533 feat(compass-web): disable search indexes via preferences COMPASS-7595
  packages/compass-components/src/components/breadcrumb.tsx
  packages/compass-e2e-tests/tests/search-indexes.test.ts
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.spec.tsx
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
  packages/compass-indexes/src/components/indexes/indexes.tsx
  packages/compass-preferences-model/src/feature-flags.ts
  packages/compass-preferences-model/src/preferences-schema.ts
  packages/compass-web/src/index.tsx
Labels: release notes, feat

#5514 feature: adapt the connection form component to the new design guidelines COMPASS-7652
  package-lock.json
  packages/compass-components/src/index.ts
  packages/connection-form/package.json
  packages/connection-form/src/components/connection-form-actions.tsx
  packages/connection-form/src/components/connection-form.spec.tsx
  packages/connection-form/src/components/connection-form.tsx
  packages/connection-form/src/hooks/use-connect-form.spec.ts
  packages/connection-form/src/hooks/use-connect-form.ts
  packages/connection-form/src/hooks/use-connection-color.spec.tsx
  packages/connection-form/src/hooks/use-connection-color.ts
Labels: feature flagged, no release notes

#5545 fix: clean up package-lock.json by removing mongodb-redux-common
  package-lock.json
Labels: fix, no release notes

#5547 feat(connection-info): setup provider to share current connection info COMPASS-7701
  package-lock.json
  packages/compass-home/src/components/home.tsx
  packages/compass-web/package.json
  packages/compass-web/sandbox/index.tsx
  packages/compass-web/src/index.spec.tsx
  packages/compass-web/src/index.tsx
  packages/connection-info/src/connection-info.ts
  packages/connection-storage/src/provider.ts
Labels: release notes, feat

#5541 feat(compass-web): show performance advisor banner COMPASS-7596
  packages/compass-indexes/src/components/indexes/indexes.tsx
  packages/compass-preferences-model/src/preferences-schema.ts
  packages/compass-schema/src/components/compass-schema.tsx
  packages/compass-schema/src/components/promo-banner.tsx
  packages/compass-web/src/index.tsx
Labels: release notes, feat

#5537 feat(compass-preferences-modal): enable rename collection feature flag (COMPASS-7699)
  packages/compass-preferences-model/src/feature-flags.ts
Labels: release notes, feat

#5549 feat: use atlas metadata for atlas links
  package-lock.json
  packages/compass-indexes/package.json
  packages/compass-indexes/src/components/indexes/indexes.tsx
  packages/compass-indexes/src/utils/atlas-search-indexes-link.spec.ts
  packages/compass-indexes/src/utils/atlas-search-indexes-link.ts
  packages/compass-schema/package.json
  packages/compass-schema/src/components/compass-schema.tsx
  packages/compass-schema/src/utils.spec.ts
  packages/compass-schema/src/utils.ts
  packages/connection-info/src/connection-info.ts
  packages/connection-info/src/index.ts
  packages/connection-storage/src/provider.ts
  packages/connection-storage/src/renderer.ts
Labels: feat, no release notes

#5553 feat(query-bar): remove the filter label/link from the querybar COMPASS-7070
  packages/compass-query-bar/src/components/query-bar.tsx
  packages/compass-query-bar/src/components/query-history-button-popover.tsx
  packages/compass-query-bar/src/components/query-option.tsx
Labels: feat, no release notes

#5561 feat(deps): bump oidc dependencies to latest versions
  package-lock.json
  packages/atlas-service/package.json
  packages/atlas-service/src/main.spec.ts
  packages/compass-e2e-tests/package.json
  packages/data-service/package.json
Labels: release notes, feat

#5559 fix(ci): remove exit commands from the start docker envs script COMPASS-7736
  .evergreen/start-docker-envs.sh
  packages/compass-e2e-tests/.gitignore
  packages/compass-e2e-tests/scripts/write-electron-versions.sh
Labels: fix, no release notes

#5566 fix: review inconsistent behaviours in the connection modal form. COMPASS-7712
  packages/connection-form/src/components/connection-form.tsx
  packages/connection-form/src/hooks/use-connect-form.spec.ts
  packages/connection-form/src/hooks/use-connect-form.ts
Labels: fix, no release notes

#5565 feat: information panels for multiple connections
  packages/compass-connections/src/components/atlas-help/atlas-help.tsx
  packages/compass-connections/src/components/connections.spec.tsx
  packages/compass-connections/src/components/connections.tsx
  packages/compass-connections/src/components/form-help/form-help.tsx
  packages/connection-form/src/components/connection-form.spec.tsx
  packages/connection-form/src/components/connection-form.tsx
  packages/connection-form/src/components/form-help/form-help.tsx
Labels: feature flagged, feat

#5570 fix: don't allow the readonly filter to grow in width indefinitely COMPASS-7728
  packages/compass-crud/src/components/bulk-update-modal.tsx
Labels: release notes, fix

#5578 feat: connection form as a modal COMPASS-7709
  packages/compass-sidebar/src/components/multiple-connections/saved-connections/saved-connection-list.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/saved-connections/saved-connection-list.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
  packages/connection-form/src/components/connection-form-actions.tsx
  packages/connection-form/src/components/connection-form-modal.tsx
  packages/connection-form/src/components/connection-form.spec.tsx
  packages/connection-form/src/components/connection-form.tsx
  packages/connection-form/src/index.ts
Labels: feature flagged, feat

#5582 feat(deps): bump mongosh, driver and bson to latest
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-components/package.json
  packages/compass-crud/package.json
  packages/compass-e2e-tests/package.json
  packages/compass-explain-plan/package.json
  packages/compass-generative-ai/package.json
  packages/compass-home/package.json
  packages/compass-import-export/package.json
  packages/compass-import-export/src/csv/csv-utils.spec.ts
  packages/compass-indexes/package.json
  packages/compass-preferences-model/package.json
  packages/compass-query-bar/package.json
  packages/compass-saved-aggregations-queries/package.json
  packages/compass-schema-validation/package.json
  packages/compass-schema/package.json
  packages/compass-shell/package.json
  packages/compass-shell/src/stores/store.ts
  packages/compass-sidebar/package.json
  packages/compass-web/package.json
  packages/compass-workspaces/package.json
  packages/compass/package.json
  packages/connection-form/package.json
  packages/connection-info/package.json
  packages/connection-storage/package.json
  packages/data-service/package.json
  packages/data-service/src/connect-mongo-client.spec.ts
  packages/databases-collections/package.json
  packages/hadron-document/package.json
  packages/hadron-type-checker/package.json
  packages/mongodb-query-util/package.json
  packages/my-queries-storage/package.json
Labels: release notes, feat

#5567 feat(compass-app-stores): makes CompassInstanceStore initialisation based on the possibility of multiple connections COMPASS-7721
  package-lock.json
  packages/compass-app-stores/package.json
  packages/compass-app-stores/src/plugin.tsx
  packages/compass-app-stores/src/provider.ts
  packages/compass-app-stores/src/stores/index.ts
  packages/compass-app-stores/src/stores/instance-store.spec.ts
  packages/compass-app-stores/src/stores/instance-store.ts
  packages/compass-home/src/components/home.tsx
  packages/compass-web/src/index.tsx
Labels: feat, no release notes

#5597 fix(connection-form): dark mode support for new connection information cards COMPASS-7753
  packages/connection-form/src/components/form-help/form-help.tsx
Labels: fix, no release notes

#5592 fix(compass): set up local mms COMPASS-7767
  packages/compass/src/main/application.ts
Labels: fix, no release notes

#5604 fix(sidebar): add missing dependency
  package-lock.json
  packages/compass-sidebar/package.json
Labels: fix, no release notes

#5601 chore(connection-form): update modal form styles COMPASS-7784
  packages/connection-form/src/components/connection-form.tsx
Labels: feature flagged, fix

#5609 fix(indexes): show the in-progress index in the list again COMPASS-7789
  packages/compass-indexes/src/stores/store.spec.ts
  packages/compass-indexes/src/stores/store.ts
Labels: release notes, fix

#5614 fix(components): fix react warning about missing key prop COMPASS-7788
  packages/compass-components/src/components/breadcrumb.tsx
Labels: fix, no release notes

#5606 feat: update atlas login screen flow COMPASS-7755
  packages/atlas-service/src/atlas-auth-service.ts
  packages/atlas-service/src/compass-atlas-auth-service.spec.ts
  packages/atlas-service/src/compass-atlas-auth-service.ts
  packages/atlas-service/src/components/ai-signin-modal.tsx
  packages/atlas-service/src/main.spec.ts
  packages/atlas-service/src/main.ts
  packages/atlas-service/src/oidc-plugin-logger.ts
  packages/atlas-service/src/renderer.ts
  packages/atlas-service/src/store/atlas-signin-reducer.ts
  packages/atlas-service/src/store/atlas-signin-store.ts
  packages/atlas-service/src/user-config-store.spec.ts
  packages/atlas-service/src/user-config-store.ts
  packages/atlas-service/src/util.ts
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-ai.spec.tsx
  packages/compass-aggregations/src/modules/pipeline-builder/pipeline-ai.ts
  packages/compass-aggregations/src/stores/store.ts
  packages/compass-aggregations/test/configure-store.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/atlas-login.test.ts
  packages/compass-generative-ai/src/atlas-ai-service.spec.ts
  packages/compass-generative-ai/src/atlas-ai-service.ts
  packages/compass-generative-ai/src/components/ai-opt-in-confirmation.tsx
  packages/compass-query-bar/src/stores/ai-query-reducer.ts
  packages/compass-query-bar/src/stores/query-bar-store.ts
  packages/compass-settings/src/components/settings/atlas-login.spec.tsx
  packages/compass-settings/src/components/settings/atlas-login.tsx
  packages/compass-settings/src/stores/atlas-login.ts
  packages/compass-settings/src/stores/index.ts
  packages/compass-settings/test/configure-store.ts
  packages/compass-web/src/index.tsx
Labels: release notes, feat

#5596 fix(compass-collections): fix onclick for collection stats COMPASS-7774
  packages/compass-collection/src/components/collection-tab-stats.tsx
  packages/compass-web/sandbox/index.tsx
Labels: fix, no release notes

#5568 feat(workspaces): handle collection sub tab from the link COMPASS-7731
  package-lock.json
  packages/compass-aggregations/src/index.ts
  packages/compass-collection/src/components/collection-tab-provider.tsx
  packages/compass-collection/src/components/collection-tab.tsx
  packages/compass-collection/src/index.ts
  packages/compass-collection/src/modules/collection-tab.ts
  packages/compass-collection/src/stores/collection-tab.spec.ts
  packages/compass-collection/src/stores/collection-tab.ts
  packages/compass-crud/src/index.ts
  packages/compass-indexes/src/index.ts
  packages/compass-schema-validation/src/index.ts
  packages/compass-schema/src/index.ts
  packages/compass-web/sandbox/index.tsx
  packages/compass-workspaces/src/components/workspaces.tsx
  packages/compass-workspaces/src/index.ts
  packages/compass-workspaces/src/provider.tsx
  packages/compass-workspaces/src/stores/workspaces.spec.ts
  packages/compass-workspaces/src/stores/workspaces.ts
  packages/compass-workspaces/src/types.ts
Labels: release notes, feat

#5617 fix: can not sign out if not signed in yet COMPASS-7787
  packages/atlas-service/src/store/atlas-signin-store.ts
  packages/compass-e2e-tests/tests/atlas-login.test.ts
  packages/compass-settings/src/stores/atlas-login.ts
Labels: release notes, fix

#5593 feat: show list of active connections COMPASS-7654
  package-lock.json
  packages/compass-connections/.prettierignore
  packages/compass-connections/package.json
  packages/compass-connections/src/provider.ts
  packages/compass-connections/src/stores/active-connections.spec.ts
  packages/compass-connections/src/stores/active-connections.ts
  packages/compass-sidebar/package.json
  packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-list.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-list.tsx
  packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection.tsx
  packages/compass-sidebar/src/components/multiple-connections/icons/server-icon.tsx
  packages/compass-sidebar/src/components/multiple-connections/open-connections/open-connection-list.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
Labels: feature flagged, feat

#5627 fix(ci): provide an id for create pr step in update authors task
  .github/workflows/authors-and-third-party-notices.yaml
Labels: fix, no release notes
