Repository mongodb-js/compass, pull requests merged in 2024-12, with the labels that each got.

#6542 fix: send a nonce in oidc request by default COMPASS-8588
  package-lock.json
  packages/atlas-service/package.json
  packages/atlas-service/src/main.spec.ts
  packages/compass-e2e-tests/package.json
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.spec.tsx
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-oidc.tsx
  packages/data-service/package.json
Labels: release notes, fix

#6540 chore(ci): do not run atlas cloud tests on PRs
  .evergreen/buildvariants-and-tasks.in.yml
  .evergreen/buildvariants-and-tasks.yml
Labels: no-title-validation

#6541 fix(compass-components): don't cut off list view value editor tooltips COMPASS-8581
  packages/compass-components/src/components/document-list/element-editors.tsx
Labels: release notes, fix

#6549 chore(ci): revert "use the devtools bot user token for PRs"
  .github/workflows/bump-packages.yaml
  .github/workflows/update-electron.yaml
Labels: no release notes, no-title-validation

#6495 chore(components): refactor `InteractivePopover` to take a type argument for the trigger element
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.tsx
  packages/compass-components/src/components/interactive-popover.tsx
  packages/compass-components/src/components/signal-popover.tsx
  packages/compass-query-bar/src/components/query-history-button-popover.tsx
  packages/compass-sidebar/src/components/connections-filter-popover.tsx
Labels: no-title-validation

#6499 chore(connections-navigation): disable sidebar right-caret on disconnected connections
  packages/compass-connections-navigation/src/base-navigation-item.tsx
  packages/compass-connections-navigation/src/navigation-item.tsx
  packages/compass-connections-navigation/src/tree-item.tsx
Labels: no release notes, no-title-validation

#6543 chore(deps): bump shell to 2.3.4 COMPASS-8577
  package-lock.json
  packages/bson-transpilers/package.json
  packages/compass-aggregations/package.json
  packages/compass-components/package.json
  packages/compass-connections/package.json
  packages/compass-crud/package.json
  packages/compass-e2e-tests/package.json
  packages/compass-explain-plan/package.json
  packages/compass-generative-ai/package.json
  packages/compass-import-export/package.json
  packages/compass-indexes/package.json
  packages/compass-preferences-model/package.json
  packages/compass-query-bar/package.json
  packages/compass-saved-aggregations-queries/package.json
  packages/compass-schema-validation/package.json
  packages/compass-schema/package.json
  packages/compass-shell/package.json
  packages/compass-sidebar/package.json
  packages/compass-web/package.json
  packages/compass-workspaces/package.json
  packages/compass/package.json
  packages/compass/src/main/validate-connection-string.ts
  packages/connection-form/package.json
  packages/connection-info/package.json
  packages/connection-storage/package.json
  packages/data-service/package.json
  packages/databases-collections/package.json
  packages/hadron-document/package.json
  packages/hadron-type-checker/package.json
  packages/mongodb-query-util/package.json
  packages/my-queries-storage/package.json
Labels: no-title-validation

#6550 fix(connections-navigation): don't show connect button while connecting COMPASS-8599
  packages/compass-connections-navigation/src/connections-navigation-tree.tsx
  packages/compass-connections-navigation/src/item-actions.ts
Labels: fix, no release notes

#6551 chore(compass-components): small editorial fixes for FileInput
  packages/compass-components/src/components/file-input.spec.tsx
  packages/compass-components/src/components/file-input.tsx
  packages/compass-e2e-tests/helpers/commands/connect-form.ts
Labels: no-title-validation

#6548 fix(components): fix element key editor tooltip and revert not updating validity COMPASS-8586
  packages/compass-components/src/components/document-list/element-editors.tsx
  packages/compass-components/src/components/document-list/element.tsx
Labels: release notes, fix

#6557 fix(crud): don't fallback to zero if the count cannot be determined
  packages/compass-crud/src/stores/crud-store.ts
Labels: release notes, fix, no-title-validation

#6552 chore(compass-components): refactor `ItemActionControls`
  packages/compass-components/src/components/actions/action-glyph.tsx
  packages/compass-components/src/components/actions/constants.tsx
  packages/compass-components/src/components/actions/dropdown-menu-button.tsx
  packages/compass-components/src/components/actions/item-action-button.tsx
  packages/compass-components/src/components/actions/item-action-controls.spec.tsx
  packages/compass-components/src/components/actions/item-action-controls.tsx
  packages/compass-components/src/components/actions/item-action-group.tsx
  packages/compass-components/src/components/actions/item-action-menu.tsx
  packages/compass-components/src/components/actions/small-icon-button.tsx
  packages/compass-components/src/components/actions/types.ts
  packages/compass-components/src/components/actions/utils.ts
  packages/compass-components/src/components/item-action-controls.tsx
  packages/compass-components/src/index.ts
  packages/compass-connections-navigation/src/connect-button.tsx
  packages/compass-connections-navigation/src/item-actions.ts
  packages/compass-connections-navigation/src/navigation-item.tsx
Labels: no-title-validation

#6558 fix(e2e): actually test the packaged app when running npm run test-packaged
  packages/compass-e2e-tests/helpers/test-runner-context.ts
  packages/compass-e2e-tests/package.json
Labels: fix, no release notes, no-title-validation

#6566 fix(e2e): add the webdriverclassic option to the atlas cloud login window remote session
  packages/compass-e2e-tests/helpers/compass-web-sandbox.ts
Labels: fix, no release notes, no-title-validation

#6546 chore(ci): do not apply 'skip actions' to automatically generated commit
  .github/workflows/authors-and-third-party-notices.yaml
Labels: no-title-validation

#6564 fix(generative-ai): when opted-in and the project setting is disabled show opt in COMPASS-8681
  packages/compass-generative-ai/src/store/atlas-optin-reducer.spec.ts
  packages/compass-generative-ai/src/store/atlas-optin-reducer.ts
Labels: fix, no release notes

#6553 fix(serverstats): update top chart write lock percentage of load visual COMPASS-8604
  packages/compass-serverstats/src/components/top-component.jsx
  packages/compass-serverstats/src/stores/top-store.js
Labels: release notes, fix

#6538 fix(compass-shell): Don't lose the isOperationInProgress state when the user switches tabs, bump mongosh to 2.3.6 COMPASS-8576 COMPASS-8689
  package-lock.json
  packages/compass-shell/package.json
  packages/compass-shell/src/components/compass-shell/compass-shell.spec.tsx
  packages/compass-shell/src/components/compass-shell/compass-shell.tsx
  packages/compass-shell/src/components/compass-shell/index.ts
  packages/compass-shell/src/components/compass-shell/tab-compass-shell.tsx
  packages/compass-shell/src/plugin.tsx
  packages/compass/package.json
  packages/compass/webpack.config.js
Labels: release notes, fix

#6572 chore(aggregations): Refactor aggregations stage toolbar
  packages/compass-aggregations/src/components/stage-toolbar/option-menu-item.tsx
  packages/compass-aggregations/src/components/stage-toolbar/option-menu.tsx
  packages/compass-components/src/components/workspace-tabs/tab.tsx
  packages/compass-components/src/components/workspace-tabs/workspace-tabs.tsx
  packages/compass-components/src/index.ts
  packages/compass-editor/src/action-button.tsx
  packages/databases-collections-list/src/namespace-card.tsx
Labels: no-title-validation

#6574 chore(deps): bump mongosh 2.3.7
  package-lock.json
  packages/compass-shell/package.json
  packages/compass/package.json
Labels: no-title-validation

#6571 feat(e2e): Smoke tests task & initial entrypoint COMPASS-8531
  .evergreen/buildvariants-and-tasks.in.yml
  .evergreen/buildvariants-and-tasks.yml
  .evergreen/functions.yml
  .evergreen/preinstall.sh
  packages/compass-e2e-tests/.gitignore
  packages/compass-e2e-tests/package.json
  packages/compass-e2e-tests/smoke-test.ts
  packages/compass-e2e-tests/tsconfig.json
  packages/hadron-build/commands/download.d.ts
  packages/hadron-build/commands/download.js
  packages/hadron-build/commands/info.d.ts
Labels: feat, no release notes

#6560 chore(compass-components): refactor `ItemActionControls` #2
  packages/compass-components/src/components/actions/dropdown-menu-button.tsx
  packages/compass-components/src/components/actions/item-action-button.tsx
  packages/compass-components/src/components/actions/item-action-controls.spec.tsx
  packages/compass-components/src/components/actions/item-action-controls.tsx
  packages/compass-components/src/components/actions/item-action-group.tsx
  packages/compass-components/src/components/actions/item-action-menu.tsx
  packages/compass-components/src/components/actions/utils.ts
  packages/compass-connections-navigation/src/base-navigation-item.tsx
  packages/compass-connections-navigation/src/connect-button.tsx
  packages/compass-connections-navigation/src/constants.tsx
  packages/compass-connections-navigation/src/item-actions.ts
  packages/compass-connections-navigation/src/navigation-item.tsx
Labels: no release notes, no-title-validation

#6582 feat(e2e): smoketest macOS .dmg files COMPASS-8709
  .evergreen/buildvariants-and-tasks.in.yml
  .evergreen/buildvariants-and-tasks.yml
  .evergreen/functions.yml
  packages/compass-e2e-tests/.prettierignore
  packages/compass-e2e-tests/helpers/chrome-startup-flags.ts
  packages/compass-e2e-tests/helpers/compass.ts
  packages/compass-e2e-tests/installers/helpers.ts
  packages/compass-e2e-tests/installers/mac-dmg.ts
  packages/compass-e2e-tests/installers/types.ts
  packages/compass-e2e-tests/smoke-test.ts
Labels: feat, no release notes

#6583 feat(autoupdate): allow setting the autoUpdate endpoint with process.env.HADRON_AUTO_UPDATE_ENDPOINT_OVERRIDE COMPASS-8534
  packages/compass/src/index.d.ts
  packages/compass/src/main/auto-update-manager.ts
Labels: feat, no release notes
