Repository mongodb-js/compass, pull requests merged in 2024-04, with the labels that each got.

#5621 chore(compass): move compass home to compass COMPASS-7433
  README.md
  package-lock.json
  packages/compass-home/.browserslistrc
  packages/compass-home/.depcheckrc
  packages/compass-home/.editorconfig
  packages/compass-home/.eslintignore
  packages/compass-home/.eslintrc.js
  packages/compass-home/.gitignore
  packages/compass-home/.mocharc.js
  packages/compass-home/.npmignore
  packages/compass-home/.nycrc
  packages/compass-home/.prettierignore
  packages/compass-home/.prettierrc.json
  packages/compass-home/README.md
  packages/compass-home/package.json
  packages/compass-home/src/components/index.ts
  packages/compass-home/src/index.spec.tsx
  packages/compass-home/src/index.ts
  packages/compass-home/tsconfig-lint.json
  packages/compass-home/tsconfig.json
  packages/compass-settings/src/stores/index.ts
  packages/compass-web/src/entrypoint.spec.tsx
  packages/compass-web/src/entrypoint.tsx
  packages/compass-web/src/index.tsx
  packages/compass-welcome/src/components/modal.tsx
  packages/compass/package.json
  packages/compass/src/app/components/entrypoint.tsx
  packages/compass/src/app/components/home.spec.tsx
  packages/compass/src/app/components/home.tsx
  packages/compass/src/app/components/restart-compass-toast-content.tsx
  packages/compass/src/app/components/workspace.tsx
  packages/compass/src/app/index.tsx
  packages/compass/src/app/utils/auto-connect.spec.ts
  packages/compass/src/app/utils/auto-connect.ts
  packages/compass/src/app/utils/csp.ts
  packages/compass/src/app/utils/telemetry.spec.ts
  packages/compass/src/app/utils/telemetry.ts
  packages/compass/src/app/utils/update-handlers.ts
  packages/compass/src/app/utils/update-title.ts
  scripts/generate-readme-packages-overview.js
Labels: release notes

#5649 fix(settings): listen to compass open settings app registry event COMPASS-7817
  packages/compass-settings/src/stores/index.ts
Labels: fix, no release notes

#5588 feat(compass-components): z-indexed stacked components COMPASS-7732
  packages/compass-components/src/components/combobox/ComboboxMenu/ComboboxMenu.tsx
  packages/compass-components/src/components/combobox/index.ts
  packages/compass-components/src/components/compass-components-provider.tsx
  packages/compass-components/src/components/feedback-popover.tsx
  packages/compass-components/src/components/guide-cue/guide-cue.tsx
  packages/compass-components/src/components/leafygreen.tsx
  packages/compass-components/src/components/modals/confirmation-modal.tsx
  packages/compass-components/src/components/modals/modal.tsx
  packages/compass-components/src/components/tooltip.tsx
  packages/compass-components/src/hooks/use-confirmation.tsx
  packages/compass-components/src/hooks/use-stacked-component.spec.tsx
  packages/compass-components/src/hooks/use-stacked-component.tsx
  packages/compass-components/src/hooks/use-toast.tsx
  packages/compass-web/sandbox/index.tsx
  packages/compass-web/src/entrypoint.tsx
Labels: release notes, feat

#5632 fix(compass-aggregations): remove space on toolbar
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/index.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-stages.tsx
Labels: fix, no release notes

#5637 fix(serverstats): click current op for details scoping error COMPASS-7805
  packages/compass-serverstats/src/components/current-op-component.jsx
Labels: release notes, fix

#5625 feat(compass-connections): introduce ConnectionScopedAppRegistry for emitting app registry events with connected connection info COMPASS-7723
  packages/compass-connections/src/connection-scoped-app-registry.spec.ts
  packages/compass-connections/src/connection-scoped-app-registry.ts
  packages/compass-connections/src/provider.ts
  packages/connection-storage/src/provider.ts
Labels: feat, no release notes

#5645 feat(sidebar): remove collapsing/expanding the sidebar COMPASS-7812
  packages/compass-components/src/components/resizeable-sidebar.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
  packages/compass-sidebar/src/components/navigation-items.spec.tsx
  packages/compass-sidebar/src/components/navigation-items.tsx
  packages/compass-sidebar/src/components/sidebar-title.tsx
  packages/compass-sidebar/src/components/sidebar.tsx
  packages/compass-sidebar/src/modules/index.ts
  packages/compass-sidebar/src/modules/is-expanded.ts
  packages/compass-sidebar/src/stores/store.ts
  packages/compass/src/app/index.tsx
  packages/compass/src/main/menu.spec.ts
  packages/compass/src/main/menu.ts
Labels: release notes, feat

#5633 feat: update the “Use Generative AI” settings flow COMPASS-7756
  packages/atlas-service/src/components/ai-signin-modal.tsx
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/atlas-login.test.ts
  packages/compass-preferences-model/src/preferences-schema.ts
  packages/compass-preferences-model/src/provider.ts
  packages/compass-preferences-model/src/utils.ts
  packages/compass-settings/src/components/modal.tsx
  packages/compass-settings/src/components/settings/atlas-login.spec.tsx
  packages/compass-settings/src/components/settings/atlas-login.tsx
  packages/compass-settings/src/components/settings/feature-preview.tsx
  packages/compass-settings/src/components/settings/gen-ai-settings.tsx
  packages/compass-settings/src/components/settings/privacy.spec.tsx
  packages/compass-settings/src/components/settings/privacy.tsx
  packages/compass-settings/src/components/settings/settings-list.tsx
Labels: release notes, feat

#5644 feat(compass-field-store): makes FieldStorePlugin aware of multiple connections and remove dependency on events for updating the store COMPASS-7722
  package-lock.json
  packages/compass-aggregations/README.md
  packages/compass-connections/src/provider.ts
  packages/compass-crud/README.md
  packages/compass-crud/src/index.ts
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-field-store/package.json
  packages/compass-field-store/src/index.spec.ts
  packages/compass-field-store/src/index.tsx
  packages/compass-field-store/src/modules/index.ts
  packages/compass-field-store/src/stores/context.ts
  packages/compass-field-store/src/stores/field-store-service.ts
  packages/compass-field-store/src/stores/hooks.ts
  packages/compass-field-store/src/stores/store.spec.ts
  packages/compass-field-store/src/stores/store.ts
  packages/compass-schema/package.json
  packages/compass-schema/src/index.ts
  packages/compass-schema/src/stores/store.spec.ts
  packages/compass-schema/src/stores/store.ts
  packages/compass/src/app/components/home.tsx
  packages/connection-storage/src/provider.ts
Labels: feat, no release notes

#5669 feat(compass-app-stores): introduce MongoDBInstancesManager for supporting workspace initialisation without DataService / MongoDBInstance COMPASS-7718
  packages/compass-app-stores/src/instances-manager.spec.ts
  packages/compass-app-stores/src/instances-manager.ts
  packages/compass-app-stores/src/plugin.tsx
  packages/compass-app-stores/src/provider.ts
  packages/compass-app-stores/src/stores/instance-store.spec.ts
  packages/compass-app-stores/src/stores/instance-store.ts
Labels: feat, no release notes

#5676 fix(components): make sure that confirmation modal always asks for confirmation input COMPASS-7613
  packages/compass-components/src/hooks/use-confirmation.spec.tsx
  packages/compass-components/src/hooks/use-confirmation.tsx
Labels: release notes, fix

#5680 feat(compass-sidebar): add settings btn to multi-connections sidebar COMPASS-7726
  packages/compass-sidebar/src/components/legacy/favorite-indicator.tsx
  packages/compass-sidebar/src/components/legacy/sidebar-title.tsx
  packages/compass-sidebar/src/components/legacy/sidebar.tsx
  packages/compass-sidebar/src/components/multiple-connections/header/sidebar-header.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
  packages/compass-sidebar/src/plugin.tsx
Labels: feature flagged, feat

#5682 feat(compass-sidebar): add My queries to the multi-connections sidebar COMPASS-7726
  packages/compass-sidebar/src/components/multiple-connections/navigation/navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
Labels: feature flagged, feat

#5666 feat(query-bar): allow to specify hints COMPASS-7829
  packages/compass-query-bar/src/components/query-bar.spec.tsx
  packages/compass-query-bar/src/components/query-bar.tsx
  packages/compass-query-bar/src/components/query-option.tsx
  packages/compass-query-bar/src/constants/query-bar-store.ts
  packages/compass-query-bar/src/constants/query-option-definition.ts
  packages/compass-query-bar/src/constants/query-properties.ts
  packages/compass-query-bar/src/stores/query-bar-reducer.spec.ts
  packages/compass-query-bar/src/utils/query.ts
Labels: release notes, feat

#5693 feat!(deps): bump electron to 29 COMPASS-7868
  .evergreen/buildvariants.yml
  .evergreen/config.json
  .evergreen/verify-artifacts.sh
  configs/webpack-config-compass/package.json
  package-lock.json
  packages/atlas-service/package.json
  packages/compass-crud/package.json
  packages/compass-e2e-tests/package.json
  packages/compass-explain-plan/package.json
  packages/compass-find-in-page/package.json
  packages/compass-import-export/package.json
  packages/compass-indexes/package.json
  packages/compass-query-bar/package.json
  packages/compass-schema-validation/package.json
  packages/compass-shell/package.json
  packages/compass-sidebar/package.json
  packages/compass-utils/package.json
  packages/compass-web/package.json
  packages/compass/package.json
  packages/compass/scripts/download-csfle.js
  packages/connection-storage/package.json
  packages/hadron-build/commands/upload.js
  packages/hadron-build/package.json
  packages/hadron-build/test/upload.test.js
  packages/hadron-ipc/package.json
  scripts/package.json
Labels: fix

#5678 feat(connections): nice error message when connecting to Stream Processing COMPASS-7809
  packages/compass-connections/src/connections-manager.spec.ts
  packages/compass-connections/src/connections-manager.ts
Labels: release notes, feat

#5683 feat(compass-aggregations): warn users when generated aggregation contains a write operation COMPASS-7298
  packages/compass-aggregations/src/modules/aggregation.ts
  packages/compass-aggregations/src/modules/data-service.ts
  packages/compass-aggregations/src/modules/index.ts
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.spec.ts
  packages/compass-aggregations/src/utils/modal-descriptions.tsx
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
  packages/instance-model/index.d.ts
Labels: release notes, feat

#5704 fix(generative-ai): parse ai response correctly COMPASS-7780
  packages/atlas-service/src/atlas-service.ts
  packages/compass-generative-ai/src/atlas-ai-service.spec.ts
  packages/compass-generative-ai/src/atlas-ai-service.ts
Labels: fix

#5700 fix(generative-ai): pass EJSON of sample field values in ai request COMPASS-7865
  package-lock.json
  packages/compass-generative-ai/package.json
  packages/compass-generative-ai/src/atlas-ai-service.spec.ts
  packages/compass-generative-ai/src/atlas-ai-service.ts
Labels: fix, no release notes

#5706 chore(bulk-operations): remove bulk features feature-flags COMPASS-7343 COMPASS-7344
  packages/compass-crud/src/components/crud-toolbar.spec.tsx
  packages/compass-crud/src/components/delete-data-menu.tsx
  packages/compass-crud/src/components/update-data-menu.tsx
  packages/compass-e2e-tests/tests/collection-bulk-delete.test.ts
  packages/compass-e2e-tests/tests/collection-bulk-update.test.ts
  packages/compass-preferences-model/src/feature-flags.ts
Labels: no release notes

#5710 chore: adapt RenameCollectionPlugin to receive the relevant dataservice when opened COMPASS-7864
  package-lock.json
  packages/compass-connections-navigation/src/connections-navigation-tree.tsx
  packages/compass-sidebar/src/components/legacy/sidebar-databases-navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.tsx
  packages/databases-collections/src/components/rename-collection-modal/rename-collection-modal.spec.tsx
  packages/databases-collections/src/index.ts
  packages/databases-collections/src/modules/rename-collection/rename-collection.spec.ts
  packages/databases-collections/src/modules/rename-collection/rename-collection.ts
  packages/databases-collections/src/stores/rename-collection.spec.tsx
  packages/databases-collections/src/stores/rename-collection.ts
Labels: feature flagged

#5707 feat(compass-connections-navigation, compass-sidebar): active connection actions (part 1)
  packages/compass-connections-navigation/src/connection-item.tsx
  packages/compass-connections-navigation/src/connections-navigation-tree.spec.tsx
  packages/compass-connections-navigation/src/connections-navigation-tree.tsx
  packages/compass-connections-navigation/src/constants.tsx
  packages/compass-sidebar/src/components/connection-info-modal.tsx
  packages/compass-sidebar/src/components/legacy/sidebar.tsx
  packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
Labels: feature flagged, feat

#5667 feat(compass-workspaces): adapt WorkspacePlugin to support tabs with multiple DataServices COMPASS-7718
  packages/compass-aggregations/src/index.ts
  packages/compass-aggregations/src/modules/create-view/index.ts
  packages/compass-aggregations/src/modules/index.ts
  packages/compass-aggregations/src/modules/out-results-fn.ts
  packages/compass-aggregations/src/modules/pipeline-builder/stage-editor.spec.ts
  packages/compass-aggregations/src/modules/update-view.spec.ts
  packages/compass-aggregations/src/modules/update-view.ts
  packages/compass-aggregations/src/stores/create-view.spec.ts
  packages/compass-aggregations/src/stores/create-view.ts
  packages/compass-aggregations/src/stores/store.ts
  packages/compass-aggregations/test/configure-store.ts
  packages/compass-collection/src/components/collection-header-actions/collection-header-actions.spec.tsx
  packages/compass-collection/src/components/collection-header-actions/collection-header-actions.tsx
  packages/compass-collection/src/components/collection-header/collection-header.spec.tsx
  packages/compass-collection/src/components/collection-header/collection-header.tsx
  packages/compass-import-export/src/index.ts
  packages/compass-import-export/src/modules/import.ts
  packages/compass-import-export/src/stores/import-store.ts
  packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.tsx
  packages/compass-saved-aggregations-queries/src/index.ts
  packages/compass-saved-aggregations-queries/src/stores/index.ts
  packages/compass-saved-aggregations-queries/src/stores/open-item.ts
  packages/compass-sidebar/src/components/legacy/navigation-items.tsx
  packages/compass-sidebar/src/components/legacy/sidebar-databases-navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.tsx
  packages/compass-sidebar/src/index.ts
  packages/compass-sidebar/src/plugin.tsx
  packages/compass-sidebar/src/stores/store.spec.ts
  packages/compass-sidebar/src/stores/store.ts
  packages/compass-web/sandbox/index.tsx
  packages/compass-web/sandbox/use-workspace-tab-router.tsx
  packages/compass-web/src/entrypoint.tsx
  packages/compass-workspaces/src/components/index.tsx
  packages/compass-workspaces/src/components/workspaces.tsx
  packages/compass-workspaces/src/index.spec.tsx
  packages/compass-workspaces/src/index.ts
  packages/compass-workspaces/src/provider.tsx
  packages/compass-workspaces/src/stores/workspaces.spec.ts
  packages/compass-workspaces/src/stores/workspaces.ts
  packages/compass-workspaces/src/types.ts
  packages/compass/src/app/components/home.spec.tsx
  packages/compass/src/app/components/home.tsx
  packages/compass/src/app/components/workspace.tsx
  packages/databases-collections/src/components/collections.tsx
  packages/databases-collections/src/components/databases.tsx
  packages/databases-collections/src/index.ts
  packages/databases-collections/src/modules/create-namespace.ts
  packages/databases-collections/src/modules/rename-collection/rename-collection.spec.ts
  packages/databases-collections/src/stores/create-namespace.spec.tsx
  packages/databases-collections/src/stores/create-namespace.ts
Labels: feat, no release notes

#5735 fix: make js files executable again
  configs/webpack-config-compass/bin/webpack.js
  packages/hadron-build/cli.js
Labels: no release notes

#5730 chore: add connection name to breadcrumbs COMPASS-7684
  packages/compass-collection/package.json
  packages/compass-collection/src/components/collection-header/collection-header.spec.tsx
  packages/compass-collection/src/components/collection-header/collection-header.tsx
  packages/databases-collections-list/src/collections.tsx
  packages/databases-collections-list/src/index.spec.tsx
  packages/databases-collections/package.json
  packages/databases-collections/src/components/collections.tsx
Labels: feat, no release notes

#5720 feat(auto-updates): add support to notify users for an update on linux/msi COMPASS-7686
  packages/compass-components/src/hooks/use-toast.tsx
  packages/compass/src/app/components/home.spec.tsx
  packages/compass/src/app/components/update-toasts.tsx
  packages/compass/src/app/index.tsx
  packages/compass/src/main/auto-update-manager.spec.ts
  packages/compass/src/main/auto-update-manager.ts
  packages/compass/src/main/auto-updater.ts
  packages/compass/src/main/menu.ts
Labels: release notes, feat

#5740 fix(compass-connections): fixes CPU hikes because of bad useEffect dependency
  packages/compass-connections/src/components/legacy-connections-modal.tsx
Labels: release notes, fix

#5734 fix(compass-connections-navigation, compass-sidebar): connection items workspace behaviour COMPASS-7880
  package-lock.json
  packages/compass-connections-navigation/package.json
  packages/compass-connections-navigation/src/connections-navigation-tree.spec.tsx
  packages/compass-connections-navigation/src/connections-navigation-tree.tsx
  packages/compass-connections-navigation/src/sc-connections-navigation-tree.spec.tsx
  packages/compass-sidebar/src/components/legacy/navigation-items.spec.tsx
  packages/compass-sidebar/src/components/legacy/navigation-items.tsx
  packages/compass-sidebar/src/components/legacy/sidebar-databases-navigation.tsx
  packages/compass-sidebar/src/components/legacy/sidebar.tsx
  packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
  packages/compass-sidebar/src/modules/instance.ts
Labels: feature flagged, fix

#5738 feat(generative-ai): add gradient while a generate request is in progress COMPASS-7836
  packages/compass-generative-ai/src/components/generative-ai-input.tsx
Labels: release notes, feat

#5659 feat(import): include the error count in the import toast COMPASS-7826
  packages/compass-e2e-tests/tests/collection-import.test.ts
  packages/compass-import-export/src/components/import-toast.tsx
  packages/compass-import-export/src/import/import-csv.spec.ts
  packages/compass-import-export/src/import/import-csv.ts
  packages/compass-import-export/src/import/import-json.spec.ts
  packages/compass-import-export/src/import/import-json.ts
  packages/compass-import-export/src/import/import-types.ts
  packages/compass-import-export/src/import/import-utils.ts
  packages/compass-import-export/src/modules/import.ts
  packages/compass-import-export/src/utils/collection-stream.ts
Labels: release notes, feat

#5749 feat: remove the Preview badge COMPASS-7890
  packages/atlas-service/src/components/ai-signin-modal.tsx
  packages/compass-settings/src/components/settings/settings-list.tsx
Labels: release notes, feat

#5696 fix: new colors for multi-connection sidebar COMPASS-7844
  packages/compass-components/src/components/placeholder.tsx
  packages/compass-components/src/components/resizeable-sidebar.tsx
  packages/compass-components/src/components/workspace-tabs/tab.tsx
  packages/compass-components/src/components/workspace-tabs/workspace-tabs.tsx
  packages/compass-components/src/index.ts
  packages/compass-connections-navigation/package.json
  packages/compass-connections-navigation/src/connections-navigation-tree.spec.tsx
  packages/compass-connections-navigation/src/connections-navigation-tree.tsx
  packages/compass-connections-navigation/src/constants.tsx
  packages/compass-connections-navigation/src/placeholder-item.tsx
  packages/compass-connections-navigation/src/styled-navigation-item.tsx
  packages/compass-connections-navigation/src/tree-item.tsx
  packages/compass-connections-navigation/src/utils.ts
  packages/compass-connections/src/hooks/use-tab-connection-theme.spec.ts
  packages/compass-connections/src/hooks/use-tab-connection-theme.ts
  packages/compass-connections/src/provider.ts
  packages/compass-sidebar/src/components/legacy/sidebar.tsx
  packages/compass-sidebar/src/components/multiple-connections/navigation/navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/saved-connections/saved-connection.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
  packages/compass-workspaces/src/components/workspaces.tsx
  packages/compass-workspaces/src/stores/workspaces.ts
  packages/connection-form/src/hooks/use-connection-color.ts
  packages/connection-form/src/index.ts
Labels: feature flagged, fix

#5756 feat: disable the query bar controls while GenAI is running COMPASS-7839
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.spec.tsx
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-header/pipeline-actions.tsx
  packages/compass-query-bar/src/components/option-editor.tsx
  packages/compass-query-bar/src/components/query-bar-row.tsx
  packages/compass-query-bar/src/components/query-bar.spec.tsx
  packages/compass-query-bar/src/components/query-bar.tsx
  packages/compass-query-bar/src/components/query-option.tsx
Labels: release notes, feat
