Repository mongodb-js/compass, pull requests merged in 2024-05, with the labels that each got.

#5765 fix(compass-sidebar): isPerformanceTabSupported check in legacy sidebar COMPASS-7900
  packages/compass-sidebar/src/components/legacy/navigation-items.tsx
Labels: fix, no release notes

#5770 feat(ci): add SBOM file to release artifacts
  .evergreen/compass_package.sh
  .evergreen/create-sbom.sh
  .evergreen/functions.yml
  package-lock.json
  packages/compass/package.json
  packages/compass/scripts/download-csfle.js
Labels: feat, no release notes

#5764 fix: performance action COMPASS-7873
  packages/compass-components/src/components/item-action-controls.tsx
  packages/compass-connections-navigation/src/connection-item.tsx
  packages/compass-connections-navigation/src/connections-navigation-tree.tsx
  packages/compass-sidebar/src/components/legacy/sidebar-databases-navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.tsx
Labels: feature flagged, fix

#5751 feat: disconnect action COMPASS-7874
  package-lock.json
  packages/compass-connections/src/connection-info-provider.tsx
  packages/compass-connections/src/connections-manager.ts
  packages/compass-connections/src/stores/connections-store.ts
  packages/compass-shell/src/plugin.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
  packages/compass-workspaces/src/index.ts
  packages/compass-workspaces/src/stores/workspaces.spec.ts
  packages/compass-workspaces/src/stores/workspaces.ts
Labels: feature flagged, feat

#5768 fix(auto-updates): only show toast when user updates
  packages/compass/src/app/components/update-toasts.tsx
  packages/compass/src/app/index.tsx
Labels: release notes, fix

#5779 fix(connection-form): fix base64 regular expression COMPASS-7541
  packages/connection-form/src/utils/validation.ts
Labels: release notes, fix

#5746 fix(bson-transpilers-python-regex): No need to escape `\` in regex
  packages/bson-transpilers/symbols/python/templates.yaml
Labels: release notes

#5780 feat(sidebar): add support to create db from connection COMPASS-7885
  packages/compass-components/src/components/item-action-controls.spec.tsx
  packages/compass-components/src/components/item-action-controls.tsx
  packages/compass-connections-navigation/src/connection-item.tsx
  packages/compass-connections-navigation/src/connections-navigation-tree.spec.tsx
  packages/compass-connections-navigation/src/constants.tsx
  packages/compass-connections-navigation/src/tree-item.tsx
  packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/saved-connections/saved-connection-list.tsx
  packages/compass-sidebar/src/components/multiple-connections/saved-connections/saved-connection.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
Labels: feature flagged, feat

#5796 fix(connections): add repository provider to make sure we don't reset repository state every time the hook is used COMPASS-7921
  packages/compass-connections/src/components/connections-provider.tsx
  packages/compass-connections/src/hooks/use-active-connections.ts
  packages/compass-connections/src/hooks/use-tab-connection-theme.ts
  packages/compass-connections/src/provider.ts
  packages/compass-connections/src/stores/connections-store.tsx
  packages/compass-web/src/entrypoint.tsx
Labels: fix, no release notes

#5775 fix(compass): update toasts copy and button style
  packages/compass/src/app/components/update-toasts.tsx
Labels: release notes, fix

#5801 feat(editor, query-bar): add disabled state for code mirror editor, use while generative ai fetching COMPASS-7902
  packages/compass-editor/src/editor.tsx
  packages/compass-query-bar/src/components/option-editor.tsx
  packages/compass-query-bar/src/components/query-bar.spec.tsx
Labels: release notes, feat

#5803 fix(components): overflow-wrap error messages
  packages/compass-components/src/components/error-warning-summary.tsx
Labels: release notes, fix

#5810 fix(hadron-build): add missing throw from recent change
  packages/hadron-build/lib/mac-notary-service.js
Labels: fix, no release notes

#5809 fix(connection-info, indexes, web): use clusterName for breadcrumbs; fix spacing in the table
  packages/compass-indexes/src/components/indexes-table/indexes-table.tsx
  packages/compass-indexes/src/components/indexes/indexes.tsx
  packages/connection-info/src/connection-title.ts
Labels: fix, no release notes

#5812 feat(compass): update close window hotkey to be cmd+shift+w to avoid conflict with close tab cmd+w COMPASS-7301
  packages/compass/src/main/menu.spec.ts
  packages/compass/src/main/menu.ts
Labels: release notes, feat

#5815 fix(bulk ops): clarify no filter applied text box for bulk deletes and updates
  packages/compass-crud/src/components/readonly-filter.tsx
Labels: no release notes

#5824 fix(connection-form): don't force the modal larger, prevent it from going too big
  packages/connection-form/src/components/connection-form.tsx
Labels: feature flagged, fix

#5792 fix(connection-form): add dynamic height to the form COMPASS-7895
  packages/connection-form/src/components/connection-form.tsx
Labels: feature flagged, fix

#5840 fix: update connect menu for multiple connections COMPASS-7913
  packages/compass/src/main/menu.spec.ts
  packages/compass/src/main/menu.ts
Labels: feature flagged, fix

#5842 fix(databases-collections): fixes the visible "Create collection" button despite Compass being in readonly mode
  packages/compass-e2e-tests/tests/read-only.test.ts
  packages/databases-collections/src/components/collections.tsx
Labels: release notes, fix
