Repository mongodb-js/compass, pull requests merged in 2024-06, with the labels that each got.

#5828 test(e2e): try quiesce fix COMPASS-7949
  packages/compass-e2e-tests/tests/oidc.test.ts
Labels: no release notes

#5832 feat: add dev build
  .evergreen/buildvariants.in.yml
  .evergreen/buildvariants.yml
  .evergreen/functions.yml
  .evergreen/print-compass-env.js
  .evergreen/print-compass-env.sh
  .evergreen/publish-dev-release.sh
  .evergreen/tasks.in.yml
  .evergreen/tasks.yml
  packages/compass/app-icons/darwin/mongodb-compass-logo-beta.icns
  packages/compass/app-icons/darwin/mongodb-compass-logo-dev.icns
  packages/compass/app-icons/darwin/mongodb-compass-logo-stable.icns
  packages/compass/app-icons/linux/mongodb-compass-logo-beta.png
  packages/compass/app-icons/linux/mongodb-compass-logo-dev.png
  packages/compass/app-icons/linux/mongodb-compass-logo-stable.png
  packages/compass/app-icons/win32/mongodb-compass-logo-beta.ico
  packages/compass/app-icons/win32/mongodb-compass-logo-dev.ico
  packages/compass/app-icons/win32/mongodb-compass-logo-stable.ico
  packages/compass/package.json
  packages/hadron-build/lib/target.js
  packages/hadron-build/lib/validate-build-config.js
  packages/hadron-build/test/fixtures/hadron-app/package.json
Labels: feat, no release notes

#5849 feat(data-service): expose close event VSCODE-536
  packages/data-service/src/data-service.ts
Labels: feat, no release notes

#5857 feat(settings): enable sample documents setting COMPASS-7931
  packages/compass-preferences-model/src/feature-flags.ts
  packages/compass-settings/src/components/settings/gen-ai-settings.spec.tsx
  packages/compass-settings/src/components/settings/gen-ai-settings.tsx
Labels: release notes, feat

#5866 fix: correct mac icons
  packages/compass/app-icons/darwin/mongodb-compass-logo-beta.icns
  packages/compass/app-icons/darwin/mongodb-compass-logo-dev.icns
Labels: fix

#5868 fix: publish key prefix to download update correctly
  .evergreen/build-dev-release-info.sh
  .evergreen/buildvariants.in.yml
  .evergreen/buildvariants.yml
  .evergreen/functions.yml
  .evergreen/print-compass-env.js
  .evergreen/publish-dev-release.sh
  .evergreen/tasks.in.yml
  .evergreen/tasks.yml
Labels: fix, no release notes

#5869 feat(generative-ai): update generative ai input to be resizable text area COMPASS-7940
  packages/compass-generative-ai/src/components/generative-ai-input.tsx
  packages/compass-query-bar/src/components/query-bar.tsx
Labels: release notes, feat

#5871 fix(compass-sidebar): ensure connection gets saved as favorite from old sidebar COMPASS-7980
  packages/compass-sidebar/src/components/legacy/sidebar.tsx
Labels: release notes, fix

#5785 feat: active connections filter COMPASS-7772
  packages/compass-app-stores/src/stores/instance-store.ts
  packages/compass-connections-navigation/src/connections-navigation-tree.tsx
  packages/compass-connections-navigation/src/tree-data.ts
  packages/compass-sidebar/src/components/legacy/navigation-items.spec.tsx
  packages/compass-sidebar/src/components/legacy/navigation-items.tsx
  packages/compass-sidebar/src/components/legacy/sidebar-databases-navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
  packages/compass-sidebar/src/components/navigation-items-filter.tsx
  packages/compass-sidebar/src/helpers/find-collection.ts
  packages/compass-sidebar/src/modules/databases.spec.ts
  packages/compass-sidebar/src/modules/databases.ts
Labels: feature flagged, feat

#5881 fix(index card explain plan): long index names COMPASS-7016
  packages/compass-explain-plan/src/components/explain-tree/explain-tree-stage.tsx
Labels: release notes

#5885 chore(ci): set minimum macOs version to 10.15+ COMPASS-7990
  packages/hadron-build/commands/upload.js
  packages/hadron-build/test/upload.test.js
Labels: release notes

#5880 fix(query-history, aggregations): regex and number long query history fix COMPASS-7215, COMPASS-7008
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-crud/package.json
  packages/compass-import-export/package.json
  packages/compass-indexes/package.json
  packages/compass-query-bar/package.json
  packages/compass-query-bar/src/utils/format-query.spec.js
  packages/compass-schema-validation/package.json
  packages/connection-form/package.json
  packages/databases-collections/package.json
Labels: release notes, fix

#5889 feat(query-bar): expand options when applied from query history with options
  packages/compass-query-bar/src/stores/query-bar-reducer.spec.ts
  packages/compass-query-bar/src/stores/query-bar-reducer.ts
Labels: release notes, feat

#5895 fix(crud): keep listeners for insert document validity on document view COMPASS-3246
  packages/compass-crud/src/components/insert-document-dialog.tsx
Labels: release notes, fix

#5897 fix(ci): run static analysis reporting only once per version COMPASS-7998
  .evergreen.yml
  .evergreen/buildvariants.in.yml
  .evergreen/buildvariants.yml
  .evergreen/compass_package.sh
  .evergreen/create-static-analysis-report.sh
  .evergreen/functions.yml
  .evergreen/generative-ai-accuracy-test.yml
  .evergreen/tasks.in.yml
  .evergreen/tasks.yml
  package-lock.json
  package.json
  packages/compass/package.json
Labels: fix, no release notes

#5896 fix(databases-collections-list): hid inaccurate collection stats for timeseries COMPASS-6712
  packages/databases-collections-list/src/collections.tsx
  packages/databases-collections-list/src/index.spec.tsx
Labels: release notes, fix

#5893 feat(generative-ai): add popover on empty content generated COMPASS-7837
  packages/compass-aggregations/src/components/pipeline-toolbar/pipeline-ai.tsx
  packages/compass-generative-ai/src/components/generative-ai-input.spec.tsx
  packages/compass-generative-ai/src/components/generative-ai-input.tsx
  packages/compass-query-bar/src/components/query-ai.tsx
Labels: release notes, feat

#5909 fix(scripts): account for prettier placeholder replacement
  scripts/generate-security-test-summary.ts
Labels: fix, no release notes

#5906 fix(web): fix deployment types; resolve deployment item for sharded from sharded and not clusters CLOUDP-253915
  packages/compass-web/src/connection-storage.spec.ts
  packages/compass-web/src/connection-storage.tsx
Labels: fix, no release notes

#5905 fix: finish readOnly logic COMPASS-7972
  packages/compass-connections-navigation/src/connections-navigation-tree.spec.tsx
  packages/compass-connections-navigation/src/connections-navigation-tree.tsx
  packages/compass-connections-navigation/src/item-actions.ts
  packages/compass-connections-navigation/src/navigation-item.tsx
  packages/compass-connections-navigation/src/tree-data.ts
Labels: feature flagged, fix

#5920 feat(compass): add confirmation dialog when quitting compass COMPASS-6435
  packages/compass-preferences-model/src/preferences-schema.ts
  packages/compass-settings/src/components/settings/general.tsx
  packages/compass/src/main/menu.spec.ts
  packages/compass/src/main/menu.ts
Labels: release notes, feat

#5841 chore(my-queries): support for multiple connections for my-queries COMPASS-7904, COMPASS-7915
  package-lock.json
  packages/compass-saved-aggregations-queries/package.json
  packages/compass-saved-aggregations-queries/src/components/aggregations-queries-list.tsx
  packages/compass-saved-aggregations-queries/src/components/no-active-connections-modal.tsx
  packages/compass-saved-aggregations-queries/src/components/open-item-modal.tsx
  packages/compass-saved-aggregations-queries/src/components/saved-item-card.test.tsx
  packages/compass-saved-aggregations-queries/src/components/saved-item-card.tsx
  packages/compass-saved-aggregations-queries/src/components/select-connection-and-namespace-modal.tsx
  packages/compass-saved-aggregations-queries/src/components/select-connection-modal.tsx
  packages/compass-saved-aggregations-queries/src/index.spec.tsx
  packages/compass-saved-aggregations-queries/src/index.ts
  packages/compass-saved-aggregations-queries/src/stores/index.ts
  packages/compass-saved-aggregations-queries/src/stores/open-item.ts
  packages/compass-sidebar/src/plugin.tsx
  packages/compass-web/src/entrypoint.tsx
  packages/compass-workspaces/src/components/index.tsx
  packages/compass-workspaces/src/components/workspaces.tsx
  packages/compass/src/app/components/home.tsx
  packages/compass/src/app/components/workspace.tsx
  packages/connection-form/src/components/connection-form.tsx
  packages/connection-form/src/index.ts
Labels: feature flagged

#5928 fix: small issue with sidebar tabbing
  packages/compass-connections-navigation/src/connections-navigation-tree.tsx
Labels: bug, release notes, fix

#5923 fix(compass-connections-navigation): fix for action button not being tabbable when tabbing through navigation tree
  packages/compass-connections-navigation/src/base-navigation-item.tsx
  packages/compass-connections-navigation/src/connections-navigation-tree.spec.tsx
  packages/compass-connections-navigation/src/connections-navigation-tree.tsx
  packages/compass-connections-navigation/src/navigation-item.tsx
  packages/compass-connections-navigation/src/virtual-list/use-virtual-navigation-tree.tsx
  packages/compass-connections-navigation/src/virtual-list/virtual-list.tsx
Labels: fix, no release notes

#5930 fix: remove 'Preview' label from OIDC COMPASS-7666
  packages/compass-settings/src/components/modal.tsx
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-tab.spec.tsx
  packages/connection-form/src/components/advanced-options-tabs/authentication-tab/authentication-tab.tsx
Labels: release notes, fix

#5921 fix(ci): include releaser name in application artifacts COMPASS-7888
  .evergreen/compass_package.sh
  .evergreen/functions.yml
  .github/workflows/start-beta.yml
  .github/workflows/start-ga.yaml
  .mailmap
  packages/compass/.gitignore
  scripts/release.js
Labels: fix, no release notes

#5936 fix(ci): pass github token to release scripts
  .github/workflows/start-beta.yml
  .github/workflows/start-ga.yaml
Labels: fix, no release notes

#5937 fix(ci): add missing `await`
  scripts/release.js
Labels: fix, no release notes

#5931 feat(web): provide callback props for logging and telemetry CLOUDP-253932
  package-lock.json
  packages/compass-logging/src/provider.ts
  packages/compass-web/package.json
  packages/compass-web/sandbox/index.tsx
  packages/compass-web/sandbox/sandbox-logger.ts
  packages/compass-web/src/compass-web-connection-storage.ts
  packages/compass-web/src/entrypoint.tsx
  packages/compass-web/src/logger-and-telemetry.spec.tsx
  packages/compass-web/src/logger-and-telemetry.tsx
Labels: feat, no release notes

#5934 chore: active tabs the same colour as the active workspace COMPASS-7958
  packages/compass-components/src/components/workspace-tabs/tab.spec.tsx
  packages/compass-components/src/components/workspace-tabs/tab.tsx
  packages/compass-connections/src/hooks/use-tab-connection-theme.spec.ts
  packages/compass-connections/src/hooks/use-tab-connection-theme.ts
Labels: feature flagged

#5877 feat(compass-sidebar): unified sidebar experience for multiple connections - COMPASS-8016
  package-lock.json
  packages/compass-components/src/components/chevron-collapse-icon.tsx
  packages/compass-components/src/components/item-action-controls.spec.tsx
  packages/compass-components/src/components/item-action-controls.tsx
  packages/compass-components/src/index.ts
  packages/compass-connections-navigation/src/base-navigation-item.tsx
  packages/compass-connections-navigation/src/connections-navigation-tree.spec.tsx
  packages/compass-connections-navigation/src/connections-navigation-tree.tsx
  packages/compass-connections-navigation/src/constants.tsx
  packages/compass-connections-navigation/src/index.ts
  packages/compass-connections-navigation/src/item-actions.ts
  packages/compass-connections-navigation/src/navigation-item.tsx
  packages/compass-connections-navigation/src/styled-navigation-item.tsx
  packages/compass-connections-navigation/src/tree-data.ts
  packages/compass-connections-navigation/src/utils.ts
  packages/compass-connections-navigation/src/with-status-marker.tsx
  packages/compass-connections/src/hooks/use-active-connections.ts
  packages/compass-connections/src/hooks/use-connection-repository.ts
  packages/compass-connections/src/hooks/use-connections-with-status.spec.ts
  packages/compass-connections/src/hooks/use-connections-with-status.ts
  packages/compass-connections/src/provider.ts
  packages/compass-sidebar/package.json
  packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/active-connections/active-connection-navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/connections-navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/header/sidebar-header.tsx
  packages/compass-sidebar/src/components/multiple-connections/navigation/navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/saved-connections/saved-connection-list.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/saved-connections/saved-connection-list.tsx
  packages/compass-sidebar/src/components/multiple-connections/saved-connections/saved-connection.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/saved-connections/saved-connection.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
  packages/compass-sidebar/src/components/use-filtered-connections.ts
Labels: feature flagged, feat

#5943 fix(shell, logging): replace createRef with useRef
  packages/compass-logging/src/provider.ts
  packages/compass-shell/src/components/compass-shell/tab-compass-shell.tsx
Labels: fix, no release notes

#5925 fix(oidc, atlas-service): use system ca certs in atlas reqs and OIDC COMPASS-7950
  package-lock.json
  packages/atlas-service/package.json
  packages/atlas-service/src/main.spec.ts
  packages/atlas-service/src/main.ts
Labels: release notes, fix

#5944 (compass-sidebar): fixes disconnected item retaining its expanded state when connected again COMPASS-7967
  package-lock.json
  packages/compass-sidebar/package.json
  packages/compass-sidebar/src/components/multiple-connections/connections-navigation.tsx
  packages/compass-sidebar/src/components/use-filtered-connections.spec.ts
  packages/compass-sidebar/src/components/use-filtered-connections.ts
Labels: no release notes

#5945 fix(collection): hide edit view button in readonly mode COMPASS-7688
  packages/compass-collection/src/components/collection-header-actions/collection-header-actions.spec.tsx
  packages/compass-collection/src/components/collection-header-actions/collection-header-actions.tsx
Labels: release notes, fix

#5946 chore: revert close button animation
  packages/compass-components/src/components/workspace-tabs/tab.spec.tsx
  packages/compass-components/src/components/workspace-tabs/tab.tsx
Labels: no release notes

#5911 fix(ci): adopt augmented SBOM integration with Silk COMPASS-7910
  .evergreen/buildvariants-and-tasks.in.yml
  .evergreen/buildvariants-and-tasks.yml
  .evergreen/create-sbom.sh
  .evergreen/functions.yml
Labels: fix, no release notes

#5956 fix(sidebar): fix import for createLogger method
  packages/compass-sidebar/src/components/use-filtered-connections.spec.ts
Labels: fix

#5879 chore(deps): update oidc, mongosh, driver
  package-lock.json
  packages/atlas-service/package.json
  packages/atlas-service/src/main.spec.ts
  packages/atlas-service/src/main.ts
  packages/compass-aggregations/package.json
  packages/compass-connections/src/connections-manager.ts
  packages/compass-e2e-tests/package.json
  packages/compass-e2e-tests/tests/oidc.test.ts
  packages/compass-explain-plan/package.json
  packages/compass-generative-ai/package.json
  packages/compass-import-export/package.json
  packages/compass-indexes/package.json
  packages/compass-query-bar/package.json
  packages/compass-schema/package.json
  packages/compass-shell/package.json
  packages/compass-sidebar/package.json
  packages/compass-web/package.json
  packages/compass-web/webpack.config.js
  packages/compass/package.json
  packages/compass/src/main/validate-connection-string.ts
  packages/connection-form/package.json
  packages/connection-info/package.json
  packages/data-service/package.json
  packages/data-service/src/data-service.ts
Labels: no release notes

#5955 fix(compass-connections-navigation): use updated reference of required props while rendering NavigationItem
  packages/compass-connections-navigation/src/connections-navigation-tree.tsx
  packages/compass-connections-navigation/src/navigation-item.tsx
  packages/compass-connections-navigation/src/virtual-list/virtual-list.spec.tsx
  packages/compass-connections-navigation/src/virtual-list/virtual-list.tsx
Labels: fix, no release notes

#5878 chore(e2e): port most e2e tests to multiple connections COMPASS-7925 COMPASS-8001
  .evergreen/buildvariants-and-tasks.in.yml
  .evergreen/buildvariants-and-tasks.yml
  .evergreen/functions.yml
  package-lock.json
  packages/compass-connections-navigation/src/navigation-item.tsx
  packages/compass-e2e-tests/helpers/commands/collection-workspaces.ts
  packages/compass-e2e-tests/helpers/commands/connect-with-connection-string.ts
  packages/compass-e2e-tests/helpers/commands/connection-workspaces.ts
  packages/compass-e2e-tests/helpers/commands/database-workspaces.ts
  packages/compass-e2e-tests/helpers/commands/disconnect.ts
  packages/compass-e2e-tests/helpers/commands/get-connect-form-connection-string.ts
  packages/compass-e2e-tests/helpers/commands/get-connect-form-state.ts
  packages/compass-e2e-tests/helpers/commands/index.ts
  packages/compass-e2e-tests/helpers/commands/instance-workspaces.ts
  packages/compass-e2e-tests/helpers/commands/reset-connect-form.ts
  packages/compass-e2e-tests/helpers/commands/save-connection-string-as-favorite.ts
  packages/compass-e2e-tests/helpers/commands/save-favorite.ts
  packages/compass-e2e-tests/helpers/commands/select-connection-menu-item.ts
  packages/compass-e2e-tests/helpers/commands/select-connection.ts
  packages/compass-e2e-tests/helpers/commands/select-favorite.ts
  packages/compass-e2e-tests/helpers/commands/select-favorites-menu-item.ts
  packages/compass-e2e-tests/helpers/commands/select-option.ts
  packages/compass-e2e-tests/helpers/commands/set-connect-form-state.ts
  packages/compass-e2e-tests/helpers/commands/wait-for-connection-result.ts
  packages/compass-e2e-tests/helpers/commands/wait-for-connection-screen.ts
  packages/compass-e2e-tests/helpers/compass.ts
  packages/compass-e2e-tests/helpers/connect-form-state.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/index.ts
  packages/compass-e2e-tests/multiple-connections.yaml
  packages/compass-e2e-tests/package.json
  packages/compass-e2e-tests/tests/auto-connect.test.ts
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
  packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
  packages/compass-e2e-tests/tests/collection-export.test.ts
  packages/compass-e2e-tests/tests/collection-import.test.ts
  packages/compass-e2e-tests/tests/connection-form.test.ts
  packages/compass-e2e-tests/tests/connection.test.ts
  packages/compass-e2e-tests/tests/database-collections-tab.test.ts
  packages/compass-e2e-tests/tests/force-connection-options.test.ts
  packages/compass-e2e-tests/tests/global-preferences.test.ts
  packages/compass-e2e-tests/tests/import-export-connections.test.ts
  packages/compass-e2e-tests/tests/in-use-encryption.test.ts
  packages/compass-e2e-tests/tests/instance-databases-tab.test.ts
  packages/compass-e2e-tests/tests/instance-my-queries-tab.test.ts
  packages/compass-e2e-tests/tests/instance-performance-tab.test.ts
  packages/compass-e2e-tests/tests/instance-sidebar.test.ts
  packages/compass-e2e-tests/tests/logging.test.ts
  packages/compass-e2e-tests/tests/oidc.test.ts
  packages/compass-e2e-tests/tests/protect-connection-strings.test.ts
  packages/compass-e2e-tests/tests/read-only.test.ts
  packages/compass-e2e-tests/tests/shell.test.ts
  packages/compass-e2e-tests/tests/show-kerberos-password-field.test.ts
  packages/compass-sidebar/src/components/multiple-connections/header/sidebar-header.tsx
  packages/connection-form/src/components/connection-form-actions.tsx
  packages/connection-form/src/components/connection-form-modal.tsx
Labels: feature flagged

#5966 fix(editor): update line numbers to not be selectable COMPASS-7941
  packages/compass-editor/src/editor.tsx
Labels: release notes, fix

#5952 feat(workspaces): change tab behavior to prevent modified tabs from being closed by accident COMPASS-5022
  packages/compass-aggregations/src/stores/store.ts
  packages/compass-e2e-tests/helpers/commands/close-workspace-tabs.ts
  packages/compass-e2e-tests/helpers/commands/collection-workspaces.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/tabs.test.ts
  packages/compass-workspaces/src/components/workspace-close-handler.tsx
  packages/compass-workspaces/src/components/workspace-tab-state-provider.tsx
  packages/compass-workspaces/src/components/workspaces.tsx
  packages/compass-workspaces/src/index.ts
  packages/compass-workspaces/src/provider.tsx
  packages/compass-workspaces/src/stores/workspaces.spec.ts
  packages/compass-workspaces/src/stores/workspaces.ts
  packages/hadron-app-registry/src/register-plugin.tsx
Labels: release notes, feat

#5972 fix(aggregations): use maxTimeMS default on preview docs COMPASS-7798
  packages/compass-aggregations/src/modules/input-documents.spec.ts
  packages/compass-aggregations/src/modules/input-documents.ts
Labels: release notes, fix

#5978 fix(connections): make sure that autoconnect info is provided in connection hooks COMPASS-8044
  packages/compass-connections/src/hooks/use-connection-repository.ts
  packages/compass-connections/src/hooks/use-connections-with-status.ts
  packages/compass-e2e-tests/tests/auto-connect.test.ts
Labels: release notes, fix
