Repository mongodb-js/compass, pull requests merged in 2025-10, with the labels that each got.

#7405 feat(compass-assistant): move the AI assistant feature from development to released COMPASS-9753
  packages/compass-assistant/src/compass-assistant-provider.spec.tsx
  packages/compass-explain-plan/src/components/explain-plan-modal.spec.tsx
  packages/compass-preferences-model/src/feature-flags.ts
Labels: release notes, feat

#7409 chore(hadron-type-checker): update to typescript
  package-lock.json
  packages/hadron-document/package.json
  packages/hadron-type-checker/.depcheckrc
  packages/hadron-type-checker/.eslintignore
  packages/hadron-type-checker/.eslintrc
  packages/hadron-type-checker/.eslintrc.js
  packages/hadron-type-checker/.gitignore
  packages/hadron-type-checker/.mocharc.js
  packages/hadron-type-checker/index.d.ts
  packages/hadron-type-checker/index.js
  packages/hadron-type-checker/package.json
  packages/hadron-type-checker/src/index.ts
  packages/hadron-type-checker/src/type-checker.ts
  packages/hadron-type-checker/test/type-checker.test.ts
  packages/hadron-type-checker/tsconfig-build.json
  packages/hadron-type-checker/tsconfig.json
Labels: no-title-validation

#7411 chore(ci): split static analysis report into its own build variant
  .evergreen/buildvariants-and-tasks.in.yml
  .evergreen/buildvariants-and-tasks.yml
Labels: no-title-validation

#7417 fix(compass-web): entrypoint provider order COMPASS-9918
  packages/compass-web/src/entrypoint.tsx
Labels: fix, no release notes

#7423 fix: don't crash when using bson-equal to compare against null COMPASS-9924
  packages/mongodb-query-util/src/bson-equal.spec.ts
  packages/mongodb-query-util/src/bson-equal.ts
Labels: release notes, fix

#7421 chore(lint): turn on dynamic css rule, move more styles to constants
  configs/eslint-config-compass/index.js
  packages/compass-aggregations/src/components/aggregation-side-panel/stage-wizard-use-cases/match/match-group-form.tsx
  packages/compass-assistant/src/components/assistant-chat.tsx
  packages/compass-assistant/src/components/confirmation-message.tsx
  packages/compass-components/src/components/actions/item-action-group.tsx
  packages/compass-components/src/components/bson-value.tsx
  packages/compass-components/src/components/document-list/element.tsx
  packages/compass-components/src/components/file-picker-dialog.tsx
  packages/compass-components/src/components/file-selector.tsx
  packages/compass-components/src/components/icons/logo-icon.tsx
  packages/compass-components/src/components/select-list.tsx
  packages/compass-components/src/components/workspace-tabs/tab.tsx
  packages/compass-connections-navigation/src/with-status-marker.tsx
  packages/compass-explain-plan/src/components/explain-tree/tree-layout.tsx
  packages/compass-global-writes/src/components/create-shard-key-form.tsx
  packages/compass-workspaces/src/components/workspace-tab-context-provider.tsx
Labels: no-title-validation

#7426 Revert "feat(database-collections): add uncompressed data stat field COMPASS-7691 (#7357)"
  packages/compass-components/src/components/inline-definition.tsx
  packages/compass-workspaces/src/index.spec.tsx
  packages/data-service/src/data-service.ts
  packages/data-service/src/instance-detail-helper.ts
  packages/data-service/src/run-command.ts
  packages/database-model/index.d.ts
  packages/database-model/lib/model.js
  packages/databases-collections-list/src/collections.tsx
  packages/databases-collections-list/src/databases.tsx
  packages/databases-collections-list/src/index.spec.tsx
Labels: release notes, no-title-validation

#7365 feat(compass-collection): Output Validation Followup - Mock Data Generator LLM CLOUDP-347048
  packages/compass-collection/src/components/mock-data-generator-modal/faker-mapping-selector.tsx
  packages/compass-collection/src/components/mock-data-generator-modal/faker-schema-editor-screen.tsx
  packages/compass-collection/src/components/mock-data-generator-modal/mock-data-generator-modal.spec.tsx
  packages/compass-collection/src/components/mock-data-generator-modal/script-generation-utils.ts
  packages/compass-collection/src/components/mock-data-generator-modal/utils.spec.ts
  packages/compass-collection/src/components/mock-data-generator-modal/utils.ts
  packages/compass-collection/src/modules/collection-tab.ts
Labels: feat, no release notes

#7389 feat(data-modeling): add nested field to object in diagram COMPASS-9742
  package-lock.json
  packages/compass-data-modeling/src/components/diagram-editor.tsx
  packages/compass-data-modeling/src/store/diagram.ts
  packages/compass-data-modeling/src/utils/nodes-and-edges.ts
  packages/compass-data-modeling/src/utils/schema.ts
Labels: feature flagged, feat
