Repository mongodb-js/compass, pull requests merged in 2025-04, with the labels that each got.

#6832 feat(release): write artifacts to new release bucket with private acls COMPASS-9238
  package-lock.json
  packages/hadron-build/lib/download-center.js
  packages/hadron-build/package.json
Labels: feat, no release notes

#6831 fix: remove logging for currentOp COMPASS-9203
  packages/data-service/src/data-service.ts
Labels: fix, no release notes

#6834 feat: add special handling of vector sub-type COMPASS-8257
  packages/compass-components/src/components/bson-value.spec.tsx
  packages/compass-components/src/components/bson-value.tsx
Labels: release notes, feat

#6836 fix(compass-crud): account for pagination in expanded table view COMPASS-9161
  packages/compass-crud/src/components/table-view/document-table-view.tsx
Labels: release notes, fix

#6838 fix: semver sort the releases latest first before picking the first non-draft of the relevant channel
  packages/hadron-build/commands/upload.js
Labels: bug, fix, no release notes, no-title-validation

#6840 fix(compass-crud): no 0 default for bulkDelete count COMPASS-8603
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
Labels: release notes, fix

#6842 fix: cleanup tooltip COMPASS-9256
  packages/compass-schema-validation/src/components/sample-documents.tsx
Labels: fix, no release notes

#6844 fix(compass-indexes): fix tooltip triggers in indexes plugin COMPASS-8449
  packages/compass-indexes/src/components/regular-indexes-table/property-field.tsx
  packages/compass-indexes/src/components/regular-indexes-table/status-field.tsx
  packages/compass-indexes/src/components/regular-indexes-table/type-field.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.tsx
Labels: release notes, fix

#6848 fix: error typo COMPASS-9242
  packages/compass-connections/src/stores/connections-store-redux.spec.tsx
  packages/compass-connections/src/stores/connections-store-redux.ts
Labels: fix, no release notes

#6849 chore(compass-main): refactor auto-updater to return objects when no update is available
  packages/compass/src/main/auto-update-manager.spec.ts
  packages/compass/src/main/auto-update-manager.ts
Labels: no release notes, no-title-validation

#6856 chore(bump-packages): add back missing env var; update PR description
  .github/workflows/bump-packages.yaml
Labels: no-title-validation

#6843 fix(compass-schema-validation): rules generated message COMPASS-9252
  packages/compass-schema-validation/src/components/validation-editor.spec.tsx
  packages/compass-schema-validation/src/components/validation-editor.tsx
  packages/compass-schema-validation/src/modules/rules-generation.ts
Labels: fix, no release notes

#6846 fix: fix the shortcuts on windows to be the app name, not executable name COMPASS-8367
  package-lock.json
  packages/compass/package.json
  packages/compass/src/main/application.ts
  packages/compass/src/main/electron-squirrel-startup.d.ts
  packages/compass/src/main/squirrel-startup.ts
  packages/hadron-build/README.md
  packages/hadron-build/lib/target.js
Labels: release notes, fix

#6851 feat(auto-updater): Error when requesting updates from an outdated MacOS machine COMPASS-9081
  package-lock.json
  packages/compass/package.json
  packages/compass/src/app/components/update-toasts.tsx
  packages/compass/src/app/index.tsx
  packages/compass/src/main/auto-update-manager.spec.ts
  packages/compass/src/main/auto-update-manager.ts
  packages/compass/src/main/menu.spec.ts
  packages/compass/src/main/menu.ts
Labels: feat, no release notes

#6863 Ignoring template files when running prettier
  .prettierignore
Labels: no-title-validation

#6869 chore(data-modeling): bootstrap data modeling workspace
  package-lock.json
  packages/compass-data-modeling/.depcheckrc
  packages/compass-data-modeling/.eslintignore
  packages/compass-data-modeling/.eslintrc.js
  packages/compass-data-modeling/.mocharc.js
  packages/compass-data-modeling/package.json
  packages/compass-data-modeling/src/components/data-modeling.tsx
  packages/compass-data-modeling/src/index.spec.tsx
  packages/compass-data-modeling/src/index.ts
  packages/compass-data-modeling/src/provider/index.ts
  packages/compass-data-modeling/src/services/data-model-storage-electron.ts
  packages/compass-data-modeling/src/services/data-model-storage-web.ts
  packages/compass-data-modeling/src/services/data-model-storage.ts
  packages/compass-data-modeling/src/store/reducer.ts
  packages/compass-data-modeling/tsconfig-lint.json
  packages/compass-data-modeling/tsconfig.json
  packages/compass-preferences-model/src/feature-flags.ts
  packages/compass-sidebar/src/components/multiple-connections/navigation/navigation.tsx
  packages/compass-web/package.json
  packages/compass-web/sandbox/index.tsx
  packages/compass-web/src/entrypoint.tsx
  packages/compass-workspaces/src/components/workspaces-provider.tsx
  packages/compass-workspaces/src/components/workspaces.tsx
  packages/compass-workspaces/src/index.ts
  packages/compass-workspaces/src/provider.tsx
  packages/compass-workspaces/src/stores/workspaces.ts
  packages/compass-workspaces/src/types.ts
  packages/compass/package.json
  packages/compass/src/app/components/workspace.tsx
Labels: no-title-validation

#6868 feat: move the signal from query bar to outside of it CLOUDP-311778
  packages/compass-components/src/components/signal-popover.spec.tsx
  packages/compass-components/src/components/signal-popover.tsx
  packages/compass-crud/src/components/crud-toolbar.tsx
  packages/compass-query-bar/src/components/option-editor.tsx
  packages/compass-query-bar/src/components/query-bar.tsx
  packages/compass-query-bar/src/components/query-option.tsx
Labels: feat, no release notes

#6860 feat: setting up early indexes experimentation and experiment viewed event CLOUDP-311776
  packages/compass-indexes/src/components/create-index-modal/create-index-modal-header.spec.tsx
  packages/compass-indexes/src/components/create-index-modal/create-index-modal-header.tsx
  packages/compass-indexes/src/components/create-index-modal/create-index-modal.tsx
  packages/compass-preferences-model/src/feature-flags.ts
  packages/compass-telemetry/src/growth-experiments.ts
  packages/compass-telemetry/src/provider.tsx
  packages/compass-telemetry/src/telemetry-events.ts
Labels: feat, no release notes, no-title-validation

#6873 feat: Add radio boxes for the two flows in create index modal CLOUDP-311780
  packages/compass-indexes/src/components/create-index-form/create-index-form.spec.tsx
  packages/compass-indexes/src/components/create-index-form/create-index-form.tsx
  packages/compass-indexes/src/components/create-index-modal/create-index-modal.tsx
  packages/compass-indexes/src/modules/create-index.tsx
Labels: feat, no release notes

#6853 fix(compass): disable spellcheck before creating window when no network traffic COMPASS-8166
  packages/compass-e2e-tests/tests/no-network-traffic.test.ts
  packages/compass/src/main/application.ts
  packages/compass/src/main/window-manager.ts
Labels: release notes, fix

#6881 feat: Add UI for Start with a Query Flow CLOUDP-311785
  packages/compass-indexes/src/components/create-index-form/create-index-form.tsx
  packages/compass-indexes/src/components/create-index-form/index-flow-section.spec.tsx
  packages/compass-indexes/src/components/create-index-form/index-flow-section.tsx
  packages/compass-indexes/src/components/create-index-form/query-flow-section.spec.tsx
  packages/compass-indexes/src/components/create-index-form/query-flow-section.tsx
Labels: feat, no release notes

#6882 feat: Added code equivalent functionality CLOUDP-311784
  packages/compass-indexes/src/components/create-index-fields.tsx
  packages/compass-indexes/src/components/create-index-form/create-index-form.tsx
  packages/compass-indexes/src/components/create-index-form/index-flow-section.spec.tsx
  packages/compass-indexes/src/components/create-index-form/index-flow-section.tsx
  packages/compass-indexes/src/components/create-index-form/mdb-code-viewer.spec.tsx
  packages/compass-indexes/src/components/create-index-form/mdb-code-viewer.tsx
  packages/compass-indexes/src/components/create-index-form/query-flow-section.spec.tsx
  packages/compass-indexes/src/components/create-index-form/query-flow-section.tsx
Labels: feat, no release notes

#6883 feat: Add covered and optimal query examples CLOUDP-311782
  packages/compass-indexes/src/components/create-index-form/index-flow-section.spec.tsx
  packages/compass-indexes/src/components/create-index-form/index-flow-section.tsx
Labels: feat, no release notes

#6880 feat(indexes): add Atlas search indexes link when banner dismissed COMPASS-9158
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.spec.tsx
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
  packages/compass-indexes/src/components/indexes/indexes.tsx
Labels: feat, no release notes

#6852 feat: disable db and coll stats via preferences COMPASS-5387
  package-lock.json
  packages/collection-model/index.d.ts
  packages/collection-model/lib/model.js
  packages/compass-aggregations/src/modules/aggregation.ts
  packages/compass-app-stores/package.json
  packages/compass-app-stores/src/instances-manager.spec.ts
  packages/compass-app-stores/src/plugin.tsx
  packages/compass-app-stores/src/provider.spec.tsx
  packages/compass-app-stores/src/provider.tsx
  packages/compass-app-stores/src/stores/instance-store.spec.ts
  packages/compass-app-stores/src/stores/instance-store.ts
  packages/compass-crud/src/plugin-title.tsx
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-indexes/src/plugin-title.tsx
  packages/compass-preferences-model/package.json
  packages/compass-preferences-model/src/preferences-schema.tsx
  packages/compass-preferences-model/tsconfig.json
  packages/compass-schema-validation/src/stores/store.spec.ts
  packages/compass-settings/src/components/settings/general.tsx
  packages/compass-settings/src/components/settings/settings-list.tsx
  packages/compass-sidebar/src/modules/databases.spec.ts
  packages/compass-sidebar/src/modules/instance.spec.ts
  packages/compass-sidebar/src/stores/store.spec.ts
  packages/compass-sidebar/test/helpers.ts
  packages/compass-workspaces/package.json
  packages/compass-workspaces/src/index.ts
  packages/database-model/index.d.ts
  packages/database-model/lib/model.js
  packages/databases-collections-list/src/collections.tsx
  packages/databases-collections-list/src/databases.tsx
  packages/databases-collections-list/src/index.spec.tsx
  packages/databases-collections-list/src/namespace-card.tsx
  packages/databases-collections-list/src/namespace-param.tsx
  packages/databases-collections/src/collections-plugin.spec.tsx
  packages/databases-collections/src/databases-plugin.spec.tsx
  packages/databases-collections/src/modules/collections.ts
  packages/databases-collections/src/stores/collections-store.ts
  packages/instance-model/index.d.ts
  packages/instance-model/lib/model.js
  packages/instance-model/package.json
  packages/instance-model/test/index.test.js
Labels: release notes, feat

#6825 feat: validation error details aggregation COMPASS-8868
  packages/compass-aggregations/src/components/pipeline-results-workspace/index.spec.tsx
  packages/compass-aggregations/src/components/pipeline-results-workspace/index.tsx
  packages/compass-aggregations/src/modules/aggregation.ts
  packages/compass-e2e-tests/helpers/commands/set-validation.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
Labels: release notes, feat
