Repository mongodb-js/compass, pull requests merged in 2025-09, with the labels that each got.

#7257 chore: add wait for flaky relationship management test
  packages/compass-e2e-tests/tests/data-modeling-tab.test.ts
Labels: feature flagged, no release notes, no-title-validation

#7163 fix(query-bar): prevent form submit from propagating COMPASS-9637
  packages/compass-query-bar/src/components/query-history/save-query-form.tsx
Labels: release notes, fix

#7249 feat(crud): do not apply default sort option for views and timeseries COMPASS-9749
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-preferences-model/src/preferences-schema.tsx
Labels: release notes, feat

#7248 feat(compass-data-modeling): update field type COMPASS-9659
  packages/compass-data-modeling/src/components/drawer/diagram-editor-side-panel.spec.tsx
  packages/compass-data-modeling/src/components/drawer/field-drawer-content.tsx
  packages/compass-data-modeling/src/store/apply-edit.ts
  packages/compass-data-modeling/src/store/diagram.ts
  packages/compass-data-modeling/src/utils/schema-traversal.spec.tsx
  packages/compass-data-modeling/src/utils/schema-traversal.tsx
  packages/compass-data-modeling/test/fixtures/data-model-with-relationships.json
Labels: feature flagged, feat

#7276 chore(ci): mark bot prs with label to make filtering easier; add api-extractor to typescript update group
  .github/workflows/bump-packages.yaml
  .github/workflows/update-dependencies.yaml
  scripts/update-dependencies-config.js
Labels: no-title-validation

#7277 chore(compass-generative-ai): use latest disclaimer, fix dark mode colour, center align
  packages/compass-generative-ai/src/components/ai-optin-modal.tsx
Labels: no-title-validation

#7217 feat(compass-aggregations): disable search stages for incompatible views COMPASS-9693
  packages/compass-aggregations/src/components/stage-toolbar/stage-operator-select.spec.tsx
  packages/compass-aggregations/src/components/stage-toolbar/stage-operator-select.tsx
  packages/compass-aggregations/src/modules/collection-stats.ts
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
  packages/compass-indexes/src/components/indexes/indexes.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.tsx
Labels: feat, no release notes

#7263 feat(compass-assistant): ensure opt-in before sending the first message COMPASS-9759
  package-lock.json
  packages/compass-assistant/package.json
  packages/compass-assistant/src/assistant-chat.spec.tsx
  packages/compass-assistant/src/assistant-chat.tsx
  packages/compass-assistant/src/compass-assistant-provider.spec.tsx
  packages/compass-assistant/src/compass-assistant-provider.tsx
  packages/compass-connections/src/stores/connections-store-redux.ts
  packages/compass-generative-ai/package.json
  packages/compass-generative-ai/src/atlas-ai-service.ts
Labels: feature flagged, feat

#7278 fix(compass-connections): connection toast fixes COMPASS-9787
  packages/compass-connections/src/components/connection-status-notifications.tsx
Labels: feature flagged, fix

#7279 feat(compass-assistant): add global per-conversation instructions COMPASS-9766
  packages/compass-assistant/src/compass-assistant-provider.spec.tsx
  packages/compass-assistant/src/compass-assistant-provider.tsx
  packages/compass-assistant/src/docs-provider-transport.ts
  packages/compass-assistant/src/prompts.ts
  packages/compass-assistant/test/assistant.eval.ts
  packages/compass-assistant/test/entrypoints/explain-plan.ts
  packages/compass-assistant/test/entrypoints/index.ts
  packages/compass-assistant/test/eval-cases/aggregation-pipeline.ts
  packages/compass-assistant/test/eval-cases/atlas-search.ts
  packages/compass-assistant/test/eval-cases/filter-docs-before-search.ts
  packages/compass-assistant/test/eval-cases/index.ts
  packages/compass-assistant/test/eval-cases/model-data.ts
  packages/compass-web/src/entrypoint.tsx
  packages/compass/src/app/components/home.tsx
Labels: feature flagged, feat

#7287 chore: use staging in dev and qa
  packages/atlas-service/src/util.ts
Labels: no-title-validation

#7291 chore(compass-assistant): hide the drawer if AI features are disabled
  packages/compass-assistant/src/compass-assistant-drawer.tsx
  packages/compass-assistant/src/compass-assistant-provider.spec.tsx
Labels: no-title-validation

#7294 chore(compass-assistant): move the two appNameForPrompt values together
  packages/compass-assistant/src/index.tsx
  packages/compass-assistant/src/prompts.ts
  packages/compass-web/src/entrypoint.tsx
  packages/compass/src/app/components/home.tsx
Labels: no-title-validation

#7320 chore: update leafygreen chat components for MessageLinks
  package-lock.json
  package.json
  packages/compass-assistant/src/assistant-chat.tsx
  packages/compass-components/package.json
Labels: no-title-validation

#7322 chore(scripts): fix electron update version to 37 temporarily
  scripts/update-dependencies-config.js
Labels: no-title-validation

#7295 feat(compass-collection): add Schema Editor UI - Mock Data Generator CLOUDP-333854
  package-lock.json
  packages/compass-collection/package.json
  packages/compass-collection/src/components/mock-data-generator-modal/faker-mapping-selector.tsx
  packages/compass-collection/src/components/mock-data-generator-modal/faker-schema-editor-screen.tsx
  packages/compass-collection/src/components/mock-data-generator-modal/mock-data-generator-modal.spec.tsx
  packages/compass-collection/src/components/mock-data-generator-modal/mock-data-generator-modal.tsx
  packages/compass-collection/src/components/mock-data-generator-modal/schema-field-selector.tsx
  packages/compass-collection/src/components/mock-data-generator-modal/types.ts
  packages/compass-collection/src/modules/collection-tab.ts
  packages/compass-web/webpack.config.js
Labels: feat, no release notes

#7192 fix(context-menu): position anchor and prevent escaping container COMPASS-9673
  configs/testing-library-compass/src/index.tsx
  packages/compass-components/src/components/content-with-fallback.spec.tsx
  packages/compass-components/src/components/context-menu.spec.tsx
  packages/compass-components/src/components/context-menu.tsx
  packages/compass-components/src/components/workspace-tabs/tab.spec.tsx
  packages/compass-context-menu/src/context-menu-provider.tsx
Labels: bug, fix, no release notes

#7313 feat(compass-collection): Mongosh Script Generation Engine - CLOUDP-333860
  package-lock.json
  packages/compass-collection/src/components/mock-data-generator-modal/script-generation-utils.spec.ts
  packages/compass-collection/src/components/mock-data-generator-modal/script-generation-utils.ts
  packages/compass-collection/src/modules/collection-tab.ts
Labels: feat, no release notes

#7344 chore(compass-assistant): keep track of confirmation and entry point sources
  packages/compass-assistant/src/compass-assistant-provider.tsx
  packages/compass-assistant/src/components/assistant-chat.spec.tsx
  packages/compass-assistant/src/components/assistant-chat.tsx
  packages/compass-telemetry/src/telemetry-events.ts
Labels: no-title-validation

#7289 chore(components): replace vendored drawer with lg dependency
  package-lock.json
  packages/compass-components/.depcheckrc
  packages/compass-components/package.json
  packages/compass-components/src/components/drawer-portal.tsx
  packages/compass-components/src/components/drawer/constants.ts
  packages/compass-components/src/components/drawer/drawer-layout/drawer-layout.tsx
  packages/compass-components/src/components/drawer/drawer-layout/drawer-layout.types.ts
  packages/compass-components/src/components/drawer/drawer-layout/index.ts
  packages/compass-components/src/components/drawer/drawer-stack-context/drawer-stack-context.tsx
  packages/compass-components/src/components/drawer/drawer-stack-context/drawer-stack-context.types.ts
  packages/compass-components/src/components/drawer/drawer-stack-context/index.ts
  packages/compass-components/src/components/drawer/drawer-toolbar-context/drawer-toolbar-context.tsx
  packages/compass-components/src/components/drawer/drawer-toolbar-context/drawer-toolbar-context.types.ts
  packages/compass-components/src/components/drawer/drawer-toolbar-context/index.ts
  packages/compass-components/src/components/drawer/drawer-toolbar-layout/drawer-toolbar-layout-container.tsx
  packages/compass-components/src/components/drawer/drawer-toolbar-layout/drawer-toolbar-layout.styles.ts
  packages/compass-components/src/components/drawer/drawer-toolbar-layout/drawer-toolbar-layout.tsx
  packages/compass-components/src/components/drawer/drawer-toolbar-layout/drawer-toolbar-layout.types.ts
  packages/compass-components/src/components/drawer/drawer-toolbar-layout/index.ts
  packages/compass-components/src/components/drawer/drawer-with-toolbar-wrapper/drawer-with-toolbar-wrapper.styles.ts
  packages/compass-components/src/components/drawer/drawer-with-toolbar-wrapper/drawer-with-toolbar-wrapper.tsx
  packages/compass-components/src/components/drawer/drawer-with-toolbar-wrapper/drawer-with-toolbar-wrapper.types.ts
  packages/compass-components/src/components/drawer/drawer-with-toolbar-wrapper/index.ts
  packages/compass-components/src/components/drawer/drawer/drawer.constants.ts
  packages/compass-components/src/components/drawer/drawer/drawer.styles.ts
  packages/compass-components/src/components/drawer/drawer/drawer.tsx
  packages/compass-components/src/components/drawer/drawer/drawer.types.ts
  packages/compass-components/src/components/drawer/drawer/index.ts
  packages/compass-components/src/components/drawer/embedded-drawer-layout/embedded-drawer-layout.styles.ts
  packages/compass-components/src/components/drawer/embedded-drawer-layout/embedded-drawer-layout.tsx
  packages/compass-components/src/components/drawer/embedded-drawer-layout/embedded-drawer-layout.types.ts
  packages/compass-components/src/components/drawer/embedded-drawer-layout/index.tsx
  packages/compass-components/src/components/drawer/index.ts
  packages/compass-components/src/components/drawer/layout-component/index.ts
  packages/compass-components/src/components/drawer/layout-component/layout-component.styles.ts
  packages/compass-components/src/components/drawer/layout-component/layout-component.tsx
  packages/compass-components/src/components/drawer/overlay-drawer-layout/index.ts
  packages/compass-components/src/components/drawer/overlay-drawer-layout/overlay-drawer-layout.styles.ts
  packages/compass-components/src/components/drawer/overlay-drawer-layout/overlay-drawer-layout.tsx
  packages/compass-components/src/components/drawer/overlay-drawer-layout/overlay-drawer-layout.types.ts
  packages/compass-components/src/components/drawer/utils/get-lg-ids.ts
  packages/compass-components/src/components/drawer/utils/index.ts
  packages/compass-components/src/components/leafygreen.tsx
  packages/compass-components/src/components/toolbar/constants.ts
  packages/compass-components/src/components/toolbar/context/index.ts
  packages/compass-components/src/components/toolbar/context/toolbar-context.tsx
  packages/compass-components/src/components/toolbar/context/toolbar-context.types.ts
  packages/compass-components/src/components/toolbar/context/toolbar-descendants-context.tsx
  packages/compass-components/src/components/toolbar/index.ts
  packages/compass-components/src/components/toolbar/toolbar-icon-button/index.ts
  packages/compass-components/src/components/toolbar/toolbar-icon-button/toolbar-icon-button.styles.ts
  packages/compass-components/src/components/toolbar/toolbar-icon-button/toolbar-icon-button.tsx
  packages/compass-components/src/components/toolbar/toolbar-icon-button/toolbar-icon-button.types.ts
  packages/compass-components/src/components/toolbar/toolbar/index.ts
  packages/compass-components/src/components/toolbar/toolbar/toolbar.styles.ts
  packages/compass-components/src/components/toolbar/toolbar/toolbar.tsx
  packages/compass-components/src/components/toolbar/toolbar/toolbar.types.ts
  packages/compass-components/src/components/toolbar/utils/get-lg-ids.ts
  packages/compass-components/src/components/toolbar/utils/index.ts
Labels: no-title-validation

#7330 fix(compass-generative-ai): fix api contract and anticipate future change CLOUDP-344335
  packages/compass-collection/src/components/mock-data-generator-modal/mock-data-generator-modal.spec.tsx
  packages/compass-collection/src/components/mock-data-generator-modal/types.ts
  packages/compass-collection/src/modules/collection-tab.ts
  packages/compass-generative-ai/src/atlas-ai-service.spec.ts
  packages/compass-generative-ai/src/atlas-ai-service.ts
Labels: fix, no release notes

#7349 chore(data-modeling): memoize functions passed to diagramming
  packages/compass-data-modeling/src/components/diagram-editor.tsx
Labels: no-title-validation

#7342 feat(compass-collection): LLM Output Validation - Mock Data Generator CLOUDP-333855
  packages/compass-collection/src/components/mock-data-generator-modal/faker-mapping-selector.tsx
  packages/compass-collection/src/components/mock-data-generator-modal/faker-schema-editor-screen.tsx
  packages/compass-collection/src/components/mock-data-generator-modal/mock-data-generator-modal.spec.tsx
  packages/compass-collection/src/components/mock-data-generator-modal/script-generation-utils.spec.ts
  packages/compass-collection/src/components/mock-data-generator-modal/script-generation-utils.ts
  packages/compass-collection/src/components/mock-data-generator-modal/types.ts
  packages/compass-collection/src/modules/collection-tab.ts
  packages/compass-collection/src/schema-analysis-types.ts
  packages/compass-generative-ai/src/atlas-ai-service.spec.ts
  packages/compass-generative-ai/src/atlas-ai-service.ts
  packages/compass-generative-ai/src/index.ts
Labels: feat, no release notes

#7345 feat(compass-data-modeling): add info banner COMPASS-9773
  packages/compass-data-modeling/src/components/diagram-editor.spec.tsx
  packages/compass-data-modeling/src/components/diagram-editor.tsx
  packages/compass-data-modeling/src/store/diagram.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/data-modeling-tab.test.ts
Labels: feature flagged, feat

#7357 feat(database-collections): add uncompressed data stat field COMPASS-7691
  packages/compass-components/src/components/inline-definition.tsx
  packages/compass-workspaces/src/index.spec.tsx
  packages/data-service/src/data-service.ts
  packages/data-service/src/instance-detail-helper.ts
  packages/data-service/src/run-command.ts
  packages/database-model/index.d.ts
  packages/database-model/lib/model.js
  packages/databases-collections-list/src/collections.tsx
  packages/databases-collections-list/src/databases.tsx
  packages/databases-collections-list/src/index.spec.tsx
Labels: ready for review, release notes, feat

#7369 chore(deps): update mongodb-ns mongodb-schema to latest
  package-lock.json
  packages/collection-model/package.json
  packages/compass-aggregations/package.json
  packages/compass-app-stores/package.json
  packages/compass-collection/package.json
  packages/compass-crud/package.json
  packages/compass-data-modeling/package.json
  packages/compass-e2e-tests/package.json
  packages/compass-export-to-language/package.json
  packages/compass-field-store/package.json
  packages/compass-generative-ai/package.json
  packages/compass-global-writes/package.json
  packages/compass-import-export/package.json
  packages/compass-indexes/package.json
  packages/compass-query-bar/package.json
  packages/compass-saved-aggregations-queries/package.json
  packages/compass-schema-validation/package.json
  packages/compass-schema/package.json
  packages/compass-serverstats/package.json
  packages/compass-sidebar/package.json
  packages/compass-web/package.json
  packages/compass-workspaces/package.json
  packages/compass/package.json
  packages/data-service/package.json
  packages/databases-collections-list/package.json
  packages/databases-collections/package.json
Labels: no-title-validation

#7351 fix(preferences): use one enableGenAISampleDocumentPassing preference CLOUDP-346490
  packages/compass-e2e-tests/tests/atlas-cloud/collection-ai-query.test.ts
  packages/compass-generative-ai/src/components/ai-optin-modal.spec.tsx
  packages/compass-generative-ai/src/components/ai-optin-modal.tsx
  packages/compass-preferences-model/src/compass-web-preferences-access.ts
  packages/compass-preferences-model/src/preferences-schema.tsx
  packages/compass-web/sandbox/index.tsx
  packages/compass-web/sandbox/sandbox-atlas-sign-in.tsx
  packages/compass-web/src/preferences.tsx
Labels: fix, no release notes

#7364 chore(databases-collections-list): update db and collection name padding
  packages/databases-collections-list/src/collections.tsx
  packages/databases-collections-list/src/databases.tsx
  packages/databases-collections-list/src/items-grid.tsx
  packages/databases-collections-list/src/namespace-card.tsx
Labels: no-title-validation

#7372 feat(compass-assistant): track opening and closing the drawer sections COMPASS-9884
  packages/compass-assistant/src/components/assistant-chat.tsx
  packages/compass-components/src/components/compass-components-provider.tsx
  packages/compass-components/src/components/drawer-portal.spec.tsx
  packages/compass-components/src/components/drawer-portal.tsx
  packages/compass-telemetry/src/telemetry-events.ts
  packages/compass-web/src/entrypoint.tsx
  packages/compass/src/app/components/home.tsx
Labels: feature flagged, feat

#7383 chore(scripts): adjust create-workspace script for new tsconfig structure
  scripts/create-workspace.js
Labels: no-title-validation

#7384 fix(crud-toolbar): flickering in refresh button COMPASS-8138
  packages/compass-crud/src/components/crud-toolbar.tsx
Labels: release notes, fix

#7387 chore(data-modeling): bump diagramming, pass new options, remove related code
  package-lock.json
  package.json
  packages/compass-data-modeling/package.json
  packages/compass-data-modeling/src/components/diagram-editor.tsx
  packages/compass-data-modeling/src/utils/nodes-and-edges.spec.ts
  packages/compass-data-modeling/src/utils/nodes-and-edges.ts
Labels: feature flagged, no-title-validation

#7394 chore: period at the end of explain plan confirmation prompt
  packages/compass-assistant/src/prompts.ts
Labels: no-title-validation

#7382 fix(compass-indexes): make search indexes open in a new tab COMPASS-9904
  packages/compass-indexes/src/components/indexes/indexes.tsx
Labels: fix, no release notes
