Repository mongodb-js/compass, pull requests merged in 2025-02, with the labels that each got.

#6674 chore(ci): add workflow to test installers on GHA
  .github/workflows/test-installers.yml
Labels: no-title-validation

#6665 feat(schema): run schema analysis with secondaryPreferred when read pref not set COMPASS-8854
  packages/compass-schema/src/modules/schema-analysis.ts
  packages/compass-schema/src/stores/reducer.ts
  packages/compass-schema/src/stores/store.spec.ts
  packages/data-service/src/data-service.spec.ts
  packages/data-service/src/data-service.ts
Labels: release notes, feat

#6677 fix: dedupe log id 1_001_000_339
  packages/compass/src/app/utils/telemetry.ts
Labels: fix, no release notes, no-title-validation

#6663 feat(query-bar): allow users to set the default sort to be recent first COMPASS-6706
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-preferences-model/src/preferences-schema.ts
  packages/compass-preferences-model/src/provider.ts
  packages/compass-settings/src/components/settings/general.spec.tsx
  packages/compass-settings/src/components/settings/general.tsx
  packages/compass-settings/src/components/settings/settings-list.tsx
Labels: release notes, feat

#6678 chore(ci): explicitly define latest stable server to test against based on maintained versions; remove default fallback version
  .evergreen/buildvariants-and-tasks.in.yml
  .evergreen/buildvariants-and-tasks.yml
  .evergreen/print-compass-env.js
  .evergreen/print-compass-env.sh
Labels: no-title-validation

#6681 fix(hadron-type-checker): remove deprecated scope from code COMPASS-8921
  packages/hadron-type-checker/src/type-checker.js
Labels: fix, no release notes

#6669 feat(smoke-tests): test updating from the latest release to the newly packaged app COMPASS-8532 COMPASS-8535
  .evergreen/functions.yml
  packages/compass-e2e-tests/tests/auto-update.test.ts
  packages/compass-smoke-tests/src/build-info.ts
  packages/compass-smoke-tests/src/cli.ts
  packages/compass-smoke-tests/src/context.ts
  packages/compass-smoke-tests/src/installers/index.ts
  packages/compass-smoke-tests/src/releases.ts
  packages/compass-smoke-tests/src/test-subject.ts
  packages/compass-smoke-tests/src/tests/auto-update-from.ts
  packages/compass-smoke-tests/src/tests/auto-update-to.ts
  packages/compass-smoke-tests/src/tests/time-to-first-query.ts
  packages/compass-smoke-tests/src/tests/types.ts
  packages/compass-smoke-tests/src/tests/update-server.ts
Labels: feat, no release notes

#6671 feat(smoke-tests): test Setup.exe installer for on Windows COMPASS-8706
  .evergreen/functions.yml
  packages/compass-smoke-tests/src/installers/index.ts
  packages/compass-smoke-tests/src/installers/windows-registry.ts
  packages/compass-smoke-tests/src/installers/windows-setup.ts
Labels: feat, no release notes

#6684 feat(smoke-tests): test tar installer for on Ubuntu COMPASS-8711
  .evergreen/buildvariants-and-tasks.in.yml
  .evergreen/buildvariants-and-tasks.yml
  .evergreen/functions.yml
  packages/compass-smoke-tests/src/installers/index.ts
  packages/compass-smoke-tests/src/installers/linux-tar.ts
Labels: feat, no release notes

#6701 chore(smoketests): use debug rather than console.log
  package-lock.json
  packages/compass-smoke-tests/package.json
  packages/compass-smoke-tests/src/build-info.ts
  packages/compass-smoke-tests/src/cli.ts
  packages/compass-smoke-tests/src/downloads.ts
  packages/compass-smoke-tests/src/execute.ts
  packages/compass-smoke-tests/src/installers/mac-utils.ts
  packages/compass-smoke-tests/src/installers/windows-msi.ts
  packages/compass-smoke-tests/src/installers/windows-setup.ts
  packages/compass-smoke-tests/src/tests/auto-update-from.ts
  packages/compass-smoke-tests/src/tests/auto-update-to.ts
  packages/compass-smoke-tests/src/tests/time-to-first-query.ts
  packages/compass-smoke-tests/src/tests/update-server.ts
Labels: no release notes, no-title-validation

#6699 feat(smoke-tests): test deb installer for on Ubuntu COMPASS-8712
  .evergreen/functions.yml
  packages/compass-smoke-tests/src/installers/apt.ts
  packages/compass-smoke-tests/src/installers/index.ts
  packages/compass-smoke-tests/src/installers/linux-deb.ts
Labels: feat, no release notes, no-title-validation

#6700 feat(deps): bump query-parser and shell-bson-parser COMPASS-8942
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-crud/package.json
  packages/compass-editor/package.json
  packages/compass-export-to-language/package.json
  packages/compass-import-export/package.json
  packages/compass-indexes/package.json
  packages/compass-query-bar/package.json
  packages/compass-schema-validation/package.json
  packages/connection-form/package.json
  packages/databases-collections/package.json
  packages/explain-plan-helper/package.json
Labels: release notes, feat

#6703 Assert `response.ok` when downloading files
  packages/compass-smoke-tests/src/downloads.ts
Labels: no release notes, no-title-validation

#6705 chore(ci): grant beta/ga workflows permissions for actions
  .github/workflows/start-beta.yml
  .github/workflows/start-ga.yaml
Labels: no-title-validation

#6706 chore: update `.mailmap` with current contributors
  .mailmap
Labels: no-title-validation

#6707 fix(indexes): add namespace to the URL params for Atlas Search link COMPASS-8917
  package-lock.json
  packages/compass-indexes/package.json
  packages/compass-indexes/src/components/indexes/indexes.tsx
  packages/compass-indexes/src/utils/atlas-search-indexes-link.spec.ts
  packages/compass-indexes/src/utils/atlas-search-indexes-link.ts
Labels: fix, no release notes

#6704 feat(smoke-tests): test rpm installer for RHEL / Rocky linux COMPASS-8713
  .evergreen/buildvariants-and-tasks.in.yml
  .evergreen/buildvariants-and-tasks.yml
  .evergreen/functions.yml
  packages/compass-smoke-tests/src/installers/index.ts
  packages/compass-smoke-tests/src/installers/linux-rpm.ts
Labels: feat, no release notes

#6668 feat(schema): add schema export modal, feature flag gated COMPASS-8703
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-schema-tab.test.ts
  packages/compass-field-store/package.json
  packages/compass-generative-ai/package.json
  packages/compass-import-export/package.json
  packages/compass-preferences-model/src/feature-flags.ts
  packages/compass-query-bar/package.json
  packages/compass-schema/package.json
  packages/compass-schema/src/components/compass-schema.tsx
  packages/compass-schema/src/components/coordinates-minichart/coordinates-minichart.jsx
  packages/compass-schema/src/components/export-schema-modal.tsx
  packages/compass-schema/src/components/schema-toolbar/schema-toolbar.spec.tsx
  packages/compass-schema/src/components/schema-toolbar/schema-toolbar.tsx
  packages/compass-schema/src/modules/schema-analysis.spec.ts
  packages/compass-schema/src/modules/schema-analysis.ts
  packages/compass-schema/src/stores/schema-analysis-reducer.ts
  packages/compass-schema/src/stores/schema-export-reducer.ts
  packages/compass-schema/src/stores/store.spec.ts
  packages/compass-schema/src/stores/store.ts
  packages/compass-schema/src/utils.ts
Labels: feature flagged, feat, no release notes

#6709 fix: sign the windows setup .exe COMPASS-8945 COMPASS-8950
  .evergreen/verify-artifacts.sh
  package-lock.json
  packages/compass/.depcheckrc
  packages/compass/package.json
  packages/hadron-build/signtool/signtool.exe
  packages/hadron-build/signtool/signtool.go
Labels: release notes, fix

#6710 feat(sidebar): show loading state when initially loading connections COMPASS-8876
  configs/testing-library-compass/src/index.tsx
  packages/compass-connections/src/provider.ts
  packages/compass-connections/src/stores/connections-store-redux.spec.tsx
  packages/compass-connections/src/stores/connections-store-redux.ts
  packages/compass-connections/src/stores/store-context.tsx
  packages/compass-e2e-tests/helpers/commands/connect.ts
  packages/compass-e2e-tests/helpers/commands/disconnect.ts
  packages/compass-e2e-tests/helpers/commands/remove-connections.ts
  packages/compass-e2e-tests/helpers/commands/sidebar-connection.ts
  packages/compass-sidebar/src/components/connections-filter-popover.tsx
  packages/compass-sidebar/src/components/multiple-connections/connections-navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
  packages/compass-sidebar/src/components/navigation-items-filter.tsx
Labels: feat, no release notes

#6711 feat(sidebar): show header for Data Explorer COMPASS-8904
  packages/compass-sidebar/src/components/multiple-connections/header/sidebar-header.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
  packages/compass-sidebar/src/plugin.tsx
  packages/compass-web/src/entrypoint.tsx
Labels: feat, no release notes

#6577 feat(connections-navigation): connect in new window via connect split-button COMPASS-8473
  package-lock.json
  packages/compass-components/package.json
  packages/compass-components/src/components/actions/item-action-controls.tsx
  packages/compass-components/src/components/actions/item-action-group.tsx
  packages/compass-components/src/components/actions/item-action-menu.tsx
  packages/compass-components/src/components/actions/types.ts
  packages/compass-components/src/components/leafygreen.tsx
  packages/compass-components/src/index.ts
  packages/compass-connections-navigation/src/connect-button-with-menu.tsx
  packages/compass-connections-navigation/src/connect-button.tsx
  packages/compass-connections-navigation/src/constants.tsx
  packages/compass-connections/src/stores/connections-store-redux.ts
  packages/compass-connections/src/stores/store-context.tsx
  packages/compass-e2e-tests/helpers/compass.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/auto-connect.test.ts
  packages/compass-e2e-tests/tests/connection.test.ts
  packages/compass-preferences-model/src/preferences-schema.ts
  packages/compass-sidebar/src/components/multiple-connections/connections-navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.tsx
  packages/compass-web/src/preferences.tsx
  packages/compass/package.json
  packages/compass/src/app/index.tsx
  packages/compass/src/main/application.ts
  packages/compass/src/main/auto-connect.ts
  packages/compass/src/main/window-manager.ts
  packages/connection-storage/src/compass-main-connection-storage.spec.ts
  packages/connection-storage/src/compass-main-connection-storage.ts
Labels: release notes, feat

#6717 chore(schema): move non serializable services off of state to services
  packages/compass-schema/src/components/schema-toolbar/schema-toolbar.spec.tsx
  packages/compass-schema/src/modules/schema-analysis.spec.ts
  packages/compass-schema/src/modules/schema-analysis.ts
  packages/compass-schema/src/stores/schema-analysis-reducer.ts
  packages/compass-schema/src/stores/schema-export-reducer.ts
  packages/compass-schema/src/stores/store.ts
Labels: no release notes, no-title-validation

#6724 chore(smoke-tests): skip uninstalling when running on GHA
  .github/workflows/test-installers.yml
  packages/compass-smoke-tests/src/cli.ts
  packages/compass-smoke-tests/src/context.ts
  packages/compass-smoke-tests/src/tests/auto-update-from.ts
  packages/compass-smoke-tests/src/tests/auto-update-to.ts
  packages/compass-smoke-tests/src/tests/time-to-first-query.ts
Labels: no release notes, no-title-validation

#6725 chore(smoke-tests): Run RPM tests on Rocky linux
  .evergreen/functions.yml
  .github/workflows/test-installers.yml
  packages/compass-smoke-tests/src/installers/linux-rpm.ts
Labels: no release notes, no-title-validation

#6730 chore(compass): update restart menu item text to restart to update
  packages/compass/src/main/menu.spec.ts
  packages/compass/src/main/menu.ts
Labels: no release notes, no-title-validation

#6729 fix(schema): update maps from map tile API v2 to raster tile API v3 COMPASS-8981
  packages/compass-schema/src/components/coordinates-minichart/constants.js
  packages/compass-schema/src/components/coordinates-minichart/utils.js
Labels: release notes, fix

#6736 fix(compass-schema-validation): prevent losing changes in validation editor COMPASS-9003
  package-lock.json
  packages/compass-schema-validation/package.json
  packages/compass-schema-validation/src/index.ts
  packages/compass-schema-validation/src/modules/index.ts
  packages/compass-schema-validation/src/stores/store.spec.ts
  packages/compass-schema-validation/src/stores/store.ts
Labels: release notes, fix

#6731 fix(schema): use editor for rendering schema export instead of LG code for performance COMPASS-8980
  package-lock.json
  packages/compass-e2e-tests/tests/auto-connect.test.ts
  packages/compass-e2e-tests/tests/collection-schema-tab.test.ts
  packages/compass-editor/src/editor.tsx
  packages/compass-schema/package.json
  packages/compass-schema/src/components/export-schema-modal.tsx
Labels: feature flagged, fix, no release notes

#6734 chore(ci): update to silkbomb 2.0
  .evergreen/buildvariants-and-tasks.in.yml
  .evergreen/buildvariants-and-tasks.yml
  .evergreen/create-sbom.sh
  .evergreen/functions.yml
Labels: no-title-validation

#6739 fix(schema-validation): document preview overflow styles COMPASS-8997
  packages/compass-schema-validation/src/components/compass-schema-validation.tsx
  packages/compass-schema-validation/src/components/sample-documents.tsx
Labels: release notes, fix

#6733 fix(compass-schema): complexity and size limits COMPASS-8905 COMPASS-8984 COMPASS-8941
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-components/src/components/error-warning-summary.tsx
  packages/compass-field-store/package.json
  packages/compass-generative-ai/package.json
  packages/compass-import-export/package.json
  packages/compass-query-bar/package.json
  packages/compass-schema/package.json
  packages/compass-schema/src/components/compass-schema.tsx
  packages/compass-schema/src/components/schema-toolbar/schema-toolbar.spec.tsx
  packages/compass-schema/src/components/schema-toolbar/schema-toolbar.tsx
  packages/compass-schema/src/constants/analysis-states.ts
  packages/compass-schema/src/modules/schema-analysis.spec.ts
  packages/compass-schema/src/modules/schema-analysis.ts
  packages/compass-schema/src/stores/schema-analysis-reducer.ts
  packages/compass-schema/src/stores/store.spec.ts
Labels: fix, no release notes

#6745 chore(schema): pass abort signal to export schema formatters
  packages/compass-schema/src/stores/schema-export-reducer.ts
Labels: no release notes, no-title-validation

#6748 chore(compass-shell): update mongosh logging
  package-lock.json
  packages/compass-e2e-tests/package.json
  packages/compass-logging/package.json
  packages/compass-shell/package.json
  packages/compass-shell/src/modules/worker-runtime.ts
  packages/compass/package.json
  packages/data-service/package.json
Labels: no-title-validation

#6754 chore(deps): update driver and patch package-lock.json hoisting for mongosh packages
  package-lock.json
Labels: fix, no-title-validation

#6740 feat(schema): File download COMPASS-8704
  packages/compass-e2e-tests/helpers/compass.ts
  packages/compass-e2e-tests/helpers/downloads.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-schema-tab.test.ts
  packages/compass-schema/src/components/export-schema-modal.tsx
  packages/compass-schema/src/stores/schema-export-reducer.ts
  packages/compass-schema/src/stores/store.spec.ts
  packages/compass-telemetry/src/telemetry-events.ts
  packages/compass-web/sandbox/index.tsx
  packages/compass/src/app/utils/csp.ts
Labels: feature flagged, feat

#6752 chore(smoke-test): fail early and propagate task url
  .evergreen/functions.yml
  .github/workflows/test-installers.yml
  packages/compass-smoke-tests/src/cli.ts
  packages/compass-smoke-tests/src/dispatch.ts
Labels: no-title-validation

#6744 chore(schema): add tooltip showing folks the export button when they legacy export schema COMPASS-8971
  packages/compass-schema/src/components/compass-schema.tsx
  packages/compass-schema/src/components/export-schema-legacy-modal.tsx
  packages/compass-schema/src/components/schema-toolbar.spec.tsx
  packages/compass-schema/src/components/schema-toolbar.tsx
  packages/compass-schema/src/stores/schema-export-reducer.ts
  packages/compass-schema/src/stores/store.ts
Labels: no release notes
