Repository mongodb-js/compass, pull requests merged in 2025-08, with the labels that each got.

#7161 fix: add relationship fields items and anyOf support COMPASS-9649
  packages/compass-data-modeling/src/store/diagram.spec.ts
  packages/compass-data-modeling/src/store/diagram.ts
Labels: feature flagged, fix

#7162 fix: allow multiple highlighted fields COMPASS-9650
  packages/compass-data-modeling/src/components/diagram-editor.spec.tsx
  packages/compass-data-modeling/src/utils/nodes-and-edges.spec.tsx
  packages/compass-data-modeling/src/utils/nodes-and-edges.tsx
Labels: feature flagged, fix

#7156 feat(compass-collection): Add mock data generator modal container CLOUD-333848
  packages/compass-collection/src/components/mock-data-generator-modal/constants.ts
  packages/compass-collection/src/components/mock-data-generator-modal/mock-data-generator-modal.spec.tsx
  packages/compass-collection/src/components/mock-data-generator-modal/mock-data-generator-modal.tsx
  packages/compass-collection/src/components/mock-data-generator-modal/types.ts
  packages/compass-collection/src/components/mock-data-generator-modal/utils.spec.ts
  packages/compass-collection/src/components/mock-data-generator-modal/utils.ts
Labels: feat, no release notes

#7172 fix: scrolling the context menu shouldn't close it COMPASS-9584
  packages/compass-components/src/components/context-menu.tsx
  packages/compass-context-menu/src/consts.ts
  packages/compass-context-menu/src/context-menu-provider.tsx
  packages/compass-context-menu/src/index.ts
Labels: release notes, fix

#7146 feat(compass-data-modeling): add relationship via dragging COMPASS-9332
  packages/compass-data-modeling/src/components/diagram-editor-toolbar.spec.tsx
  packages/compass-data-modeling/src/components/diagram-editor-toolbar.tsx
  packages/compass-data-modeling/src/components/diagram-editor.tsx
  packages/compass-data-modeling/src/store/diagram.ts
  packages/compass-data-modeling/src/utils/nodes-and-edges.tsx
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/data-modeling-tab.test.ts
Labels: feature flagged, feat

#7174 feat(data-modeling): add rename collection to side panel COMPASS-9658
  package-lock.json
  packages/compass-data-modeling/src/components/drawer/collection-drawer-content.tsx
  packages/compass-data-modeling/src/components/drawer/diagram-editor-side-panel.spec.tsx
  packages/compass-data-modeling/src/services/data-model-storage.ts
  packages/compass-data-modeling/src/store/diagram.ts
  packages/compass-e2e-tests/package.json
  packages/compass-e2e-tests/tests/data-modeling-tab.test.ts
Labels: feature flagged, feat

#7190 chore(data-modeling): use change on blur hook for collection name for consistency
  packages/compass-data-modeling/src/components/drawer/collection-drawer-content.tsx
Labels: no-title-validation

#7189 chore(compass-assistant): add compass AI assistant with placeholders COMPASS-9603
  package-lock.json
  packages/atlas-service/src/atlas-service.spec.ts
  packages/atlas-service/src/atlas-service.ts
  packages/atlas-service/src/main.spec.ts
  packages/atlas-service/src/util.ts
  packages/compass-assistant/.depcheckrc
  packages/compass-assistant/.eslintignore
  packages/compass-assistant/.eslintrc.js
  packages/compass-assistant/.mocharc.js
  packages/compass-assistant/package.json
  packages/compass-assistant/src/@ai-sdk/react/chat-react.ts
  packages/compass-assistant/src/@ai-sdk/react/throttle.ts
  packages/compass-assistant/src/@ai-sdk/react/use-chat.ts
  packages/compass-assistant/src/assistant-chat.spec.tsx
  packages/compass-assistant/src/assistant-chat.tsx
  packages/compass-assistant/src/assistant-provider.tsx
  packages/compass-assistant/src/docs-provider-transport.ts
  packages/compass-assistant/src/index.spec.tsx
  packages/compass-assistant/src/index.tsx
  packages/compass-assistant/tsconfig-lint.json
  packages/compass-assistant/tsconfig.json
  packages/compass-preferences-model/src/feature-flags.ts
  packages/compass-web/package.json
  packages/compass-web/src/entrypoint.tsx
  packages/compass/package.json
  packages/compass/src/app/components/home.tsx
  packages/compass/src/app/utils/csp.ts
Labels: feature flagged

#7114 feat(save-user-data): extend user data abstract class for api backend COMPASS-9558
  package-lock.json
  packages/atlas-service/src/atlas-service.spec.ts
  packages/atlas-service/src/atlas-service.ts
  packages/atlas-service/src/main.spec.ts
  packages/atlas-service/src/secret-store.ts
  packages/atlas-service/src/util.ts
  packages/compass-data-modeling/src/services/data-model-storage-electron.tsx
  packages/compass-preferences-model/src/preferences-persistent-storage.ts
  packages/compass-preferences-model/src/user-storage.ts
  packages/compass-shell/src/modules/history-storage.ts
  packages/compass-user-data/src/index.ts
  packages/compass-user-data/src/user-data.spec.ts
  packages/compass-user-data/src/user-data.ts
  packages/connection-storage/src/compass-main-connection-storage.ts
  packages/my-queries-storage/src/compass-pipeline-storage.spec.ts
  packages/my-queries-storage/src/compass-pipeline-storage.ts
  packages/my-queries-storage/src/compass-query-storage.ts
  packages/my-queries-storage/src/pipeline-storage.ts
  packages/my-queries-storage/src/query-storage.ts
Labels: feat, no release notes

#7205 feat(compass-collection): Process schema into format for LLM submission for Mock Data Generator – CLOUDP-337090
  package-lock.json
  packages/compass-collection/package.json
  packages/compass-collection/src/modules/collection-tab.ts
  packages/compass-collection/src/schema-analysis-types.ts
  packages/compass-collection/src/transform-schema-to-field-info.spec.ts
  packages/compass-collection/src/transform-schema-to-field-info.ts
Labels: feat, no release notes

#7195 feat(data-modeling): add collection COMPASS-9655
  configs/webpack-config-compass/src/index.ts
  package-lock.json
  packages/compass-components/src/components/drawer-portal.spec.tsx
  packages/compass-components/src/components/drawer-portal.tsx
  packages/compass-data-modeling/package.json
  packages/compass-data-modeling/src/components/diagram-editor-toolbar.spec.tsx
  packages/compass-data-modeling/src/components/diagram-editor-toolbar.tsx
  packages/compass-data-modeling/src/components/diagram-editor.spec.tsx
  packages/compass-data-modeling/src/components/diagram-editor.tsx
  packages/compass-data-modeling/src/components/drawer/collection-drawer-content.tsx
  packages/compass-data-modeling/src/components/drawer/diagram-editor-side-panel.spec.tsx
  packages/compass-data-modeling/src/components/icons/add-collection.tsx
  packages/compass-data-modeling/src/services/data-model-storage.ts
  packages/compass-data-modeling/src/store/diagram.spec.ts
  packages/compass-data-modeling/src/store/diagram.ts
  packages/compass-e2e-tests/helpers/compass-web-sandbox.ts
  packages/compass-e2e-tests/helpers/compass.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/data-modeling-tab.test.ts
Labels: feature flagged, feat

#7198 feat(compass-aggregations): add confirm banner for edit pipeline and new banners COMPASS-9700
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-aggregations/src/modules/search-indexes.ts
  packages/compass-aggregations/src/modules/update-view.spec.ts
  packages/compass-aggregations/src/modules/update-view.ts
  packages/compass-aggregations/src/utils/stage.spec.ts
  packages/compass-collection/package.json
  packages/compass-editor/package.json
  packages/compass-indexes/package.json
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.spec.tsx
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
  packages/compass-indexes/src/components/indexes/indexes.spec.tsx
  packages/compass-indexes/src/components/indexes/indexes.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.spec.tsx
  packages/compass-indexes/src/components/search-indexes-table/search-indexes-table.tsx
  packages/compass-indexes/src/components/view-version-incompatible-banners/view-version-incompatible-banners.tsx
  packages/compass-indexes/src/modules/collection-stats.ts
  packages/compass-indexes/src/modules/search-indexes.ts
  packages/compass-query-bar/package.json
  packages/compass-schema-validation/package.json
  packages/compass-sidebar/package.json
Labels: feat, no release notes

#7215 chore(e2e-tests): wait for data modeling components in tests
  packages/compass-e2e-tests/tests/data-modeling-tab.test.ts
Labels: no-title-validation

#7223 chore(components): use npm overrides to force transitive leafygreen dependencies to the same version of shared packages
  configs/eslint-plugin-compass/rules/no-leafygreen-outside-compass-components.js
  package-lock.json
  package.json
  packages/compass-assistant/src/assistant-chat.spec.tsx
  packages/compass-assistant/src/assistant-chat.tsx
  packages/compass-assistant/src/compass-assistant-provider.spec.tsx
  packages/compass-collection/src/components/collection-tab.tsx
  packages/compass-components/package.json
  packages/compass-components/scripts/patch-leafygreen-button.js
  packages/compass-components/src/components/leafygreen.tsx
  packages/compass-data-modeling/package.json
Labels: no-title-validation

#7222 fix(logger): replace PassThrough with Writable for log handling COMPASS-9736
  packages/compass-connections/src/stores/connections-store-redux.ts
  packages/compass-web/src/logger.spec.tsx
  packages/compass-web/src/logger.tsx
  packages/data-service/src/data-service.spec.ts
  packages/data-service/src/data-service.ts
Labels: fix, no release notes

#7230 chore(ci): use one github action with variants for package bumps
  .github/workflows/update-dependencies.yaml
  .github/workflows/update-electron.yaml
  .github/workflows/update-eslint.yaml
  scripts/update-dependencies-config.js
  scripts/update-dependencies.js
Labels: no-title-validation

#7224 feat(compass-assistant): connection error entrypoint COMPASS-9605
  package-lock.json
  packages/compass-assistant/package.json
  packages/compass-assistant/src/compass-assistant-drawer.tsx
  packages/compass-assistant/src/compass-assistant-provider.spec.tsx
  packages/compass-assistant/src/compass-assistant-provider.tsx
  packages/compass-assistant/src/index.tsx
  packages/compass-assistant/src/prompts.ts
  packages/compass-connections/package.json
  packages/compass-connections/src/components/connection-status-notifications.tsx
  packages/compass-connections/src/index.tsx
  packages/compass-connections/src/stores/connections-store-redux.spec.tsx
  packages/compass-connections/src/stores/connections-store-redux.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/connection.test.ts
  packages/compass/src/app/components/home.tsx
Labels: feature flagged, feat

#7234 fix(ci): build matrix value dynamically based on optional dispatch input
  .github/workflows/update-dependencies.yaml
Labels: fix, no release notes, no-title-validation

#7242 chore(scripts): allow to pass force flag when updating via script
  scripts/update-dependencies.js
Labels: no-title-validation

#7237 feat(compass-data-modeling): delete and rename field COMPASS-9659
  packages/compass-data-modeling/src/components/drawer/diagram-editor-side-panel.spec.tsx
  packages/compass-data-modeling/src/components/drawer/diagram-editor-side-panel.tsx
  packages/compass-data-modeling/src/components/drawer/field-drawer-content.tsx
  packages/compass-data-modeling/src/services/data-model-storage.ts
  packages/compass-data-modeling/src/store/apply-edit.ts
  packages/compass-data-modeling/src/store/diagram.ts
  packages/compass-data-modeling/src/utils/schema-traversal.spec.tsx
  packages/compass-data-modeling/src/utils/schema-traversal.tsx
  packages/compass-data-modeling/src/utils/utils.spec.tsx
  packages/compass-data-modeling/src/utils/utils.ts
Labels: feature flagged, feat
