Repository mongodb-js/compass, pull requests merged in 2025-06, with the labels that each got.

#6978 fix(shell): prevent horizontal overflow scroll COMPASS-9418
  packages/compass-shell/src/components/compass-shell/tab-compass-shell.tsx
Labels: release notes, fix

#6975 chore(aggregations,schema-validation,shell): replace enzyme usage with react-testing-library
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-aggregations/src/components/saving-pipeline-modal/saving-pipeline-modal.spec.ts
  packages/compass-aggregations/src/components/settings/settings.spec.tsx
  packages/compass-aggregations/src/components/settings/settings.tsx
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-schema-validation/package.json
  packages/compass-schema-validation/src/components/compass-schema-validation.spec.tsx
  packages/compass-schema-validation/src/components/document-preview.spec.tsx
  packages/compass-shell/package.json
  packages/compass-shell/src/components/shell-header/shell-header.spec.tsx
  packages/compass-shell/src/components/shell-header/shell-header.tsx
  packages/compass-shell/src/components/shell-info-modal/shell-info-modal.spec.tsx
  packages/compass-shell/src/modules/worker-runtime.ts
Labels: no-title-validation

#6964 feat(electron): update electron to v36 COMPASS-9098
  configs/webpack-config-compass/package.json
  package-lock.json
  packages/atlas-service/package.json
  packages/compass-crud/package.json
  packages/compass-e2e-tests/package.json
  packages/compass-explain-plan/package.json
  packages/compass-find-in-page/package.json
  packages/compass-import-export/package.json
  packages/compass-indexes/package.json
  packages/compass-query-bar/package.json
  packages/compass-schema-validation/package.json
  packages/compass-shell/package.json
  packages/compass-utils/package.json
  packages/compass-web/package.json
  packages/compass/package.json
  packages/compass/src/main/menu.ts
  packages/connection-storage/package.json
  packages/hadron-build/package.json
  packages/hadron-ipc/package.json
  scripts/package.json
  scripts/update-electron.js
Labels: release notes, feat

#6984 fix: update tar-fs to fix vulnerability
  package-lock.json
Labels: release notes, fix, no-title-validation

#6972 feat: Implement dark mode for create index modal in early journey variant CLOUDP-313986
  packages/compass-indexes/src/components/create-index-form/index-flow-section.tsx
  packages/compass-indexes/src/components/create-index-form/query-flow-section.tsx
  packages/compass-indexes/src/components/create-index-modal/create-index-modal-header.tsx
Labels: feat, no release notes

#6990 fix: link to vector search docs when editing vector indexes COMPASS-9435
  packages/compass-indexes/src/components/search-indexes-modals/base-search-index-modal.tsx
  packages/compass-indexes/src/components/search-indexes-modals/update-search-index-modal.spec.tsx
Labels: release notes, fix

#6991 fix: set --gtk-version=3 on linux COMPASS-9437
  packages/compass/src/main/application.ts
Labels: release notes, fix

#6998 fix(editor): remove `EDIT_CONTEXT` workaround COMPASS-9131
  packages/compass-editor/src/editor.tsx
Labels: release notes, fix

#6985 chore(web): manually split bundle into multiple chunks
  packages/compass-web/webpack.config.js
Labels: no-title-validation

#6999 fix(aggregations): pass dataService to redux thunk arg, fix types COMPASS-9375
  packages/compass-aggregations/src/modules/index.ts
  packages/compass-aggregations/src/stores/store.ts
Labels: release notes, fix

#7007 fix(e2e): wait for the footer to update with the error
  packages/compass-e2e-tests/tests/in-use-encryption.test.ts
Labels: fix, no release notes, no-title-validation

#7010 chore(eslint-config): update typescript-eslint to latest
  .github/workflows/update-eslint.yaml
  configs/eslint-config-compass/index.js
  configs/eslint-config-compass/package.json
  configs/eslint-config-compass/plugin.js
  package-lock.json
  package.json
  packages/compass-components/src/components/virtual-list.tsx
  packages/compass-connection-import-export/src/hooks/use-export-connections.ts
  packages/compass-connection-import-export/src/hooks/use-import-connections.ts
  packages/compass-connections-navigation/src/connections-navigation-tree.tsx
  packages/compass-crud/src/components/table-view/document-table-view.tsx
  packages/compass-import-export/.eslintrc.js
  packages/compass/src/main/auto-connect.spec.ts
Labels: no-title-validation

#7021 fix(deps): bump mongosh to latest COMPASS-9424 COMPASS-9419
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-data-modeling/package.json
  packages/compass-field-store/package.json
  packages/compass-generative-ai/package.json
  packages/compass-import-export/package.json
  packages/compass-query-bar/package.json
  packages/compass-schema/package.json
  packages/compass-shell/package.json
  packages/compass/package.json
Labels: release notes, fix

#7012 feat: Update covered queries with new links, esr order swap, copy change CLOUDP-323671
  packages/compass-indexes/src/components/create-index-fields.tsx
  packages/compass-indexes/src/components/create-index-form/index-flow-section.spec.tsx
  packages/compass-indexes/src/components/create-index-form/index-flow-section.tsx
  packages/compass-indexes/src/components/create-index-form/query-flow-section.tsx
  packages/compass-indexes/src/components/create-index-modal/create-index-modal.tsx
  packages/compass-telemetry/src/telemetry-events.ts
Labels: feat, no release notes, no-title-validation

#7024 chore(crud): explicitly not await for store actions in render
  packages/compass-crud/src/components/editable-document.tsx
  packages/compass-crud/src/components/json-editor.tsx
  packages/compass-crud/src/components/table-view/document-table-view.tsx
  packages/compass-crud/src/components/table-view/full-width-cell-renderer.tsx
Labels: no-title-validation

#6979 feat(data-modeling): integrate diagramming package COMPASS-9357
  .evergreen/print-compass-env.sh
  configs/webpack-config-compass/src/index.ts
  package-lock.json
  packages/compass-data-modeling/package.json
  packages/compass-data-modeling/src/components/data-modeling.tsx
  packages/compass-data-modeling/src/components/diagram-editor.tsx
  packages/compass-data-modeling/src/store/diagram.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/data-modeling-tab.test.ts
Labels: feat, no release notes

#7025 chore: cleanup package-lock from removed workspaces
  package-lock.json
Labels: no-title-validation

#7029 chore(e2e-tests): update interval on starting import to ensure we disconnect before fully importing
  packages/compass-e2e-tests/tests/collection-import.test.ts
Labels: no release notes, no-title-validation

#6997 feat(workspaces): move tab rendering to the plugins COMPASS-9413
  packages/compass-collection/src/index.ts
  packages/compass-collection/src/plugin-tab-title.tsx
  packages/compass-components/src/components/workspace-tabs/tab.tsx
  packages/compass-components/src/components/workspace-tabs/workspace-tabs.spec.tsx
  packages/compass-components/src/components/workspace-tabs/workspace-tabs.tsx
  packages/compass-components/src/index.ts
  packages/compass-data-modeling/src/index.spec.tsx
  packages/compass-data-modeling/src/index.ts
  packages/compass-data-modeling/src/plugin-tab-title.tsx
  packages/compass-saved-aggregations-queries/src/index.spec.tsx
  packages/compass-saved-aggregations-queries/src/index.ts
  packages/compass-saved-aggregations-queries/src/plugin-tab-title.tsx
  packages/compass-saved-aggregations-queries/src/stores/index.ts
  packages/compass-serverstats/src/index.ts
  packages/compass-serverstats/src/plugin-tab-title.tsx
  packages/compass-shell/src/index.ts
  packages/compass-shell/src/plugin-tab-title.tsx
  packages/compass-shell/src/plugin.spec.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
  packages/compass-welcome/src/index.ts
  packages/compass-welcome/src/plugin-tab-title.tsx
  packages/compass-workspaces/src/components/index.tsx
  packages/compass-workspaces/src/components/workspace-close-handler.tsx
  packages/compass-workspaces/src/components/workspace-tab-context-provider.tsx
  packages/compass-workspaces/src/components/workspaces-provider.tsx
  packages/compass-workspaces/src/components/workspaces.tsx
  packages/compass-workspaces/src/index.spec.tsx
  packages/compass-workspaces/src/index.ts
  packages/compass-workspaces/src/provider.tsx
  packages/compass-workspaces/src/stores/workspaces.spec.ts
  packages/compass-workspaces/src/stores/workspaces.ts
  packages/compass-workspaces/src/types.ts
  packages/databases-collections/src/collections-plugin-title.tsx
  packages/databases-collections/src/collections-plugin.spec.tsx
  packages/databases-collections/src/collections-plugin.tsx
  packages/databases-collections/src/databases-plugin-title.tsx
  packages/databases-collections/src/databases-plugin.spec.tsx
  packages/databases-collections/src/databases-plugin.tsx
  packages/databases-collections/src/index.ts
  packages/databases-collections/src/stores/databases-store.ts
Labels: feat, no release notes

#7030 fix(test): deflake diagram-editor tests COMPASS-9462
  packages/compass-data-modeling/src/components/diagram-editor.tsx
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/data-modeling-tab.test.ts
Labels: fix, no release notes

#7034 chore(deps): disable custom dependabot rules
  .github/_dependabot.yml
Labels: no-title-validation

#6982 chore(intercom): Add request to the update server to determine if Intercom integration is allowed COMPASS-9371
  packages/compass-e2e-tests/tests/proxy.test.ts
  packages/compass-intercom/src/setup-intercom.spec.ts
  packages/compass-intercom/src/setup-intercom.ts
  packages/compass/src/app/utils/csp.ts
Labels: no release notes

#7036 feat: Fix the state management for the two flows (disabled state, displaying covered queries) CLOUDP-325467
  packages/compass-indexes/src/components/create-index-form/create-index-form.tsx
  packages/compass-indexes/src/components/create-index-form/index-flow-section.spec.tsx
  packages/compass-indexes/src/components/create-index-form/index-flow-section.tsx
  packages/compass-indexes/src/components/create-index-form/query-flow-section.spec.tsx
  packages/compass-indexes/src/components/create-index-form/query-flow-section.tsx
  packages/compass-indexes/src/components/create-index-modal/create-index-modal.tsx
  packages/compass-indexes/src/components/indexes/indexes.tsx
  packages/compass-indexes/src/modules/create-index.spec.ts
  packages/compass-indexes/src/modules/create-index.tsx
  packages/compass-indexes/src/stores/store.ts
Labels: feat, no release notes

#7035 chore(workspaces): move workspace tab theming to provider
  packages/compass-collection/src/plugin-tab-title.tsx
  packages/compass-components/src/components/workspace-tabs/tab.tsx
  packages/compass-components/src/components/workspace-tabs/use-tab-theme.tsx
  packages/compass-components/src/index.ts
  packages/compass-connections/src/hooks/connection-tab-theme-provider.spec.tsx
  packages/compass-connections/src/hooks/connection-tab-theme-provider.tsx
  packages/compass-connections/src/hooks/use-tab-connection-theme.spec.ts
  packages/compass-connections/src/hooks/use-tab-connection-theme.ts
  packages/compass-connections/src/provider.ts
  packages/compass-serverstats/src/plugin-tab-title.tsx
  packages/compass-shell/src/plugin-tab-title.tsx
  packages/compass-workspaces/src/components/workspace-tab-context-provider.tsx
  packages/databases-collections/src/collections-plugin-title.tsx
  packages/databases-collections/src/databases-plugin-title.tsx
Labels: no release notes, no-title-validation

#7057 chore(deps): hoist mongodb-schema package
  package-lock.json
Labels: no-title-validation

#7047 feat: apply initial layout COMPASS-9432
  package-lock.json
  packages/compass-data-modeling/package.json
  packages/compass-data-modeling/src/components/diagram-editor.spec.tsx
  packages/compass-data-modeling/src/components/diagram-editor.tsx
  packages/compass-data-modeling/src/index.spec.tsx
  packages/compass-data-modeling/src/index.ts
  packages/compass-data-modeling/src/services/data-model-storage.ts
  packages/compass-data-modeling/src/store/diagram.spec.ts
  packages/compass-data-modeling/src/store/diagram.ts
  packages/compass-e2e-tests/tests/data-modeling-tab.test.ts
  packages/compass-web/sandbox/index.tsx
  packages/compass-web/src/entrypoint.tsx
  packages/compass/src/app/components/workspace.tsx
Labels: feature flagged, feat

#7062 feat(data-modeling): show mixed type information on node field COMPASS-9433
  package-lock.json
  packages/compass-data-modeling/package.json
  packages/compass-data-modeling/src/components/diagram-editor.tsx
Labels: feature flagged, feat, no release notes
