Repository mongodb-js/compass, pull requests merged in 2025-01, with the labels that each got.

#6585 fix(connections): adjust status marker position CLOUDP-289203
  packages/compass-connections-navigation/src/with-status-marker.tsx
Labels: release notes, fix

#6588 fix(compass-web): update sandbox toast action to make actions visible
  packages/compass-web/sandbox/sandbox-atlas-sign-in.tsx
Labels: fix, no release notes, no-title-validation

#6587 fix(compass-web): add tracking for compass-provider COMPASS-8658
  packages/compass-web/src/entrypoint.tsx
Labels: release notes, fix

#6591 chore: gha workflow updates
  .github/workflows/codeql.yml
  .github/workflows/publish-compass.yaml
  .github/workflows/publish-packages.yaml
  .github/workflows/start-beta.yml
  .github/workflows/start-ga.yaml
  .github/workflows/update-electron.yaml
Labels: no-title-validation

#6594 chore(e2e): Smoke test cli cleanup
  packages/compass-e2e-tests/smoke-test.ts
Labels: no-title-validation

#6595 chore(indexes): do not show rolling indexes UI for flex tier clusters COMPASS-8622
  packages/compass-connections/src/utils/connection-supports.spec.ts
  packages/compass-connections/src/utils/connection-supports.ts
Labels: no release notes

#6596 chore(telemetry): add is_compass_web to tracking event types
  packages/compass-telemetry/src/index.spec.tsx
  packages/compass-telemetry/src/telemetry-events.ts
Labels: no-title-validation

#6593 feat(compass-web): add welcome page COMPASS-8657
  packages/compass-connections/src/stores/connections-store-redux.ts
  packages/compass-web/src/entrypoint.tsx
  packages/compass-welcome/src/components/desktop-welcome-tab.spec.tsx
  packages/compass-welcome/src/components/desktop-welcome-tab.tsx
  packages/compass-welcome/src/components/index.ts
  packages/compass-welcome/src/components/modal.tsx
  packages/compass-welcome/src/components/web-welcome-tab.spec.tsx
  packages/compass-welcome/src/components/web-welcome-tab.tsx
  packages/compass-welcome/src/components/welcome-image.tsx
  packages/compass-welcome/src/components/welcome-tab.tsx
  packages/compass-welcome/src/index.ts
  packages/compass/src/app/components/workspace.tsx
Labels: release notes, feat

#6599 feat(compass-web): add onFailToLoadConnections callback COMPASS-8657
  configs/testing-library-compass/src/index.tsx
  packages/compass-connections/src/index.tsx
  packages/compass-connections/src/stores/connections-store-redux.spec.tsx
  packages/compass-connections/src/stores/connections-store-redux.ts
  packages/compass-web/sandbox/index.tsx
  packages/compass-web/src/entrypoint.spec.tsx
  packages/compass-web/src/entrypoint.tsx
  packages/compass/src/app/components/home.tsx
Labels: release notes, feat

#6605 chore(monorepo): remove legacy-peer-deps from the npmrc
  .npmrc
  package-lock.json
Labels: no-title-validation

#6600 chore(e2e): Lint for restricted globals in e2e tests
  package-lock.json
  packages/compass-e2e-tests/.eslintrc.js
  packages/compass-e2e-tests/helpers/commands/codemirror.ts
  packages/compass-e2e-tests/helpers/commands/scroll-to-virtual-item.ts
  packages/compass-e2e-tests/helpers/commands/select-file.ts
  packages/compass-e2e-tests/helpers/commands/set-export-filename.ts
  packages/compass-e2e-tests/helpers/compass-web-sandbox.ts
  packages/compass-e2e-tests/helpers/compass.ts
  packages/compass-e2e-tests/helpers/telemetry.ts
  packages/compass-e2e-tests/package.json
  packages/compass-e2e-tests/tests/auto-connect.test.ts
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
  packages/compass-e2e-tests/tests/intercom.test.ts
  packages/compass-e2e-tests/tsconfig-lint.json
  packages/compass-e2e-tests/tsconfig.json
Labels: no-title-validation

#6609 fix(compass-web): Show search indexes banner instead of disabled search indexes feature toggle in compass-web COMPASS-8802 CLOUDP-289698
  packages/compass-web/src/preferences.tsx
Labels: fix, no release notes

#6612 feat(compass): show the autoupdate installed toast even when we downgrade COMPASS-8808
  packages/compass/src/app/components/update-toasts.tsx
  packages/compass/src/app/index.tsx
Labels: feat, no release notes

#6607 chore(e2e): few suggestions to smoke-test.ts
  packages/compass-e2e-tests/smoke-test.ts
Labels: no-title-validation

#6613 fix(e2e): do not pass version to hadron build info - have it figure it out on its own COMPASS-8812
  packages/compass-e2e-tests/smoke-test.ts
Labels: fix, no release notes, no-title-validation

#6610 Re-revert: chore(ci): do not apply 'skip actions' to automatically generated commit COMPASS-8789
  .github/workflows/authors-and-third-party-notices.yaml
  scripts/generate-tracking-plan.ts
Labels: no-title-validation

#6614 chore(e2e): remove the retry
  packages/compass-e2e-tests/tests/time-to-first-query.test.ts
Labels: no-title-validation

#6616 chore(e2e): forgot to remove half the comment
  packages/compass-e2e-tests/tests/time-to-first-query.test.ts
Labels: no-title-validation

#6611 fix(compass-web): Rename connections list to clusters list in compass-web COMPASS-8698
  packages/compass-sidebar/src/components/multiple-connections/connections-navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
  packages/compass-sidebar/src/index.ts
  packages/compass-web/src/entrypoint.tsx
Labels: fix, no release notes

#6618 chore(e2e): throw if we're unexpectedly building Compass COMPASS-8615
  packages/compass-e2e-tests/helpers/compass.ts
  packages/compass-e2e-tests/helpers/test-runner-global-fixtures.ts
Labels: no release notes

#6619 chore: scp -v to try and debug timeouts
  .evergreen/create-sbom.sh
Labels: no-title-validation

#6617 feat(database-collections): remove option to create capped coll COMPASS-8292
  packages/collection-model/lib/collection-properties.js
  packages/collection-model/lib/model.js
  packages/compass-e2e-tests/helpers/commands/add-collection.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/database-collections-tab.test.ts
  packages/compass-telemetry/src/telemetry-events.ts
  packages/databases-collections/src/components/collection-fields/capped-collection-fields.jsx
  packages/databases-collections/src/components/collection-fields/capped-collection-fields.spec.jsx
  packages/databases-collections/src/components/collection-fields/clustered-collection-fields.jsx
  packages/databases-collections/src/components/collection-fields/clustered-collection-fields.spec.jsx
  packages/databases-collections/src/components/collection-fields/collection-fields.jsx
  packages/databases-collections/src/components/collection-fields/collection-fields.spec.jsx
  packages/databases-collections/src/components/collection-fields/fle2-fields.jsx
  packages/databases-collections/src/components/collection-fields/fle2-fields.spec.jsx
  packages/databases-collections/src/components/collection-fields/time-series-fields.jsx
  packages/databases-collections/src/components/collection-fields/time-series-fields.spec.jsx
  packages/databases-collections/src/modules/create-namespace.ts
Labels: release notes, feat

#6615 fix(e2e-tests): close the focus-mode modal COMPASS-8820
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
Labels: fix, no release notes

#6623 Add `autoUpdatable` flag and refactor installer logic
  packages/compass-e2e-tests/helpers/smoke-test/build-info.ts
  packages/compass-e2e-tests/smoke-test.ts
Labels: no-title-validation

#6622 fix(compass-import-export): handle export flake COMPASS-8839
  packages/compass-import-export/src/export/export-json.spec.ts
  packages/compass-import-export/src/export/export-json.ts
Labels: fix, no release notes

#6626 chore(e2e): reuse the existing connection for the second test
  packages/compass-e2e-tests/tests/time-to-first-query.test.ts
Labels: no-title-validation

#6624 fix(atlas-service): dont signin twice in tests COMPASS-8837
  packages/atlas-service/src/store/atlas-signin-reducer.spec.ts
Labels: fix, no release notes

#6627 chore(ci): move e2e secrets to their own anchor
  .evergreen/functions.yml
  packages/data-service/package.json
Labels: no-title-validation

#6625 chore(smoke-tests): move files into its own package
  .evergreen/functions.yml
  package-lock.json
  packages/compass-e2e-tests/.gitignore
  packages/compass-e2e-tests/.prettierignore
  packages/compass-e2e-tests/package.json
  packages/compass-smoke-tests/.depcheckrc
  packages/compass-smoke-tests/.eslintignore
  packages/compass-smoke-tests/.eslintrc.js
  packages/compass-smoke-tests/.gitignore
  packages/compass-smoke-tests/.prettierignore
  packages/compass-smoke-tests/.prettierrc.json
  packages/compass-smoke-tests/package.json
  packages/compass-smoke-tests/src/build-info.ts
  packages/compass-smoke-tests/src/cli.ts
  packages/compass-smoke-tests/src/context.ts
  packages/compass-smoke-tests/src/directories.ts
  packages/compass-smoke-tests/src/downloads.ts
  packages/compass-smoke-tests/src/execute.ts
  packages/compass-smoke-tests/src/installers/mac-dmg.ts
  packages/compass-smoke-tests/src/installers/mac-zip.ts
  packages/compass-smoke-tests/src/installers/types.ts
  packages/compass-smoke-tests/src/packages.ts
  packages/compass-smoke-tests/tsconfig.json
Labels: no-title-validation

#6628 fix(e2e-tests): wait for modal to disappear COMPASS-8847
  packages/compass-e2e-tests/helpers/commands/save-aggregation-pipeline.ts
Labels: fix, no release notes

#6630 chore(ci): retry the scp and ssh commands in create-sbom.sh
  .evergreen/functions.yml
Labels: no release notes, no-title-validation

#6632 chore(ci): ignore more files as ci triggers in Evergreen
  .evergreen.yml
Labels: no-title-validation

#6633 chore(ci): use encoded cert in e2e tests
  .evergreen/connectivity-tests/run.sh
  .evergreen/functions.yml
  packages/compass-e2e-tests/tests/connection.test.ts
  packages/data-service/src/connect.spec.ts
Labels: no-title-validation

#6631 fix(typo): "no longer exists"
  packages/compass-components/src/components/document-list/document-edit-actions-footer.tsx
Labels: no release notes, no-title-validation

#6637 feat(smoke-tests): test zip installer for on Windows COMPASS-8710
  .evergreen/buildvariants-and-tasks.in.yml
  .evergreen/buildvariants-and-tasks.yml
  .evergreen/functions.yml
  packages/compass-smoke-tests/src/build-info.ts
  packages/compass-smoke-tests/src/cli.ts
  packages/compass-smoke-tests/src/installers/windows-zip.ts
Labels: feat, no release notes

#6643 chore(ci): remove publish-packages-next task from evergreen
  .evergreen/buildvariants-and-tasks.in.yml
  .evergreen/buildvariants-and-tasks.yml
  .evergreen/functions.yml
  package.json
Labels: no-title-validation

#6646 chore(ci): re-enable setting the author of the automated PRs
  .github/workflows/bump-packages.yaml
  .github/workflows/update-electron.yaml
Labels: no-title-validation

#6644 fix(package-lock): downgrade puppeteer-core to align with version required by webdriverio
  .evergreen/functions.yml
  package-lock.json
  package.json
  packages/compass-e2e-tests/package.json
Labels: fix, no release notes, no-title-validation

#6652 chore(ci): use correct format for automated PR author
  .github/workflows/bump-packages.yaml
  .github/workflows/update-electron.yaml
Labels: no-title-validation

#6651 chore: setup auto-update when testing auto-update, even in CI.
  packages/compass-e2e-tests/helpers/compass.ts
  packages/compass/src/main/application.ts
Labels: no-title-validation

#6659 fix(tracking): unformat the url to avoid placeholder disappearing
  scripts/generate-tracking-plan.ts
Labels: fix

#6660 chore(ci): fix npm cache path for windows; remove the whole cache fol…
  .evergreen/functions.yml
  .evergreen/npm_ci.sh
  .evergreen/print-compass-env.js
Labels: no-title-validation

#6649 fix(query-bar): retain current query when new query is applied COMPASS-8262
  packages/compass-query-bar/src/components/option-editor.spec.tsx
  packages/compass-query-bar/src/components/option-editor.tsx
  packages/compass-query-bar/src/components/query-option.tsx
  packages/compass-query-bar/src/constants/query-option-definition.ts
  packages/compass-query-bar/src/stores/query-bar-reducer.ts
Labels: bug, release notes, fix

#6640 feat(smoke-tests): test MSI installer for on Windows COMPASS-8707
  .evergreen/functions.yml
  packages/compass-smoke-tests/src/cli.ts
  packages/compass-smoke-tests/src/context.ts
  packages/compass-smoke-tests/src/execute.ts
  packages/compass-smoke-tests/src/installers/types.ts
  packages/compass-smoke-tests/src/installers/windows-msi.ts
Labels: feat, no release notes, no-title-validation

#6666 chore(web): remove maxTimeMS from default preferences
  packages/compass-web/src/preferences.tsx
Labels: no-title-validation

#6629 feat(smoke-tests): test auto-updating from the version of Compass that was just packaged COMPASS-8536
  .evergreen/functions.yml
  .evergreen/preinstall.sh
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/auto-update.test.ts
  packages/compass-smoke-tests/.depcheckrc
  packages/compass-smoke-tests/src/cli.ts
  packages/compass-smoke-tests/src/compass-mongodb-com.d.ts
  packages/compass-smoke-tests/src/context.ts
  packages/compass-smoke-tests/src/execute.ts
  packages/compass-smoke-tests/src/installers/mac-dmg.ts
  packages/compass-smoke-tests/src/installers/mac-utils.ts
  packages/compass-smoke-tests/src/installers/mac-zip.ts
  packages/compass-smoke-tests/tsconfig.json
  packages/compass/src/main/auto-update-manager.ts
Labels: feat, no release notes

#6664 feat(databases-collections): handle non-existent namespaces COMPASS-5750
  package-lock.json
  packages/collection-model/index.d.ts
  packages/collection-model/lib/model.js
  packages/compass-components/src/components/workspace-tabs/tab.tsx
  packages/compass-connections-navigation/src/navigation-item-icon.tsx
  packages/compass-connections-navigation/src/navigation-item.tsx
  packages/compass-connections-navigation/src/styled-navigation-item.tsx
  packages/compass-connections-navigation/src/tree-data.ts
  packages/compass-sidebar/src/components/use-filtered-connections.spec.ts
  packages/compass-sidebar/src/modules/databases.spec.ts
  packages/compass-sidebar/src/modules/databases.ts
  packages/compass-sidebar/src/modules/instance.ts
  packages/compass-sidebar/test/helpers.ts
  packages/compass-workspaces/src/components/workspaces.tsx
  packages/compass-workspaces/src/index.ts
  packages/compass-workspaces/src/stores/workspaces.spec.ts
  packages/compass-workspaces/src/stores/workspaces.ts
  packages/data-service/src/data-service.spec.ts
  packages/data-service/src/data-service.ts
  packages/data-service/src/instance-detail-helper.ts
  packages/database-model/index.d.ts
  packages/database-model/lib/model.js
  packages/databases-collections-list/package.json
  packages/databases-collections-list/src/collections.tsx
  packages/databases-collections-list/src/databases.tsx
  packages/databases-collections-list/src/items-grid.tsx
  packages/databases-collections-list/src/namespace-card.tsx
Labels: release notes, feat
