Repository mongodb-js/compass, pull requests merged in 2025-05, with the labels that each got.

#6839 chore(telemetry): track the view used to run queries
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
  packages/compass-telemetry/src/telemetry-events.ts
Labels: no-title-validation

#6884 feat: update atlas cluster states COMPASS-8228
  packages/compass-connections-navigation/src/base-navigation-item.tsx
  packages/compass-connections-navigation/src/connections-navigation-tree.tsx
  packages/compass-connections-navigation/src/navigation-item-icon.tsx
  packages/compass-connections-navigation/src/navigation-item.tsx
  packages/compass-connections-navigation/src/styled-navigation-item.tsx
  packages/compass-connections-navigation/src/tree-data.ts
  packages/compass-connections/src/hooks/use-connectable.ts
  packages/compass-connections/src/index.tsx
  packages/compass-connections/src/provider.ts
  packages/compass-connections/src/stores/connections-store-redux.ts
  packages/compass-connections/src/utils/connection-supports.ts
  packages/compass-preferences-model/src/feature-flags.ts
  packages/compass-web/sandbox/index.tsx
  packages/compass-web/src/connection-storage.tsx
  packages/connection-info/src/connection-info.ts
Labels: feat, no release notes

#6893 chore: skip validation tests for < 5.0
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
Labels: no release notes, no-title-validation

#6892 feat(data-modeling): display errors when creating a diagram COMPASS-9307
  packages/compass-data-modeling/src/components/new-diagram-form.spec.tsx
  packages/compass-data-modeling/src/components/new-diagram-form.tsx
  packages/compass-data-modeling/src/index.ts
  packages/compass-data-modeling/src/provider/index.tsx
  packages/compass-data-modeling/src/store/analysis-process.ts
  packages/compass-data-modeling/src/store/generate-diagram-wizard.ts
  packages/compass-data-modeling/src/store/index.ts
  packages/compass-data-modeling/src/store/reducer.ts
  packages/compass-data-modeling/test/setup-store.tsx
Labels: feature flagged, feat

#6895 feat(data-modeling): add collection search and fix styles COMPASS-9308 COMPASS-9309
  packages/compass-data-modeling/src/components/new-diagram-form.tsx
Labels: feature flagged, feat

#6887 feat: Fetching index suggestions and dealing with the states CLOUDP-311786
  package-lock.json
  packages/compass-components/package.json
  packages/compass-components/src/index.ts
  packages/compass-indexes/package.json
  packages/compass-indexes/src/components/create-index-form/mdb-code-viewer.tsx
  packages/compass-indexes/src/components/create-index-form/query-flow-section.spec.tsx
  packages/compass-indexes/src/components/create-index-form/query-flow-section.tsx
  packages/compass-indexes/src/modules/create-index.tsx
  packages/compass-indexes/src/stores/store.ts
  packages/compass-indexes/test/setup-store.ts
Labels: feat, no release notes

#6901 feat: Made early indexes variables update when changed CLOUDP-317478
  packages/compass-preferences-model/src/compass-web-preferences-access.ts
  packages/compass-web/src/entrypoint.tsx
Labels: feat, no release notes

#6894 feat(schema, data-modeling): use iterable cursor in schema analysis COMPASS-9150 COMPASS-9315
  package-lock.json
  packages/compass-data-modeling/package.json
  packages/compass-data-modeling/src/store/analysis-process.ts
  packages/compass-schema-validation/src/index.ts
  packages/compass-schema-validation/src/modules/index.ts
  packages/compass-schema-validation/src/stores/store.spec.ts
  packages/compass-schema/src/index.ts
  packages/compass-schema/src/modules/schema-analysis.spec.ts
  packages/compass-schema/src/modules/schema-analysis.ts
  packages/compass-schema/src/stores/store.spec.ts
  packages/compass-schema/src/stores/store.ts
  packages/data-service/src/data-service.spec.ts
  packages/data-service/src/data-service.ts
Labels: release notes, feat, no-title-validation

#6906 chore: also skip afterEach()
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
  packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
Labels: no release notes, no-title-validation

#6907 fix(web): Provide an actionable error message on DE errors CLOUDP-313461
  packages/compass-indexes/src/modules/regular-indexes.ts
Labels: fix, no release notes

#6909 chore: wait for text to include the expected result
  packages/compass-e2e-tests/tests/collection-aggregations-tab.test.ts
  packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
  packages/compass-e2e-tests/tests/collection-import.test.ts
Labels: no-title-validation

#6896 fix: Make create form keyboard accessible COMPASS-9335
  packages/compass-components/src/components/select-list.spec.tsx
  packages/compass-components/src/components/select-list.tsx
  packages/compass-components/src/components/select-table.tsx
  packages/compass-components/src/index.ts
  packages/compass-connection-import-export/src/components/export-modal.tsx
  packages/compass-connection-import-export/src/components/import-modal.tsx
  packages/compass-data-modeling/src/components/new-diagram-form.tsx
  packages/compass-e2e-tests/tests/import-export-connections.test.ts
Labels: feature flagged, fix, no release notes

#6900 fix: empty diagram list view COMPASS-9310
  packages/compass-components/src/components/empty-content.tsx
  packages/compass-data-modeling/src/components/icons/collaborate.tsx
  packages/compass-data-modeling/src/components/icons/flexibility.tsx
  packages/compass-data-modeling/src/components/icons/insight.tsx
  packages/compass-data-modeling/src/components/icons/schema-visualization.tsx
  packages/compass-data-modeling/src/components/saved-diagrams-list.spec.tsx
  packages/compass-data-modeling/src/components/saved-diagrams-list.tsx
  packages/compass-data-modeling/src/provider/index.tsx
Labels: feature flagged, fix

#6904 feat: Open create index modal with query context CLOUDP-311788
  package-lock.json
  packages/compass-components/package.json
  packages/compass-components/src/components/insights-chip.tsx
  packages/compass-components/src/components/leafygreen.tsx
  packages/compass-components/src/index.ts
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-indexes/src/components/create-index-form/create-index-form.spec.tsx
  packages/compass-indexes/src/components/create-index-form/create-index-form.tsx
  packages/compass-indexes/src/components/create-index-form/query-flow-section.spec.tsx
  packages/compass-indexes/src/components/create-index-form/query-flow-section.tsx
  packages/compass-indexes/src/components/create-index-modal/create-index-modal.tsx
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
  packages/compass-indexes/src/modules/create-index.spec.ts
  packages/compass-indexes/src/modules/create-index.tsx
  packages/compass-indexes/src/stores/store.ts
Labels: feat, no release notes

#6902 feat: Added new accordion with updated styles CLOUDP-314036
  packages/compass-indexes/src/components/create-index-form/create-index-form.tsx
Labels: feature flagged, feat, no release notes, no-title-validation

#6919 chore: update log id to fix duplication
  packages/compass-connections/src/utils/end-of-life-server.ts
Labels: no release notes, no-title-validation

#6918 chore(preferences): remove enableQueryHistoryAutocomplete feature flag
  packages/compass-preferences-model/src/feature-flags.ts
  packages/compass-query-bar/src/components/option-editor.tsx
Labels: no release notes, no-title-validation

#6920 chore(indexes): update padding to allow for focus ring to show on toolbar buttons
  packages/compass-indexes/src/components/indexes-toolbar/indexes-toolbar.tsx
  packages/compass-indexes/src/components/indexes/indexes.tsx
Labels: no release notes, no-title-validation

#6928 chore(ci): use Node.js 22 in CI COMPASS-9381
  .evergreen/connectivity-tests/Dockerfile
  .evergreen/functions.yml
  .evergreen/preinstall.sh
  .github/workflows/authors-and-third-party-notices.yaml
  .github/workflows/bump-packages.yaml
  .github/workflows/publish-compass.yaml
  .github/workflows/publish-packages.yaml
  .github/workflows/start-beta.yml
  .github/workflows/start-ga.yaml
  .github/workflows/test-installers.yml
  .github/workflows/update-electron.yaml
  CONTRIBUTING.md
  package-lock.json
  package.json
  packages/compass-components/src/hooks/use-hotkeys.spec.tsx
Labels: no release notes, no-title-validation

#6911 chore(webpack, web): add saslprep no-op alias for webpack bundle web
  packages/compass-web/polyfills/@mongodb-js/saslprep/index.ts
  packages/compass-web/webpack.config.js
Labels: no-title-validation

#6934 chore(ci): pin node-version to align with the other workflows
  .github/workflows/test-installers.yml
Labels: no release notes, no-title-validation

#6924 chore(schema): remove unused proptype
  packages/compass-schema/src/components/minichart/minichart.jsx
Labels: no release notes, no-title-validation

#6938 chore: add asdf .tool-versions file with node js
  .tool-versions
Labels: no release notes, no-title-validation

#6936 chore(compass-web): do not expose internal logger details to web `onLog` hook
  package-lock.json
  packages/compass-web/package.json
  packages/compass-web/polyfills/@mongodb-js/devtools-proxy-support/index.ts
  packages/compass-web/polyfills/net/index.ts
  packages/compass-web/sandbox/sandbox-logger.ts
  packages/compass-web/src/logger-and-telemetry.spec.tsx
  packages/compass-web/src/logger-and-telemetry.tsx
  packages/compass-web/tsconfig.json
Labels: no-title-validation

#6931 feat(data-modeling): grid list and toolbar COMPASS-9311
  packages/compass-data-modeling/src/components/diagram-card.tsx
  packages/compass-data-modeling/src/components/diagram-list-toolbar.tsx
  packages/compass-data-modeling/src/components/saved-diagrams-list.spec.tsx
  packages/compass-data-modeling/src/components/saved-diagrams-list.tsx
Labels: feature flagged, feat, no release notes

#6930 fix(sidebar): show profiler collections COMPASS-9377
  packages/collection-model/lib/model.js
Labels: release notes, fix

#6945 fix: fix terminated cluster states COMPASS-9367
  packages/compass-web/src/connection-storage.spec.ts
  packages/compass-web/src/connection-storage.tsx
Labels: fix, no release notes

#6947 chore: ignore two not applicable electron vulnerabilities for longer
  .snyk
Labels: no-title-validation

#6932 feat: diagram edit handling COMPASS-9312
  package-lock.json
  packages/compass-data-modeling/src/components/diagram-editor.tsx
  packages/compass-data-modeling/src/services/data-model-storage.ts
  packages/compass-data-modeling/src/store/analysis-process.ts
  packages/compass-data-modeling/src/store/diagram.spec.ts
  packages/compass-data-modeling/src/store/diagram.ts
  packages/compass-e2e-tests/tests/data-modeling-tab.test.ts
  packages/compass-preferences-model/package.json
  packages/compass-preferences-model/src/global-config.ts
  packages/compass-preferences-model/src/preferences-persistent-storage.ts
  packages/compass-preferences-model/src/preferences-schema.tsx
  packages/compass-preferences-model/src/preferences.ts
  packages/compass-preferences-model/src/user-storage.spec.ts
  packages/compass-preferences-model/src/user-storage.ts
  packages/compass-user-data/package.json
Labels: feature flagged, feat

#6954 chore(e2e-tests): disable end-of-life connection modal when testing COMPASS-9361
  packages/compass-connections/src/stores/connections-store-redux.ts
  packages/compass-connections/src/utils/end-of-life-server.ts
  packages/compass-e2e-tests/helpers/compass.ts
  packages/compass-preferences-model/src/preferences-schema.tsx
Labels: no release notes

#6955 chore(smoke-tests): try updating the package index first COMPASS-9405
  packages/compass-smoke-tests/src/installers/linux-deb.ts
Labels: no release notes

#6917 chore(connections): update here text to connect
  packages/compass-connections-navigation/src/connect-button-with-menu.tsx
Labels: no release notes, no-title-validation

#6940 feat: revert nudge back to icon on default and expand on hover CLOUDP-319356
  packages/compass-components/src/components/signal-popover.spec.tsx
  packages/compass-components/src/components/signal-popover.tsx
  packages/compass-crud/src/components/crud-toolbar.tsx
Labels: feat, no release notes, no-title-validation
