Repository mongodb-js/compass, pull requests merged in 2025-03, with the labels that each got.

#6741 fix(connections, web): handle flex clusters without deployment COMPASS-9008
  packages/atlas-service/src/atlas-service.ts
  packages/compass-connections/src/utils/connection-supports.spec.ts
  packages/compass-connections/src/utils/connection-supports.ts
  packages/compass-indexes/src/modules/rolling-indexes-service.ts
  packages/compass-schema/src/utils.ts
  packages/compass-web/src/connection-storage.spec.ts
  packages/compass-web/src/connection-storage.tsx
  packages/compass-web/webpack.config.js
  packages/connection-info/src/connection-info.ts
Labels: fix, no release notes, no-title-validation

#6750 feat(connection-form): add connection and anonymous id to app name for atlas connections COMPASS-8591
  packages/compass-connections/src/stores/connections-store-redux.ts
  packages/connection-form/src/hooks/use-connect-form.ts
  packages/connection-form/src/utils/set-app-name-if-missing.spec.ts
  packages/connection-form/src/utils/set-app-name-if-missing.ts
Labels: feat, no release notes

#6749 feat: enable auto-update-to tests, auto-update-from on mac and upload logs COMPASS-9063 COMPASS-8128
  .github/workflows/test-installers.yml
  packages/compass-e2e-tests/tests/auto-update.test.ts
Labels: feat, no release notes

#6766 feat(schema-validation): add confirmation modal when applying rules, add explicit editing state COMPASS-8861
  packages/compass-e2e-tests/helpers/commands/set-validation.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-validation-tab.test.ts
  packages/compass-editor/src/editor.tsx
  packages/compass-schema-validation/src/components/validation-editor.spec.tsx
  packages/compass-schema-validation/src/components/validation-editor.tsx
  packages/compass-schema-validation/src/modules/edit-mode.spec.ts
  packages/compass-schema-validation/src/modules/edit-mode.ts
  packages/compass-schema-validation/src/modules/validation.ts
  packages/compass-schema-validation/src/modules/zero-state.ts
  packages/compass-schema-validation/src/stores/store.spec.ts
  packages/compass-schema-validation/src/stores/store.ts
  packages/compass-schema/src/components/export-schema-modal.tsx
Labels: release notes, feat

#6773 fix(connection-form)!: use a simpler parameter for differentiating Atlas and non-Atlas connections
  packages/compass-connections/src/stores/connections-store-redux.ts
  packages/connection-form/src/hooks/use-connect-form.ts
Labels: fix, no release notes, no-title-validation

#6774 feat(deps): bump mongosh, driver to latest COMPASS-9056
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-connections/package.json
  packages/compass-e2e-tests/package.json
  packages/compass-explain-plan/package.json
  packages/compass-generative-ai/package.json
  packages/compass-import-export/package.json
  packages/compass-indexes/package.json
  packages/compass-query-bar/package.json
  packages/compass-schema/package.json
  packages/compass-shell/package.json
  packages/compass-sidebar/package.json
  packages/compass-web/package.json
  packages/compass/package.json
  packages/connection-form/package.json
  packages/connection-info/package.json
  packages/data-service/package.json
  packages/data-service/src/csfle-collection-tracker.spec.ts
  packages/data-service/src/csfle-collection-tracker.ts
Labels: release notes, feat

#6755 feat: show error details on insert COMPASS-8864
  package-lock.json
  packages/compass-components/src/components/modals/error-details-modal.tsx
  packages/compass-components/src/index.ts
  packages/compass-crud/package.json
  packages/compass-crud/src/actions/index.ts
  packages/compass-crud/src/components/document-json-view.tsx
  packages/compass-crud/src/components/document-list-view.spec.tsx
  packages/compass-crud/src/components/document-list-view.tsx
  packages/compass-crud/src/components/document-list.tsx
  packages/compass-crud/src/components/insert-document-dialog.tsx
  packages/compass-crud/src/components/json-editor.tsx
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-e2e-tests/helpers/commands/try-to-insert-document.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
  packages/compass-e2e-tests/tests/connection.test.ts
  packages/compass-import-export/src/components/export-code-view.tsx
  packages/compass-import-export/src/components/export-modal.tsx
Labels: feat, no release notes

#6769 fix(compass-validation): unified validation preview CTA COMPASS-8862
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-validation-tab.test.ts
  packages/compass-schema-validation/src/components/document-preview.spec.tsx
  packages/compass-schema-validation/src/components/document-preview.tsx
  packages/compass-schema-validation/src/components/sample-documents.spec.tsx
  packages/compass-schema-validation/src/components/sample-documents.tsx
  packages/compass-schema-validation/src/modules/sample-documents.spec.ts
  packages/compass-schema-validation/src/modules/sample-documents.ts
  packages/compass-schema-validation/src/stores/store.spec.ts
Labels: release notes, fix

#6771 feat(schema): allow aborting analysis while in progress COMPASS-9052
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-field-store/package.json
  packages/compass-generative-ai/package.json
  packages/compass-import-export/package.json
  packages/compass-import-export/src/export/gather-fields.ts
  packages/compass-query-bar/package.json
  packages/compass-schema/package.json
Labels: release notes, feat

#6789 fix: switch from forEachPackage to listAllPackages
  scripts/find-packages-on-old-config.js
  scripts/update-electron.js
Labels: fix, no release notes, no-title-validation

#6788 chore: bump electron to 32.3.3
  configs/webpack-config-compass/package.json
  package-lock.json
  packages/atlas-service/package.json
  packages/compass-crud/package.json
  packages/compass-e2e-tests/package.json
  packages/compass-explain-plan/package.json
  packages/compass-find-in-page/package.json
  packages/compass-import-export/package.json
  packages/compass-indexes/package.json
  packages/compass-query-bar/package.json
  packages/compass-schema-validation/package.json
  packages/compass-shell/package.json
  packages/compass-utils/package.json
  packages/compass-web/package.json
  packages/compass/package.json
  packages/connection-storage/package.json
  packages/hadron-build/package.json
  packages/hadron-ipc/package.json
  scripts/package.json
Labels: release notes, no-title-validation

#6791 fix(connection-form): use a double dash for separating appName identifiers COMPASS-8591
  packages/connection-form/src/utils/set-app-name-if-missing.spec.ts
  packages/connection-form/src/utils/set-app-name-if-missing.ts
Labels: fix, no release notes

#6764 fix(compass-web): make banners dismissible COMPASS-8976
  packages/compass-indexes/src/components/indexes/indexes.tsx
  packages/compass-schema/src/components/compass-schema.tsx
Labels: fix, no release notes

#6781 feat: validation rules generation COMPASS-8859
  package-lock.json
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-validation-tab.test.ts
  packages/compass-schema-validation/package.json
  packages/compass-schema-validation/src/components/validation-states.spec.tsx
  packages/compass-schema-validation/src/components/validation-states.tsx
  packages/compass-schema-validation/src/components/zero-graphic.tsx
  packages/compass-schema-validation/src/index.ts
  packages/compass-schema-validation/src/modules/index.ts
  packages/compass-schema-validation/src/modules/rules-generation.ts
  packages/compass-schema-validation/src/stores/store.spec.ts
  packages/compass-schema-validation/src/stores/store.ts
  packages/compass-schema/src/index.ts
Labels: feature flagged, feat

#6785 chore(schema-validation): remove unused action
  packages/compass-schema-validation/src/modules/validation.spec.ts
  packages/compass-schema-validation/src/modules/validation.ts
Labels: no release notes, no-title-validation

#6794 feat: add telemetry for rules generation COMPASS-8863
  docs/tracking-plan.md
  packages/compass-schema-validation/src/modules/rules-generation.ts
  packages/compass-schema-validation/src/stores/store.spec.ts
  packages/compass-telemetry/src/telemetry-events.ts
Labels: feature flagged, feat

#6796 feat: file download success/failure COMPASS-9095
  packages/compass/src/app/index.tsx
  packages/compass/src/main/application.ts
Labels: feature flagged, feat

#6795 feat: validation errors on import COMPAS-8867
  packages/compass-e2e-tests/helpers/commands/set-validation.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
  packages/compass-e2e-tests/tests/collection-import.test.ts
  packages/compass-e2e-tests/tests/collection-validation-tab.test.ts
  packages/compass-import-export/src/components/import-error-details-modal.spec.tsx
  packages/compass-import-export/src/components/import-error-details-modal.tsx
  packages/compass-import-export/src/components/import-toast.tsx
  packages/compass-import-export/src/import-plugin.tsx
  packages/compass-import-export/src/import/import-types.ts
  packages/compass-import-export/src/import/import-utils.ts
  packages/compass-import-export/src/modules/import.ts
Labels: feature flagged, feat

#6799 feat(indexes): show tooltip for rolling index build status COMPASS-9129
  packages/compass-indexes/src/components/regular-indexes-table/status-field.tsx
Labels: feat, no release notes

#6798 fix: bump mongodb-schema COMPASS-9110
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-field-store/package.json
  packages/compass-generative-ai/package.json
  packages/compass-import-export/package.json
  packages/compass-query-bar/package.json
  packages/compass-schema/package.json
Labels: fix, no release notes

#6802 chore(schema-validation): add initial load loading spinner
  packages/compass-schema-validation/src/components/validation-states.tsx
Labels: no-title-validation

#6804 fix(compass-schema): sticky copy button COMPASS-9141
  packages/compass-schema/src/components/export-schema-modal.tsx
Labels: feature flagged, fix

#6793 feat(schema-validation): add default template COMPASS-8860
  package-lock.json
  packages/compass-aggregations/package.json
  packages/compass-collection/package.json
  packages/compass-editor/package.json
  packages/compass-indexes/package.json
  packages/compass-query-bar/package.json
  packages/compass-schema-validation/package.json
  packages/compass-schema-validation/src/components/validation-editor.tsx
  packages/compass-schema-validation/src/modules/edit-mode.ts
  packages/compass-schema-validation/src/modules/is-loaded.ts
  packages/compass-schema-validation/src/modules/rules-generation.ts
  packages/compass-schema-validation/src/modules/sample-documents.ts
  packages/compass-schema-validation/src/modules/validation.spec.ts
  packages/compass-schema-validation/src/modules/validation.ts
  packages/compass-schema-validation/src/modules/zero-state.ts
  packages/compass-schema-validation/src/stores/store.spec.ts
  packages/compass-schema-validation/src/util.ts
Labels: feature flagged, feat

#6809 fix(compass-schema-validation): add generate button to the editor COMPASS-9145
  packages/compass-schema-validation/src/components/validation-editor.spec.tsx
  packages/compass-schema-validation/src/components/validation-editor.tsx
  packages/compass-schema-validation/src/components/validation-selectors.tsx
Labels: feature flagged, fix

#6746 feat(schema): enable export schema feature COMPASS-8819
  packages/compass-e2e-tests/tests/collection-schema-tab.test.ts
  packages/compass-preferences-model/src/feature-flags.ts
  packages/compass-schema/src/components/schema-toolbar.spec.tsx
Labels: release notes, feat

#6814 fix: update @babel/runtime and @babel/helpers to 7.26.10 COMPASS-9137 COMPASS-9136 COMPASS-9135 COMPASS-9134 COMPASS-9133 COMPASS-9132
  package-lock.json
Labels: fix, no release notes

#6813 fix: update braces to 3.0.2
  package-lock.json
Labels: fix, no release notes, no-title-validation

#6818 fix: remove readPreferenceTags for database&collection lookups if the cluster is sharded and readPreferenceTags was set COMPASS-9111
  packages/data-service/src/connect.spec.ts
  packages/data-service/src/data-service.ts
Labels: release notes, fix

#6801 feat(release): dual write release artifacts to new bucket COMPASS-9160
  .evergreen/functions.yml
  package-lock.json
  packages/hadron-build/commands/upload.js
  packages/hadron-build/lib/download-center.js
  packages/hadron-build/package.json
Labels: feat, no release notes

#6816 feat(schema-validation): add in progress saving state COMPASS-9077
  packages/compass-schema-validation/src/components/validation-editor.spec.tsx
  packages/compass-schema-validation/src/components/validation-editor.tsx
  packages/compass-schema-validation/src/modules/validation.spec.ts
  packages/compass-schema-validation/src/modules/validation.ts
  packages/compass-schema-validation/src/stores/store.spec.ts
Labels: release notes, feat

#6821 fix: use mongodb version 8.0.5 on macOS versions < 14
  .evergreen/buildvariants-and-tasks.in.yml
  .evergreen/buildvariants-and-tasks.yml
  .github/workflows/test-installers.yml
Labels: fix, no release notes, no-title-validation

#6819 chore: use switch-exhaustiveness-check, add updatemany to fixtures
  packages/compass-saved-aggregations-queries/.eslintrc.js
  packages/compass-saved-aggregations-queries/src/hooks/use-grid-filters.spec.tsx
  packages/compass-saved-aggregations-queries/src/index.spec.tsx
  packages/compass-saved-aggregations-queries/src/stores/delete-item.ts
  packages/compass-saved-aggregations-queries/src/stores/edit-item.ts
  packages/compass-saved-aggregations-queries/src/stores/open-item.ts
  packages/compass-saved-aggregations-queries/test/fixtures.ts
Labels: no release notes, no-title-validation

#6797 feat: show validation error details COMPASS-8864 COMPASS-8867 COMPASS-8865
  package-lock.json
  packages/compass-components/src/components/document-list/document-edit-actions-footer.tsx
  packages/compass-components/src/hooks/use-confirmation.tsx
  packages/compass-components/src/hooks/use-error-details.tsx
  packages/compass-components/src/index.ts
  packages/compass-crud/package.json
  packages/compass-crud/src/components/document-list.tsx
  packages/compass-crud/src/components/insert-document-dialog.tsx
  packages/compass-crud/src/stores/crud-store.spec.ts
  packages/compass-crud/src/stores/crud-store.ts
  packages/compass-e2e-tests/helpers/commands/set-validation.ts
  packages/compass-e2e-tests/helpers/commands/try-to-insert-document.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
  packages/compass-e2e-tests/tests/collection-import.test.ts
  packages/compass-e2e-tests/tests/collection-validation-tab.test.ts
  packages/compass-e2e-tests/tests/connection.test.ts
  packages/compass-import-export/src/components/export-code-view.tsx
  packages/compass-import-export/src/components/export-modal.tsx
  packages/compass-import-export/src/components/import-toast.tsx
  packages/compass-import-export/src/import/import-csv.spec.ts
  packages/compass-import-export/src/import/import-json.spec.ts
  packages/compass-import-export/src/import/import-types.ts
  packages/compass-import-export/src/import/import-utils.ts
  packages/compass-import-export/src/modules/import.ts
  packages/hadron-document/package.json
  packages/hadron-document/src/document.ts
Labels: release notes, feat

#6815 fix: catch parse error on multi insert
  packages/compass-crud/src/stores/crud-store.ts
Labels: release notes, fix, no-title-validation

#6827 fix(ci): don't allow empty commits in update generated files task; skip task when previous commit was also generated by it
  .github/workflows/authors-and-third-party-notices.yaml
  package.json
Labels: fix, no-title-validation

#6824 chore: skip errInfo tests on server version < 5
  packages/compass-e2e-tests/tests/collection-documents-tab.test.ts
Labels: no release notes, no-title-validation

#6829 fix(e2e): skip more validation details tests
  packages/compass-e2e-tests/tests/collection-import.test.ts
Labels: fix, no release notes, no-title-validation

#6820 feat(compass-schema-validator): add validation action option for 'errorAndLog' with 8.1 COMPASS-8983
  packages/compass-schema-validation/src/components/validation-editor.spec.tsx
  packages/compass-schema-validation/src/components/validation-editor.tsx
  packages/compass-schema-validation/src/components/validation-selectors.tsx
  packages/compass-schema-validation/src/modules/validation.ts
  packages/compass-telemetry/src/telemetry-events.ts
Labels: release notes, feat

#6830 chore: bump tar-fs 2.1.1 to 2.1.2
  package-lock.json
Labels: no-title-validation

#6823 chore(components): remove useToast / useConfirmationModal hooks, only provide global functions as interface
  packages/compass-components/src/hooks/use-confirmation.spec.tsx
  packages/compass-components/src/hooks/use-confirmation.tsx
  packages/compass-components/src/hooks/use-error-details.tsx
  packages/compass-components/src/hooks/use-toast.spec.tsx
  packages/compass-components/src/hooks/use-toast.tsx
  packages/compass-components/src/index.ts
  packages/compass-connection-import-export/src/components/export-modal.tsx
  packages/compass-connection-import-export/src/components/import-modal.tsx
  packages/compass-schema-validation/src/components/validation-editor.tsx
  packages/connection-form/src/components/connection-string-input.tsx
Labels: no-title-validation
