Repository mongodb-js/compass, pull requests merged in 2025-07, with the labels that each got.

#7064 fix(deps): bump @codemirror/commands for multiline editor fix COMPASS-9485
  package-lock.json
  packages/compass-editor/package.json
Labels: release notes, fix

#7066 Add `useContextMenuGroups` hook
  configs/eslint-config-compass/index.js
  packages/compass-components/src/components/context-menu.tsx
  packages/compass-components/src/index.ts
  packages/compass-context-menu/src/context-menu-content.ts
  packages/compass-context-menu/src/use-context-menu.tsx
Labels: no release notes, no-title-validation

#6956 feat(compass-components): add context menu COMPASS-9386
  configs/eslint-config-compass/index.js
  package-lock.json
  packages/compass-components/package.json
  packages/compass-components/src/components/compass-components-provider.tsx
  packages/compass-components/src/components/content-with-fallback.spec.tsx
  packages/compass-components/src/components/context-menu.spec.tsx
  packages/compass-components/src/components/context-menu.tsx
  packages/compass-components/src/components/leafygreen.tsx
  packages/compass-components/src/index.ts
  packages/compass-context-menu/src/context-menu-content.ts
  packages/compass-context-menu/src/context-menu-provider.spec.tsx
  packages/compass-context-menu/src/context-menu-provider.tsx
  packages/compass-context-menu/src/types.ts
  packages/compass-context-menu/src/use-context-menu.spec.tsx
  packages/compass-context-menu/src/use-context-menu.tsx
  packages/compass-crud/src/components/document-list-view.spec.tsx
Labels: feat, no release notes

#7074 chore(context-menu): context menu feature flag
  packages/compass-components/src/components/compass-components-provider.tsx
  packages/compass-components/src/components/context-menu.tsx
  packages/compass-context-menu/src/context-menu-provider.tsx
  packages/compass-preferences-model/src/feature-flags.ts
  packages/compass/src/app/components/home.tsx
Labels: no release notes, no-title-validation

#7073 chore(context-menu): use anchor ref and compact menu
  packages/compass-components/src/components/content-with-fallback.spec.tsx
  packages/compass-components/src/components/context-menu.spec.tsx
  packages/compass-components/src/components/context-menu.tsx
Labels: no release notes, no-title-validation

#7071 chore(scripts): refactor update-electron to general purpose update-dependencies; replace usage in CI
  .github/workflows/update-electron.yaml
  .github/workflows/update-eslint.yaml
  package-lock.json
  scripts/package.json
  scripts/update-dependencies-config.js
  scripts/update-dependencies.js
  scripts/update-electron.js
Labels: no-title-validation

#7053 feat(workspaces): context menu on tabs to duplicate and close all other tabs COMPASS-9397
  packages/compass-components/src/components/workspace-tabs/tab.spec.tsx
  packages/compass-components/src/components/workspace-tabs/tab.tsx
  packages/compass-components/src/components/workspace-tabs/workspace-tabs.spec.tsx
  packages/compass-components/src/components/workspace-tabs/workspace-tabs.tsx
  packages/compass-workspaces/src/components/workspaces.tsx
  packages/compass-workspaces/src/stores/workspaces.spec.ts
  packages/compass-workspaces/src/stores/workspaces.ts
Labels: release notes, feat

#7072 fix(databases-collections): add question mark to the modal title COMPASS-9505
  packages/databases-collections/src/stores/drop-namespace.tsx
Labels: release notes, fix

#7081 fix(scripts): update overrides when updating packages
  scripts/update-dependencies-config.js
  scripts/update-dependencies.js
Labels: fix, no release notes, no-title-validation

#7082 feat: Changing the sort example for 2 index fields CLOUDP-329033
  packages/compass-indexes/src/components/create-index-form/index-flow-section.spec.tsx
  packages/compass-indexes/src/components/create-index-form/index-flow-section.tsx
Labels: feat, no release notes

#7055 feat(data-modeling): export diagram to png COMPASS-9449
  package-lock.json
  packages/compass-data-modeling/package.json
  packages/compass-data-modeling/src/components/export-diagram-modal.tsx
  packages/compass-data-modeling/src/services/export-diagram.ts
  packages/compass-data-modeling/src/services/export-diagram.tsx
  packages/compass-e2e-tests/helpers/commands/hide-visible-toasts.ts
  packages/compass-e2e-tests/helpers/compass.ts
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/package.json
  packages/compass-e2e-tests/tests/data-modeling-tab.test.ts
Labels: feat, no release notes

#7092 chore(data-modeling): move export state to redux and add telemetry COMPASS-9523
  packages/compass-data-modeling/src/components/diagram-editor-toolbar.tsx
  packages/compass-data-modeling/src/components/export-diagram-modal.tsx
  packages/compass-data-modeling/src/services/export-diagram.tsx
  packages/compass-data-modeling/src/store/analysis-process.ts
  packages/compass-data-modeling/src/store/diagram.ts
  packages/compass-data-modeling/src/store/export-diagram.ts
  packages/compass-data-modeling/src/store/index.ts
  packages/compass-data-modeling/src/store/reducer.ts
  packages/compass-telemetry/src/telemetry-events.ts
Labels: feature flagged, no release notes

#6996 feat(compass-crud): add right click menus for the CRUD toolbar COMPASS-9388
  packages/compass-crud/src/components/crud-toolbar.spec.tsx
  packages/compass-crud/src/components/crud-toolbar.tsx
Labels: feat, no release notes

#7090 fix(compass-data-modeling): add telemetry for diagram created COMPASS-9525
  packages/compass-data-modeling/src/store/analysis-process.ts
  packages/compass-telemetry/src/telemetry-events.ts
Labels: feature flagged, fix

#7098 fix(data-modeling): update subtitle and radio button size COMPASS-9551
  packages/compass-data-modeling/src/components/export-diagram-modal.tsx
Labels: fix, no release notes

#7105 chore(e2e-tests): skip j int test as it isn't recognized on CI
  packages/compass-e2e-tests/tests/data-modeling-tab.test.ts
Labels: no-title-validation

#7070 feat(sidebar): context menu to control specific navigation items COMPASS-9393
  package-lock.json
  packages/compass-components/src/components/actions/dropdown-menu-button.tsx
  packages/compass-components/src/components/actions/item-action-group.tsx
  packages/compass-components/src/components/actions/item-action-menu.tsx
  packages/compass-components/src/components/actions/types.ts
  packages/compass-components/src/components/actions/utils.spec.ts
  packages/compass-components/src/components/actions/utils.ts
  packages/compass-components/src/components/context-menu.tsx
  packages/compass-components/src/index.ts
  packages/compass-connections-navigation/package.json
  packages/compass-connections-navigation/src/base-navigation-item.tsx
  packages/compass-connections-navigation/src/connections-navigation-tree.spec.tsx
  packages/compass-connections-navigation/src/connections-navigation-tree.tsx
  packages/compass-connections-navigation/src/context-menus.ts
  packages/compass-connections-navigation/src/item-actions.ts
  packages/compass-connections-navigation/src/navigation-item.tsx
  packages/compass-connections-navigation/src/tree-data.ts
  packages/compass-connections-navigation/src/virtual-list/use-virtual-navigation-tree.tsx
  packages/compass-connections-navigation/src/virtual-list/virtual-list.tsx
  packages/compass-sidebar/package.json
  packages/compass-sidebar/src/components/multiple-connections/connections-navigation.tsx
  packages/compass-sidebar/src/components/multiple-connections/sidebar.spec.tsx
Labels: release notes, feat

#7108 fix: pull the chromium version from the binary, not the monorepo when testing the packaged app COMPASS-9421
  packages/compass-e2e-tests/helpers/compass-web-sandbox.ts
  packages/compass-e2e-tests/helpers/compass.ts
  packages/compass-e2e-tests/helpers/test-runner-paths.ts
  packages/compass-preferences-model/src/preferences-schema.tsx
  packages/compass/src/main/index.ts
Labels: fix, no release notes

#7106 feat(data-modeling): show previous edits when opening the diagram COMPASS-9544
  packages/compass-data-modeling/src/store/diagram.ts
  packages/compass-e2e-tests/tests/data-modeling-tab.test.ts
Labels: feature flagged, feat, no release notes

#7089 chore(data-service, connections): make sure that instance info is only fetched once on initial connection COMPASS-9549
  packages/compass-app-stores/src/stores/instance-store.ts
  packages/compass-connections/src/stores/connections-store-redux.ts
  packages/data-service/src/data-service.ts
Labels: no-title-validation

#7113 feat(aggregations): add feature flag for search activation program phase 1 COMPASS-9571
  packages/compass-aggregations/src/components/aggregations/aggregations.spec.tsx
  packages/compass-aggregations/src/components/pipeline/pipeline.tsx
  packages/compass-aggregations/src/plugin.tsx
  packages/compass-preferences-model/src/feature-flags.ts
Labels: feature flagged, feat

#7119 fix: try and preserve Double and Long/Int64 types in the json editor COMPASS-8337
  packages/compass-crud/src/components/json-editor.tsx
  packages/hadron-document/src/document.ts
  packages/hadron-document/src/element.ts
  packages/hadron-document/test/document.test.ts
Labels: release notes, fix

#7121 fix(compass-web): skip ping on connect for compass web COMPASS-9579
  packages/compass-web/polyfills/@mongodb-js/devtools-connect/index.ts
Labels: fix, no release notes

#7120 feat: vendor LG drawer and toolbar COMPASS-9406
  package-lock.json
  packages/compass-components/package.json
  packages/compass-components/src/components/drawer/constants.ts
  packages/compass-components/src/components/drawer/drawer-layout/drawer-layout.tsx
  packages/compass-components/src/components/drawer/drawer-layout/drawer-layout.types.ts
  packages/compass-components/src/components/drawer/drawer-layout/index.ts
  packages/compass-components/src/components/drawer/drawer-stack-context/drawer-stack-context.tsx
  packages/compass-components/src/components/drawer/drawer-stack-context/drawer-stack-context.types.ts
  packages/compass-components/src/components/drawer/drawer-stack-context/index.ts
  packages/compass-components/src/components/drawer/drawer-toolbar-context/drawer-toolbar-context.tsx
  packages/compass-components/src/components/drawer/drawer-toolbar-context/drawer-toolbar-context.types.ts
  packages/compass-components/src/components/drawer/drawer-toolbar-context/index.ts
  packages/compass-components/src/components/drawer/drawer-toolbar-layout/drawer-toolbar-layout-container.tsx
  packages/compass-components/src/components/drawer/drawer-toolbar-layout/drawer-toolbar-layout.styles.ts
  packages/compass-components/src/components/drawer/drawer-toolbar-layout/drawer-toolbar-layout.tsx
  packages/compass-components/src/components/drawer/drawer-toolbar-layout/drawer-toolbar-layout.types.ts
  packages/compass-components/src/components/drawer/drawer-toolbar-layout/index.ts
  packages/compass-components/src/components/drawer/drawer-with-toolbar-wrapper/drawer-with-toolbar-wrapper.styles.ts
  packages/compass-components/src/components/drawer/drawer-with-toolbar-wrapper/drawer-with-toolbar-wrapper.tsx
  packages/compass-components/src/components/drawer/drawer-with-toolbar-wrapper/drawer-with-toolbar-wrapper.types.ts
  packages/compass-components/src/components/drawer/drawer-with-toolbar-wrapper/index.ts
  packages/compass-components/src/components/drawer/drawer/drawer.constants.ts
  packages/compass-components/src/components/drawer/drawer/drawer.styles.ts
  packages/compass-components/src/components/drawer/drawer/drawer.tsx
  packages/compass-components/src/components/drawer/drawer/drawer.types.ts
  packages/compass-components/src/components/drawer/drawer/index.ts
  packages/compass-components/src/components/drawer/embedded-drawer-layout/embedded-drawer-layout.styles.ts
  packages/compass-components/src/components/drawer/embedded-drawer-layout/embedded-drawer-layout.tsx
  packages/compass-components/src/components/drawer/embedded-drawer-layout/embedded-drawer-layout.types.ts
  packages/compass-components/src/components/drawer/embedded-drawer-layout/index.tsx
  packages/compass-components/src/components/drawer/index.ts
  packages/compass-components/src/components/drawer/layout-component/index.ts
  packages/compass-components/src/components/drawer/layout-component/layout-component.styles.ts
  packages/compass-components/src/components/drawer/layout-component/layout-component.tsx
  packages/compass-components/src/components/drawer/overlay-drawer-layout/index.ts
  packages/compass-components/src/components/drawer/overlay-drawer-layout/overlay-drawer-layout.styles.ts
  packages/compass-components/src/components/drawer/overlay-drawer-layout/overlay-drawer-layout.tsx
  packages/compass-components/src/components/drawer/overlay-drawer-layout/overlay-drawer-layout.types.ts
  packages/compass-components/src/components/drawer/utils/get-lg-ids.ts
  packages/compass-components/src/components/drawer/utils/index.ts
  packages/compass-components/src/components/leafygreen.tsx
  packages/compass-components/src/components/toolbar/constants.ts
  packages/compass-components/src/components/toolbar/context/index.ts
  packages/compass-components/src/components/toolbar/context/toolbar-context.tsx
  packages/compass-components/src/components/toolbar/context/toolbar-context.types.ts
  packages/compass-components/src/components/toolbar/context/toolbar-descendants-context.tsx
  packages/compass-components/src/components/toolbar/index.ts
  packages/compass-components/src/components/toolbar/toolbar-icon-button/index.ts
  packages/compass-components/src/components/toolbar/toolbar-icon-button/toolbar-icon-button.styles.ts
  packages/compass-components/src/components/toolbar/toolbar-icon-button/toolbar-icon-button.tsx
  packages/compass-components/src/components/toolbar/toolbar-icon-button/toolbar-icon-button.types.ts
  packages/compass-components/src/components/toolbar/toolbar/index.ts
  packages/compass-components/src/components/toolbar/toolbar/toolbar.styles.ts
  packages/compass-components/src/components/toolbar/toolbar/toolbar.tsx
  packages/compass-components/src/components/toolbar/toolbar/toolbar.types.ts
  packages/compass-components/src/components/toolbar/utils/get-lg-ids.ts
  packages/compass-components/src/components/toolbar/utils/index.ts
Labels: feature flagged, feat

#7124 fix: rename and reorder the download center links COMPASS-9588
  packages/hadron-build/commands/upload.js
  packages/hadron-build/lib/target.js
  packages/hadron-build/test/upload.test.js
Labels: release notes, fix

#7135 feat: improve relationship selected COMPASS-9478
  packages/compass-components/src/components/accordion.spec.tsx
  packages/compass-components/src/components/accordion.tsx
  packages/compass-data-modeling/src/components/diagram-editor-side-panel.spec.tsx
  packages/compass-data-modeling/src/components/diagram-editor.spec.tsx
  packages/compass-data-modeling/src/components/diagram-editor.tsx
  packages/compass-data-modeling/src/components/relationship-drawer-content.tsx
  packages/compass-data-modeling/src/services/data-model-storage.ts
  packages/compass-data-modeling/src/store/diagram.ts
  packages/compass-data-modeling/test/fixtures/data-model-with-relationships.json
  packages/compass-telemetry/src/telemetry-events.ts
Labels: feature flagged, feat

#7143 chore(ci): increase timeout for compass-web with atlas tests again
  .evergreen/functions.yml
Labels: no-title-validation

#7138 feat(components, data-modeling): add portal version of the Drawer component; use new DrawerSection in data-modeling COMPASS-9610
  package-lock.json
  packages/compass-components/package.json
  packages/compass-components/src/components/compass-components-provider.tsx
  packages/compass-components/src/components/drawer-portal.tsx
  packages/compass-components/src/components/leafygreen.tsx
  packages/compass-components/src/index.ts
  packages/compass-data-modeling/src/components/diagram-editor-side-panel.spec.tsx
  packages/compass-data-modeling/src/components/diagram-editor-side-panel.tsx
  packages/compass-data-modeling/src/components/diagram-editor.tsx
  packages/compass-data-modeling/src/components/relationship-drawer-content.tsx
  packages/compass-workspaces/src/components/workspaces.tsx
Labels: feature flagged, feat, no-title-validation

#7136 chore(connections): add error code cause chain to connection failed telemetry COMPASS-9527
  packages/compass-connections/src/stores/connections-store-redux.ts
  packages/compass-connections/src/utils/telemetry.spec.tsx
  packages/compass-connections/src/utils/telemetry.tsx
  packages/compass-telemetry/src/telemetry-events.ts
Labels: no release notes

#7141 fix(e2e-tests): wait for diagram nodes to be visible COMPASS-9627
  packages/compass-e2e-tests/tests/data-modeling-tab.test.ts
Labels: fix, no release notes, no-title-validation

#7157 fix: clear the errors in the insert document modal when there are no errors COMPASS-3246
  packages/compass-crud/src/components/insert-document-dialog.tsx
  packages/compass-e2e-tests/helpers/selectors.ts
  packages/compass-e2e-tests/tests/collection-import.test.ts
Labels: release notes, fix

#7151 feat: Compass Experimentation Provider CLOUDP-333843
  package-lock.json
  packages/compass-telemetry/.eslintrc.js
  packages/compass-telemetry/package.json
  packages/compass-telemetry/src/experimentation-provider.tsx
  packages/compass-telemetry/src/index.ts
  packages/compass-web/src/index.tsx
Labels: feat, no release notes
